C=======================================================================
C
C   SUBROUTINE S02NAP
C              STANP1
C              STAN11
C              STAN13
C              STAN15
C              STAN24
C              STA130
C
C=======================================================================
      SUBROUTINE S14NAP
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
CS     GLAVNI PROGRAM ZA POZIVANJE PROGRAMA ZA STAMPANJE NAPONA
CE     MAIN PROGRAM FOR PRINTOUT STRESS IN SHELLS 
C
      include 'paka.inc'
      
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /ZAPISI/ LSTAZA(5)
      COMMON /DUPLAP/ IDVA
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
C
      LAU=LMAX
CS     UCITAVANJE PODATAKA O ELEMENTIMA I NAPONA SA DISKA
CE     READ DATA FROM DISK 
      CALL READ14(A(LAU))
CS     PODPROGRAM ZA STAMPANJE NAPONA
CE     PRINT STRESS
      IF(INDPR.EQ.0.OR.INDPR.EQ.2) CALL STANP14(A(LAU)) 
CS     PODPROGRAM ZA STAMPANJE NAPONA ZA POSTPROCESIRANJE
CE     PRINT STRESS FOR POSTPROCESSING 
C      IF(INDGR.EQ.0.OR.INDGR.EQ.2) CALL STANG14(A(LAU))
C
      RETURN
      IF(IATYP.EQ.0) RETURN
      IF(NMODM.LE.4.OR.NMODM.EQ.11.OR.NMODM.EQ.12) RETURN
C....  ZAPIS NAPONA TECENJA I PLASTICNIH DEF. NA KRAJU KORAKA
      NPROS=NE*MODPR1( NMODM )*IDVA
      LMA8=LSTAZA(3)-1
      CALL WRITDD(A(LPLAS1),NPROS/IDVA,IELEM,LMA8,LDUZI)
      RETURN
      END
C======================================================================
      SUBROUTINE STANP14(AU)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      include 'paka.inc'
      
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      DIMENSION AU(*)
      REAL AU
C
      CALL STAN114(A(LSIGMA),AU,AU(LISNA),AU(LCEL),ICVEL)
      RETURN
      END
C======================================================================
      SUBROUTINE STAN114(SIGMA,AU,ISNA,MCVEL,ICVEL)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /PERKOR/ LNKDT,LDTDT,LVDT,NDT,DT,VREME,KOR
      COMMON /BTHDTH/ INDBTH,INDDTH,LTBTH,LTDTH
      COMMON /SRPSKI/ ISRPS
      DIMENSION SIGMA(NE,*),ISNA(*),MCVEL(*)
      DIMENSION AU(*)
      REAL AU
C
      INDSN=0
      DO 20 NLM=1,NE
C
CS       NASTAJANJE I NESTAJANJE ELEMENATA
CE       ELEMENT BIRTH AND DEATH OPTION
C
         IBD=0
         CALL DTHBTH(AU(LTBTH),AU(LTDTH),VREME,NLM,IBD)
         IF(IBD.EQ.1) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2040) NLM
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6040) NLM
         GO TO 20
         ENDIF
C
         ISN=ISNA(NLM)
         IF(ISN.GT.0) GO TO 20
      IF(ISRPS.EQ.0.AND.INDSN.EQ.0)
     1WRITE(IZLAZ,2010)
      IF(ISRPS.EQ.1.AND.INDSN.EQ.0)
     1WRITE(IZLAZ,6010)
         INDSN=1
         NMM=NLM
         IF(ICVEL.EQ.1) NMM=MCVEL(NLM)
         WRITE(IZLAZ,5000) NMM,(SIGMA(NLM,I),I=1,6)
   20 CONTINUE
      RETURN
 5000 FORMAT(I5,11X,6(1PE11.4))
C-----------------------------------------------------------------------
 2010 FORMAT('1'/' ELEM. BR.',7X,'S I L E      I      T E K U C I      G 
     1 A P                       '/21X,'FN',9X,'FS',9X,'FT',9X,'UN',9X,
     1'US',9X,'UT')
 2040 FORMAT(/' NESTAO JE ELEMENT -',I5)
 6010 FORMAT('1'/' ELEM. NU.',7X,'G A P      F O R C E S      A N D       
     1 C U R R E N T      G A P  '/21X,'FN',9X,'FS',9X,'FT',9X,'UN',9X,
     1'US',9X,'UT')
 6040 FORMAT(/' DEATH ELEMENT -',I5)
C-----------------------------------------------------------------------
      END