C=======================================================================
C   SUBROUTINE S11NAP
C              STA11P
C              STN111
C=======================================================================
      SUBROUTINE S11NAP
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
CS     GLAVNI PROGRAM ZA POZIVANJE PROGRAMA ZA STAMPANJE NAPONA
CE     MAIN PROGRAM FOR PRINTOUT STRESS IN SHELLS 
C
      include 'paka.inc'
      
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /ZAPISI/ LSTAZA(5)
      COMMON /DUPLAP/ IDVA
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
C
      LAU=LMAX
CS     UCITAVANJE PODATAKA O ELEMENTIMA I NAPONA SA DISKA
CE     READ DATA FROM DISK 
      CALL READ11(A(LAU),1)
CS     PODPROGRAM ZA STAMPANJE NAPONA
CE     PRINT STRESS
      IF(INDPR.EQ.0.OR.INDPR.EQ.2) CALL STA11P(A(LAU))
CS     PODPROGRAM ZA STAMPANJE NAPONA ZA POSTPROCESIRANJE
CE     PRINT STRESS FOR POSTPROCESSING 
C      IF(INDGR.EQ.0.OR.INDGR.EQ.2) CALL STANG1(A(LAU))
      RETURN
      END
C======================================================================
      SUBROUTINE STA11P(AU)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      include 'paka.inc'
      
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TEMPCV/ LTECV,ITEMP
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /DUPLAP/ IDVA
      DIMENSION AU(*)
      REAL AU
C
      CALL STN111(A(LSIGMA),AU,AU(LISNA),AU(LCEL),ICVEL)
      RETURN
      END
C======================================================================
      SUBROUTINE STN111(SIGMA,AU,ISNA,MCVEL,ICVEL)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /PERKOR/ LNKDT,LDTDT,LVDT,NDT,DT,VREME,KOR
      COMMON /BTHDTH/ INDBTH,INDDTH,LTBTH,LTDTH
      COMMON /SRPSKI/ ISRPS
      DIMENSION SIGMA(NE,*),ISNA(*),MCVEL(*)
      DIMENSION AU(*)
      REAL AU
C
      INDSN=0
      DO 20 NLM=1,NE
C
CS       NASTAJANJE I NESTAJANJE ELEMENATA
CE       ELEMENT BIRTH AND DEATH OPTION
C
         IBD=0
         CALL DTHBTH(AU(LTBTH),AU(LTDTH),VREME,NLM,IBD)
         IF(IBD.EQ.1) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2040) NLM
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6040) NLM
         GO TO 20
         ENDIF
C
         ISN=ISNA(NLM)
         IF(ISN.GT.0) GO TO 20
      IF(ISRPS.EQ.0.AND.INDSN.EQ.0)
     1WRITE(IZLAZ,2010)
      IF(ISRPS.EQ.1.AND.INDSN.EQ.0)
     1WRITE(IZLAZ,6010)
         INDSN=1
         NMM=NLM
         IF(ICVEL.EQ.1) NMM=MCVEL(NLM)
         WRITE(IZLAZ,5000) NMM,
     1        SIGMA(NLM,3),SIGMA(NLM,4),SIGMA(NLM,1),SIGMA(NLM,2)
   20 CONTINUE
      RETURN
 5000 FORMAT(I5,9X,2(1PD12.4),4X,2(1PD12.4))
C-----------------------------------------------------------------------
 2010 FORMAT('1'/' ELEM. BR.',7X,'E L A S T I C N I    O S L O N C I    
     1 -  N A P O N I'/
     117X,'DEFORM-XX   DEFORM-XY        NAPON-XX    NAPON-XY')
 2040 FORMAT(/' NESTAO JE ELEMENT -',I5)
 6010 FORMAT('1'/' ELEM. NU.',7X,'E L A S T I C    S U P P O R T S        
     1S T R E S S'/
     117X,'STRAIN-XX   STRAIN-XY       STRESS-XX   STRESS-XY')
 6040 FORMAT(/' DEATH ELEMENT -',I5)
C-----------------------------------------------------------------------
      END
