C=======================================================================
C
CE        PRINTOUT STRESS 2/D ELEMENTS
CS        STAMPANJE NAPONA 2/D ELEMENATA
C
C   SUBROUTINE K09NAP
C              STANPR
C              STANGR
C              STAN01
C              STAN03
C              STAN05
C              STAG01
C
C=======================================================================
      SUBROUTINE K29NAP
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.   P R O G R A M
CE.       TO PRINTOUT STRESS IN 2/D ELEMENTS
CS.   P R O G R A M
CS.       ZA POZIVANJE PROGRAMA ZA STAMPANJE NAPONA 2/D ELEMENATA
C .
C ......................................................................
C
      include 'paka.inc'
      
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /ZAPISI/ LSTAZA(5)
      COMMON /DUPLAP/ IDVA
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /CDEBUG/ IDEBUG
C
      IF(IDEBUG.GT.0) PRINT *, ' K09NAP'
      LAU=LMAX
CS    UCITAVANJE PODATAKA O ELEMENTIMA I NAPONA SA DISKA
CE    READ DATA FROM DISK 
      CALL R2ADE(A(LAU))
CS    PODPROGRAM ZA STAMPANJE NAPONA
CE    PRINT STRESS
      IF(NMODM.GT.4) THEN
       NPROS=NE*NGS12*MXS*MODPR2( NMODM )*IDVA
       LMA8=LSTAZA(3)-1
C      CALL WRR(A(LPLAS1),NPROS,'LP23')
       CALL WRITDD(A(LPLAS1),NPROS/IDVA,IELEM,LMA8,LDUZI)
      END IF
      IF(INDPR.EQ.0.OR.INDPR.EQ.2) CALL STANPR(A(LAU))
CS    PODPROGRAM ZA STAMPANJE NAPONA ZA POSTPROCESIRANJE
CE    PRINT STRESS FOR POSTPROCESSING 
      IF(INDGR.EQ.0.OR.INDGR.EQ.2) CALL STANGR(A(LAU))
      IF(IATYP.EQ.0) RETURN
      IF(NMODM.LE.4) RETURN
      NPROS=NE*NGS12*MXS*MODPR2( NMODM )*IDVA
      LMA8=LSTAZA(3)-1
C      CALL WRR(A(LPLAS1),NPROS,'LP23')
CC      CALL WRITDD(A(LPLAS1),NPROS/IDVA,IELEM,LMA8,LDUZI)
      RETURN
      END
