C=======================================================================
C
CE        READING DATA ABOUT 2/D ELEMENTS
CS        UCITAVANJE PODATAKA O 2/D ELEMENTIMA
C
C   SUBROUTINE UL2EGL
C              UL2EK
C              UL2EKC
C              LMIMHT
C              UCGRP2
C              PSPOLJ
C
C=======================================================================
      SUBROUTINE U22EGL
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.   P R O G R A M
CE.      TO FORM POINTERS AND READING INPUT DATA ABOUT 2/D ELEMENTS
CS.   P R O G R A M
CS.      ZA FORMIRANJE REPERA I UCITAVANJE OPSTIH ULAZNIH PODATAKA
CS.      O ELEMENTIMA: 2/D, TROUGAO
C .
C ......................................................................
C
      CHARACTER*250 ACOZ
      include 'paka.inc'
      
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /SIMO2D/ LALFE,LHAEM,LHINV,LGEEK,IALFA
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /DUPLAP/ IDVA
      COMMON /BROJUK/ KARTIC,INDFOR,NULAZ
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /UGAOVL/ TE(4,4)
      COMMON /ORIENT/ CPP(3,3),XJJ(3,3),TSG(6,6),BETA,LBET0,IBB0
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /INTGRA/ INCOTX,INCOTY,INCOTZ
      COMMON /AXISYM/ INDAX
      COMMON /BTHDTH/ INDBTH,INDDTH,LTBTH,LTDTH
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /SRPSKI/ ISRPS
      COMMON /SPANEL/ ISHEAR
      COMMON /PODTIP/ IPODT
      COMMON /GEORGE/ TOLG,ALFAG,ICCGG
      COMMON /MIXEDM/ MIXED,IOPGS(6),NDS
      COMMON /COMEFG/ RADIJ,NBASE,NCVP,NPEFG,NCVS,NS,LCORS,LNOC,LNOS
      COMMON /CNPE/ NPE
      COMMON /CDEBUG/ IDEBUG
C
      IF(IDEBUG.GT.0) PRINT *, ' UL2EGL'
C
CS    OSNOVNI PODACI O ELEMENTIMA
CE    BASIC DATA ABOUT ELEMENTS
C     
      ialfa=-1
      CALL ISPITA(ACOZ)
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) IETYP,NGAUSX,NGAUSY,MSET,BETA,MSLOJ,
     1              (CPP(J,1),J=1,3),IALFA
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1000) IETYP,NGAUSX,NGAUSY,MSET,BETA,MSLOJ,
     1                (CPP(J,1),J=1,3),IALFA
      IF(IETYP.EQ.1) INDAX=1
      IF(IALFA.EQ.0.AND.IETYP.NE.1) IALFA=2
      IF(IALFA.EQ.0.AND.IETYP.EQ.1) IALFA=2
      IF(IALFA.GT.2) IALFA=2 
      ialfa=-1
CE      CHECK FOR 5-POINTS INTEGRATION
c       IF(NGAUSX.EQ.5) NGAUSY=1
C
CE      CHECK FOR NEWTON-COTES INTEGRATION
        INCOTX=INCOT(NGAUSX)
        INCOTY=INCOT(NGAUSY)
        INCOTZ=0
      IF(MSLOJ.EQ.0) MSLOJ = 10
      IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
        CALL WBROJK(KARTIC,0)
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2004) IETYP
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6004) IETYP
      IF(ISRPS.EQ.0.AND.INCOTX.EQ.0)
     1WRITE(IZLAZ,2000) NGAUSX
      IF(ISRPS.EQ.1.AND.INCOTX.EQ.0)
     1WRITE(IZLAZ,6000) NGAUSX
      IF(ISRPS.EQ.0.AND.INCOTX.EQ.1)
     1WRITE(IZLAZ,2001) NGAUSX
      IF(ISRPS.EQ.1.AND.INCOTX.EQ.1)
     1WRITE(IZLAZ,6001) NGAUSX
      IF(ISRPS.EQ.0.AND.INCOTY.EQ.0)
     1WRITE(IZLAZ,2002) NGAUSY
      IF(ISRPS.EQ.1.AND.INCOTY.EQ.0)
     1WRITE(IZLAZ,6002) NGAUSY
      IF(ISRPS.EQ.0.AND.INCOTY.EQ.1)
     1WRITE(IZLAZ,2003) NGAUSY
      IF(ISRPS.EQ.1.AND.INCOTY.EQ.1)
     1WRITE(IZLAZ,6003) NGAUSY
        IF(MSET.GT.0) THEN
      IF(ISRPS.EQ.0) WRITE(IZLAZ,2010) MSET,BETA,MSLOJ
      IF(ISRPS.EQ.1) WRITE(IZLAZ,6010) MSET,BETA,MSLOJ
          ELSE
      IF(ISRPS.EQ.0) WRITE(IZLAZ,2020) BETA
      IF(ISRPS.EQ.1) WRITE(IZLAZ,6020) BETA
        ENDIF
      IF(ISRPS.EQ.0) WRITE(IZLAZ,2025) (CPP(J,1),J=1,3),IALFA
      IF(ISRPS.EQ.1) WRITE(IZLAZ,6025) (CPP(J,1),J=1,3),IALFA
      ENDIF
C
CS    SETOVANJE ZA SMICUCI PANEL
CE    SET SHEAR PANEL
C
      ISHEAR=0
      IF(IETYP.EQ.4) THEN
        IETYP =3
        ISHEAR=1
      ENDIF   
C
      BETA=BETA*3.1415926536D0/180.D0
      IBB0=1
      IF(DABS(CPP(1,1)).LT.1.D-6.AND.DABS(CPP(2,1)).LT.1.D-6.AND.
     1   DABS(CPP(3,1)).LT.1.D-6) IBB0=0
C PAZNJA!!!! NIJE DOGRADJEN UGAO PROJEKCIONOG PRAVCA U LBET0 ZA IBB0=1
C
CS    REPERI U VEKTORU AU ZA ULAZNE PODATKE
CE    POINTERS IN INPUT STORAGE VECTOR  AU
C      
      CALL ISPITA(ACOZ)
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) NBASE,NCVP,NPEFG,RADIJ
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1010) NBASE,NCVP,NPEFG,RADIJ
      NCVP=NPE
      NPEFG=NPE
      IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
        CALL WBROJK(KARTIC,0)
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2035) NBASE,NCVP,NPEFG,RADIJ
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6035) NBASE,NCVP,NPEFG,RADIJ
      ENDIF
C
      NCVE=9
c      IF(IPODT.EQ.1) NCVE=6
      LNSLOJ=1
      LMATSL=LNSLOJ+MSET
      LBBET =LMATSL+MSET*MSLOJ
      CALL DELJIV(LBBET,2,INDL)
      IF(INDL.EQ.0) LBBET=LBBET+1
      LDSLOJ=LBBET+MSET*MSLOJ*IDVA
      LTHID =LDSLOJ+MSET*MSLOJ*IDVA
      LBET0 =LTHID+NE*IDVA
      NDEB=1
      IF(IATYP.GT.3) THEN
         NDEB=4
         IF(IPODT.EQ.1) NDEB=3
         LBET0 =LTHID+NDEB*NE*IDVA
      ENDIF
      LTBTH =LBET0+NE*IDVA
      LTDTH =LTBTH
      IF(INDBTH.EQ.1) LTDTH=LTBTH+NE*IDVA
      LNMAT =LTDTH
      IF(INDDTH.EQ.1) LNMAT=LTDTH+NE*IDVA
      LIPGC =LNMAT+NE
      LISNA =LIPGC+NE
      LIPRC =LISNA+NE
      LNEL  =LIPRC+NE
C
      NTOT=LMAX+LNEL-LNSLOJ
      LCEL=LNEL
      IF(ICVEL.EQ.1) THEN
        LNEL=LCEL+NE
        NTOT=NTOT+NE
      ENDIF
      IF(NTOT.GT.MTOT) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2030) NTOT,MTOT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6030) NTOT,MTOT
      STOP
      ENDIF
C
CS    POZIVANJE PROGRAMA ZA ULAZNE PODATKE U VEKTOR AU
CE    CALL ROUTINES FOR INPUT DATA IN VECTOR AU
C
      LAU=LMAX
      CALL U22EK(A(LAU))
      IF(IETYP.LE.2) THEN
      NEFG=4*NBASE*NBASE+NCVS*(12+4*NBASE+NCVS)
         MXAE = ND+(29+11*NCVE+ND*(ND+1)/2+nefg)*IDVA
         IF(IETYP.EQ.1) MXAE = MXAE + (7+ND)*IDVA
      ELSE
         MXAE = ND+(29+12*NCVE+15*NCVE*NCVE+ND*(ND+1)/2)*IDVA
      ENDIF
      IF(ICCGG.EQ.2) MXAE=MXAE+(ND+NDS)*(ND+NDS)*IDVA
      K4=3
      IF(IETYP.EQ.1) K4=4
      IF(MIXED.EQ.1) MXAE=MXAE+(NDS+2*K4*NDS+ND*NDS+NDS*(NDS+1)/2)*IDVA
      IF(IALFA.GE.0) THEN
         MXAE = MXAE + 39*IDVA
         IF(IETYP.EQ.1) MXAE = MXAE + 17*IDVA
      ENDIF
      LMAX = LMAX + MXAE
      RETURN
C
 1000 FORMAT(4I5,F10.3,I5,3F10.3,I5)
 1010 FORMAT(3I5,2F10.3)
C-----------------------------------------------------------------------
 2004 FORMAT(
     111X,'INDIKATOR VRSTE 2/D ELEMENTA ................... IETYP =',I5/
     116X,'EQ.0; RAVANSKO STANJE NAPONA U RAVNI X - Y'/
     116X,'EQ.1; OSNOSIMETRICAN PROBLEM OKO Y OSE'/
     116X,'EQ.2; RAVANSKO STANJE DEFOFMACIJE U RAVNI X - Y'/
     116X,'EQ.3; 2/D ELEMENT U PROSTORU'/
     116X,'EQ.4; SMICUCI PANEL U PROSTORU'//)
 2000 FORMAT(
     611X,'BROJ GAUSOVIH TACAKA U PRAVCU OSE R   ......... NGAUSX =',I5/
     616X,'EQ.0; NGAUSX = 2'//)
 2002 FORMAT(
     611X,'BROJ GAUSOVIH TACAKA U PRAVCU OSE S   ......... NGAUSY =',I5/
     616X,'EQ.0; NGAUSY = 2'//)
 2001 FORMAT(
     611X,'BROJ NJUTN-KOTESOVIH TACAKA U PRAVCU OSE R  ... NGAUSX =',I5/
     6//)
 2003 FORMAT(
     611X,'BROJ NJUTN-KOTESOVIH TACAKA U PRAVCU OSE S  ... NGAUSY =',I5/
     6//)
 2010 FORMAT(
     611X,'BROJ RAZLICITIH VISESLOJNIH SETOVA MATERIJALA ... MSET =',I5/
     616X,'GT.0; VISESLOJNA LJUSKA'///
     611X,'UGAO SETOVA U ODNOSU NA REFERENTNI PRAVAC .. BETA =',1PD10.3/
     6//11X,'MAKSIMALAN BROJ SLOJEVA ................... MSLOJ =',5X,I5)
 2020 FORMAT(
     611X,'UGAO VLAKANA U ODNOSU NA REFERENTNI PRAVAC . BETA =',1PD10.3)
 2025 FORMAT(//
     611X,'KOORDINATE TACKE PROJEKCIONOG PRAVCA ....... CPPX =',1PD10.3/
     611X,'                                     ....... CPPY =',1PD10.3/
     611X,'                                     ....... CPPZ =',1PD10.3/
     6//
     611X,'METOD INKOMPATIBILNIH MODOVA ................... IALFA =',I5/
     616X,'EQ.-1; NE KORISTI SE'/
     616X,'EQ. 0; IALFA=1'/
     616X,'EQ. 1; 4 PARAMETARA - TAYLOR'/
     616X,'EQ. 2; 5 PARAMETARA')
 2030 FORMAT(///' NEDOVOLJNA DIMENZIJA U VEKTORU A ZA PODATKE O ELEMENTI
     1MA LJUSKE'/' POTREBNA DIMENZIJA , LMAX=',I10/' RASPOLOZIVA DIMENZI
     2JA,  MTOT =',I10)  
 2035 FORMAT(//
     611X,'TIP BAZE ...................................... NBASE =',I5/ 
     616X,'EQ. 3; LINEARNA'/
     616X,'EQ. 6; KVADRATNA'/
     616X,'EQ.10; KUBNA'//
     611X,'BROJ CVOROVA CELIJA ...........................  NCVP =',I5//
     611X,'BROJ SLOBODNIH CVOROVA ........................ NPEFG =',I5//
     611X,'POLUPRECNIK OKO INTEGRACIONE TACKE ......... RADIJ =',F10.3)
C-----------------------------------------------------------------------
 6004 FORMAT(
     111X,'2/D ELEMENT TYPE IN THE CURRENT GROUP .......... IETYP =',I5/
     116X,'EQ.0; PLANE STRESS'/
     116X,'EQ.1; AXISYMMETRIC'/
     116X,'EQ.2; PLANE STRAIN'/
     116X,'EQ.3; PLANE STRESS IN SPACE'/
     116X,'EQ.4; SHEAR PANEL IN SPACE'//)
 6000 FORMAT(
     611X,'NUMBER OF GAUSS POINTS IN R-DIRECTION ......... NGAUSX =',I5/
     616X,'EQ.0; NGAUSX = 2'//)
 6002 FORMAT(
     611X,'NUMBER OF GAUSS POINTS IN S-DIRECTION ......... NGAUSY =',I5/
     616X,'EQ.0; NGAUSY = 2'//)
 6001 FORMAT(
     611X,'NUMBER OF NEWTON-COTES POINTS IN R-DIRECTION .. NGAUSX =',I5/
     6//)
 6003 FORMAT(
     611X,'NUMBER OF NEWTON-COTES POINTS IN S-DIRECTION .. NGAUSY =',I5/
     6//)
 6010 FORMAT(
     611X,'NUMBER OF DIFFERENT MULTILAYERD MATERIAL SETS ... MSET =',I5/
     616X,'GT.0; MULTILAYERD SHELL'///
     611X,'ANGLE OF SETS TO REFERENT DIRECTION ........ BETA =',1PD10.3/
     6//11X,'MAXIMUM NUMBER OF LAYERS .................. MSLOJ =',5X,I5)
 6020 FORMAT(
     611X,'ANGLE OF FIBER TO REFERENT DIRECTION ....... BETA =',1PD10.3)
 6025 FORMAT(//
     611X,'COORDINATES FOR PROJECTING DIRECTION ....... CPPX =',1PD10.3/
     611X,'                                     ....... CPPY =',1PD10.3/
     611X,'                                     ....... CPPZ =',1PD10.3/
     6//
     611X,'METHOD OF INCOMPATIBLE MODES ................... IALFA =',I5/
     616X,'EQ.-1; NOT USED'/
     616X,'EQ. 0; IALFA=1'/
     616X,'EQ. 1; 4 PARAMETERS - TAYLOR'/
     616X,'EQ. 2; 5 PARAMETERS')
 6030 FORMAT(///' NOT ENOUGH SPACE IN WORKING VECTOR  A'
     1/' REQUESTED DIMENSION , LMAX=',I10
     2/' AVAILABLE DIMENSION , MTOT=',I10)           
 6035 FORMAT(//
     611X,'BASE TYPE ..................................... NBASE =',I5/ 
     616X,'EQ. 3; LINEAR'/
     616X,'EQ. 6; CVADRATIC'/
     616X,'EQ.10; KUBIC'//
     611X,'TOTAL NUMBER OF NODES FOR CELLS ...............  NCVP =',I5//
     611X,'TOTAL NUMBER OF FREE NODES .................... NPEFG =',I5//
     611X,'RADIUS AROUND INTEGRATION POINT ............ RADIJ =',F10.3)
C-----------------------------------------------------------------------
      END
C=======================================================================
C
C=======================================================================
      SUBROUTINE U22EK(AU)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.   P R O G R A M
CE.      TO FORM POINTERS AND READING INPUT DATA ABOUT 2/D ELEMENTS
CE.      IN VECTOR AU
CS.   P R O G R A M
CS.      ZA FORMIRANJE REPERA I U VEKTOR AU UCITAVANJE OPSTIH ULAZNIH 
CS.      PODATAKA O ELEMENTIMA: 2/D, TROUGAO
C .
C ......................................................................
C
      include 'paka.inc'
      
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /SIMO2D/ LALFE,LHAEM,LHINV,LGEEK,IALFA
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /UGAOVL/ TE(4,4)
      COMMON /ORIENT/ CPP(3,3),XJJ(3,3),TSG(6,6),BETA,LBET0,IBB0
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD 
      COMMON /GLAVNI/ NP,NGELEM,NMATM,NPER,
     1                IOPGL(6),KOSI,NDIN,ITEST
      COMMON /REPERI/ LCORD,LID,LMAXA,LMHT
      COMMON /DUPLAP/ IDVA
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /BTHDTH/ INDBTH,INDDTH,LTBTH,LTDTH
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /INTGRA/ INCOTX,INCOTY,INCOTZ
      COMMON /MASINA/ INDPC,ICRTA
      COMMON /RESTAR/ TSTART,IREST
      COMMON /SRPSKI/ ISRPS
      COMMON /PODTIP/ IPODT
      COMMON /SPANEL/ ISHEAR
      COMMON /GAUSVR/ LTEMGT,LCORGT,ICORGT
      COMMON /CVSILE/ NSILA,LESILA
      COMMON /MIXEDM/ MIXED,IOPGS(6),NDS
      COMMON /LEVDES/ ILEDE,NLD,ICPM1
      COMMON /SUMELE/ ISUMEL,ISUMGR
      COMMON /COMEFG/ RADIJ,NBASE,NCVP,NPEFG,NCVS,NS,LCORS,LNOC,LNOS
      DIMENSION AU(*)
      REAL AU
      COMMON /CDEBUG/ IDEBUG
C
      IF(IDEBUG.GT.0) PRINT *, ' UL2EK'
      LMAX8=LMAX8+1
      IF(IREST.EQ.1) THEN
        LMA8=LMAX8
        READ(IELEM,REC=LMAX8)
     1IETYP,NGAUSX,NGAUSY,BETA,NCVE,ITERME,ICORGT,LCEL,LELC,NMA,NMI,
     1MXAU,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,LLMEL,IPODT,ISHEAR,
     1ND,NGS12,MSLOJ,MXS,MSET,NSILA,LESILA,LCORS,LNOC,LNOS,
     1LNSLOJ,LMATSL,LDSLOJ,LBBET,INCOTX,INCOTY,INCOTZ,
     1LBET0,(CPP(J,1),J=1,3),IBB0,LALFE,LHAEM,LHINV,LGEEK,IALFA,
     1INDBTH,INDDTH,LTBTH,LTDTH,RADIJ,NBASE,NCVP
     1,NPEFG,NCVS,NS 
        CALL READDD(AU(LNSLOJ),MXAU/IDVA,IELEM,LMAX8,LDUZI)
        LMAX8=LMA8
      ENDIF
C             
c      print*,nld,icpm1
CS     POZIVANJE PROGRAMA ZA ULAZNE PODATKE  O  2/D ELEMENTIMA
CE     CALL ROUTINE FOR INPUT DATA ABOUT 2/D ELEMENTS
C      
      NMA=0
      NMI=0
      CALL U22EKC(AU(LNEL),AU(LNMAT),AU(LIPGC),AU(LISNA),AU(LIPRC),
     1            AU(LTHID),AU(LNSLOJ),AU(LMATSL),AU(LBBET),AU(LDSLOJ),
     1            AU(LTBTH),AU(LTDTH),au(lcel),NMA,NMI,ICVEL)
C PAZNJA!!!! NIJE DOGRADJEN UGAO PROJEKCIONOG PRAVCA U LBET0 ZA IBB0=1    
      NS=NE*NGAUSX*NGAUSY
      LCORS=LNEL+NE*NCVE
      LNOC=LCORS+NCVP*3*IDVA
      LNOS=LNOC+NS
      LHE=LNOS+NS*100
      CALL ICLEAR(AU(LNOS),NS*100)
      CALL DELJIV(LHE,2,INDL)
      IF(INDL.EQ.0) LHE=LHE+1
      LMXAU=LHE+3*NCVE*IDVA
      NTOT=LMAX+LMXAU-LNSLOJ
      IF(NTOT.GT.MTOT) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2005) NTOT,MTOT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6005) NTOT,MTOT
      STOP
      ENDIF
      CALL CLEAR(AU(LBET0),NE)
C      
C               CALL U2AZE9(AU(LCORS),NCVP)
C        STAMPANJE KOORDINATA PRESEKA U UNV FILE
CE    WRITING DATA ABOUT ELEMENTS IN GRAPHIC OUTPUT FILES
      ISUMG=ISUMGR
      ISUME=ISUMEL
      IF(NBLGR.GE.0)
     1CALL TGRAFE(AU(LNEL),AU(LCEL),ICVEL,AU(LTHID),AU(LNMAT))
C
      ISUMGR=ISUMG
      ISUMEL=ISUME
      IF(NBLGR.GE.0) 
     +CALL TGRAU2(AU(LNEL),AU(LCEL),ICVEL,AU(LNMAT),AU(LTHID),49)
C         IF(NBLGR.GE.0) CALL TGRA9K(AU(LCORS),NCVP,IGRA1)
C     FORMIRANJE ELEMENATA ZA GAUSS TACKE
C      CALL ELEFG(A(LCORD),AU(LCORS),AU(LNEL),AU(LNOC),AU(LNOS),AU(LHE),
C     CALL ELEFG(A(LCORD),A(LCORD),AU(LNEL),AU(LNOC),AU(LNOS),AU(LHE),
C    1           NP,NCVP,NE,NS,RADIJ,NCVS,au(lipgc))
      CALL ELEFG(A(LCORD),A(LCORD),AU(LNEL),AU(LNOC),AU(LNOS),AU(LHE),
     1           NP,NP,NE,NS,RADIJ,NCVS,au(lipgc)) 
C
c      CALL T2RAFE(AU(LNos),AU(LCEL),ICVEL,AU(LTHID),AU(LNMAT))
c      IF(NBLGR.GE.0)
c     1CALL TGRAFE(AU(LNEL),AU(LCEL),ICVEL,AU(LTHID),AU(LNMAT))
      IF(ICVEL.EQ.1) CALL VEZACE(AU(LNEL),A(LELCV),NE,NCVE)
C
      K4=3
      IF(IETYP.EQ.1) K4=4
      NDS=0
      IF(MIXED.EQ.1) NDS=NCVE*K4
      NCVE2=NCVs*2 
      IF(IETYP.LE.2) THEN
         ND=NCVE2
      ELSE
         ND=NCVs*3
      ENDIF
      LLMEL=Lnos+Ns*NCVs
      LELC=LLMEL
      IF(ICVEL.EQ.1) THEN
        LLMEL=LELC+NMA-NMI+1
        LMAX=LAU+LLMEL-1
        IF(LMAX.GT.MTOT) GO TO 4
        CALL ICLEAR(AU(LELC),NMA-NMI+1)
        CALL VEZAEL(AU(LCEL),AU(LELC),NE,NMI)
      ENDIF
      LMXAU=LLMEL+ns*nd
      LALFE=LMXAU
      LHAEM=LMXAU
      LHINV=LMXAU
      LGEEK=LMXAU
      IF(NCVE.NE.4) IALFA=-1
      LA=1
      IF(IALFA.EQ.1) LA=4
      IF(IALFA.EQ.2) LA=5
      IF(IALFA.EQ.3) LA=4
      CALL DELJIV(LMXAU,2,INDL)
      IF(INDL.EQ.0) LMXAU=LMXAU+1
      IF(IALFA.GE.0) THEN
         LALFE=LMXAU
         LHAEM=LALFE+NE*LA*IDVA
         LHINV=LHAEM+NE*LA*IDVA
         LGEEK=LHINV+NE*LA*LA*IDVA
         LMXAU=LGEEK+NE*LA*NCVE2*IDVA
      ENDIF
      LESILA=LMXAU
      
      LMXAU=LESILA+NSILA*ND*IDVA
C
      MXAU = LMXAU - 1
      CALL DELJIV(MXAU,2,INDL)
      IF(INDL.EQ.1) MXAU=MXAU+1
      LMAX=LAU+MXAU
    4 IF(LMAX.GT.MTOT) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2005) LMAX,MTOT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6005) LMAX,MTOT
      STOP
      ENDIF
C
CE    FORM VECTOR LM AND HEIGHT COLUMNS IN STIFFNESS MATRIX
CS    FORMIRANJE VEKTORA LM I VISINA STUBOVA
C
      IF((IALFA.GE.0.OR.NSILA.GT.0).AND.IREST.NE.1) 
     1CALL CLEAR(AU(LALFE),(LMXAU-LALFE)/IDVA)
c      NDNDS=ND+NS
c      NDNDS=ND+NDS
c      NLMM=NE*NDNDS
      NLMM=NS*ND
c      NLMM=NE*NDNDS
      CALL ICLEAR(AU(LLMEL),NLMM)
      CALL L2IMHT(A(LID),AU(LNOC),AU(LNOS),AU(LLMEL),NP,ns,nd,IETYP)
c      CALL LMIMHT(A(LID),AU(LNEL),AU(LLMEL),NDNDS,K4)
C
      NGS12=NGAUSX*NGAUSY
C
CS    ZAPISIVANJE SKALARA NA DIREKT ACCES FILE 
CE    WRITE SCALARS TO A DIRECT ACCESS FILE
C
      IF(LDUZI.LE.100) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2000) LDUZI
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6000) LDUZI
      STOP
      ENDIF
      WRITE(IELEM,REC=LMAX8)
     1IETYP,NGAUSX,NGAUSY,BETA,NCVE,ITERME,ICORGT,LCEL,LELC,NMA,NMI,
     1MXAU,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,LLMEL,IPODT,ISHEAR,
     1ND,NGS12,MSLOJ,MXS,MSET,NSILA,LESILA,LCORS,LNOC,LNOS,
     1LNSLOJ,LMATSL,LDSLOJ,LBBET,INCOTX,INCOTY,INCOTZ,
     1LBET0,(CPP(J,1),J=1,3),IBB0,LALFE,LHAEM,LHINV,LGEEK,IALFA,
     1INDBTH,INDDTH,LTBTH,LTDTH,RADIJ,NBASE,NCVP
     1,NPEFG,NCVS,NS
      CALL WRITDD(AU(LNSLOJ),MXAU/IDVA,IELEM,LMAX8,LDUZI)
      CALL DELJIV(LMAX,2,INDL)
      IF(INDL.EQ.0) LMAX=LMAX+1
C
      LPLAST=LMAX
      LPLAS1=LMAX
      LSIGMA=LMAX
      IF(IATYP.EQ.0) GO TO 10
      IF(NMODM.LE.4) GO TO 10
      NPROS=NE*NGS12*MXS*MODPR2( NMODM )*IDVA
      LPLAS1=LPLAST+NPROS
      LMAX=LPLAS1+NPROS
      IF(LMAX.GT.MTOT) CALL ERROR(1)
      IF(IREST.NE.1) THEN
         CALL CLEAR(A(LPLAST),NPROS*2/IDVA)
         CALL WRITDD(A(LPLAST),NPROS/IDVA,IELEM,LMAX8,LDUZI)
         CALL WRITDD(A(LPLAS1),NPROS/IDVA,IELEM,LMAX8,LDUZI)
      ELSE
         CALL READDD(A(LPLAST),NPROS/IDVA,IELEM,LMAX8,LDUZI)
         CALL READDD(A(LPLAS1),NPROS/IDVA,IELEM,LMAX8,LDUZI)
      ENDIF
      IF(IATYP.GE.4) GO TO 10
      NPROS=0
      LSIGMA=LMAX
      IF(ITERME.EQ.1) GO TO 20
      IF(ICORGT.EQ.1) GO TO 30
      RETURN
C
   10 LSIGMA=LMAX
      N45=4
      NPROS=NE*NGS12*N45*MXS*IDVA
      LMAX=LSIGMA+NPROS
      LCOR0=LMAX
      IF(IATYP.GE.4) THEN
         NPRO1=Ne*NCVE*3*IDVA
         LMAX=LCOR0+NPRO1
         NPROS=NPROS+NPRO1
      ENDIF
   20 LTEMGT=LMAX
      IF(ITERME.EQ.1) THEN
         NPRO1=NE*NGS12*MXS*IDVA
         LMAX=LTEMGT+NPRO1
         NPROS=NPROS+NPRO1
      ENDIF
   30 LCORGT=LMAX
      IF(ICORGT.EQ.1) THEN
         NPRO1=NE*NGS12*3*MXS*IDVA
         LMAX=LCORGT+NPRO1
         NPROS=NPROS+NPRO1
      ENDIF
      IF(LMAX.GT.MTOT) CALL ERROR(1)
      IF(IREST.NE.1) THEN
         CALL CLEAR(A(LSIGMA),NPROS/IDVA)
C
CS       ZADAVANJE POCETNE VREDNOSTI ZA - B
CE       INITIAL VALUE FOR - B 
C
         IF(IATYP.GE.4)
     1   CALL Z2DA2B(A(LSIGMA),Ne,NGS12,MXS,N45)
         CALL WRITDD(A(LSIGMA),NPROS/IDVA,IELEM,LMAX8,LDUZI)
      ELSE
         CALL READDD(A(LSIGMA),NPROS/IDVA,IELEM,LMAX8,LDUZI)
      ENDIF
      RETURN
C-----------------------------------------------------------------------
 2000 FORMAT(//' DUZINA STAZE RECL=LDUZI=',I5,' ZA FILE=IELEM, ACCESS=
     1DIRECT, MORA BITI VECA OD    100'//' PROGRAM STOP'//)
 2005 FORMAT(///' NEDOVOLJNA DIMENZIJA U VEKTORU A ZA PODATKE O 2D ELEME
     1NTIMA'/' POTREBNA DIMENZIJA , LMAX=',I10/' RASPOLOZIVA DIMENZIJA,
     2NTOT =',I10)
C-----------------------------------------------------------------------
 6000 FORMAT(//' RECORD LENGHT RECL=LDUZI=',I5,'  FILE=IELEM, ACCESS=
     1DIRECT, MUST BE  .GT. THEN  100'//' PROGRAM STOP'//)
 6005 FORMAT(///' NOT ENOUGH SPACE IN WORKING VECTOR A FOR 2/D ELEMENTS'
     1/' REQUESTED DIMENSION , LMAX=',I10
     2/' AVAILABLE DIMENSION , MTOT=',I10)
C-----------------------------------------------------------------------
      END
C=======================================================================
C
C=======================================================================
      SUBROUTINE U22EKC(NEL,MATV,IPGCV,ISNAP,IPRCV,THICK,NSLOJ,MATSL,
     1                 BBET,DSLOJ,TBTH,TDTH,mcvel,NMA,NMI,ICVEL)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.   P R O G R A M
CE.      TO READING INPUT DATA ABOUT 2/D ELEMENTS - FREE NUMBERING
CS.   P R O G R A M
CS.      ZA UCITAVANJE ULAZNIH PODATAKA O ELEMENTIMA: 2/D, TROUGAO
C .
C ......................................................................
C
      CHARACTER*250 ACOZ
      CHARACTER*5  CH
C
      include 'paka.inc'
      
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /BROJUK/ KARTIC,INDFOR,NULAZ
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /BTHDTH/ INDBTH,INDDTH,LTBTH,LTDTH
      COMMON /GAUSVR/ LTEMGT,LCORGT,ICORGT
      COMMON /SRPSKI/ ISRPS
      COMMON /PODTIP/ IPODT
      COMMON /CVSILE/ NSILA,LESILA
      COMMON /RESTAR/ TSTART,IREST
C
      DIMENSION NEL(NE,*),MATV(*),IPGCV(*),ISNAP(*),IPRCV(*),THICK(NE,*)
     1         ,NSLOJ(*),MATSL(MSLOJ,*),BBET(MSLOJ,*),DSLOJ(MSLOJ,*),
     1          TBTH(*),TDTH(*),MCVEL(*),THI(4)
      DIMENSION PODT(9)
      COMMON /CDEBUG/ IDEBUG
C
      IF(IDEBUG.GT.0) PRINT *, ' UL2EKC'
      NDEB=1
      IF(IATYP.GT.3) THEN
         NDEB=4
         IF(IPODT.EQ.1) NDEB=3
      ENDIF
      IF(ISRPS.EQ.0) CH=' BROJ'
      IF(ISRPS.EQ.1) CH='NUMBE'
      MXS=1 
c      nge=1
      ICORGT=1
C
CS     P  O  D  A  C  I      O      S  L  O  J  E  V  I  M  A
CE     D  A  T  A      A  B  O  U  T      L  A  Y  E  R  S
C
      IF(MSET.GT.0) THEN
         CH='  SET'
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,2500)
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,6500)
         DO 2 I=1,MSET
            CALL ISPITA(ACOZ)
            IF(INDFOR.EQ.1)
     1      READ(IULAZ,*) NSLOJ(I)
            IF(INDFOR.EQ.2)
     1      READ(ACOZ,1000) NSLOJ(I)
            IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2530) I,NSLOJ(I)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6530) I,NSLOJ(I)
            ENDIF
            IF(NSLOJ(I).LT.1.OR.NSLOJ(I).GT.MSLOJ) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2505)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6505)
               STOP 'STOP - UL2EKC'
            ENDIF
            IF(NSLOJ(I).GT.MXS) MXS=NSLOJ(I) 
            TTT=0.D0
            DO 1 J=1,NSLOJ(I)
               CALL ISPITA(ACOZ)
               IF(INDFOR.EQ.1)
     1         READ(IULAZ,*)   MATSL(J,I),DSLOJ(J,I),BBET(J,I)
               IF(INDFOR.EQ.2)
     1         READ(ACOZ,1515) MATSL(J,I),DSLOJ(J,I),BBET(J,I)
               IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2540) J,MATSL(J,I),DSLOJ(J,I),BBET(J,I)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6540) J,MATSL(J,I),DSLOJ(J,I),BBET(J,I)
               ENDIF
               BBET(J,I)=BBET(J,I)*3.1415926536D0/180.D0
               TTT=TTT+DSLOJ(J,I)
    1       CONTINUE
CS....      PROVERA ZA DEBLJINE
            IF(DABS(TTT-1.D0).LT.1.D-6) GO TO 2
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2550) TTT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6550) TTT
            STOP 'STOP - UL2EKC'
    2    CONTINUE      
      ENDIF
C
CS    P  O  D  A  C  I      O      E  L  E  M  E  N  T  I  M  A
CE    D  A  T  A      A  B  O  U  T      E  L  E  M  E  N  T  S
C
      IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
         IF(IPODT.EQ.0) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2000) NGE,CH
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6000) NGE,CH
         ENDIF
         IF(IPODT.EQ.1) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2010) NGE,CH
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6010) NGE,CH
         ENDIF
      ENDIF
      IT1=4
      IT2=9
      IF(IPODT.EQ.1) THEN
         IT1=3
         IT2=6
      ENDIF
      NMATS=  1
      IPRCOS=-1
      IPGSS= -1
      ISNAA= -1
      THICS=  1.0D0
      I = 0
      NAUT=0
    5 I = I + 1
      CALL ISPITA(ACOZ)
      IF(I.EQ.1) KARTI=KARTIC
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) NN,NMAT,IPRCO,ISNA,IPGS,THI(1),KORC,BTH,DTH,
     +              (THI(J),J=2,NDEB)
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1010) NN,NMAT,IPRCO,ISNA,IPGS,THI(1),KORC,BTH,DTH,
     +                (THI(J),J=2,NDEB)
      IF(IPRCO.EQ.1) ICORGT=1
      IF(ICVEL.EQ.1) THEN
         MCVEL(I)=NN
         NI=NN
         IF(I.EQ.1) THEN
            NMA=NN
            NMI=NN
         ELSE
            IF(NMA.LT.NN) NMA=NN
            IF(NMI.GT.NN) NMI=NN
         ENDIF
         NN=I
      ENDIF 
      CALL ISPITA(ACOZ)
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) (NEL(NN,J),J=1,NCVE)
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1000) (NEL(NN,J),J=1,NCVE)
      IF(NMAT.EQ.0) NMAT=NMATS
      NMATS=NMAT
      MATV(NN)= NMAT
      IF(IPRCO.EQ.0) IPRCO=IPRCOS
      IPRCOS=IPRCO
      IF(IPRCO.LT.0) IPRCO = 0
      IPRCV(NN)=IPRCO
      IF(ISNA.EQ.0) ISNA=ISNAA
      ISNAA=ISNA
      IF(ISNA.LT.0) ISNA = 0
      ISNAP(NN)=ISNA
c      ipgs=1
      IF(IPGS.EQ.0) IPGS=IPGSS
      IPGSS=IPGS
      IF(IPGS.LT.0) IPGS = 0
      IPGCV(NN)=IPGS
      IF(DABS(THI(1)).LT.1.D-10) THI(1)=THICS
      THICS=THI(1)
      THICK(NN,1)=THI(1)
      DO 731 J=2,NDEB
C         RELATIVNE DEBLJINE
C         IF(DABS(THI(J)).LT.1.D-10) THI(J)=1.D0
C         THICK(NN,J)=THI(1)*THI(J)
C        UKUPNE DEBLJINE
         IF(DABS(THI(J)).LT.1.D-10) THI(J)=THI(1)
         THICK(NN,J)=THI(J)
  731 CONTINUE
      IF(INDBTH.EQ.1) TBTH(NN)=BTH
      IF(INDDTH.EQ.1) TDTH(NN)=DTH
      IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
         IF(ICVEL.EQ.1) IN=MCVEL(NN)
         IF(ICVEL.EQ.0) IN=NN
         IF(IPODT.EQ.0) WRITE(IZLAZ,5000) IN,(NEL(NN,J),J=1,IT1),NMAT,
     1                  IPRCO,ISNA,IPGS,THI(1),KORC,(THI(J),J=2,NDEB)
         IF(IPODT.EQ.0.AND.NCVE.GT.IT1) 
     +                  WRITE(IZLAZ,5011) (NEL(NN,J),J=IT1+1,NCVE)
         IF(IPODT.EQ.1) WRITE(IZLAZ,5002) IN,(NEL(NN,J),J=1,IT1),NMAT,
     1                  IPRCO,ISNA,IPGS,THI(1),KORC,(THI(J),J=2,NDEB)
         IF(IPODT.EQ.1.AND.NCVE.GT.IT1) 
     +                  WRITE(IZLAZ,5013) (NEL(NN,J),J=IT1+1,NCVE)
         IF(INDBTH.EQ.1) THEN
         IF(DABS(TBTH(NN)).GT.1.0D-10) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2040) TBTH(NN)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6040) TBTH(NN)
         ENDIF
         ENDIF
         IF(INDDTH.EQ.1) THEN 
         IF(DABS(TDTH(NN)).GT.1.0D-10) THEN 
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2050) TDTH(NN)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6050) TDTH(NN)
         ENDIF
         ENDIF
      ENDIF
      IF(NAUT.GT.0) GO TO 30
      IF(KORC.NE.0) GO TO 20
      IF(I.EQ.NE) GO TO 50
      GO TO 5
C
   20 NAUT=1
      IF(ICVEL.EQ.1) N1=NI
      IF(ICVEL.EQ.0) NN1=NN
      KORA=KORC
      GO TO 5
C
CS    AUTOMATSKO GENERISANJE PODATAKA IZMEDJU CVOROVA N1 I N2
CE    AUTOMATIC  GENERATION BETWEN NODES  N1  AND  N2
C
   30 NN2=NN
      IF(ICVEL.EQ.1) THEN
         NN1=NN-1
         N2=NI
      ENDIF
      N11=NEL(NN1,1)
      N22=NEL(NN2,1)
      N12=N22-N11
      CALL DELJIV(N12,KORA,INDD)
      IF(INDD.EQ.1) GO TO 100
      DO 40 NC=2,IT1
         N11=NEL(NN1,NC)
         N22=NEL(NN2,NC)
         N21=N22-N11
         IF(N12.NE.N21) GO TO 100
   40 CONTINUE
      IF(NCVE.GT.IT1) THEN
         DO 45 NC=IT1+1,NCVE
            N11=NEL(NN1,NC)
            N22=NEL(NN2,NC)
            IF(N11.EQ.0.AND.N22.EQ.0) GO TO 45
            N21=N22-N11
            IF(N12.NE.N21) GO TO 100
   45    CONTINUE
      ENDIF
      IF(ICVEL.EQ.1) NNN=N2-N1-1
      IF(ICVEL.EQ.0) NNN=NN2-NN1-1
      NGG=N12/KORA-1
      IF(NNN.NE.NGG) THEN
         IF(ICVEL.EQ.1) THEN
            NN1=N1
            NN2=N2
         ENDIF
         GO TO 150
      ENDIF
      IAUT=N12/KORA-1
      IF(ICVEL.EQ.1) THEN
         NM=NN+IAUT
         MCVEL(NM)=MCVEL(NN)
         MATV(NM) = MATV(NN)
         IPRCV(NM)=IPRCV(NN)
         ISNAP(NM)=ISNAP(NN)
         IPGCV(NM)=IPGCV(NN)
         DO 732 J=1,NDEB
            THICK(NM,J)=THICK(NN,J)
  732    CONTINUE
         IF(INDBTH.EQ.1) TBTH(NM) = TBTH(NN)
         IF(INDDTH.EQ.1) TDTH(NM) = TDTH(NN)
         DO 32 II=1,NCVE
            NEL(NM,II)=NEL(NN,II)
   32    CONTINUE
      ENDIF
      DO 34 J=1,IAUT
         JJ=NN1+J
         IF(ICVEL.EQ.1) THEN
            N1=N1+1
            MCVEL(JJ)=N1
         ENDIF
         MATV(JJ) = MATV(NN1)
         IPRCV(JJ)=IPRCV(NN1)
         ISNAP(JJ)=ISNAP(NN1)
         IPGCV(JJ)=IPGCV(NN1)
         DO 735 II=1,NDEB
            THICK(JJ,II)=THICK(NN1,II)
  735    CONTINUE
         IF(INDBTH.EQ.1) TBTH(JJ) = TBTH(NN1)
         IF(INDDTH.EQ.1) TDTH(JJ) = TDTH(NN1)
         DO 35 II=1,NCVE
            NODP=NEL(JJ-1,II)
            NEL(JJ,II)=NODP+KORA
            IF(NODP.EQ.0) NEL(JJ,II) = 0
   35    CONTINUE
   34 CONTINUE
      IF(ICVEL.EQ.1) I=NM
      IF(ICVEL.EQ.0) I=I+IAUT
      IF(I.EQ.NE) GO TO 50
      NAUT=0
      IF(KORC.EQ.0) GO TO 5
      KORA=KORC
      NAUT=1
      IF(ICVEL.EQ.1) N1=N2
      IF(ICVEL.EQ.0) NN1=NN2
      GO TO 5
C
CS    ODREDJIVANJE MAKSIMALNOG BROJA CVOROVA
CE    OBTAIN MAXIMUM NUMBER OF NODES PER ELEMENT
C
   50 IF(IREST.EQ.1) GO TO 61
      NCVE=IT1
      DO 60 I=1,NE
      DO 60 J=IT1+1,IT2
         IJ=NEL(I,J)
         IF(IJ.GT.0.AND.J.GT.NCVE) NCVE=J
   60 CONTINUE
C
   61 NSILA=0
      IF(IETYP.GT.2) THEN
         CALL ICLEAR(IPGCV,NE)
      ELSE
      DO 65 I=1,NE
         IF(IPGCV(I).EQ.1) THEN
            NSILA=NSILA+1
            IPGCV(I)=NSILA
         ELSE
            IPGCV(I)=0
         ENDIF
   65 CONTINUE
      ENDIF
C
CS    STAMPANJE UCITANIH I GENERISANIH PODATAKA
CE    PRINT INPUT AND GENERATED DATA
C
      IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
         CALL WBROJK(KARTI,0)
         IF(IPODT.EQ.0) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2140) NGE,CH
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6140) NGE,CH
         ENDIF
         IF(IPODT.EQ.1) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2240) NGE,CH
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6240) NGE,CH
         ENDIF
         DO 70 I=1,NE
            IF(ICVEL.EQ.1) IN=MCVEL(I)
            IF(ICVEL.EQ.0) IN=I
            IF(IPODT.EQ.0) WRITE(IZLAZ,5001) IN,(NEL(I,J),J=1,IT1),
     1                     MATV(I),IPRCV(I),ISNAP(I),IPGCV(I),
     +                     (THICK(I,J),J=1,NDEB)
            IF(IPODT.EQ.0.AND.NCVE.GT.IT1) 
     1                     WRITE(IZLAZ,5011) (NEL(I,J),J=IT1+1,NCVE)
            IF(IPODT.EQ.1) WRITE(IZLAZ,5003) IN,(NEL(I,J),J=1,IT1),
     1                     MATV(I),IPRCV(I),ISNAP(I),IPGCV(I),
     +                     (THICK(I,J),J=1,NDEB)
            IF(IPODT.EQ.1.AND.NCVE.GT.IT1) 
     1                     WRITE(IZLAZ,5013) (NEL(I,J),J=IT1+1,NCVE)
         IF(INDBTH.EQ.1) THEN
         IF(DABS(TBTH(I)).GT.1.0D-10) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2040) TBTH(I)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6040) TBTH(I)
         ENDIF
         ENDIF
         IF(INDDTH.EQ.1) THEN 
         IF(DABS(TDTH(I)).GT.1.0D-10) THEN 
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2050) TDTH(I)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6050) TDTH(I)
         ENDIF
         ENDIF
   70    CONTINUE
      ENDIF
C
      IF(IPODT.EQ.1) THEN
         NCVZ=2
         IF(NCVE.EQ.3) NCVZ=1
         NCVE=NCVE+NCVZ
         DO 170 I=1,NE
            DO 171 J=4,IT2
               PODT(J)=NEL(I,J)
  171       CONTINUE
            NEL(I,4)=NEL(I,1)
            IF(NCVE.GT.4) THEN
               NEL(I,8)=NEL(I,1)
               DO 172 J=1,3
                  NEL(I,J+4)=PODT(J+3)
  172          CONTINUE
            ENDIF
  170    CONTINUE
      ENDIF
      RETURN
C
  150 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2110) NN1,NN2,NGG
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6110) NN1,NN2,NGG
      STOP
C
  100 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2100) N22,N11,KORA
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6100) N22,N11,KORA
      STOP
C
 1000 FORMAT(14I5)
 1010 FORMAT(5I5,F10.0,I5,2F10.0,3F5.3)
 1515 FORMAT(I5,2F10.0)
 5000 FORMAT(I6,1X,4I6,5X,4I6,1PD11.3,I6,3(1PD11.3))
 5001 FORMAT(I6,1X,4I6,5X,4I6,4(1PD11.3))
 5011 FORMAT(6X,5I6)
 5002 FORMAT(I6,3X,3I8,3X,4I6,1PD11.3,I6,3(1PD11.3))
 5003 FORMAT(I6,3X,3I8,3X,4I6,4(1PD11.3))
 5013 FORMAT(6X,3I8)
C-----------------------------------------------------------------------
 2000 FORMAT(///' UCITANI PODACI O CETVOROUGAONIM 2/D ELEMENTIMA GRUPE E
     1LEMENATA',I6/1X,68('-')///
     1' ELEME  CVOR1 CVOR2 CVOR3 CVOR4      MATER KOORD NAPON NAPON  DEB
     1LJINA  KORAK'/
     1'  BROJ CVOR5 CVOR6 CVOR7 CVOR8 CVOR9 ',A5,' STAMP STAMP CVORA  EL
     1EMENTA  GENER')
 2010 FORMAT(///' UCITANI PODACI O TROUGAONIM 2/D ELEMENTIMA GRUPE ELEME
     1NATA',I6/1X,64('-')///
     1' ELEME      CVOR1   CVOR2   CVOR3    MATER KOORD NAPON NAPON  DEB
     1LJINA  KORAK'/
     1'  BROJ   CVOR4   CVOR5   CVOR6       ',A5,' STAMP STAMP CVORA  EL
     1EMENTA  GENER')
 2100 FORMAT(///' BROJ CVORA N2=',I5,' NE MOZE SE DOBITI SABIRANJEM BROJ
     1A CVORA N1=',I5,' I KONACNOG BROJA KORAKA KORA=',I5)
 2110 FORMAT(///' IZMEDJU ELEMENATA N1=',I5,' I N2=',I5,' NEMA NG=',I5,
     1' ELEMENATA KOJE TREBA GENERISATI')
 2140 FORMAT(' GENERISANI PODACI O CETVOROUGAONIM 2/D ELEMENTIMA GRUPE E
     1LEMENATA',I6/1X,71('-')///
     3' ELEME  CVOR1 CVOR2 CVOR3 CVOR4      MATER KOORD NAPON NAPON  DEB
     1LJINA'/
     1'  BROJ CVOR5 CVOR6 CVOR7 CVOR8 CVOR9 ',A5,' STAMP STAMP CVORA  EL
     1EMENTA')
 2240 FORMAT(' GENERISANI PODACI O TROUGAONIM 2/D ELEMENTIMA GRUPE ELEME
     1NATA',I6/1X,67('-')///
     1' ELEME      CVOR1   CVOR2   CVOR3    MATER KOORD NAPON NAPON  DEB
     1LJINA'/
     1'  BROJ   CVOR4   CVOR5   CVOR6       ',A5,' STAMP STAMP CVORA  EL
     1EMENTA')
 2500 FORMAT(///6X,' UCITANI PODACI O VISESLOJNIM SETOVIMA MATERIJALA'/
     16X,49('-')///)
 2505 FORMAT(///' BROJ SLOJEVA U MATERIJALNOM SETU MORA BITI VECI OD 0'/
     1' (MAKSIMALNO :     MSLOJ )')
 2530 FORMAT(//10X,'MATERIJALNI SET (',I3,') ',5X,'BROJ SLOJEVA =',I3/)
 2540 FORMAT(/10X,'SLOJ =',I3/10X,'MATERIJAL =',I3/10X,'RELATIVNA ',
     1'DEBLJINA =',1PD10.3/10X,'UGAO VLAKANA =',1PD10.3) 
 2550 FORMAT(/// ' ZBIR RELATIVNIH DEBLJINA SLOJEVA U MATERIJALNOM SETU 
     1MORA BITI   1.00'/' (KONTROLNI ZBIR JE :   TTT =',1PD10.3)
 2040 FORMAT(/' VREME NASTAJANJA ELEMENTA - TBTH =',1PD10.3)
 2050 FORMAT(/' VREME NESTAJANJA ELEMENTA - TDTH =',1PD10.3)
C-----------------------------------------------------------------------
 6000 FORMAT(///' READING DATA ABOUT TO ISOPARAMETRIC 2/D ELEMENTS FOR G
     1ROUP',I6/1X,64('-')///
     1' ELEME  NODE1 NODE2 NODE3 NODE4      MATER COORD STRES STRES    T
     1HICK    STEP'/
     1' NUMBE NODE5 NODE6 NODE7 NODE8 NODE9 ',A5,' PRINT PRINT  NODE   E
     1LEMENT  GENER')
 6010 FORMAT(///' READING DATA ABOUT TO ISOPARAMETRIC TRIANGULAR ELEMENT
     1S FOR GROUP',I6/1X,71('-')///
     1' ELEME      NODE1   NODE2   NODE3    MATER COORD STRES STRES    T
     1HICK    STEP'/
     1' NUMBE   NODE4   NODE5   NODE6       ',A5,' PRINT PRINT  NODE   E
     1LEMENT  GENER')
 6100 FORMAT(///' NODE NUMBER N2=',I5,' CAN NOT BE DEFINED BY SUPERPOSIT
     1ION OF NODE N1=',I5,' WITH A NUMBER OF STEPS  KORA=',I5)
 6110 FORMAT(///' AMONG ELEMENTS N1=',I5,' AND N2=',I5,' THERE IS NO  ',
     1'NG=',I5,' ELEMENTS TO GENERATE')
 6140 FORMAT (' GENERATED DATA ABOUT TO ISOPARAMETRIC 2/D ELEMENTS FOR G
     1ROUP',I6/1X,66('-')///
     1' ELEME  NODE1 NODE2 NODE3 NODE4      MATER COORD STRES STRES    T
     1HICK '/
     1' NUMBE NODE5 NODE6 NODE7 NODE8 NODE9 ',A5,' PRINT PRINT  NODE   E
     1LEMENT')
 6240 FORMAT (' GENERATED DATA ABOUT TO ISOPARAMETRIC TRIANGULAR ELEMENT
     1S FOR GROUP',I6/1X,73('-')///
     1' ELEME      NODE1   NODE2   NODE3    MATER COORD STRES STRES    T
     1HICK '/
     1' NUMBE   NODE4   NODE5   NODE6       ',A5,' PRINT PRINT  NODE   E
     1LEMENT')
 6500 FORMAT(///6X,' READING DATA ABOUT MULTILAYERED MATERIAL SETS'/
     16X,46('-')///)
 6505 FORMAT(///' NUMBER OF LAYERS IN MATERIAL SET MUST BE GREATER',
     1          ' THAN   0'/' (MAXIMUM :     MSLOJ )')
 6530 FORMAT(//10X,'MATERIAL SET (',I3,') ',5X,'NUMBER OF LAYERS =',I3/)
 6540 FORMAT(/10X,'LAYER =',I3/10X,'MATERIAL =',I3/10X,'RELATIV ',
     1'THICKNESS =',1PD10.3/10X,'FIBER ANGLE =',1PD10.3) 
 6550 FORMAT(/// ' RELATIV THICKNESSES SUM IN MATERIAL SET MUST BE', 
     1'   1.00'/' (CONTROL SUM IS :   TTT =',1PD10.3)
 6040 FORMAT(/' ELEMENT BIRTH TIME - TBTH =',1PD10.3)
 6050 FORMAT(/' ELEMENT DEATH TIME - TDTH =',1PD10.3)
C-----------------------------------------------------------------------
      END
C=======================================================================
C
C=======================================================================  
      SUBROUTINE U2AZE9(CORD,NP)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*1 CH
C
C ......................................................................
C .
CE.    P R O G R A M
CE.        TO READ NODAL POINT COORDINATES AND CONSTRAINTS SECTION
CS.    P R O G R A M
CS.        ZA UCITAVANJE KOORDINATA I OGRANICENJA CVORNIH TACAKA PRESEKA
C .
CE.           I=1,NP (NP - TOTAL NUMBEL OF NODAL POINT
CS.           I=1,NP (NP - UKUPAN BROJ CVORNIH TACAKA)
C .
CE.            CH - INDICATOR OF POLAR COORDINATES SYSTEM
CS.            CH - KARAKTER INDIKATOR POLARNOG KOORD. SISTEMA
C .
CE.            CORD(I,1) - X COORDINATE
CE.            CORD(I,2) - Y COORDINATE
CE.            CORD(I,3) - Z COORDINATE
CS.            CORD(I,1) - KOORDINATA  X
CS.            CORD(I,2) - KOORDINATA  Y
CS.            CORD(I,3) - KOORDINATA  Z
C .
CE.              ID(I,1) - CONSTRAINT OF TRANSLATION IN DIRECTION X AXIS
CE.              ID(I,2) - CONSTRAINT OF TRANSLATION IN DIRECTION Y AXIS
CE.              ID(I,3) - CONSTRAINT OF TRANSLATION IN DIRECTION Z AXIS
CE.              ID(I,4) - CONSTRAINT OF ROTATION AROUND X AXIS
CE.              ID(I,5) - CONSTRAINT OF ROTATION AROUND Y AXIS
CE.              ID(I,6) - CONSTRAINT OF ROTATION AROUND Z AXIS
CS.              ID(I,1) - OGRANICENJE POMERANJA U PRAVCU - X OSE
CS.              ID(I,2) - OGRANICENJE POMERANJA U PRAVCU - Y OSE
CS.              ID(I,3) - OGRANICENJE POMERANJA U PRAVCU - Z OSE
CS.              ID(I,4) - OGRANICENJE ROTACIJA OKO - X OSE
CS.              ID(I,5) - OGRANICENJE ROTACIJA OKO - Y OSE
CS.              ID(I,6) - OGRANICENJE ROTACIJA OKO - Z OSE
C .
C ......................................................................
C
      CHARACTER*250 ACOZ
      include 'paka.inc'
      
      COMMON /SISTEM/ LSK,LRTDT,NWK,JEDN,LFTDT
      COMMON /BROJUK/ KARTIC,INDFOR,NULAZ
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
      COMMON /PODTIP/ IPODT
      COMMON /SRPSKI/ ISRPS
      DIMENSION CORD(NP,*),DXYZ(3),ID(6)
      COMMON /CDEBUG/ IDEBUG
C
      IF(IDEBUG.GT.0) PRINT *, ' 2LAZE9'
      IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2030)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6030)
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2000)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6000)
      ENDIF
C
      I =0
      NAUT=0
    5 I=I+1
      CALL ISPITA(ACOZ)
      IF(I.EQ.1) KARTI=KARTIC
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) N,CH,(ID(J),J=1,6),(CORD(N,J),J=1,3),KORC
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1000) N,CH,(ID(J),J=1,6),(CORD(N,J),J=1,3),KORC
      IF(N.GT.NP) GO TO 110
      IF(NULAZ.EQ.1.OR.NULAZ.EQ.3)
     1WRITE(IZLAZ,5010) N,CH,(CORD(N,J),J=1,3),KORC
      IF(NAUT.GT.0) GO TO 30
      IF(KORC.NE.0) GO TO 20
      IF(CH.EQ.'p'.OR.CH.EQ.'P') CALL POLAR(CORD(N,1),CORD(N,2))
      IF(I.EQ.NP) GO TO 50
      GO TO 5
C
   20 NAUT=1
      N1=N
      KORA=KORC
      GO TO 5
C
CE    AUTOMATIC GENERATE DATA BETWEEN NODAL POINT N1 AND N2
CS    AUTOMATSKO GENERISANJE PODATAKA IZMEDJU CVOROVA N1 I N2
C
   30 N2=N
      CALL DELJIV(N2-N1,KORA,INDD)
      IF(INDD.EQ.1) GO TO 100
      RKORA = KORA
      RN1N2 = N2-N1
      DD = RKORA/RN1N2
      IF(DD.LT.0.0D00) GO TO 100
      DO 31 J=1,3
   31 DXYZ(J)=DD*(CORD(N2,J)-CORD(N1,J))
      IAUT=(N2-N1)/KORA-1
      N = N1
      DO 34 J=1,IAUT
      DO 35 K=1,3
   35 CORD(N+KORA,K)=CORD(N,K)+DXYZ(K)
      IF(CH.EQ.'p'.OR.CH.EQ.'P') CALL POLAR(CORD(N,1),CORD(N,2))
C      DO 36 K=1,6
C   36 ID(N+KORA,K)=ID(N1,K)
      N=N+KORA
   34 CONTINUE
      IF(CH.EQ.'p'.OR.CH.EQ.'P') CALL POLAR(CORD(N,1),CORD(N,2))
      I=I+IAUT
      IF(I.EQ.NP)THEN
        IF(CH.EQ.'p'.OR.CH.EQ.'P') CALL POLAR(CORD(N2,1),CORD(N2,2))
        GO TO 50
      ENDIF
      NAUT=0
      IF(KORC.EQ.0)THEN
        IF(CH.EQ.'p'.OR.CH.EQ.'P') CALL POLAR(CORD(N2,1),CORD(N2,2))
        GO TO 5
      ENDIF
      KORA=KORC
      NAUT=1
      N1=N2
      GO TO 5
C
CE    PRINT GENERATED DATA FOR NODAL POINTS
CS    STAMPANJE GENERISANIH PODATAKA O CVOROVIMA
C
   50 IF(NULAZ.NE.1.AND.NULAZ.NE.3) RETURN
      CALL WBROJK(KARTI,1)
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2020)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6020)
      DO 70 I=1,NP
      WRITE(IZLAZ,5030) I,(CORD(I,J),J=1,3)
   70 CONTINUE
      RETURN
C
  100 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2100) N2,N1,KORA
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6100) N2,N1,KORA
      STOP 'PROGRAM STOP: PAK221 - 2LAZE9'
C
  110 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2200) N,NP
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6200) N,NP
      STOP 'PROGRAM STOP: PAK221 - 2LAZE9'
C
 1000 FORMAT(I5,A1,6I2,2X,3F10.2,I5)
 5010 FORMAT(1X,I5,4X,A1,20X,3F12.6,I5,I5)
 5030 FORMAT(1X,I5,30X,3F12.6,I5)
C-----------------------------------------------------------------------
 2030 FORMAT(//////1X,
     1'U C I T A N I   P O D A C I   Z A   C E L I J E'/
     11X,47('-'))
 2000 FORMAT(////1X,
     1'U C I T A N I   P O D A C I   O   C V O R O V I M A'/
     11X,51('-')//
     21X,'(MOGUCE GENERISANJE PODATAKA O CVOROVIMA,'/
     32X,'UCITATI POTREBAN BROJ KARTICA ZA DEFINISANJE SVIH CVOROVA)'//
     11X,' CVOR KORD    OGRANICENJA          K  O  O  R  D  I  N  A  T 
     1E     KOR KOSI'/
     11X,' BROJ SIST NX NY NZ WX WY WZ        X           Y           Z
     1      GEN SIST')
 2020 FORMAT(1X,
     1'G E N E R I S A N I   P O D A C I   O   C V O R O V I M A'/
     11X,57('-')///
     11X,' CVOR  O  G  R  A  N  I  C  E  NJ  A    K  O  O  R  D  I  N  A
     1  T  E    KOSI'/
     11X,' BROJ   NX   NY   NZ   WX   WY   WZ      X           Y        
     1   Z      SIST')
 2100 FORMAT(///' BROJ N2=',I5,' NE MOZE SE DOBITI SABIRANJEM BROJA N1='
     1,I5,' I KONACNOG BROJA KORAKA KORA=',I5)
 2200 FORMAT(///' UCITANI CVOR BROJ N =',I5,' VECI JE OD UKUPNOG BROJA
     1CVORNIH TACAKA NP =',I5)
C-----------------------------------------------------------------------
 6030 FORMAT(//////1X,
     1'I N P U T   D A T A   F O R   C E L L S'/
     11X,43('-'))
 6000 FORMAT(////1X,
     1'I N P U T   N O D A L   D A T A'/
     11X,31('-')///
     11X,' NODE COOR    CONSTRAINTS        C  O  O  R  D  I  N  A  T  E
     1 S   STEP SKEW'/
     11X,' NUMB SYST NX NY NZ WX WY WZ        X           Y           Z
     1     GENE SYST')
 6020 FORMAT(1X,
     1'G E N E R A T E D   N O D A L   D A T A'/
     11X,39('-')///
     11X,' NODE  C  O  N  S  T  R  A  I  N  S   C  O  O  R  D  I  N  A  
     1T  E  S   SKEW'/
     11X,' NUMB   NX   NY   NZ   WX   WY   WZ      X           Y        
     1   Z      SYST')
 6100 FORMAT(///' NUMBER N2=',I5,' HAS NOT OBTAIN BY THE SUM OF NUBMBER
     1N1 =',I5,'AND FINITE NUMBER OF STEPS KORA=',I5)
 6200 FORMAT(///' NODE NUMBER N =',I5,' IS GREATER THAN TOTAL NUMBER OF
     1NODAL POINT NP =',I5)
C-----------------------------------------------------------------------
      END
C=======================================================================
      SUBROUTINE ELEFG(CORD,CORS,NEL,NOC,NOS,HE,
     1                 NP,NCVP,NE,NS,RADIJ,NCVS,ipgcv)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /ELEMEN/ ELAST(6,6),XJ(3,3),ALFA(6),TEMP0,DET,NLM,KK
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /INTGRA/ INCOTX,INCOTY,INCOTZ 
      COMMON /CVSILE/ NSILA,LESILA
      COMMON /CDEBUG/ IDEBUG
      COMMON /CNPE/ NPE
c      COMMON /COMEFG/ RADIJ,NBASE,NCVP,NPEFG,NCVS,NS,LCORS,LNOC,LNOS
c
      DIMENSION CORD(NP,*),CORS(NCVP,*),NEL(NE,*),NOC(*),NOS(NS,*),
     1          CORDL(2,9),HE(NCVE,*),IPGCV(*)
      DIMENSION XG(55),WGT(55),NREF(11),XNC(15),WNC(15)
      DIMENSION XG5(5),YG5(5),WG5(5)
      DATA NREF/0,1,3,6,10,15,21,28,36,45,55/
      DATA WGT/            2.D0,               1.D0,               1.D0,
     1       .555555555555556D0, .888888888888889D0, .555555555555556D0,
     2       .347854845137454D0, .652145154862546D0, .652145154862546D0,
     3       .347854845137454D0, .236926885056189D0, .478628670499366D0,
     4       .568888888888889D0, .478628670499366D0, .236926885056189D0,
     5       .171324492379170D0, .360761573048139D0, .467913934572691D0,
     6       .467913934572691D0, .360761573048139D0, .171324492379170D0,
     7       .129484966168870D0, .279705391489277D0, .381830050505119D0,
     8       .417959183673469D0, .381830050505119D0, .279705391489277D0,
     9       .129484966168870D0, .101228536290376D0, .222381034453374D0,
     9       .313706645877887D0, .362683783378362D0, .362683783378362D0,
     1       .313706645877887D0, .222381034453374D0, .101228536290376D0,
     2       .081274388361574D0, .180648160694857D0, .260610696402935D0,
     3       .312347077040003D0, .330239355001260D0, .312347077040003D0,
     4       .260610696402935D0, .180648160694857D0, .081274388361574D0,
     5       .066671344308688D0, .149451349150581D0, .219086362515982D0,
     6       .269266719309996D0, .295524224714753D0, .295524224714753D0,
     7       .269266719309996D0, .219086362515982D0, .149451349150581D0,
     8       .066671344308688D0/
      DATA XG /            0.D0,-.577350269189626D0, .577350269189626D0,
     1      -.774596669241483D0,               0.D0, .774596669241483D0,
     2      -.861136311594053D0,-.339981043584856D0, .339981043584856D0,
     3       .861136311594053D0,-.906179845938664D0,-.538469310105683D0,
     4                     0.D0, .538469310105683D0, .906179845938664D0,
     5      -.932469514203152D0,-.661209386466265D0,-.238619186083197D0,
     6       .238619186083197D0, .661209386466265D0, .932469514203152D0,
     7      -.949107912342759D0,-.741531185599394D0,-.405845151377397D0,
     8                     0.D0, .405845151377397D0, .741531185599394D0,
     9       .949107912342759D0,-.960289856497536D0,-.796666477413627D0,
     9      -.525532409916329D0,-.183434642495650D0, .183434642495650D0,
     1       .525532409916329D0, .796666477413627D0, .960289856497536D0,
     2      -.968160239507626D0,-.836031107326636D0,-.613371432700590D0,
     3      -.324253423403809D0,               0.D0, .324253423403809D0,
     4       .613371432700590D0, .836031107326636D0, .968160239507626D0,
     5      -.973906528517172D0,-.865063366688985D0,-.679409568299024D0,
     6      -.433395394129247D0,-.148874338981631D0, .148874338981631D0,
     7       .433395394129247D0, .679409568299024D0, .865063366688985D0,
     8       .973906528517172D0/
C
      DATA WNC/            2.D0,               1.D0,               1.D0,
     1       .333333333333333D0,1.333333333333333D0, .333333333333333D0,
     2       .250000000000000D0, .750000000000000D0, .750000000000000D0,
     3       .250000000000000D0, .155555555555556D0, .711111111111111D0,
     4       .266666666666667D0, .711111111111111D0, .155555555555556D0/
C
      DATA XNC/            0.D0,              -1.D0,               1.D0,
     1                    -1.D0,               0.D0,               1.D0,
     2                    -1.D0,-.333333333333333D0, .333333333333333D0,
     3                     1.D0,              -1.D0,             -0.5D0,
     4                     0.D0,              0.5D0,               1.D0/
C
      DATA WG5/1.77777777777778D0,.555555555555556D0,.555555555555556D0,
     1         .555555555555556D0,.555555555555556D0/
      DATA XG5/            0.D0,-.774596669241483D0,-.774596669241483D0,
     1                           .774596669241483D0, .774596669241483D0/
      DATA YG5/            0.D0,-.774596669241483D0, .774596669241483D0,
     1                          -.774596669241483D0, .774596669241483D0/
C
      IF(IDEBUG.GT.0) PRINT *, ' ELEFG'
CS            P E T L J A    P O    C E L I J A M A
CE            L O O P    O V E R    C E L L S
c      WRITE(3,*) ' E F G     E L E M E N T I '
c      WRITE(3,*) 'JG,X1,X2,NC,NLM,NGR,NGS/(NOS(I),I=1,NC)'
C
C      OVO JG JE JGG U PAK 222.FOR A PREDSTAVLJA GLOBALNI BROJAC 
C      INTEGRACIONIH TACAKA NA NIVOU CELE KONSTRUKCIJE
      JG=0
C     IVAR PROMENLJIVA POKAZUJE KOJU VARIJANTU PRORACUNA KORISTIMO
C     IVAR = 0 - NA INTEGRAC. TACKU UTICU SAMO CVOROVI CELIJE U KOJOJ SE NALAZI
C     IVAR = 1 - UTICAJ ODREDJEN DUZINOM NAJVECE DIJAGONALE CELIJE
      IVAR=0   
      NCVS=0
      DO 10 NLM=1,NE
C     FORMIRANJE LOKALNIH KOORDINATA
         DO 600 I=1,NCVE
            II = NEL(NLM,I)
            IF(II.EQ.0) GO TO 600
            DO 610 J=1,2
  610       CORDL(J,I)=CORS(II,J)
  600    CONTINUE
CS    P E T L J A    P O    S L O J E V I M A
CE    L O O P    O V E R    L A Y E R S
C
CS       PETLJA PO GAUSOVIM TACKAMA 
CE       LOOP OVER GAUSS POINTS
C
C        ODREDJIVANJE NAJDUZE DIJAGONALE
         DIJMAX=0
C
         K1=NEL(NLM,1)
	   K3=NEL(NLM,3)
	   DX=CORD(K1,1)-CORD(K3,1)
	   DY=CORD(K1,2)-CORD(K3,2)
	   DIJ=DSQRT(DX*DX+DY*DY)
	   IF(DIJ.GT.DIJMAX)DIJMAX=DIJ
C
	   K1=NEL(NLM,1)
	   K3=NEL(NLM,3)
	   DX=CORD(K1,1)-CORD(K3,1)
	   DY=CORD(K1,2)-CORD(K3,2)
	   DIJ=DSQRT(DX*DX+DY*DY)
	   IF(DIJ.GT.DIJMAX)DIJMAX=DIJ
C
         RMAX=DIJMAX
C 
         DO 920 NGR=1,NGAUSX
            JGR=NREF(NGAUSX)+NGR
            IF(INCOTX.EQ.0) THEN
               R=XG(JGR)
               WR=WGT(JGR)
            ELSE
               R =XNC(JGR)
               WR=WNC(JGR)
            ENDIF
C
         DO 920 NGS=1,NGAUSY
            JGR=NREF(NGAUSY)+NGS
            IF(INCOTY.EQ.0) THEN
                S=XG(JGR)
                WS=WGT(JGR)
            ELSE
               S =XNC(JGR)
               WS=WNC(JGR)
            ENDIF
C
            JG=JG+1
C	WRITE(*,*) 'NLM,JG',NLM,JG
C     WRITE(3,*) 'NLM,JG',NLM,JG
C
         CALL JACTEL(NEL,CORDL,HE,R,S,0)
      X1=0.0D0
      X2=0.0D0
      DO 80 I=1,NCVE
         IC=NEL(NLM,I)
         IF(IC.EQ.0) GO TO 80
         X1=X1+HE(I,1)*CORDL(1,I)
         X2=X2+HE(I,1)*CORDL(2,I)
   80 CONTINUE
      NC=0 
     	IF(IVAR.EQ.0)THEN                   
      DO 98 k=1,ncve
         MM=nel(nlm,k)
         NC=NC+1
         NOS(JG,NC)=MM
   98 CONTINUE
      ENDIF
C
	IF(IVAR.EQ.1)THEN
         DO MM=1,NPE
	   DX=CORd(MM,1)-X1
           DY=CORd(MM,2)-X2
           DR=DSQRT(DX*DX+DY*DY)
C
	     IF(DR.LT.RMAX)THEN
	        NC=NC+1
	        NOS(JG,NC)=MM
	     ENDIF
	   ENDDO
	ENDIF
	   NOC(JG)=NC
C      
      IF(NC.LE.3)STOP 'NC.LT.3'				
      IF(NC.GT.NCVS) NCVS=NC
	
c 
  920 CONTINUE 
c 
   10 CONTINUE 
C
 1000 FORMAT(10I5)
      RETURN
      END
C=======================================================================
C
C=======================================================================
      SUBROUTINE L2IMHT(ID,NOC,Nel,LMEL,NP,ne,ND,IETYP)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C .......................................................................
C .
CE.   P R O G R A M
CE.       TO FORM VECTOR LM AND HEIGHT COLUMNS
CS.   P R O G R A M
CS.       ZA FORMIRANJE VEKTORA LM I VISINA STUBOVA MATRICE KRUTOSTI
C .
C .......................................................................
C
      include 'paka.inc'
      
      COMMON /REPERI/ LCORD,LID,LMAXA,LMHT
c      COMMON /COMEFG/ RADIJ,NBASE,NCVP,NPEFG,NCVS,NS,LCORS,LNOC,LNOS
      DIMENSION ID(NP,*),NOC(*),Nel(Ne,*),LMEL(ND,*)
      COMMON /CDEBUG/ IDEBUG
C
      IF(IDEBUG.GT.0) PRINT *, ' L2IMHT'
CE    LOOP OVER ELEMENTS
CS    PETLJA PO ELEMENTIMA
      DO 100 NLM=1,NE
         NCVE=NOC(NLM)
         DO 10 NC=1,NCVE                            
            IF(NEL(NLM,NC).EQ.0) GO TO 10              
            NNC=2*(NC-1)                               
            IF(IETYP.EQ.3) NNC=3*(NC-1)
            JJ=NEL(NLM,NC)
            NN=2
            IF(IETYP.EQ.3) NN=3
            DO 20 I=1,NN
               LMEL(NNC+I,NLM)=ID(JJ,I)
   20       CONTINUE                                                        
   10    CONTINUE                                                        
C
CE    FORM HEIGHT COLUMNS
CS    FORMIRANJE VISINA STUBOVA
C
         NDD=NCVE*NN
         CALL VISINE(A(LMHT),NDD,LMEL(1,NLM))
c      WRITE(3,*) 'NLM,NOC',NLM,NCVE
c      WRITE(3,*) 'NOS',(NEL(NLM,IJ),IJ=1,NCVE)
c      CALL IWRR(LMEL(1,NLM),ND,'LMEL')
c      WRITE(3,*) 'NLM,NOC',NLM,NCVE
c      WRITE(3,*) 'NOS',(NEL(NLM,IJ),IJ=1,NCVE)
  100 CONTINUE
      RETURN
      END 
C======================================================================   
      SUBROUTINE T2RAFE(Nos,MCVEL,ICVEL,THID,NMAT)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C .......................................................................
C .
CE.   P R O G R A M
CE.       TO PRINTOUT 2/D ELEMENTS DATA IN UNIVERSAL GRAPHICS FILE
CS.   P R O G R A M
CS.       ZA STAMPANJE 2/D ELEMENATA U UNIVERZALNI FILE
C .
C .......................................................................
C
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP 
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /SUMELE/ ISUMEL,ISUMGR
      COMMON /SRPSKI/ ISRPS
      COMMON /COMEFG/ RADIJ,NBASE,NCVP,NPEFG,NCVS,NS,LCORS,LNOC,LNOS
      DIMENSION MCVEL(*),THID(*),NMAT(*),nos(ns,*)   
      DIMENSION FIZ(14)         
      COMMON /CDEBUG/ IDEBUG
C
      IF(IDEBUG.GT.0) PRINT *, ' 2GRAFE'
      ISUMGR=ISUMGR+1
C
C     FIZICKE OSOBINE
C
      CALL CLEAR(FIZ,14)
      ICL=1
      IPH=40
      NPR=3
      IF(IETYP.EQ.1) THEN
         ICL=6
         IPH=80
         NPR=1
      ENDIF
      IF(IETYP.EQ.2) THEN
         ICL=6
         IPH=50
         NPR=1
      ENDIF
      FIZ(1)=THID(1)
      IND=-1
      ITYP=772
      WRITE(IGRAF,1100) IND
      WRITE(IGRAF,1100) ITYP
      WRITE(IGRAF,1000) ISUMGR,IPH,NPR
      IF(ISRPS.EQ.0)
     1WRITE(IGRAF,2000) ISUMGR
      IF(ISRPS.EQ.1)
     1WRITE(IGRAF,6000) ISUMGR
      WRITE(IGRAF,1200) (FIZ(I),I=ICL,14)
      WRITE(IGRAF,1100) IND
C
C     M A T E R I J A L I
C
      MAT=NMAT(1)
      CALL MELGR(MAT)
C
C     E L E M E N T I
C
      IF(ISRPS.EQ.0.AND.(NCVE.NE.4.AND.NCVE.NE.8))
     1WRITE(IZLAZ,2200) NGE
      IF(ISRPS.EQ.1.AND.(NCVE.NE.4.AND.NCVE.NE.8))
     1WRITE(IZLAZ,6200) NGE
      NNCVE=NCVE
      IF(NCVE.LT.8) NCVE=4
      IF(NCVE.EQ.9) NCVE=8
      IF(NGAUSX.NE.5.AND.NGAUSX.NE.NGAUSY) GO TO 160
C     GRAFICKI OPIS RAVANSKOG ELEMENTA: SA 4 CVORA = 5, SA 8 CVOROVA = 6
C      IFGD=5
C      IF(NCVE.EQ.8) IFGD=6
C     GRAFICKI OPIS OSNOSIMETRICNOG ELEMENTA: 
C     SA 4 CVORA = 27, SA 8 CVOROVA = 28
C      IF(IETYP.EQ.1) THEN
        IFGD=27
        IF(NCVE.EQ.8) IFGD=28
C      ENDIF
C     VRSTA 2/D ELEMENTA: 
C          RAVNO STANJE NAPONA: SA 4 CVORA = 44, SA 8 CVOROVA = 45
      IFDI=44
      IF(NCVE.EQ.8) IFDI=45
C          OSNOSIMETRICAN PROBLEM: SA 4 CVORA = 84, SA 8 CVOROVA = 85
      IF(IETYP.EQ.1) THEN
        IFDI=84
        IF(NCVE.EQ.8) IFDI=85
      ENDIF
C          RAVNO STANJE DEFORMACIJE: SA 4 CVORA = 54, SA 8 CVOROVA = 55
      IF(IETYP.EQ.2) THEN
        IFDI=54
        IF(NCVE.EQ.8) IFDI=55
      ENDIF
C     TABELA FIZICKIH OSOBINA
      IPTN=ISUMGR
C     TABELA MATERIJALA
      MPTN=ISUMGR
C     BOJA  
      ICOL=7
C     BROJ CVOROVA NA ELEMENTU
      NNODS=NCVE
      IND=-1
      ITYP=71
      WRITE(IGRAF,1100) IND
      WRITE(IGRAF,1100) ITYP 
      ii=0
            DO 10 I=1,Ns,ngausx*ngausy 
            ii=ii+1
            
C        REDNI BROJ ELEMENTA
         IEL=I
         IF(ICVEL.EQ.1) IEL=MCVEL(I)
         WRITE(IGRAF,1000) Ii,IFGD,IFDI,IPTN,MPTN,ICOL,NNODS
c         IF(NCVE.EQ.4) THEN 
c            noss=nos(i,3)
c            nos(i,3)=nos(i,4)
c            nos(i,4)=noss
            WRITE(IGRAF,1000)(Nos(I,J),J=1,ncve) 
            write(izlaz,*)i,(Nos(I,J),J=1,ncve)
c         ELSE
c            WRITE(IGRAF,1000) (Nos(I,J),nos(I,J+4),J=1,4)
c         ENDIF
   10 CONTINUE
      WRITE(IGRAF,1100) IND
      ISUMEL=ISUMEL+NE
      NCVE=NNCVE
      RETURN
C
  160 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2160) NGE
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6160) NGE
      STOP
C
 1000 FORMAT(8I10)
 1100 FORMAT(I6)
 1200 FORMAT(6(1PE13.5))
C-----------------------------------------------------------------------
 2000 FORMAT('FIZICKI SET :',I10)
 2160 FORMAT(//' ZBOG GRAFIKE U GRUPI ELEMENATA NGE =',I5/
     1' GAUSOVA INTEGRACIJA U (R) I (S) PRAVCU MORA BITI ISTOG REDA')
 2200 FORMAT(//' PROGRAM ZA GRAFICKO PRIKAZIVANJE REZULTATA "IDEAS"'/
     1' ZAHTEVA 2/D ELEMENT SA 4 ILI 8 CVOROVA U GRUPI ELEMENATA NGE ='
     1,I5)
C-----------------------------------------------------------------------
 6000 FORMAT('PHISICAL PROPERTIES SET :',I10)
 6160 FORMAT(//' FOR GRAPHIC OUTPUT FOR ELEMENT GROUP  NGE =',I5/
     1' GAUSS INTEGRATION IN (R),(S) DIRECTION MUST BE SAME')
 6200 FORMAT(//' GRAPHIC PACKAGE   "IDEAS"'/
     1' PERMITS ONLY 2/D ELEMENTS WITH 4 OR 8 NODES PER ELEMENT IN',
     1' GROUP   NGE =',I5)
C-----------------------------------------------------------------------
      END
C=======================================================================
C
      SUBROUTINE Z2DA2B(TAU,NE,NGS12,MXS,N45)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.   P R O G R A M
CE.      TO INITIAL VALUE MATRIX - B
CS.   P R O G R A M
CS.      ZA ZADAVANJE POCETNE JEDINICNE VREDNOSTI ZA MATRICU - B
C .
C ......................................................................
C
      DIMENSION TAU(N45,NGS12,NE,*)
C
      DO 10 J=1,MXS
      DO 10 I=1,NE
         DO 20 K=1,NGS12
            IF(N45.EQ.4) THEN
               TAU(1,K,I,J)=1.D0
               TAU(2,K,I,J)=1.D0
               TAU(3,K,I,J)=1.D0
            ELSE
               TAU(1,K,I,J)=1.D0
               TAU(5,K,I,J)=1.D0
               TAU(9,K,I,J)=1.D0
            ENDIF
   20    CONTINUE
   10 CONTINUE
      RETURN
      END

C=======================================================================
      SUBROUTINE UCGBM
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.   P R O G R A M
CE.      TO INITIAL VALUE MATRIX - B
CS.   P R O G R A M
CS.      ZA ZADAVANJE POCETNE JEDINICNE VREDNOSTI ZA MATRICU - B
C .
C ......................................................................
C
      CHARACTER*250 ACOZ
      COMMON /MESLESS/ IGBM,ndif,idif(50),NKI,IKI(10)
      COMMON /CNPE/ NPE
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /BROJUK/ KARTIC,INDFOR,NULAZ
      COMMON /SRPSKI/ ISRPS

      NPE=0
      NDIF=0
      NKI=0
      IF(IGBM.GT.0) THEN
	   
         CALL ISPITA(ACOZ)
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) NPE,NDIF,NKI
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1010) NPE,NDIF,NKI
C         NPE=NP
         if(ndif.gt.0)then
            CALL ISPITA(ACOZ)
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) (idif(i),i=1,ndif)
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1010) (idif(i),i=1,ndif)
         endif
         if(nki.gt.0)then
            CALL ISPITA(ACOZ)
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) (IKI(i),i=1,NKI)
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1010) (IKI(i),i=1,NKI)
         endif
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2042) NPE,NDIF,NKI
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6042) NPE,NDIF,NKI
         IF(NDIF.GT.0)THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2044)(IDIF(I),I=1,NDIF)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6044)(IDIF(I),I=1,NDIF)
         ENDIF
         IF(NKI.GT.0)THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2046)(IKI(I),I=1,NKI)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6046)(IKI(I),I=1,NKI)
         ENDIF
      ENDIF
      RETURN
C
 1010 FORMAT(14I5)
C-----------------------------------------------------------------------
 2042 FORMAT(//
     111X,'BROJ SLOBODNIH TACAKA (GBM)      ............... NPE   =',I5/
     111X,'BROJ TACAKA ZA DIFRAKCIJU         ............. NDIF   =',I5/
     111X,'BR.TACAKA ZA RACUNANJE K.INTEZIVNOSTI ......... NKI    =',I5)
 2044 FORMAT(//11X,
     9'GRANICNI CVOROVI ZA DIFRAKCIJU'/
     916X,10I5)
 2046 FORMAT(//11X,
     9'CVOROVI ZA IZRACUNAVANJE KOEFICIJENTA INTEZIVNOSTI NAPONA'/
     916X,10I5)
C-----------------------------------------------------------------------
 6042 FORMAT(//
     111X,'NUMBER OF FREE POINTS (GBM)      ............... NPE   =',I5/
     111X,'NUMBER OF POINTS FOR DIFFRACTION METHOD ....... NDIF   =',I5/
     111X,'NUMBER OF POINTS FOR STRESS INTESITY FACTOR ... NKI    =',I5)
 6044 FORMAT(//11X,
     9'BOUNDARY NODES FOR DIFFRACTION'/
     916X,10I5)
 6046 FORMAT(//11X,
     9'NODES FOR STRESS INTESITY FACTOR'/
     916X,10I5)
C-----------------------------------------------------------------------
      END
