C=======================================================================
C
C=======================================================================
      SUBROUTINE PRINKN
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      include 'paka.inc'
      
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /IGRGLA/ NGRU,NGSU,NGTU,NGS,NTE,NUD,IANAL,JTAU,NWE,NT6,INEL
     *,MATG
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /DUPLAP/ IDVA
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /PERKOR/ LNKDT,LDTDT,LVDT,NDT,DT,VREME,KOR
      COMMON /ZAPISI/ LSTAZA(5)
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON/CONSKG/C43,C23,C13,C15,C19
C
C**************
C              STAMPANJE NAPONA
C**************
      LAU=LMAX
C
C UCITAVANJE PODATAKA O ELEMENTIMA I NAPONA SA DISKA 8
C
      CALL READEG(A(LAU))
C
C POZIVANJE PROGRAMA ZA STAMPANJE NAPONA
C
      CALL STANIG
       IF(IATYP.EQ.0) RETURN
       IF(NMODM.LE.4) RETURN
      NPROS=NE*NGS*(JTAU+10)*IDVA
      LMAX8=LSTAZA(3)-1
      CALL WRITDD(A(LPLAS1),NPROS/IDVA,IELEM,LMAX8,LDUZI)
      RETURN
      END
      SUBROUTINE STANIG
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      include 'paka.inc'
      
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /IGRGLA/ NGRU,NGSU,NGTU,NGS,NTE,NUD,IANAL,JTAU,NWE,NT6,INEL
     *,MATG
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /DUPLAP/ IDVA
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /ZAPISI/ LSTAZA(5)
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
C
C POZIVANJE PODPROGRAMA ZA STAMPANJE NAPONA
C
      GO TO (1,1,1,1,5,5,5,5) ,NMODM
   1  CALL STIG01(A(LSIGMA))
      RETURN
   5  CALL STIG05(A(LPLAS1))
      RETURN
      END
      SUBROUTINE STIG01(TAU)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      include 'paka.inc'
      
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /IGRGLA/ NGRU,NGSU,NGTU,NGS,NTE,NUD,IANAL,JTAU,NWE,NT6,INEL
     *,MATG
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /DUPLAP/ IDVA
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /ZAPISI/ LSTAZA(5)
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON/CONSKG/C43,C23,C13,C15,C19
      DIMENSION TAU(1),TA6(7)
C
      DO 600 NLM=1,NE
      IBTC =0
      JNGSS=0
      DO 600   J=1,NGS
       IBTC =IBTC +1
       JNGSS=JNGSS+1
      LL = 1 + (NLM-1)*NGS*JTAU + (IBTC-1)*JTAU
      IF(IANAL.EQ.1) GO TO 60
      IF(JNGSS.GT.1.OR.NLM.GT.1) GO TO 55
      WRITE(3,11)
   11 FORMAT(//' ', 10X ,'N',5X,'A',5X,'P',5X,'O',5X,'N',5X,'I'
     1//' ','ELEMENT',3X,'GAUS.TACKA',23X,'SR',12X,'TRS',12X,'TRT'//)
C  55 DO 20 I=1,3
C     U(I)=0.
C     DO 20 J=1,6
C  20 U(I)=U(I)+TSG(J,I)*TA6(J)
   55 IF(JNGSS.EQ.1)WRITE(3,220)NLM,JNGSS,(TAU(K),K=LL,LL+JTAU-1)
      IF(JNGSS.GT.1)WRITE(3,221)JNGSS,(TAU(K),K=LL,LL+JTAU-1)
  220 FORMAT(' ',I7,I13,10X,3D15.4)
  221 FORMAT(' ',I20,10X,3D15.4)
      GO TO 600
C   STAMPANJE NAPONA PRI ANALITICKOJ INTEGRACIJI
   60 DO 510 K=1,JTAU
  510 TA6(K)=TAU(K)
      WRITE(3,62)NLM,J
   62 FORMAT(//' ','ELEMENT',I4,2X,'PRESEK R=',I5,1X,'TACKA',3X,'S',
     14X,'T',17X,'SR',9X,'TRS',9X,'TRT',19X,'SEKV')
      N=0
C PRVA TACKA
      N=N+1
      S=-1.
      T=-1.
      SR=3.*TA6(1)-TA6(4)-TA6(6)
      TRS=0.
      TRT=0.
      SEKV=DABS(SR)
      WRITE(3,63)N,S,T,SR,TRS,TRT,SEKV
   63 FORMAT(' ',32X,I1,2F5.0,9X,3D12.4,D23.4)
C   DRUGA TACKA
      N=N+1
      S=-1.
      T=0.
      SR=2.*TA6(1)-TA6(4)
      TRS=0.
      TRTS=TA6(3)*C23*5./2.-TA6(5)
C     TRT=TRTS-C23*TA6(3)
      TRT=TRTS
C     TRT=2.5*C23*TA6(3)-TA6(5)
      SEKV=DSQRT(SR*SR+3.*(TRS*TRS+TRT*TRT))
      WRITE(3,63)N,S,T,SR,TRS,TRT,SEKV
C  TRECA TACKA
      N=N+1
      S=-1.
      T=1.
      SR=TA6(1)-TA6(4)+TA6(6)
      TRS=0.
      TRT=0.
      SEKV=DABS(SR)
      WRITE(3,63)N,S,T,SR,TRS,TRT,SEKV
C  CETVRTA TACKA
      N=N+1
      S=0.
      T=-1.
      SR=2.*TA6(1)-TA6(6)
      TRST=C23*TA6(2)*5./2.-TA6(7)
C     TRS=TRST-C23*TA6(2)
      TRS=TRST
C     TRS=2.5*C23*TA6(2)-TA6(7)
      TRT=0.
      SEKV=DSQRT(SR*SR+3.*(TRS*TRS+TRT*TRT))
      WRITE(3,63)N,S,T,SR,TRS,TRT,SEKV
C  PETA TACKA
      N=N+1
      S=0.
      T=0.
      SR=TA6(1)
      TRS=TA6(2)
      TRT=TA6(3)
      SEKV=DSQRT(SR*SR+3.*(TRS*TRS+TRT*TRT))
      WRITE(3,63)N,S,T,SR,TRS,TRT,SEKV
C SESTA TACKA
      N=N+1
      S=0.
      T=1.
      SR=TA6(6)
C     TRS=TA6(7)-C23*TA6(2)
      TRS=TA6(7)+.5*TA6(2)*C23
C     TRS=C23*TRS
C     TRS=1.5*TA6(7)
      TRT=0.
      SEKV=DSQRT(SR*SR+3.*(TRS*TRS+TRT*TRT))
      WRITE(3,63)N,S,T,SR,TRS,TRT,SEKV
C SEDMA TACKA
      N=N+1
      S=1.
      T=-1.
      SR=TA6(4)-TA6(6)+TA6(1)
      TRS=0.
      TRT=0.
      SEKV=DABS(SR)
      WRITE(3,63)N,S,T,SR,TRS,TRT,SEKV
C  OSMA TACKA
      N=N+1
      S=1.
      T=0.
      SR=TA6(4)
      TRS=0.
C     TRT=TA6(5)-C23*TA6(3)
      TRT=TA6(5)+.5*TA6(3)*C23
C     TRT=TA6(5)*1.5
      SEKV=DSQRT(SR*SR+3.*(TRS*TRS+TRT*TRT))
      WRITE(3,63)N,S,T,SR,TRS,TRT,SEKV
C  DEVETA TACKA
      N=N+1
      S=1.
      T=1.
      SR=TA6(4)+TA6(6)-TA6(1)
      TRS=0.
      TRT=0.
      SEKV=DABS(SR)
      WRITE(3,63)N,S,T,SR,TRS,TRT,SEKV
C
  600 CONTINUE
      RETURN
      END
      SUBROUTINE STIG05(PLAST)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      include 'paka.inc'
      
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /IGRGLA/ NGRU,NGSU,NGTU,NGS,NTE,NUD,IANAL,JTAU,NWE,NT6,INEL
     *,MATG
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /DUPLAP/ IDVA
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /ZAPISI/ LSTAZA(5)
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON/CONSKG/C43,C23,C13,C15,C19
      DIMENSION PLAST(1)
C
C STAMPANJE NAPONA I DEFORMACIJA ZA PLASTICNOST
C
      WRITE(IZLAZ,2010)
 2010 FORMAT('1',10X,'N A P O N I   I    D E F O R M A C I J E   ZA',
     *'  IZOPARAMETARSKE KRIVE GREDE'//)
      IBTC=0
      JNGSS=0
      DO 600 NLM=1,NE
      DO 601   J=1,NGS
      JNGSS=JNGSS+1
      IBTC =IBTC +1
      LL=1+(NLM-1)*NGS*(JTAU+10)     +(IBTC-1)*(JTAU+10)
      IF(JNGSS.GT.1.OR.NLM.GT.1) GO TO 55
C     WRITE(IZLAZ,11)
C  11 FORMAT(//' ','ELEMENT',3X,'GAUS.TACKA',5X,'NAPONI',
C    *',UKUPNA DEFORMACIJA,PLASTICNA DEFORMACIJA,INDIK.PLAST.'/)
   55 IF(JNGSS.EQ.1)WRITE(IZLAZ,220)NLM,JNGSS,(PLAST(II),II=LL,LL+2)
  220 FORMAT(//' ','ELEMENT',3X,'GAUS.TACKA',5X,'NAPONI'/
     *       ' ',2I3, 3D12.4)
      IF(JNGSS.GT.1)WRITE(IZLAZ,224)    JNGSS,(PLAST(II),II=LL,LL+2)
  224 FORMAT(  ' ',          3X,'GAUS.TACKA',5X,'NAPONI'/
     *       ' ',I6 , 3D12.4)
                    WRITE(IZLAZ,222)(PLAST(II),II=LL+3,LL+5),
     *                              (PLAST(II),II=LL+6,LL+8)
  222 FORMAT(' ', 6X,'UKUPNA DEFORMACIJA,PLASTICNA DEFORMACIJA'/
     *       ' ', 6X,6D11.4)
                    WRITE(IZLAZ,223)
     *               PLAST(LL+9 ), PLAST(LL+10),PLAST(LL+11)
     *              ,PLAST(LL+12)
  223 FORMAT(' ', 6X,'EKV.NAPON,NAPON TECENJA,EKV.PL.DEF,IND.PLAST'/
     *       ' ', 6X,4D11.4)
  601 CONTINUE
      IBTC=0
      JNGSS=0
  600 CONTINUE
      RETURN
      END
