C=======================================================================
C
C     SUBROUTINE UPL3M
C                UEL3A  (AU)
C                UEL4U3 (DEB,NOP,NELC,IMAT,NAPV,NESA2)
C                UEL3M  (NEL,IMAT,ELK,DEB,NAPV,IREAD)
C                LMMHT3 (ID,NEL,LMEL)
C                ERROR5 (NN)
C                GRAF3E (NEL)
C                                                         23.06.1988.G.
C=======================================================================
      SUBROUTINE UPL3M
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
CS     GLAVNI PROGRAM ZA UCITAVANJE ULAZNIH PODATAKA ZA 
CS     IZOPARAMETARSKE TROUGAONE PLOCE ( 3 CVORA )
CE     MAIN PROGRAM FOR INPUT DATA ABOUT
CE     ISOPARAMETRIC TRIANGULAR PLATE ( 3 NODES )
C
      CHARACTER*250 ACOZ
      include 'paka.inc'
      
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON/PL3CEL/ NPP,NGAUS,INULAZ,KDT,
     1IPP,IPMK,IPP2,MAXSK,INDPF,MATP,INDNA,NAPONG(3,5),LM(18),NDEB
      COMMON /GLAVNI/ NP,NGELEM,NMATM,NPER,
     1                IOPGL(6),KOSI,NDIN,ITEST
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /DUPLAP/ IDVA
      COMMON /BROJUK/ KARTIC,INDFOR,NULAZ
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /SISTEM/ LSK,LRTDT,NWK,JEDN,LFTDT
      COMMON /UPDLAG/ LUL,LCORUL
      COMMON /GREDE4/ IPRIR,INDGR4
      COMMON /ORIENT/ CPP(3,3),XJJ(3,3),TSG(6,6),BETA,LBET0,IBB0
      COMMON /SRPSKI/ ISRPS
C
      IF(IATYP.GT.1) THEN 
         LUL=1
         INDGR4=1
      ENDIF
      CALL ISPITA(ACOZ)
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*)  INULAZ,KDT,MSET,BETA,MSLOJ,(CPP(J,1),J=1,3)
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1000)INULAZ,KDT,MSET,BETA,MSLOJ,(CPP(J,1),J=1,3)
      IF(INULAZ.EQ.0) INULAZ = 1
      IF(KDT.EQ.1.OR.KDT.EQ.2) NE=2*NE
      IF(KDT.EQ.3) NE=4*NE
      NGAUS= 3
      INDNA= 1
      INDPF= 0
      NPP  = 3
      NCVE = 3
      MATP = NE
      NDEB = NE
      KIMAT= NE
      KDEB = NE
      KNAP = NE
      IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
       CALL WBROJK(KARTIC,0)
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2004) INULAZ,KDT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6004) INULAZ,KDT
       IF(MSET.GT.0) THEN
      IF(ISRPS.EQ.0)WRITE(IZLAZ,2010) MSET,BETA,MSLOJ,(CPP(J,1),J=1,3)
      IF(ISRPS.EQ.1)WRITE(IZLAZ,6010) MSET,BETA,MSLOJ,(CPP(J,1),J=1,3)
        ELSE
      IF(ISRPS.EQ.0)WRITE(IZLAZ,2020) BETA,(CPP(J,1),J=1,3)
      IF(ISRPS.EQ.1)WRITE(IZLAZ,6020) BETA,(CPP(J,1),J=1,3)
       ENDIF
      ENDIF
C
      BETA=BETA*3.1415926536D0/180.D0
      IBB0=1
      IF(DABS(CPP(1,1)).LT.1.D-6.AND.DABS(CPP(2,1)).LT.1.D-6.AND.
     1   DABS(CPP(3,1)).LT.1.D-6) IBB0=0
C
      LNSLOJ=1
      LMATSL=LNSLOJ+MSET
      LBBET =LMATSL+MSET*MSLOJ
        CALL DELJIV(LBBET,2,INDL)
        IF(INDL.EQ.0) LBBET=LBBET+1
      LDSLOJ=LBBET+MSET*MSLOJ*IDVA
      LTHID =LDSLOJ+MSET*MSLOJ*IDVA
      LBET0 =LTHID+NE*IDVA
      LNMAT =LBET0+NE*IDVA
      LIPGC =LNMAT+NE
      LISNA =LIPGC+NE
      LIPRC =LISNA+NE
      LNEL  =LIPRC+NE
C
      NTOT=LMAX+LNEL-LNSLOJ
      LCEL=LNEL
      IF(ICVEL.EQ.1) THEN
        LNEL=LCEL+NE
        NTOT=NTOT+NE
      ENDIF
      IF(NTOT.GT.MTOT) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2030) NTOT,MTOT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6030) NTOT,MTOT
      STOP
      ENDIF
C
CS     POZIVANJE PROGRAMA ZA ULAZNE PODATKE U VEKTOR AU
CE     CALL ROUTINES FOR INPUT DATA IN VECTOR   AU
C
      LAU=LMAX
      CALL UEL3A(A(LAU))
      IF(LMAX.GT.MTOT) CALL ERROR(1)
      RETURN
C
 1000 FORMAT(2I5,5X,I5,F10.3,I5,3F10.3)
C-----------------------------------------------------------------------
 2004 FORMAT(
     111X,'INDIKATOR ULAZNIH PODATAKA  .................... INULAZ=',I5/
     216X,'EQ.0; INULAZ = 1'/
     216X,'EQ.1; UCITAVAJU SE TROUGAONI ELEMENTI (3 CVORA)'/
     416X,'EQ.3; UCIT. SE CETVOROUGAONI ELEMENTI (4 ILI 5 CVORA)'// 
     511X,'INDIKATOR USMERENOSTI HIPOTENUZE ................. KDT =',I5/
     616X,'EQ.0; UCITAVAJU SE TROUGAONI ELEMENTI '/
     716X,'EQ.1; HIPOTENUZA USMERENA U JEDNU STRANU'/
     716X,'EQ.2; HIPOTENUZA USMERENA U DRUGU STRANU'/
     716X,'EQ.3; UNAKRSNI TROUGLOVI U CETVOROUGLU'/)
 2010 FORMAT(/
     611X,'BROJ RAZLICITIH VISESLOJNIH SETOVA MATERIJALA ... MSET =',I5/
     616X,'GT.0; VISESLOJNA LJUSKA'//
     611X,'UGAO SETOVA U ODNOSU NA REFERENTNI PRAVAC .. BETA =',1PD10.3/
     611X,'MAKSIMALAN BROJ SLOJEVA   ................. MSLOJ =',5X,I5//
     611X,'KOORDINATE TACKE PROJEKCIONOG PRAVCA   ....  CPPX =',1PD10.3/
     650X,                                       '....  CPPY =',1PD10.3/
     650X,                                       '....  CPPZ =',1PD10.3)
 2020 FORMAT(
     611X,'UGAO VLAKANA U ODNOSU NA REFERENTNI PRAVAC . BETA =',1PD10.3/
     611X,'KOORDINATA TACKE PROJEKCIONOG PRAVCA   ..... CPPX =',1PD10.3/
     650X,                                       '..... CPPY =',1PD10.3/
     650X,                                       '..... CPPZ =',1PD10.3)
 2030 FORMAT(///' NEDOVOLJNA DIMENZIJA U VEKTORU A ZA PODATKE O ELEMENTI
     1MA LJUSKE'/' POTREBNA DIMENZIJA , LMAX=',I10/' RASPOLOZIVA DIMENZI
     2JA,  MTOT =',I10)
C-----------------------------------------------------------------------
 6004 FORMAT(
     111X,'INDICATOR FOR INPUT DATA ....................... INULAZ=',I5/
     216X,'EQ.0; INULAZ = 1'/
     216X,'EQ.1; READING TRIANGULAR ELEMENTS (3 NODES)'/
     416X,'EQ.3; READING RECTANGULAR ELEMENTS (4 OR 5 NODES)'//
     511X,'INDICATOR HYPOTENUSES DIRECTION .................. KDT =',I5/
     616X,'EQ.0; READING TRIANGULAR ELEMENTS '/
     716X,'EQ.1; HYPOTENUSE IN ONE DIRECTION'/
     716X,'EQ.2; HYPOTENUSE IN OTHER DIRECTION'/
     716X,'EQ.3; HYPOTENUSE IN BOTH DIRECTION'/)
 6010 FORMAT(
     611X,'NUMBER OF DIFFERENT MULTILAYERD MATERIAL SETS ... MSET =',I5/
     616X,'GT.0; MULTILAYERD SHELL'//
     611X,'ANGLE OF SETS TO REFERENT DIRECTION .......  BETA =',1PD10.3/
     611X,'MAXIMUM NUMBER OF LAYERS .................. MSLOJ =',5X,I5/
     611X,'COORDINATES FOR PROJECTING DIRECTION   ....  CPPX =',1PD10.3/
     650X,                                       '....  CPPY =',1PD10.3/
     650X,                                       '....  CPPZ =',1PD10.3)
 6020 FORMAT(/
     611X,'ANGLE OF FIBER TO REFERENT DIRECTION ....... BETA =',1PD10.3/
     611X,'COORDINATES FOR PROJECTING DIRECTION   ..... CPPX =',1PD10.3/
     650X,                                       '..... CPPY =',1PD10.3/
     650X,                                       '..... CPPZ =',1PD10.3)
 6030 FORMAT(///' NOT ENOUGH SPACE IN WORKING VECTOR  A'
     1/' REQUESTED DIMENSION , LMAX=',I10
     2/' AVAILABLE DIMENSION , MTOT=',I10)
C-----------------------------------------------------------------------
      END
C=======================================================================
      SUBROUTINE UEL3A(AU)
C
CS     UPRAVLJACKI PROGRAM ZA UCITAVANJE ULAZNIH PODATAKA U AU
CE     MENAGEMENT ROUTINE FOR INPUT DATA IN    AU
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      include 'paka.inc'
      
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /ORIENT/ CPP(3,3),XJJ(3,3),TSG(6,6),BETA,LBET0,IBB0
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /REPERI/ LCORD,LID,LMAXA,LMHT
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /DUPLAP/ IDVA
      COMMON /MASINA/ INDPC,ICRTA
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON/PL3CEL/ NPP,NGAUS,INULAZ,KDT,
     1IPP,IPMK,IPP2,MAXSK,INDPF,MATP,INDNA,NAPONG(3,5),LM(18),NDEB
      COMMON /PL3REP/ LSKEB,LSKEM,LEMB,LSIGB,LEN,LFUE
      COMMON /SRPSKI/ ISRPS
      COMMON /PODTIP/ IPODT
C
      DIMENSION AU(*)
      REAL AU
C
       LLMEL=LNEL+NE*NCVE
       LNEC=LNEL 
       LNMAC=LNMAT
       LISNC=LISNA
       LTHIC=LTHID
       LIPCG=LIPGC
       LIPCR=LIPRC
       NESA2=NE
       IPODT=1
       IF(KDT.EQ.3) THEN
          NESA2=NE/4
          NCVE=5
       ENDIF
       IF(KDT.EQ.1.OR.KDT.EQ.2) THEN
          NESA2=NE/2
          NCVE=4
       ENDIF
       IF(KDT.GT.0) THEN
          CALL DELJIV(LLMEL,2,INDL)
          IF(INDL.EQ.0) LLMEL=LLMEL+1
          LTHIC =LLMEL
          LNMAC =LTHIC+NESA2*IDVA
          LIPCG =LNMAC+NESA2
          LISNC =LIPCG+NESA2
          LIPCR =LISNC+NESA2
          LNEC  =LIPCR+NESA2
          LLMEL=LNEC+NESA2*NCVE
          IPODT=0
       ENDIF
       LMAX=LAU+LLMEL-1
       IF(LMAX.GT.MTOT) GO TO 4
C
CS     POZIVANJE PROGRAMA ZA ULAZNE PODATKE  O LJUSKAMA
CE     CALL ROUTINE FOR INPUT DATA ABOUT SHELLS
C
      IF(ICVEL.EQ.0) THEN
      CALL UEL3B(AU(LNEC),AU(LNMAC),AU(LIPCG),AU(LISNC),AU(LIPCR),
     1 AU(LTHIC),AU(LNSLOJ),AU(LMATSL),AU(LBBET),AU(LDSLOJ),NESA2)
      NCVE=3
      IF(INULAZ.GT.1)
     1CALL UEL4U3(AU(LTHIC),AU(LNEC),AU(LNMAC),AU(LISNC),
     1 AU(LTHID),AU(LNEL),AU(LNMAT),AU(LISNA),NESA2,
     1 AU(LNSLOJ),AU(LMATSL),AU(LBBET),AU(LDSLOJ))
      NMA=0
      NMI=0
      IF(NBLGR.GE.0)
     &   CALL GRAF3E(AU(LNEL),AU(LCEL),ICVEL,AU(LTHID),AU(LNMAT))
      ELSE
      CALL UEL3BC(AU(LNEC),AU(LNMAC),AU(LIPCG),AU(LISNC),AU(LIPCR),
     1 AU(LTHIC),AU(LNSLOJ),AU(LMATSL),AU(LBBET),AU(LDSLOJ),AU(LCEL),
     1 NMA,NMI,NESA2)
      NCVE=3
      IF(INULAZ.GT.1)
     1CALL UEL4U3(AU(LTHIC),AU(LNEC),AU(LNMAC),AU(LISNC),
     1 AU(LTHID),AU(LNEL),AU(LNMAT),AU(LISNA),NESA2,
     1 AU(LNSLOJ),AU(LMATSL),AU(LBBET),AU(LDSLOJ))
      IF(NBLGR.GE.0)
     &   CALL GRAF3E(AU(LNEL),AU(LCEL),ICVEL,AU(LTHID),AU(LNMAT))
      CALL VEZACE(AU(LNEL),A(LELCV),NE,NCVE)
      ENDIF
C
      LLMEL = LNEL + NE*NCVE
      LELC=LLMEL
      IF(ICVEL.EQ.1.AND.INULAZ.EQ.1) THEN
        LLMEL=LELC+NMA-NMI+1
        LMAX=LAU+LLMEL-1
        IF(LMAX.GT.MTOT) GO TO 4
        CALL ICLEAR(AU(LELC),NMA-NMI+1)
        CALL VEZAEL(AU(LCEL),AU(LELC),NE,NMI)
      ENDIF
      LMXAU = LLMEL+ NE*NCVE*6
      MXAU=LMXAU-1
      CALL DELJIV(MXAU,2,INDL)
      IF(INDL.EQ.1) MXAU=MXAU+1
      LMAX=LAU+MXAU
    4 IF(LMAX.GT.MTOT) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2005) LMAX,MTOT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6005) LMAX,MTOT
      STOP
      ENDIF
C
C     FORMIRANJE VEKTORA LM I VISINA STUBOVA
C
      NPP6=NPP*6
      CALL ICLEAR(AU(LLMEL),NE*NPP6)
      CALL LMMHT3(A(LID),AU(LNEL),AU(LLMEL),NPP6)
C
C   ZAPISIVANJE SKALARA NA DIREKT ACCES FILE
C
      LMAX8=LMAX8+1
      WRITE(IELEM,REC=LMAX8)
     1 NPP,INULAZ,INDNA,KDT,MATP,NE,INDPF,NDEB,
     2 LNEL,LTHID,LNMAT,LIPGC,LIPRC,LISNA,MXAU,
     3 MSLOJ,MXS,MSET,
     4 LNSLOJ,LMATSL,LDSLOJ,LBBET,LBET0,(CPP(J,1),J=1,3),IBB0
C
      CALL WRITDD(AU(LNSLOJ),MXAU/IDVA,IELEM,LMAX8,LDUZI)
      CALL DELJIV(LMAX,2,INDL)
      IF(INDL.EQ.0) LMAX=LMAX+1
C
      IF(NMODM.LE.4) GO TO 10
C     LPLAST=LMAX
C     NPROS=NE*NGAUS *NGAUS *15*IDVA
C     LPLAS1=LPLAST+NPROS
C     LMAX=LPLAS1+NPROS
C     IF(LMAX.GT.MTOT) CALL ERROR(1)
C     CALL CLEAR(A(LPLAST),NPROS*2/IDVA)
C     CALL WRITDD(A(LPLAS1),NPROS/IDVA,IELEM,LMAX8,LDUZI)
C     RETURN
   10 LSIGB=LMAX
      LEN  =LSIGB+NE* 3* MXS* IDVA
      LFUE =LEN  +NE* 3* MXS* IDVA
      LEMB =LFUE +NE* 18*MXS* IDVA
      LMAX=LEMB +NE* 9* MXS* IDVA 
      NPROS=LMAX-LSIGB
      IF(LMAX.GT.MTOT) CALL ERROR(1)
      CALL CLEAR (A(LSIGB),NPROS/IDVA)
      CALL WRITDD(A(LSIGB),NPROS/IDVA,IELEM,LMAX8,LDUZI)
      LSKEM=LMAX
      LSKEB=LSKEM+NE*21*IDVA
      LMAX =LSKEB+NE*45*IDVA
      NPROS=LMAX-LSKEM
      IF(LMAX.GT.MTOT) CALL ERROR(1)
      CALL CLEAR (A(LSKEM),NPROS/IDVA)
      CALL WRITDD(A(LSKEM),NPROS/IDVA,IELEM,LMAX8,LDUZI)
      RETURN
C-----------------------------------------------------------------------
 2005 FORMAT(///' NEDOVOLJNA DIMENZIJA U VEKTORU A ZA PODATKE O ELEMENTI
     1MA LJUSKI'/' POTREBNA DIMENZIJA , LMAX=',I10/' RASPOLOZIVA DIMENZI
     2JA,  MTOT =',I10)
C-----------------------------------------------------------------------
 6005 FORMAT(///' NOT ENOUGH SPACE IN WORKING VECTOR  A'
     1/' REQUESTED DIMENSION , LMAX=',I10
     2/' AVAILABLE DIMENSION , MTOT=',I10)
C-----------------------------------------------------------------------
      END
C=======================================================================
      SUBROUTINE UEL3B (NEL,MATV,IPGCV,ISNAP,IPRCV,THICK,NSLOJ,MATSL,
     1                  BBET,DSLOJ,NESA)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
CS     PODPROGRAM ZA UCITAVANJE PODATAKA O IZOPARMETARSKIM LUSKAMA
CE     SUBROUTINE FOR READING DATA ABOUT SHELLS
C
      CHARACTER*250 ACOZ
      CHARACTER*4  CH
C
      include 'paka.inc'
      
      COMMON/PL3CEL/ NPP,NGAUS,INULAZ,KDT,
     1IPP,IPMK,IPP2,MAXSK,INDPF,MATP,INDNA,NAPONG(3,5),LM(18),NDEB
      COMMON /BROJUK/ KARTIC,INDFOR,NULAZ
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /PODTIP/ IPODT
      COMMON /SRPSKI/ ISRPS
C
      DIMENSION NEL(NESA,*),MATV(*),IPGCV(*),ISNAP(*),IPRCV(*),THICK(*),
     1          NSLOJ(*),MATSL(MSLOJ,*),BBET(MSLOJ,*),DSLOJ(MSLOJ,*)
C
      K34=3
      IF(IPODT.NE.1)K34=4
      IF(ISRPS.EQ.0)CH='BROJ'
      IF(ISRPS.EQ.1)CH='NUM.'
      MXS=1
C
CS     P  O  D  A  C  I      O      S  L  O  J  E  V  I  M  A
CE     D  A  T  A      A  B  O  U  T      L  A  Y  E  R  S
C
      IF(MSET.GT.0) THEN
        CH='SET '
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,2500)
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,6500)
        DO 2 I=1,MSET
          CALL ISPITA(ACOZ)
          IF(INDFOR.EQ.1)
     1    READ(IULAZ,*) NSLOJ(I)
          IF(INDFOR.EQ.2)
     1    READ(ACOZ,1000) NSLOJ(I)
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,2530) I,NSLOJ(I)
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,6530) I,NSLOJ(I)
          IF(NSLOJ(I).LT.1.OR.NSLOJ(I).GT.MSLOJ)THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2505)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6505)
            STOP 'STOP - UEL4B'
          ENDIF
      IF(NSLOJ(I).GT.MXS) MXS=NSLOJ(I) 
            TTT=0.D0
            DO 1 J=1,NSLOJ(I)
              CALL ISPITA(ACOZ)
              IF(INDFOR.EQ.1)
     1        READ(IULAZ,*)   MATSL(J,I),DSLOJ(J,I),BBET(J,I)
              IF(INDFOR.EQ.2)
     1        READ(ACOZ,1515) MATSL(J,I),DSLOJ(J,I),BBET(J,I)
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,2540) J,MATSL(J,I),DSLOJ(J,I),BBET(J,I)
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,6540) J,MATSL(J,I),DSLOJ(J,I),BBET(J,I)
              BBET(J,I)=BBET(J,I)*3.1415926536D0/180.D0
            TTT=TTT+DSLOJ(J,I)
    1       CONTINUE
CS....  PROVERA ZA DEBLJINE
      IF(DABS(TTT-1.D0).LT.1.D-6) GO TO 2
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2550) TTT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6550) TTT
        STOP'STOP - UEL4B'
    2   CONTINUE      
      ENDIF
C
CS     P  O  D  A  C  I      O      E  L  E  M  E  N  T  I  M  A
CE     D  A  T  A      A  B  O  U  T      E  L  E  M  E  N  T  S
C
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3).AND.IPODT.NE.1)
     1WRITE(IZLAZ,2000) CH
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3).AND.IPODT.NE.1)
     1WRITE(IZLAZ,6000) CH
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3).AND.IPODT.EQ.1)
     1WRITE(IZLAZ,2600) CH
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3).AND.IPODT.EQ.1)
     1WRITE(IZLAZ,6600) CH
      NMATS=  1
      IPRCOS=-1
      IPGSS= -1
      ISNAA= -1
      ISNAA=  0
      THICS=  1.D0
      I = 0
      NAUT=0
    5 I = I + 1
      CALL ISPITA(ACOZ)
      IF(I.EQ.1) KARTI=KARTIC
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) NN,NMAT,IPRCO,ISNA,IPGS,THI,KORC
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1010) NN,NMAT,IPRCO,ISNA,IPGS,THI,KORC
      CALL ISPITA(ACOZ)
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) (NEL(NN,J),J=1,NCVE)
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1000) (NEL(NN,J),J=1,NCVE)
      IF(NMAT.EQ.0) NMAT=NMATS
      NMATS=NMAT
      MATV(NN)= NMAT
      IF (IPRCO.EQ.0) IPRCO=IPRCOS
      IPRCOS=IPRCO
      IF(IPRCO.LT.0) IPRCO = 0
      IPRCV(NN)=IPRCO
      IF(ISNA.EQ.0) ISNA=ISNAA
      ISNAA=ISNA
      IF(ISNA.LT.0) ISNA = 0
      ISNAP(NN)=ISNA
      IF(IPGS.EQ.0) IPGS=IPGSS
      IPGSS=IPGS
      IF(IPGS.LT.0) IPGS = 0
      IPGCV(NN)=IPGS
      IF (DABS(THI).LT.1.D-20) THI=THICS
      THICS=THI
      THICK(NN)=THI
      IF(IPODT.EQ.1)THEN
        IF(NULAZ.EQ.1.OR.NULAZ.EQ.3)
     1  WRITE(IZLAZ,5001) NN,(NEL(NN,J),J=1,3),NMAT,IPRCO,ISNA,IPGS,THI,
     1  KORC
      ENDIF
      IF(IPODT.NE.1)THEN
        IF(NULAZ.EQ.1.OR.NULAZ.EQ.3)
     1  WRITE(IZLAZ,1001) NN,(NEL(NN,J),J=1,4),NMAT,IPRCO,ISNA,IPGS,THI,
     1  KORC
        IF((NULAZ.EQ.1.OR.NULAZ.EQ.3).AND.KDT.EQ.3)
     1  WRITE(IZLAZ,1002)  (NEL(NN,J),J=5,NCVE)
      ENDIF
      IF(NAUT.GT.0) GO TO 30
      IF(KORC.NE.0) GO TO 20
      IF(I.EQ.NESA) GO TO 50
      GO TO 5
C
   20 NAUT=1
      NN1=NN
      KORA=KORC
      GO TO 5
C
CS     AUTOMATSKO GENERISANJE PODATAKA IZMEDJU CVOROVA N1 I N2
CE     AUTOMATIC  GENERATION BETWEN NODES  N1  AND  N2
C
   30 NN2=NN
      N11=NEL(NN1,1)
      N22=NEL(NN2,1)
      N12=N22-N11
      CALL DELJIV(N12,KORA,INDD)
      IF(INDD.EQ.1) GO TO 100
      DO 40 NC=2,K34
      N11=NEL(NN1,NC)
      N22=NEL(NN2,NC)
      N21=N22-N11
      IF(N12.NE.N21) GO TO 100
   40 CONTINUE
      DO 45 NC=K34+1,NCVE
      N11=NEL(NN1,NC)
      N22=NEL(NN2,NC)
      IF(N11.EQ.0.AND.N22.EQ.0) GO TO 45
      N21=N22-N11
      IF(N12.NE.N21) GO TO 100
   45 CONTINUE
      NNN=NN2-NN1-1
      NGG=N12/KORA-1
      IF(NNN.NE.NGG) THEN
         IF(ICVEL.EQ.1) THEN
C           NN1=N1
C           NN2=N2
         ENDIF
         GO TO 150
      ENDIF
      IAUT=N12/KORA-1
      DO 34 J=1,IAUT
      JJ=NN1+J
      MATV(JJ) = MATV(NN1)
      IPRCV(JJ)=IPRCV(NN1)
      ISNAP(JJ)=ISNAP(NN1)
      IPGCV(JJ)=IPGCV(NN1)
      THICK(JJ)=THICK(NN1)
      DO 35 NN=1,NCVE
      NODP=NEL(JJ-1,NN)
      NEL(JJ,NN)=NODP+KORA
      IF(NODP.EQ.0) NEL(JJ,NN) = 0
   35 CONTINUE
   34 CONTINUE
      I=I+IAUT
      IF(I.EQ.NESA) GO TO 50
      NAUT=0
      IF(KORC.EQ.0) GO TO 5
      KORA=KORC
      NAUT=1
      NN1=NN2
      GO TO 5
C
CS     ODREDJIVANJE MAKSIMALNOG BROJA CVOROVA
CE     OBTAIN MAXIMUM NUMBER OF NODES PER ELEMENT
C
   50 NNNN=NCVE
C     NCVE=K34
C     DO 60 I=1,NESA
C     DO 60 J=K34+1,NNNN
C     IJ=NEL(I,J)
C     IF(IJ.GT.0.AND.J.GT.NCVE) NCVE=J
C  60 CONTINUE
C
CS     STAMPANJE UCITANIH I GENERISANIH PODATAKA
CE     PRINT INPUT AND GENERATED DATA
C
      IF(NULAZ.NE.1.AND.NULAZ.NE.3) RETURN
      CALL WBROJK(KARTI,0)
      IF(ISRPS.EQ.0.AND.IPODT.EQ.1)
     1WRITE(IZLAZ,2740) CH
      IF(ISRPS.EQ.1.AND.IPODT.EQ.1)
     1WRITE(IZLAZ,6740) CH
      IF(ISRPS.EQ.0.AND.IPODT.NE.1)
     1WRITE(IZLAZ,2140) CH
      IF(ISRPS.EQ.1.AND.IPODT.NE.1)
     1WRITE(IZLAZ,6140) CH
      DO 70 I=1,NESA
      IF(IPODT.EQ.1)THEN
        WRITE(IZLAZ,5001) I,(NEL(I,J),J=1,3),
     1  MATV(I),IPRCV(I),ISNAP(I),IPGCV(I),THICK(I)
      ENDIF
      IF(IPODT.NE.1)THEN
        WRITE(IZLAZ,1001) I,(NEL(I,J),J=1,4),
     1  MATV(I),IPRCV(I),ISNAP(I),IPGCV(I),THICK(I)
        IF(KDT.EQ.3) WRITE(IZLAZ,1002) (NEL(I,J),J=5,NCVE)
      ENDIF
   70 CONTINUE
      RETURN
C
  150 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2110) NN1,NN2,NGG
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6110) NN1,NN2,NGG
      STOP
  100 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2100) N22,N11,KORA
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6100) N22,N11,KORA
      STOP
C
 1000 FORMAT(14I5)
 1001 FORMAT(11X,I5,8X,4I6,2X,I6,3X,I6,3X,I6,4X,I6,6X,1PD10.3,I6)
 1002 FORMAT(19X,13I6)
 1010 FORMAT(5I5,F10.0,I5)
 1515 FORMAT(I5,2F10.4)
 5001 FORMAT(11X,I5,8X,3I6,8X,I6,3X,I6,3X,I6,4X,I6,6X,1PD10.3,I6)
C-----------------------------------------------------------------------
 2000 FORMAT(///6X,'U C I T A N I    P O D A C I   O    E L E M E N T I
     1M A    I Z O P A R A M E T A R S K E    L J U S K E'/6X,103('-')//
     1/11X,'(MOGUCE GENERISANJE PODATAKA O ELEMENTIMA,'/12X,         'UC
     2ITATI POTREBAN BROJ KARTICA ZA DEFINISANJE SVIH ELEMENATA)'///11X,
     3'ELEMENT',7X,'CVOR1 CVOR2 CVOR3 CVOR4',5X,'MAT.',4X,'KOORD.',4X,
     4'NAPON',5X,'NAPON',5X,'DEBLJINA',4X,'KORAK'/12X,'BROJ',3X,' CVOR5
     4                       ',4X,A4,4X,'STAMPA',4X,'STAMPA',4X,
     4'CVORA')
 2100 FORMAT(///' BROJ CVORA N2=',I5,' NE MOZE SE DOBITI SABIRANJEM BROJ
     1A CVORA N1=',I5,' I KONACNOG BROJA KORAKA KORA=',I5)
 2110 FORMAT(///' IZMEDJU ELEMENATA N1=',I5,' I N2=',I5,' NEMA NG=',I5,
     1' ELEMENATA KOJE TRBA GENERISATI')
 2140 FORMAT(6X,'G E N E R I S A N I    P O D A C I    O    E L E M E N
     1 T I M A    I Z O P A R A M E T A R S K E   L J U S K E'
     1 /6X,110('-')///11X,
     3'ELEMENT',7X,'CVOR1 CVOR2 CVOR3 CVOR4',5X,'MAT.',4X,'KOORD.',4X,
     4'NAPON',5X,'NAPON',5X,'DEBLJINA'           /12X,'BROJ',3X,' CVOR5
     4                       ',4X,A4,4X,'STAMPA',4X,'STAMPA',4X,
     4'CVORA')
 2500 FORMAT(///6X,' U C I T A N I    P O D A C I   O   V I S E S L O J 
     1N I M    S E T O V I M A    M A T E R I J A L A'/6X,99('-')///)
 2505 FORMAT(///' BROJ SLOJEVA U MATERIJALNOM SETU MORA BITI VECI OD 0'/
     1' (MAKSIMALNO :     MSLOJ )')
 2530 FORMAT(//10X,'MATERIJALNI SET (',I3,') ',5X,'BROJ SLOJEVA =',I3/)
 2540 FORMAT(/10X,'SLOJ =',I3/10X,'MATERIJAL =',I3/10X,'RELATIVNA ',
     1'DEBLJINA =',1PD10.3/10X,'UGAO VLAKANA =',1PD10.3) 
 2550 FORMAT(/// ' ZBIR RELATIVNIH DEBLJINA SLOJEVA U MATERIJALNOM SETU 
     1MORA BITI   1.00'/' (KONTROLNI ZBIR JE :   TTT =',1PD10.3)
 2600 FORMAT(///6X,'U C I T A N I    P O D A C I   O    E L E M E N T I
     1M A    T R O U G A O N E    P L O C E / L J U S K E'/6X,103('-')//
     1/11X,'(MOGUCE GENERISANJE PODATAKA O ELEMENTIMA,'/12X,         'UC
     2ITATI POTREBAN BROJ KARTICA ZA DEFINISANJE SVIH ELEMENATA)'///11X,
     3'ELEMENT',7X,'CVOR1 CVOR2 CVOR3      ',5X,'MAT.',4X,'KOORD.',4X,
     4'NAPON',5X,'NAPON',5X,'DEBLJINA',4X,'KORAK'/12X,'BROJ',3X,'      
     4                       ',4X,A4,4X,'STAMPA',4X,'STAMPA',4X,
     4'CVORA')
 2740 FORMAT(6X,'G E N E R I S A N I    P O D A C I    O    E L E M E N
     1 T I M A    T R O U G A O N E   P L O C E / L J U S K E'
     1 /6X,110('-')///11X,
     3'ELEMENT',7X,'CVOR1 CVOR2 CVOR3      ',5X,'MAT.',4X,'KOORD.',4X,
     4'NAPON',5X,'NAPON',5X,'DEBLJINA'           /12X,'BROJ',3X,'       
     4                       ',4X,A4,4X,'STAMPA',4X,'STAMPA',4X,
     4'CVORA')
C-----------------------------------------------------------------------
 6000 FORMAT(///6X,'R E A D I N G    D A T A    A B O U T    S H E L L    
     1  E L E M E N T S'/6X,71('-')///11X,
     3'ELEMENT',7X,'NODE1 NODE2 NODE3 NODE4',5X,'MAT.',4X,'COORD.',4X,
     4'STRESS',4X,'STRESS',5X,'THICK',6X,'STEP'/11X,'NUMBER',2X,' NODE5
     4                       ',4X,A4,4X,'PRINT ',4X,'PRINT ',3X,
     4'AT NODE')
 6100 FORMAT(///' NODE NUMBER N2=',I5,' CAN NOT BE DEFINED BY SUPERPOSIT
     1ION OF NODE N1=',I5,' WITH A NUMBER OF STEPS  KORA=',I5)
 6110 FORMAT(///' AMONG ELEMENTS N1=',I5,' AND N2=',I5,' THERE IS NO  ',
     1'NG=',I5,' ELEMENTS TO GENERATE')
 6140 FORMAT(6X,'G E N E R A T E D   D A T A   A B O U T   S H E L L   E
     1 L E M E N T S'/6X,69('-')///11X,
     3'ELEMENT',7X,'NODE1 NODE2 NODE3 NODE4',5X,'MAT.',4X,'COORD.',4X,
     4'STRESS',4X,'STRESS',5X,'THICK',6X,'STEP'/11X,'NUMBER ',2X,'NODE5
     4                       ',4X,A4,4X,'PRINT ',4X,'PRINT ',3X,
     4'AT NODE')
 6500 FORMAT(///6X,' R E A D I N G    D A T A    A B O U T    M U L T I 
     1L A Y E R E D    M A T E R I A L    S E T S'/6X,93('-')///)
 6505 FORMAT(///' NUMBER OF LAYERS IN MATERIAL SET MUST BE GREATER',
     1          ' THAN   0'/' (MAXIMUM :     MSLOJ )')
 6530 FORMAT(//10X,'MATERIAL SET (',I3,') ',5X,'NUMBER OF LAYERS =',I3/)
 6540 FORMAT(/10X,'LAYER =',I3/10X,'MATERIAL =',I3/10X,'RELATIV ',
     1'THICKNESS =',1PD10.3/10X,'FIBER ANGLE =',1PD10.3) 
 6550 FORMAT(/// ' RELATIV THICKNESSES SUM IN MATERIAL SET MUST BE', 
     1'   1.00'/' (CONTROL SUM IS :   TTT =',1PD10.3)
 6600 FORMAT(///6X,'R E A D I N G    D A T A    A B O U T    T R I A N G  
     1 U L A R     S H E L L  /  P L A T E'/6X,90('-')///11X,
     3'ELEMENT',7X,'NODE1 NODE2 NODE3      ',5X,'MAT.',4X,'COORD.',4X,
     4'STRESS',4X,'STRESS',5X,'THICK',6X,'STEP'/11X,'NUMBER',2X,'      
     4                       ',4X,A4,4X,'PRINT ',4X,'PRINT ',3X,
     4'AT NODE')
 6740 FORMAT(6X,'G E N E R A T E D   D A T A   A B O U T   T R I A N G U
     1 L A R    S H E L L  /  P L A T E'/6X,87('-')///11X,
     3'ELEMENT',7X,'NODE1 NODE2 NODE3      ',5X,'MAT.',4X,'COORD.',4X,
     4'STRESS',4X,'STRESS',5X,'THICK',6X,'STEP'/11X,'NUMBER ',2X,'     
     4                       ',4X,A4,4X,'PRINT ',4X,'PRINT ',3X,
     4'AT NODE')
C-----------------------------------------------------------------------
      END
C=======================================================================
      SUBROUTINE UEL3BC (NEL,MATV,IPGCV,ISNAP,IPRCV,THICK,NSLOJ,MATSL,
     1                  BBET,DSLOJ,MCVEL,NMA,NMI,NESA)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
CS     PODPROGRAM ZA UCITAVANJE PODATAKA O IZOPARMETARSKIM LUSKAMA
CS                -  SLOBODNA NUMERACIJA  -
CE     SUBROUTINE FOR READING DATA ABOUT SHELLS - FREE NUMERATION
C
      CHARACTER*250 ACOZ
      CHARACTER*4  CH
C
      include 'paka.inc'
      
      COMMON/PL3CEL/ NPP,NGAUS,INULAZ,KDT,
     1IPP,IPMK,IPP2,MAXSK,INDPF,MATP,INDNA,NAPONG(3,5),LM(18),NDEB
      COMMON /BROJUK/ KARTIC,INDFOR,NULAZ
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /PODTIP/ IPODT
      COMMON /SRPSKI/ ISRPS
C
      DIMENSION NEL(NESA,*),MATV(*),IPGCV(*),ISNAP(*),IPRCV(*),THICK(*),
     1          NSLOJ(*),MATSL(MSLOJ,*),BBET(MSLOJ,*),DSLOJ(MSLOJ,*),
     1          MCVEL(*)
C
      K34=3
      IF(IPODT.NE.1)K34=4
      IF(ISRPS.EQ.0)CH='BROJ'
      IF(ISRPS.EQ.1)CH='NUM.'
      MXS=1
C
CS     P  O  D  A  C  I      O      S  L  O  J  E  V  I  M  A
CE     D  A  T  A      A  B  O  U  T      L  A  Y  E  R  S
C
      IF(MSET.GT.0) THEN
        CH='SET '
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,2500)
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,6500)
        DO 2 I=1,MSET
          CALL ISPITA(ACOZ)
          IF(INDFOR.EQ.1)
     1    READ(IULAZ,*) NSLOJ(I)
          IF(INDFOR.EQ.2)
     1    READ(ACOZ,1000) NSLOJ(I)
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,2530) I,NSLOJ(I)
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,6530) I,NSLOJ(I)
          IF(NSLOJ(I).LT.1.OR.NSLOJ(I).GT.MSLOJ)THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2505)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6505)
            STOP 'STOP - UEL4BC'
          ENDIF
      IF(NSLOJ(I).GT.MXS) MXS=NSLOJ(I) 
            TTT=0.D0
            DO 1 J=1,NSLOJ(I)
              CALL ISPITA(ACOZ)
              IF(INDFOR.EQ.1)
     1        READ(IULAZ,*)   MATSL(J,I),DSLOJ(J,I),BBET(J,I)
              IF(INDFOR.EQ.2)
     1        READ(ACOZ,1515) MATSL(J,I),DSLOJ(J,I),BBET(J,I)
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,2540) J,MATSL(J,I),DSLOJ(J,I),BBET(J,I)
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,6540) J,MATSL(J,I),DSLOJ(J,I),BBET(J,I)
              BBET(J,I)=BBET(J,I)*3.1415926536D0/180.D0
            TTT=TTT+DSLOJ(J,I)
    1       CONTINUE
CS....  PROVERA ZA DEBLJINE
      IF(DABS(TTT-1.D0).LT.1.D-6) GO TO 2
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2550) TTT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6550) TTT
        STOP'STOP - UEL4BC'
    2   CONTINUE      
      ENDIF
C
CS     P  O  D  A  C  I      O      E  L  E  M  E  N  T  I  M  A
CE     D  A  T  A      A  B  O  U  T      E  L  E  M  E  N  T  S
C
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3).AND.IPODT.NE.1)
     1WRITE(IZLAZ,2000) CH
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3).AND.IPODT.NE.1)
     1WRITE(IZLAZ,6000) CH
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3).AND.IPODT.EQ.1)
     1WRITE(IZLAZ,2600) CH
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3).AND.IPODT.EQ.1)
     1WRITE(IZLAZ,6600) CH
      NMATS=  1
      IPRCOS=-1
      IPGSS= -1
      ISNAA= -1
      ISNAA=  0
      THICS=  1.D0
      I = 0
      NAUT=0
    5 I = I + 1
      CALL ISPITA(ACOZ)
      IF(I.EQ.1) KARTI=KARTIC
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) NN,NMAT,IPRCO,ISNA,IPGS,THI,KORC
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1010) NN,NMAT,IPRCO,ISNA,IPGS,THI,KORC
      MCVEL(I)=NN
      NI=NN
      IF(I.EQ.1) THEN
        NMA=NN
        NMI=NN
      ELSE
        IF(NMA.LT.NN) NMA=NN
        IF(NMI.GT.NN) NMI=NN
      ENDIF
      NN=I
      CALL ISPITA(ACOZ)
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) (NEL(NN,J),J=1,NCVE)
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1000) (NEL(NN,J),J=1,NCVE)
      IF(NMAT.EQ.0) NMAT=NMATS
      NMATS=NMAT
      MATV(NN)= NMAT
      IF (IPRCO.EQ.0) IPRCO=IPRCOS
      IPRCOS=IPRCO
      IF(IPRCO.LT.0) IPRCO = 0
      IPRCV(NN)=IPRCO
      IF(ISNA.EQ.0) ISNA=ISNAA
      ISNAA=ISNA
      IF(ISNA.LT.0) ISNA = 0
      ISNAP(NN)=ISNA
      IF(IPGS.EQ.0) IPGS=IPGSS
      IPGSS=IPGS
      IF(IPGS.LT.0) IPGS = 0
      IPGCV(NN)=IPGS
      IF (DABS(THI).LT.1.D-20) THI=THICS
      THICS=THI
      THICK(NN)=THI
      IF(IPODT.EQ.1)THEN
        IF(NULAZ.EQ.1.OR.NULAZ.EQ.3)
     1  WRITE(IZLAZ,5001) MCVEL(NN),(NEL(NN,J),J=1,3),NMAT,IPRCO,ISNA,
     1  IPGS,THI,KORC
      ENDIF
      IF(IPODT.NE.1)THEN
        IF(NULAZ.EQ.1.OR.NULAZ.EQ.3)
     1  WRITE(IZLAZ,1001) MCVEL(NN),(NEL(NN,J),J=1,4),NMAT,IPRCO,ISNA,
     1  IPGS,THI,KORC
        IF((NULAZ.EQ.1.OR.NULAZ.EQ.3).AND.KDT.EQ.3)
     1  WRITE(IZLAZ,1002)  (NEL(NN,J),J=5,NCVE)
      ENDIF
      IF(NAUT.GT.0) GO TO 30
      IF(KORC.NE.0) GO TO 20
      IF(I.EQ.NESA) GO TO 50
      GO TO 5
C
   20 NAUT=1
      N1=NI
      KORA=KORC
      GO TO 5
C
CS     AUTOMATSKO GENERISANJE PODATAKA IZMEDJU CVOROVA N1 I N2
CE     AUTOMATIC  GENERATION BETWEN NODES  N1  AND  N2
C
   30 N2=NI
      NN2=NN
      NN1=NN-1
      N11=NEL(NN1,1)
      N22=NEL(NN2,1)
      N12=N22-N11
      CALL DELJIV(N12,KORA,INDD)
      IF(INDD.EQ.1) GO TO 100
      DO 40 NC=2,K34
      N11=NEL(NN1,NC)
      N22=NEL(NN2,NC)
      N21=N22-N11
      IF(N12.NE.N21) GO TO 100
   40 CONTINUE
      DO 45 NC=K34+1,NCVE
      N11=NEL(NN1,NC)
      N22=NEL(NN2,NC)
      IF(N11.EQ.0.AND.N22.EQ.0) GO TO 45
      N21=N22-N11
      IF(N12.NE.N21) GO TO 100
   45 CONTINUE
      NNN=N2-N1-1
      NGG=N12/KORA-1
      IF(NNN.NE.NGG) GO TO 150
      IAUT=N12/KORA-1
      NM=NN+IAUT
      MCVEL(NM)=MCVEL(NN)
      MATV(NM) = MATV(NN)
      IPRCV(NM)=IPRCV(NN)
      ISNAP(NM)=ISNAP(NN)
      IPGCV(NM)=IPGCV(NN)
      THICK(NM)=THICK(NN)
      DO 32 II=1,NCVE
      NEL(NM,II)=NEL(NN,II)
   32 CONTINUE
      DO 34 J=1,IAUT
      JJ=NN1+J
      N1=N1+1
      MCVEL(JJ)=N1
      MATV(JJ) = MATV(NN1)
      IPRCV(JJ)=IPRCV(NN1)
      ISNAP(JJ)=ISNAP(NN1)
      IPGCV(JJ)=IPGCV(NN1)
      THICK(JJ)=THICK(NN1)
      DO 35 II=1,NCVE
      NODP=NEL(JJ-1,II)
      NEL(JJ,II)=NODP+KORA
      IF(NODP.EQ.0) NEL(JJ,II) = 0
   35 CONTINUE
   34 CONTINUE
      I=NM
      IF(I.EQ.NESA) GO TO 50
      NAUT=0
      IF(KORC.EQ.0) GO TO 5
      KORA=KORC
      NAUT=1
      N1=N2
      GO TO 5
C
CS     ODREDJIVANJE MAKSIMALNOG BROJA CVOROVA
CE     OBTAIN MAXIMUM NUMBER OF NODES PER ELEMENT
C
   50 NNNN=NCVE
C     NCVE=K34
C     DO 60 I=1,NESA
C     DO 60 J=K34+1,NNNN
C     IJ=NEL(I,J)
C     IF(IJ.GT.0.AND.J.GT.NCVE) NCVE=J
C  60 CONTINUE
C
CS     STAMPANJE UCITANIH I GENERISANIH PODATAKA
CE     PRINT INPUT AND GENERATED DATA
C
      IF(NULAZ.NE.1.AND.NULAZ.NE.3) RETURN
      CALL WBROJK(KARTI,0)
      IF(ISRPS.EQ.0.AND.IPODT.EQ.1)
     1WRITE(IZLAZ,2740) CH
      IF(ISRPS.EQ.1.AND.IPODT.EQ.1)
     1WRITE(IZLAZ,6740) CH
      IF(ISRPS.EQ.0.AND.IPODT.NE.1)
     1WRITE(IZLAZ,2140) CH
      IF(ISRPS.EQ.1.AND.IPODT.NE.1)
     1WRITE(IZLAZ,6140) CH
      DO 70 I=1,NESA
      IF(IPODT.EQ.1)THEN
        WRITE(IZLAZ,5001) MCVEL(I),(NEL(I,J),J=1,3),
     1  MATV(I),IPRCV(I),ISNAP(I),IPGCV(I),THICK(I)
      ENDIF
      IF(IPODT.NE.1)THEN
        WRITE(IZLAZ,1001) MCVEL(I),(NEL(I,J),J=1,4),
     1  MATV(I),IPRCV(I),ISNAP(I),IPGCV(I),THICK(I)
        IF(KDT.EQ.3) WRITE(IZLAZ,1002) (NEL(I,J),J=5,NCVE)
      ENDIF
   70 CONTINUE
      RETURN
C
  150 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2110) NN1,NN2,NGG
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6110) NN1,NN2,NGG
      STOP
  100 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2100) N22,N11,KORA
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6100) N22,N11,KORA
      STOP
C
 1000 FORMAT(14I5)
 1001 FORMAT(11X,I5,8X,4I6,2X,I6,3X,I6,3X,I6,4X,I6,6X,1PD10.3,I6)
 1002 FORMAT(19X,13I6)
 1010 FORMAT(5I5,F10.0,I5)
 1515 FORMAT(I5,2F10.4)
 5001 FORMAT(11X,I5,8X,3I6,8X,I6,3X,I6,3X,I6,4X,I6,6X,1PD10.3,I6)
C-----------------------------------------------------------------------
 2000 FORMAT(///6X,'U C I T A N I    P O D A C I   O    E L E M E N T I
     1M A    I Z O P A R A M E T A R S K E    L J U S K E'/6X,103('-')//
     1/11X,'(MOGUCE GENERISANJE PODATAKA O ELEMENTIMA,'/12X,         'UC
     2ITATI POTREBAN BROJ KARTICA ZA DEFINISANJE SVIH ELEMENATA)'///11X,
     3'ELEMENT',7X,'CVOR1 CVOR2 CVOR3 CVOR4',5X,'MAT.',4X,'KOORD.',4X,
     4'NAPON',5X,'NAPON',5X,'DEBLJINA',4X,'KORAK'/12X,'BROJ',3X,' CVOR5
     4                       ',4X,A4,4X,'STAMPA',4X,'STAMPA',4X,
     4'CVORA')
 2100 FORMAT(///' BROJ CVORA N2=',I5,' NE MOZE SE DOBITI SABIRANJEM BROJ
     1A CVORA N1=',I5,' I KONACNOG BROJA KORAKA KORA=',I5)
 2110 FORMAT(///' IZMEDJU ELEMENATA N1=',I5,' I N2=',I5,' NEMA NG=',I5,
     1' ELEMENATA KOJE TRBA GENERISATI')
 2140 FORMAT(6X,'G E N E R I S A N I    P O D A C I    O    E L E M E N
     1 T I M A    I Z O P A R A M E T A R S K E   L J U S K E'
     1 /6X,110('-')///11X,
     3'ELEMENT',7X,'CVOR1 CVOR2 CVOR3 CVOR4',5X,'MAT.',4X,'KOORD.',4X,
     4'NAPON',5X,'NAPON',5X,'DEBLJINA'           /12X,'BROJ',3X,' CVOR5
     4                       ',4X,A4,4X,'STAMPA',4X,'STAMPA',4X,
     4'CVORA')
 2500 FORMAT(///6X,' U C I T A N I    P O D A C I   O   V I S E S L O J 
     1N I M    S E T O V I M A    M A T E R I J A L A'/6X,99('-')///)
 2505 FORMAT(///' BROJ SLOJEVA U MATERIJALNOM SETU MORA BITI VECI OD 0'/
     1' (MAKSIMALNO :     MSLOJ )')
 2530 FORMAT(//10X,'MATERIJALNI SET (',I3,') ',5X,'BROJ SLOJEVA =',I3/)
 2540 FORMAT(/10X,'SLOJ =',I3/10X,'MATERIJAL =',I3/10X,'RELATIVNA ',
     1'DEBLJINA =',1PD10.3/10X,'UGAO VLAKANA =',1PD10.3) 
 2550 FORMAT(/// ' ZBIR RELATIVNIH DEBLJINA SLOJEVA U MATERIJALNOM SETU 
     1MORA BITI   1.00'/' (KONTROLNI ZBIR JE :   TTT =',1PD10.3)
 2600 FORMAT(///6X,'U C I T A N I    P O D A C I   O    E L E M E N T I
     1M A    T R O U G A O N E    P L O C E / L J U S K E'/6X,103('-')//
     1/11X,'(MOGUCE GENERISANJE PODATAKA O ELEMENTIMA,'/12X,         'UC
     2ITATI POTREBAN BROJ KARTICA ZA DEFINISANJE SVIH ELEMENATA)'///11X,
     3'ELEMENT',7X,'CVOR1 CVOR2 CVOR3      ',5X,'MAT.',4X,'KOORD.',4X,
     4'NAPON',5X,'NAPON',5X,'DEBLJINA',4X,'KORAK'/12X,'BROJ',3X,'      
     4                       ',4X,A4,4X,'STAMPA',4X,'STAMPA',4X,
     4'CVORA')
 2740 FORMAT(6X,'G E N E R I S A N I    P O D A C I    O    E L E M E N
     1 T I M A    T R O U G A O N E   P L O C E / L J U S K E'
     1 /6X,110('-')///11X,
     3'ELEMENT',7X,'CVOR1 CVOR2 CVOR3      ',5X,'MAT.',4X,'KOORD.',4X,
     4'NAPON',5X,'NAPON',5X,'DEBLJINA'           /12X,'BROJ',3X,'       
     4                       ',4X,A4,4X,'STAMPA',4X,'STAMPA',4X,
     4'CVORA')
C-----------------------------------------------------------------------
 6000 FORMAT(///6X,'R E A D I N G    D A T A    A B O U T    S H E L L    
     1  E L E M E N T S'/6X,71('-')///11X,
     3'ELEMENT',7X,'NODE1 NODE2 NODE3 NODE4',5X,'MAT.',4X,'COORD.',4X,
     4'STRESS',4X,'STRESS',5X,'THICK',6X,'STEP'/11X,'NUMBER',2X,' NODE5
     4                       ',4X,A4,4X,'PRINT ',4X,'PRINT ',3X,
     4'AT NODE')
 6100 FORMAT(///' NODE NUMBER N2=',I5,' CAN NOT BE DEFINED BY SUPERPOSIT
     1ION OF NODE N1=',I5,' WITH A NUMBER OF STEPS  KORA=',I5)
 6110 FORMAT(///' AMONG ELEMENTS N1=',I5,' AND N2=',I5,' THERE IS NO  ',
     1'NG=',I5,' ELEMENTS TO GENERATE')
 6140 FORMAT(6X,'G E N E R A T E D   D A T A   A B O U T   S H E L L   E
     1 L E M E N T S'/6X,69('-')///11X,
     3'ELEMENT',7X,'NODE1 NODE2 NODE3 NODE4',5X,'MAT.',4X,'COORD.',4X,
     4'STRESS',4X,'STRESS',5X,'THICK',6X,'STEP'/11X,'NUMBER ',2X,'NODE5
     4                       ',4X,A4,4X,'PRINT ',4X,'PRINT ',3X,
     4'AT NODE')
 6500 FORMAT(///6X,' R E A D I N G    D A T A    A B O U T    M U L T I 
     1L A Y E R E D    M A T E R I A L    S E T S'/6X,93('-')///)
 6505 FORMAT(///' NUMBER OF LAYERS IN MATERIAL SET MUST BE GREATER',
     1          ' THAN   0'/' (MAXIMUM :     MSLOJ )')
 6530 FORMAT(//10X,'MATERIAL SET (',I3,') ',5X,'NUMBER OF LAYERS =',I3/)
 6540 FORMAT(/10X,'LAYER =',I3/10X,'MATERIAL =',I3/10X,'RELATIV ',
     1'THICKNESS =',1PD10.3/10X,'FIBER ANGLE =',1PD10.3) 
 6550 FORMAT(/// ' RELATIV THICKNESSES SUM IN MATERIAL SET MUST BE', 
     1'   1.00'/' (CONTROL SUM IS :   TTT =',1PD10.3)
 6600 FORMAT(///6X,'R E A D I N G    D A T A    A B O U T    T R I A N G  
     1 U L A R     S H E L L  /  P L A T E'/6X,90('-')///11X,
     3'ELEMENT',7X,'NODE1 NODE2 NODE3      ',5X,'MAT.',4X,'COORD.',4X,
     4'STRESS',4X,'STRESS',5X,'THICK',6X,'STEP'/11X,'NUMBER',2X,'      
     4                       ',4X,A4,4X,'PRINT ',4X,'PRINT ',3X,
     4'AT NODE')
 6740 FORMAT(6X,'G E N E R A T E D   D A T A   A B O U T   T R I A N G U
     1 L A R    S H E L L  /  P L A T E'/6X,87('-')///11X,
     3'ELEMENT',7X,'NODE1 NODE2 NODE3      ',5X,'MAT.',4X,'COORD.',4X,
     4'STRESS',4X,'STRESS',5X,'THICK',6X,'STEP'/11X,'NUMBER ',2X,'     
     4                       ',4X,A4,4X,'PRINT ',4X,'PRINT ',3X,
     4'AT NODE')
C-----------------------------------------------------------------------
      END
C======================================================================
      SUBROUTINE UEL4U3 (DEC,NELC,IMAC,NAPC,DEB,NOP,IMAT,NAPV,NESA2,
     1                   NSLOJ,MATSL,BBET,DSLOJ)

      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C . ULAZNI PODACI ZA PLOCE SA 4 CVORA PO ELEMENTU 
C . -PREVODJENJE NA TROUGAONE ELEMENTE
C
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /GLAVNI/ NP,NGELEM,NMATM,NPER,
     1                IOPGL(6),KOSI,NDIN,ITEST
      COMMON/PL3CEL/ NPP,NGAUS,INULAZ,KDT,
     1IPP,IPMK,IPP2,MAXSK,INDPF,MATP,INDNA,NAPONG(3,5),LM(18),NDEB
      COMMON /BROJUK/ KARTIC,INDFOR,NULAZ
      COMMON /SRPSKI/ ISRPS
      DIMENSION NELC(NESA2,*),NAPC(*),IMAC(*),DEC(*),
     1          NOP(NE,*),NAPV(*),IMAT(*),DEB(*),
     1          NSLOJ(*),MATSL(MSLOJ,*),BBET(MSLOJ,*),DSLOJ(MSLOJ,*)
C
      IF(KDT.EQ.3) THEN
      DO 7 IN=1,NESA2
      DO 7 KE=1,4
      K=KE+1
      IF (KE.EQ.4) K=1
      N1=4*(IN-1)+KE
      NOP(N1,1)=NELC(IN,5)
      NOP(N1,2)=NELC(IN,KE)
      NOP(N1,3)=NELC(IN,K)
      IMAT(N1) = IMAC(IN)
      DEB(N1)  = DEC(IN)
      NAPV(N1) = NAPC(IN)
    7 CONTINUE
      GO TO 100
      ENDIF
C
      IF(KDT.EQ.1.OR.KDT.EQ.2) THEN
      DO 8 IN=1,NESA2
      N1=2*IN-1
      N2=N1+1
      IF (KDT.EQ.1) GO TO 20
C . ORIJENTACIJA HIPOTENUZE U DESNO ; KDT=2
      NOP(N1,1)=NELC(IN,4)
      NOP(N1,2)=NELC(IN,1)
      NOP(N1,3)=NELC(IN,3)
      NOP(N2,1)=NELC(IN,2)
      NOP(N2,2)=NELC(IN,3)
      NOP(N2,3)=NELC(IN,1)
      IMAT(N1) = IMAC(IN)
      IMAT(N2) = IMAC(IN)
      DEB(N1)  = DEC(IN)
      DEB(N2)  = DEC(IN)
      NAPV(N1) = NAPC(IN)
      NAPV(N2) = NAPC(IN) 
      GO TO 8
C . ORIJENTACIJA HIPOTENUZE U LEVO ; KDT=1 ;
   20 DO 9 I=1,2
      NOP(N2,I)=NELC(IN,I+2)
    9 NOP(N1,I)=NELC(IN,I)
      NOP(N1,3)=NELC(IN,4)
      NOP(N2,3)=NELC(IN,2)
      IMAT(N1) = IMAC(IN)
      IMAT(N2) = IMAC(IN)
      DEB(N1)  = DEC(IN)
      DEB(N2)  = DEC(IN)
      NAPV(N1) = NAPC(IN)
      NAPV(N2) = NAPC(IN) 
    8 CONTINUE
      ENDIF
C
  100 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2008)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6008)
      DO 30 K=1,NE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2009) K,(NOP(K,I),I=1,3)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6009) K,(NOP(K,I),I=1,3)
   30 CONTINUE
      RETURN
C
C-----------------------------------------------------------------------
 2008 FORMAT(/20X,'ELEMENT    DOBIJENI  CVOROVI'/
     1        21X, 'BROJ        I   II   III ')
 2009 FORMAT(19X,I5,5X,3I5)
C-----------------------------------------------------------------------
 6008 FORMAT(/20X,'ELEMENT    GENERATED NODES  '/
     1        21X, 'NUMBER      I   II   III ')
 6009 FORMAT(19X,I5,5X,3I5)
C-----------------------------------------------------------------------
      END
C=======================================================================
      SUBROUTINE LMMHT3(ID,NEL,LMEL,NPP6)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C===================================================
C     FORMIRANJE VEKTORA LM I VISINA STUBOVA (MHT)
C===================================================
      include 'paka.inc'
      
C
      COMMON/PL3CEL/ NPP,NGAUS,INULAZ,KDT,
     1IPP,IPMK,IPP2,MAXSK,INDPF,MATP,INDNA,NAPONG(3,5),LM(18),NDEB
      COMMON /GLAVNI/ NP,NGELEM,NMATM,NPER,
     1                IOPGL(6),KOSI,NDIN,ITEST
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /REPERI/ LCORD,LID,LMAXA,LMHT
      COMMON /GEORGE/ TOLG,ALFAG,ICCGG
      COMMON /DRAKCE/ IDRAKCE,NELUK,NZERO,NEED1,NEED2,NEED3,NNZERO
     1                ,IROWS,LAILU,LUCG,LVCG,LWCG,LPCG,LRCG
C
      DIMENSION ID(NP,*),NEL(NE,*),LMEL(NPP6,*)
C....   PETLJA PO ELEMENTIMA
      DO 100 NLM=1,NE
      DO 10 NC=1,NPP
      IF(NEL(NLM,NC).EQ.0) GO TO 10
      JJ=NEL(NLM,NC)
      KK=6*(NC-1)
      DO 20 I=1,6
   20 LMEL(KK+I,NLM)=ID(JJ,I)
   10 CONTINUE
C....   FORMIRANJE VISINA STUBOVA
      CALL VISINE(A(LMHT),NPP6,LMEL(1,NLM))
      IF (IABS(ICCGG).EQ.1) THEN
         ND=NPP6
         WRITE(IDRAKCE) ND,(LMEL(I,NLM),I=1,ND)
         NELUK=NELUK+1
      ENDIF
  100 CONTINUE
      RETURN
      END
C=======================================================================
      SUBROUTINE GRAF3E(NEL,MCVEL,ICVEL,THID,NMAT)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C   
CS     PROGRAM ZA STAMPANJE TROUGAONE LJUSKE U UNIVERZALNI FILE
CE     TRIANGULAR SHELL
CE     PROGRAM FOR PRINTOUT DATA IN UNIVERSAL GRAPHICS FILE
C
      COMMON/PL3CEL/ NPP,NGAUS,INULAZ,KDT,
     1IPP,IPMK,IPP2,MAXSK,INDPF,MATP,INDNA,NAPONG(3,5),LM(18),NDEB
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /SUMELE/ ISUMEL,ISUMGR
      COMMON /SRPSKI/ ISRPS
      COMMON /NIDEAS/ IDEAS
C
      DIMENSION NEL(NE,*),MCVEL(*),THID(*),NMAT(*)
      DIMENSION FIZ(18),NNEL(6)
C
      IF(ideas.eq.-1) return
      ISUMGR=ISUMGR+1
C
C     FIZICKE OSOBINE
C
      CALL CLEAR(FIZ,18)
      ICL=1
      IPH=60
      NPR=6
      FIZ(1)=THID(1)
      IND=-1
      ITYP=772
      WRITE(IGRAF,1100) IND
      WRITE(IGRAF,1100) ITYP
      WRITE(IGRAF,1000) ISUMGR,IPH,NPR
      IF(ISRPS.EQ.0)
     1WRITE(IGRAF,2000) ISUMGR
      IF(ISRPS.EQ.1)
     1WRITE(IGRAF,6000) ISUMGR
      WRITE(IGRAF,1200) (FIZ(I),I=ICL,18)
      WRITE(IGRAF,1100) IND
C
C     M A T E R I J A L I
C
      MAT=NMAT(1)
      CALL MELGR(MAT)
C
C     E L E M E N T I
C
      IF(NCVE.NE.3.AND.NCVE.NE.6) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2200) NGE
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6200) NGE
      ENDIF
      NNCVE=NCVE
      IF(NCVE.GT.3.AND.NCVE.LT.6) NCVE=3
C      IF(NGAUSX.EQ.7.AND.NCVE.EQ.3) GO TO 150
C     GRAFICKI OPIS LJUSKE: SA 3 CVORA = 2, SA 6 CVOROVA = 3
      IFGD=2
      IF(NCVE.EQ.6) IFGD=3
C     VRSTA  ELEMENTA: 
C          JEDNOSLOJNA    SA  3 CVORA = 91, SA 6 CVOROVA = 92
      IFDI=91
      IF(NCVE.EQ.6) IFDI=92
C          VISESLOJNA     SA  3 CVORA = 91, SA 6 CVOROVA = 92
      IF(MSET.GT.0) THEN
         IFDI=91
         IF(NCVE.EQ.6) IFDI=92
      ENDIF
C     TABELA FIZICKIH OSOBINA
      IPTN=ISUMGR
C     TABELA MATERIJALA
      MPTN=ISUMGR
C     BOJA  
      ICOL=7
C     BROJ CVOROVA NA ELEMENTU
      NNODS=NCVE
      IND=-1
      ITYP=71
      WRITE(IGRAF,1100) IND
      WRITE(IGRAF,1100) ITYP
      DO 10 I=1,NE
C        REDNI BROJ ELEMENTA
         IEL=I+ISUMEL
         IF(ICVEL.EQ.1.AND.INULAZ.EQ.1) IEL=MCVEL(I)
         WRITE(IGRAF,1000) IEL,IFGD,IFDI,IPTN,MPTN,ICOL,NNODS
         IF(NCVE.EQ.3) THEN
            WRITE(IGRAF,1000)(NEL(I,J),J=1,3)
         ELSE
            IZ=0
            DO 5 J=1,3
               IZ=IZ+1
               NNEL(IZ)=NEL(I,J)
               IZ=IZ+1
               NNEL(IZ)=NEL(I,J+3)
               IF(NNEL(IZ).EQ.0)NNEL(IZ)=NNEL(IZ-1)
    5       CONTINUE
            WRITE(IGRAF,1000) NNEL
         ENDIF
   10 CONTINUE
      WRITE(IGRAF,1100) IND
      ISUMEL=ISUMEL+NE
      NCVE=NNCVE
      RETURN
C
 1000 FORMAT(8I10)
 1100 FORMAT(I6)
 1200 FORMAT(6(1PE13.5))
C-----------------------------------------------------------------------
 2000 FORMAT('FIZICKI SET :',I10)
 2200 FORMAT(//' PROGRAM ZA GRAFICKO PRIKAZIVANJE REZULTATA "IDEAS"'/
     1' ZAHTEVA TROUGAO SA 3 ILI 6 CVOROVA U GRUPI ELEMENATA NGE ='
     1,I5)
C-----------------------------------------------------------------------
 6000 FORMAT('PHISICAL PROPERTIES SET :',I10)
 6200 FORMAT(//' GRAPHIC PACKAGE   "IDEAS"'/
     1' PERMITS ONLY TRIANGLES WITH 3 OR 6 NODES PER ELEMENT IN GROUP',
     1'  NGE =',I5)
C-----------------------------------------------------------------------
      END
