C=======================================================================
C
C        READ DATA ABOUT BEAM ELEMENTS
C
C   SUBROUTINE UL6EGL
C              UL6EK
C              UL6EK2
C              LIMMH6
C              TGRAF6
C
C=======================================================================
      SUBROUTINE ULTPG
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C     MAIN PROGRAM FOR DATA READING
C
      include 'paka.inc'
      
      COMMON /ELEMA6/ MXAU,LAU,LLMEL,LNEL,LNMAT,LCTR,LMGLV,LLUV,LINDPR,
     1                LELKG,LNAPGV,LPRR,LNTIPG
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /DUPLAP/ IDVA
      COMMON /BROJUK/ KARTIC,INDFOR,NULAZ
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /DIREKT/ LSTAZZ(9),LDRV0,LDRV1,LDRV,IDIREK
      COMMON /PGREDC/ NPUN,NPRBR,MAXPRR,NPRES,ICV1,ICV2,MATG,
     1                NKARD,MG,NVR,NWRITE,NAPG,INDOF
      COMMON /COMPRF/ YC,ZC,YI,ZI,ALFB,TK,CAPAY,CAPAZ,AREA,POVR,YM,ZM,
     1                DDELT,YP,SWO(1),OM(1),DELTAP(3),TAUTK(3),OY,OZ,
     2                NT,NELM,NTIP,NKAR,IND,INDRPR(3),KR1,NEXTR,NPRPR
      COMMON /PAKDFL/ IND16,IR16,IND40,IND49,IND69,IND99
      COMMON /BTHDTH/ INDBTH,INDDTH,LTBTH,LTDTH
C
      IDIREK=0
C
C     INPUT DATA LOCATION
C
      NPRES=1
      MATG=1 
C
      MG=0
      NVR=0
      NPRPR=1
      IND16=0
C
      NAPG=3 
      NCVE=2
      LNEL = 1
      LNTIPG = LNEL + NE * 2
C      I = NE
C      IF(NPRES.GT.1.OR.MATG.GT.1) I = NE
C      IF(NPRES.GT.1.AND.MATG.GT.1) I = I + I
      LCTR = LNTIPG + NE * 2
      CALL DELJIV(LCTR,2,INDL)
      IF(INDL.EQ.0) LCTR=LCTR+1
      LTBTH = LCTR + NE*3*IDVA
      LTDTH =LTBTH
      IF(INDBTH.EQ.1) LTDTH=LTBTH+NE*IDVA
      LMGLV =LTDTH
      IF(INDDTH.EQ.1) LMGLV=LTDTH+NE*IDVA
      IF(MG.EQ.2) GO TO 5
      LLUV = LMGLV + 1
      LINDPR = LLUV + 1
      GO TO 6
    5 LLUV = LMGLV + NE
      LINDPR = LLUV + 12*NE
C
    6 LELKG = LINDPR + NPRES
      CALL DELJIV(LELKG,2,INDL)
      IF(INDL.EQ.0) LELKG=LELKG+1
      LNAPGV = LELKG + 3*MATG*IDVA
      LPRR = LNAPGV + 1
      IF(NAPG.EQ.3) LPRR = LNAPGV + NE
      LCEL=LPRR
      IF(ICVEL.EQ.1) THEN
        LPRR=LCEL+NE
      ENDIF
      CALL DELJIV(LPRR,2,INDL)
      IF(INDL.EQ.0) LPRR=LPRR+1
      CALL DELJIV(LMAX,2,INDL)
      IF(INDL.EQ.0) LMAX=LMAX+1
      LAU = LMAX
C
C     CALL SUBROUTINE TO READ DATA IN VECTOR AU
C
      CALL UL6EK(A(LAU))
      NCVE6=NCVE*6
      NN6 = NCVE6*NCVE6
      MXAE = NCVE6+(2*NN6+NCVE6*(NCVE6+1)/2)*IDVA
      LMAX = LMAX + MXAE
C
      RETURN
      END
C=======================================================================
C
C=======================================================================
      SUBROUTINE UL6EK(AU)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C     MAIN CONTROL SUBROUTINE FOR DATA READING IN AU
C
      include 'paka.inc'
      
      COMMON /ELEMA6/ MXAU,LAU,LLMEL,LNEL,LNMAT,LCTR,LMGLV,LLUV,LINDPR,
     1                LELKG,LNAPGV,LPRR,LNTIPG
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /REPERI/ LCORD,LID,LMAXA,LMHT
      COMMON /DUPLAP/ IDVA
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /COMPRF/ YC,ZC,YI,ZI,ALFB,TK,CAPAY,CAPAZ,AREA,POVR,YM,ZM,
     1                DDELT,YP,SWO(1),OM(1),DELTAP(3),TAUTK(3),OY,OZ,
     2                NT,NELM,NTIP,NKAR,IND,INDRPR(3),KR1,NEXTR,NPRPR
      COMMON /RAPRES/ MCOR,MELM,MCORK,MNNKAR,MNBROJ,MSTEX,MSZ,MSY,MEL,
     1                MCSI,MEXC,MSEX,MINDI,MDV,MELV,MKT,MPRRMX
      COMMON /TRAN/ X1,Y1,Z1,X2,Y2,Z2,DUZ,TRR(3,3),AKOR(4)
      COMMON /PGREDC/ NPUN,NPRBR,MAXPRR,NPRES,ICV1,ICV2,MATG,
     1                NKARD,MG,NVR,NWRITE,NAPG,INDOF
      COMMON /ITERAC/ METOD,MAXIT,TOLE,TOLS,TOLM,KONVE,KONVS,KONVM
      COMMON /SRPSKI/ ISRPS
      COMMON /RESTAR/ TSTART,IREST
      COMMON /LUCGRE/ ILU,ICP
      COMMON /BTHDTH/ INDBTH,INDDTH,LTBTH,LTDTH
      DIMENSION AU(*),IA(1)
      REAL AU
      EQUIVALENCE (A(1),IA(1))
C
C     CALL SUBROUTINE TO READ DATA IN VECTOR AU
C
      CALL ICLEAR(AU(LNEL),NE*NCVE)
C
      NMA=0
      NMI=0
      CALL UL6EK2(AU(LNEL),AU(LNTIPG),AU(LCTR),AU(LMGLV),
     1            AU(LLUV),AU(LINDPR),AU(LNAPGV),AU(LPRR),MXPR,
     1            AU(LCEL),NMA,NMI,ICVEL,0,AU(LTBTH),AU(LTDTH))
      IF(NBLGR.GE.0) CALL TGRAF6(AU(LNEL),AU(LCEL),AU(LCTR),ICVEL)
      IF(NBLGR.GE.0) 
     +       CALL TGRAU6(AU(LNEL),AU(LCEL),ICVEL,AU(LNTIPG),AU(LCTR),49)
      IF(ICVEL.EQ.1) CALL VEZACE(AU(LNEL),A(LELCV),NE,NCVE)
      CALL UL6EK2(AU(LNEL),AU(LNTIPG),AU(LCTR),AU(LMGLV),
     1            AU(LLUV),AU(LINDPR),AU(LNAPGV),AU(LPRR),MXPR,
     1            AU(LCEL),NMA,NMI,ICVEL,1,AU(LTBTH),AU(LTDTH))
C
      LLMEL=LPRR+(MPRRMX-MCOR)*IDVA
      LELC=LLMEL
      IF(ICVEL.EQ.1) THEN
        LLMEL=LELC+NMA-NMI+1
        CALL ICLEAR(AU(LELC),NMA-NMI+1)
        CALL VEZAEL(AU(LCEL),AU(LELC),NE,NMI)
      ENDIF
      LMXAU=LLMEL+NE*NCVE*6
      MXPR2=2*MXPR
      LMXAU=LMXAU+MXPR2
      MXAU = LMXAU - 1
      CALL DELJIV(MXAU,2,INDL)
      IF(INDL.EQ.1) MXAU=MXAU+1
      LMAX=LAU+MXAU
      IF (LMAX.LE.MTOT) GO TO 5
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2005) LMAX,MTOT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6005) LMAX,MTOT
      STOP
C
C     CALCULATION OF VECTOR LM AND CLOUMN HIGHTS
C
    5 CALL ICLEAR(AU(LLMEL),NE*NCVE*6)
      CALL LMIMH6(A(LID),AU(LNEL),AU(LLMEL))
C
      LMAX8=LMAX8+1
      WRITE(IELEM,REC=LMAX8)
     1 NCVE,MXAU,LNEL,LNMAT,LNTIPG,LCTR,LMGLV,LLUV,LINDPR,LELKG,
     2 LNAPGV,LPRR,LCEL,LELC,NMA,NMI,
     3 YC,ZC,YI,ZI,ALFB,TK,CAPAY,CAPAZ,YM,ZM,AREA,POVR,DDELT,YP,
     1 OY,OZ,(DELTAP(I),I=1,3),(TAUTK(I),I=1,3),(AKOR(I),I=1,4),
     2 NT,NELM,NTIP,NKAR,KR1,NEXTR,NPRPR,INDOF,ILU,ICP,
     1 INDBTH,INDDTH,LTBTH,LTDTH
      CALL WRITDD(AU(LNEL),MXAU/IDVA,IELEM,LMAX8,LDUZI)
      CALL DELJIV(LMAX,2,INDL)
      IF(INDL.EQ.0) LMAX=LMAX+1
      IF(IATYP.EQ.0) GO TO 10
CS....  VELICINE NA KRAJU PRETHODNOG KORAKA
      LPLAST=LMAX
      NPROS =NE*25+2
      LPLAS1=LPLAST+NPROS*IDVA
CS....  VELICINE ZA TEKUCI KORAK
      NPROS1=NE*25+2
      LMAX  =LPLAS1+NPROS1*IDVA
      IF(LMAX.GT.MTOT) CALL ERROR(1)
C
      IF(IREST.NE.1) THEN
C         IA(LPLAS1)=0
C         IA(LPLAS1+1)=0
         IA(LPLAST)=0
         IA(LPLAST+1)=0
         CALL CLEAR(A(LPLAST+2*IDVA),NE*25)
         CALL WRITDD(A(LPLAST),NPROS,IELEM,LMAX8,LDUZI)
         CALL WRITDD(A(LPLAST),NPROS,IELEM,LMAX8,LDUZI)
         CALL WRITDD(A(LPLAST),NPROS,IELEM,LMAX8,LDUZI)
      ELSE
         CALL READDD(A(LPLAST),NPROS,IELEM,LMAX8,LDUZI)
         CALL READDD(A(LPLAST),NPROS,IELEM,LMAX8,LDUZI)
         CALL READDD(A(LPLAST),NPROS,IELEM,LMAX8,LDUZI)
      ENDIF
      RETURN
C
   10 LSIGMA=LMAX
      NPROS=12*NE
      LMAX=LSIGMA+NPROS*IDVA
      IF(LMAX.GT.MTOT) CALL ERROR(1)
      CALL CLEAR(A(LSIGMA),NPROS)
      CALL WRITDD(A(LSIGMA),NPROS,IELEM,LMAX8,LDUZI)
      RETURN
C-----------------------------------------------------------------------
 2005 FORMAT(///' NEDOVOLJNA DIMENZIJA U VEKTORU A ZA PODATKE O GREDAMA
     1A'/' POTREBNA DIMENZIJA , LMAX=',I10/' RASPOLOZIVA DIMENZIJA,
     2NTOT =',I10)
 6005 FORMAT(///' NOT ENOUGH SPACE IN WORKING VECTOR  A'
     1/' REQUESTED DIMENSION , LMAX=',I10
     2/' AVAILABLE DIMENSION , MTOT=',I10)
C-----------------------------------------------------------------------
      END
C=======================================================================
C
C=======================================================================
      SUBROUTINE UL6EK2(NEL,NTIPG,CTR,MGLV,LUV,INDPR,NAPGV,PR,MAXPR,
     1                  MCVEL,NMA,NMI,ICVEL,IND10,TBTH,TDTH)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C     SUBROUTINE FOR READING DATA ABOUT BEAM ELEMENTS
C
      CHARACTER*250 ACOZ
      include 'paka.inc'
      
      COMMON /GLAVNI/ NP,NGELEM,NMATM,NPER,
     1                IOPGL(6),KOSI,NDIN,ITEST
      COMMON /REPERI/ LCORD,LID,LMAXA,LMHT
      COMMON /BROJUK/ KARTIC,INDFOR,NULAZ
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /PAKDFL/ IND16,IR16,IND40,IND49,IND69,IND99
      COMMON /RATPG/ LNITPG,LNORPV,LCTR,LCXYZ,LMGLV,LLUV,LINDER,LPRR
      COMMON /RAPRES/ MCOR,MELM,MCORK,MNNKAR,MNBROJ,MSTEX,MSZ,MSY,MEL,
     1                MCSI,MEXC,MSEX,MINDI,MDV,MELV,MKT,MPRRMX
      COMMON /PGREDG/ ELCON(3),EE,PNE,G
      COMMON /PGREDC/ NPUN,NPRBR,MAXPRR,NPRES,ICV1,ICV2,MATG,
     1                NKARD,MG,NVR,NWRITE,NAPG,INDOF
      COMMON /COMPRF/ YC,ZC,YI,ZI,ALFB,TK,CAPAY,CAPAZ,AREA,POVR,YM,ZM,
     1                DDELT,YP,SWO(1),OM(1),DELTAP(3),TAUTK(3),OY,OZ,
     2                NT,NELM,NTIP,NKAR,IND,INDRPR(3),KR1,NEXTR,NPRPR
      COMMON /RESTAR/ TSTART,IREST
      COMMON /SRPSKI/ ISRPS
      COMMON /LUCGRE/ ILU,ICP
      DIMENSION NEL(NE,*),NTIPG(NE,*),CTR(NE,*),TBTH(*),TDTH(*),
     1MGLV(*),LUV(NE,*),INDPR(*),NAPGV(*),PR(*),MCVEL(*)
C
C     DATA ABOUT ELEMENTS
C
      IF(IND10.EQ.1) GO TO 999
      MGL=0
      MAXPR = 0
      NAPP=1 
      NDISKE=46
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,2021)
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,6021)
C
C     DATA ABOUT CROSS SECTIONS
C
      MCOR   = 1
      MPRRMX = 1
C
      IR16 = IND16 - 1
      IF(IR16.LT.0) IR16 = 0
C
      DO 10 NPRBR = 1,NPRES
       CALL ISPITA(ACOZ)
       READ(ACOZ,1001) NT,NELM,NTIP,NKAR,OY,OZ,YM,ZM,ALFAU,INDOF
C... AKO JE NT.LT.2 ONDA SE ZADAJU GOTOVE KARAKTERISTIKE PRESEKA
      IF(NT.GE.2)THEN
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,2008) NPRBR,NT,NELM,NTIP,NKAR
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,6008) NPRBR,NT,NELM,NTIP,NKAR
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,2520) OY,OZ,ALFAU,INDOF
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,6520) OY,OZ,ALFAU,INDOF
C
        IF(NTIP.EQ.0) NTIP=1
        IPOMP=0
        IF(NTIP.LT.0) THEN
          NTIP=-NTIP
          IPOMP=1
        ENDIF 
        IF(NTIP.EQ.1) NKAR = 0
        NKAR1 = 0
        IF(NKAR.EQ.2) NKAR1 = 3
        IF(NAPP.EQ.0.OR.NAPG.EQ.0) GO TO 45
        MAXPRR = 5*NT+36*NELM+(4+NELM)*NKAR+NKAR1*NELM+1
        IF(NKAR.EQ.2) MAXPRR = MAXPRR + NELM
        GO TO 46
   45   MAXPRR = 5*NT+7*NELM+NKAR*(4+NELM)+NKAR1*NELM+1
   46   IF(MAXPR.LT.MAXPRR) MAXPR = MAXPRR
C
        LMAX = LMAX + MAXPRR
        IF(LMAX.LE.MTOT) GO TO 9
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2005) LMAX,MTOT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6005) LMAX,MTOT
        STOP'ULTPG1'
C
C  REPERI U RADNOM VEKTORU PRR
C
    9   MELM = MCOR + 3 * NT
        MCORK = MELM + NELM * 4
CE     CLOSED SECTION
        MNNKAR = MCORK + NKAR * 3
        MNBROJ = MNNKAR + NKAR
        NKARD = NKAR
        IF(NKARD.EQ.0) NKARD=1
        MEL = MNBROJ + NELM * NKAR
C
        MSTEX = MEL + NELM
        IF(IND16.EQ.0) IND16 = 1
C
CE     READ DATA ABOUT SECTION 
C
        CALL ULPRES (PR(MCOR),PR(MELM),PR(MCORK),PR(MNNKAR),
     1  PR(MNBROJ),ALFAU)
C
CE  SECTION DATA CALCULATION 
C
        CALL PROFIL (PR(1),PR(MELM),PR(MCORK),PR(MNNKAR),PR(MNBROJ),
     1  PR(MEL),PR(MSTEX),IPOMP)
C
        IF(INDOF.EQ.0) THEN
          OY=0.
          OZ=0.
        ELSE
          OY=ZC
          OZ=YC
C          WRITE(3,*) 'OY,OZ,ALFA-61',OY,OZ,ALFA
        ENDIF
      ELSE
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,2510) OY,OZ,YM,ZM
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,6510) OY,OZ,YM,ZM
C
C... UCITAVANJE MOMENATA INERCIJE (NT.LT.2)
C
        CALL ISPITA(ACOZ)
        READ(ACOZ,1500) POVR,YI,ZI,TK,ALFB,CAPAY,CAPAZ,ILU,ICP
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,2500) NPRBR,POVR,YI,ZI,TK,ALFB,CAPAY,CAPAZ,ILU,ICP
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,6500) NPRBR,POVR,YI,ZI,TK,ALFB,CAPAY,CAPAZ,ILU,ICP
        IF(DABS(CAPAY).LT.1.D-6) CAPAY=1.2D0
        IF(DABS(CAPAZ).LT.1.D-6) CAPAZ=1.2D0
        ALFB=ALFB*3.1415926536D0/180.D0
      ENDIF
C
        CAL=DCOS(ALFB)
        SAL=DSIN(ALFB)
        DUM=OY
        OY=DUM*CAL-OZ*SAL
        OZ=DUM*SAL+OZ*CAL
C
        INDPR(NPRBR) = 0
C
   10 CONTINUE
C
C     DATA ABOUT ELEMENTS 
C
      MGLV(1) = 0
      LUV(1,1) = 0
      NAPGV(1) = 0
      IF (MG.NE.2) GO TO 60
C
      DO 14 N=1,NE
      MGLV(N) = 0
      DO 14 J=1,12
   14 LUV(N,J) = 0
C
   60 IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2003)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6003)
      IF(ISRPS.EQ.0.AND.MG.EQ.2)
     1WRITE(IZLAZ,2007)
      IF(ISRPS.EQ.1.AND.MG.EQ.2)
     1WRITE(IZLAZ,6007)
C      IF(ISRPS.EQ.0.AND.MG.NE.2)
C     1WRITE(IZLAZ,2004)
C      IF(ISRPS.EQ.1.AND.MG.NE.2)
C     1WRITE(IZLAZ,6004)
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2013)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6013)
      ENDIF
C
C     LOOP OVER ALL ELEMENTS IN GROUP
C
      NN11 = 1
      MAT1 = 1
      NAP1 = 1
C
      DO 30 N=1,NE
         CALL ISPITA(ACOZ)
         if(ind56.eq.0) then
         READ(ACOZ,1002) NN,(NEL(N,J),J=1,2),MAT,NAP,(CTR(N,J),J=1,3),
     1                   BTH,DTH
         else
         READ(ACOZ,4002) NN,(NEL(N,J),J=1,2),MAT,NAP,(CTR(N,J),J=1,3),
     1                   BTH,DTH
         endif
      IF(ICVEL.EQ.1) THEN
         MCVEL(N)=NN
         NI=NN
         IF(N.EQ.1) THEN
            NMA=NN
            NMI=NN
         ELSE
            IF(NMA.LT.NN) NMA=NN
            IF(NMI.GT.NN) NMI=NN
         ENDIF
         NN=N
      ENDIF
         IF(INDBTH.EQ.1) TBTH(NN)=BTH
         IF(INDDTH.EQ.1) TDTH(NN)=DTH
C ZILE 
C OVO NIJE KOREKTNO ZA VISE PRESEKA !!!!!!!!!!!
      IF(NPRES.GT.1) GO TO 17
      NTIP = 1
      GO TO 19
C      GO TO 18
   17 NTIPG(NN,1) = NTIP
      IF(N.EQ.1.AND.NTIP.EQ.0) NTIPG(NN,1) = 1
      IF (NTIPG(NN,1).EQ.0) NTIPG(NN,1) = NTIPG(NN11,1)
      NN11 = NN
      NTIP = NTIPG(NN,1)
C
C   18 IF(MATG.GT.1) GO TO 19
C      MAT = 1
C      GO TO 21
   19 NTIPG(NN,2) = MAT
      IF(N.EQ.1.AND.MAT.EQ.0) NTIPG(NN,2) = 1
      IF(NTIPG(NN,2).EQ.0) NTIPG(NN,2) = NTIPG(MAT1,2)
      MAT1 = NN
      MAT = NTIPG(NN,2)
C
C  21 IF(NAPG.EQ.3) GO TO 22
      IF(NAPG.EQ.3) GO TO 22
      IF(NAPG.EQ.1) NAP = 1
      IF(NAPG.EQ.2) NAP = 2
      GO TO 23
CZ
   22 IF(N.EQ.1) NAP0=NAP
      IF(N.GT.1.AND.NAP0.EQ.-1) NAP=-1
CZ
      NAPGV(NN) = NAP
C
   23 IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
         IF(ICVEL.EQ.1) IN=MCVEL(NN)
         IF(ICVEL.EQ.0) IN=NN
         WRITE(IZLAZ,1010) IN,(NEL(NN,J),J=1,2),MAT,NAP,
     1                        (CTR(NN,J),J = 1,3),BTH,DTH
      ENDIF
C
      IF (MG.NE.2) GO TO 30
      MGLV(NN) = MGL
      IF (MGL.EQ.0) GO TO 30
      CALL ISPITA(ACOZ)
      READ(ACOZ,1000) (LUV(NN,J),J=1,12)
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2006) NN,(LUV(NN,J),J=1,12)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6006) NN,(LUV(NN,J),J=1,12)
C
   30 CONTINUE
      RETURN
C
C
C        STAMPANJE SEGMENATA U UNIVERZALNI FILE
C
C         IF(KOR.EQ.1.AND.ITER.EQ.0.AND.ISKNP.NE.2)
  999 IF(NT.GE.2)
     1         CALL TGRAS6(NEL,CTR,NE,NP,IATYP,NELM,NT,NGE,IREST,
     1                     A(LCORD),PR(MCOR),PR(MELM),YC,ZC,ALFB,INDOF)
C
      RETURN
C
 1000 FORMAT(14I5)
 1001 FORMAT(4I5,5F10.0,I5)
czile ovaj format nije korektan proveriti u starim primerima iz greda kako je tamo. 
 1002 FORMAT(4I5,5X,I5,5X,5F10.2)
c 
 4002 FORMAT(3I10,5x,I5,I5,5X,5F10.2)
 1010 FORMAT(I7,2I6,7X,2I5,6X,5(1PD12.4))
 1500 FORMAT(7F10.3,2i1)
C-----------------------------------------------------------------------
 2005 FORMAT(///' NEDOVOLJNA DIMENZIJA U VEKTORU A ZA PODATKE O GREDAMA
     1A'/' POTREBNA DIMENZIJA , LMAX=',I10/' RASPOLOZIVA DIMENZIJA,
     2NTOT =',I10)
 2021 FORMAT(///6X,'U C I T A N I   P O D A C I   O   T A N K O Z I D N
     1I M   G R E D A M A'/6X,71('-')///)
 2008 FORMAT(///6X,'P R E S E K   B R O J   ',I2//
     111X,'BROJ TACAKA ...................................    NT =',I5//
     211X,'BROJ SEGMENATA ................................  NELM =',I5//
     311X,'TIP PRESEKA ...................................  NTIP =',I5/
     616X,'EQ.1;  OTVOREN'/
     616X,'EQ.2;  ZATVOREN'/
     616X,'EQ.-1; OTVOREN, POMEREN'/
     616X,'EQ.-2; ZATVOREN, POMEREN'//
     411X,'BROJ GRANICNIH PRESEKA ........................  NKAR =',I5)
 2003 FORMAT(///6X,'P O D A C I   O   E L E M E N T I M A')
 2013 FORMAT(/' ELEMENT    CVOROVI         MAT  NAP     ',
     1'        TACKA ZA LOKALNI SISTEM         RADJANJE   -   UMIRANJE',
     3 /48X,'X',11X,'Y',11X,'Z',10X,'BTH',9X,'DTH')
 2007 FORMAT(/6X,' SVE VEZE U CVOR. NISU KRUTE :',
     1' U DODATNOJ KARTICI ZGL.VEZE ELEM.(VEKTOR LU(12)) : 0 - ZNACI KRU
     2TU VEZU, 1 - SLOBODNO POMERANJE')
C 2004 FORMAT(/6X,' SVE VEZE U CVOROVIMA SU KRUTE')
 2006 FORMAT(' ',' POSTOJE SLOB. POMERANJA ELEMENTA BR.',I4,2X,
     1'(VEKTOR LUV(12)) :',12I5)
 2500 FORMAT(///6X,'P R E S E K   B R O J   ',I2//
     111X,'POVRSINA POPRECNOG PRESEKA ................  POVR =',1PD12.5/
     311X,'MOMENTI INERCIJE         ..................  J(Y) =',1PD12.5/
     311X,'                                             J(Z) =',1PD12.5/
     511X,'TORZIONA KONSTANTA ........................    TK =',1PD12.5/
     411X,'UGAO IZMEDJU INICIJALNIH I GLAVNIH OSA ....  ALFA =',1PD12.5/
     211X,'SMICAJNI KOEFICIJENTI    ..................  CAPAY=',1PD12.5/
     211X,'                                             CAPAZ=',1PD12.5/
     311X,'INDIKATOR ZA LUCNU GREDU ..................   ILU =',I5/
     116X,'EQ.0; PRAVA GREDA'/ 
     116X,'EQ.1; LUCNA GREDA'/ 
     311X,'INDIKATOR ZA CEVNI ELEMENT ................   ICP =',I5/
     116X,'EQ.0; BEZ UNUTRASNJEG PRITISKA'/ 
     116X,'EQ.1; SA UNUTRASNJIM PRITISKOM'/) 
 2510 FORMAT(///6X,'P O M E R E N O S T   N E U T R A L N E   O S E',//
     311X,'OY =',1PD12.5,'  OZ =',1PD12.5 
     3       ///6X,'N A P O N S K E    T A C K E',//
     311X,'YM =',1PD12.5,'  ZM =',1PD12.5)
 2520 FORMAT(///6X,'KOREKCIJA LOKALNIH KOORDINATA I ROTACIJA PRESEKA',//
     311X,'KOREKCIJA LOKALNIH KOORDINATA U PRAVCU - YL .. OY =',1PD12.5/
     311X,'KOREKCIJA LOKALNIH KOORDINATA U PRAVCU - ZL .. OZ =',1PD12.5/
     311X,'ROTACIJA PRESEKA OKO PRAVCA - XL .......... ALFAU =',1PD12.5/
     111X,'INDIKATOR POMERENOSTI NEUTRALNE OSE ............ INDOF =',I5/
     116X,'EQ.0; NEUTRALNA OSA U TEZISTU PRESEKA'/ 
     116X,'EQ.1; NEUTRALNA OSA U LOKALNOM KOORDINATNOM POCETKU'/) 
C-----------------------------------------------------------------------
 6005 FORMAT(///' NOT ENOUGH SPACE IN WORKING VECTOR  A'
     1/' REQUESTED DIMENSION , LMAX=',I10
     2/' AVAILABLE DIMENSION , MTOT=',I10)
 6021 FORMAT (///' T H I N   W A L L E D   B E A M - ARBITRARY SECT.'/)
 6008 FORMAT(//' ','S E C T I O N   ',I2/
     1' ','NUMBER OF POINTS                     NT    =',I5/
     2' ','NUMBER OF SEGMENTS                   NELM  =',I5/
     3' ','SECTION TYPE (1-OPEN ,2-CLOSED)      NTIP  =',I5/
     4' ','NUMBER OF CARACTER.- CLOSED SECTION  NKAR  =',I5/
     8' ','TORSION TYPE                         NVR   =',I5 )
 6003 FORMAT(///6X,'D A T A    A B O U T    E L E M E N T S')
 6013 FORMAT(/' ELEMENT    NODES           MAT  STRESS  ',
     1'        ORIENTATION POINT                 BIRTH    -    DEATH',
     3 /48X,'X',11X,'Y',11X,'Z',10X,'BTH',9X,'DTH')
 6007 FORMAT(/6X,' SVE VEZE U CVOR. NISU KRUTE :',
     1' U DODATNOJ KARTICI ZGL.VEZE ELEM.(VEKTOR LU(12)) : 0 - ZNACI KRU
     2TU VEZU, 1 - SLOBODNO POMERANJE')
C 6004 FORMAT(/6X,' SVE VEZE U CVOROVIMA SU KRUTE')
 6006 FORMAT(' ',' POSTOJE SLOB. POMERANJA ELEMENTA BR.',I4,2X,
     1'(VEKTOR LUV(12)) :',12I5)
 6500 FORMAT(//6X,'S E C T I O N   ',I2/
     111X,'CROSS SECTION AREA ........................  POVR =',1PD12.5/
     311X,'MOMENTS OF INERTIA       J(Y) =',1PD12.5,'  J(Z) =',1PD12.5/
     511X,'TORSIONAL CONSTANT ........................    TK =',1PD12.5/
     411X,'ANGLE BETWEEN INITIAL AND MAIN AXES .......  ALFA =',1PD12.5/
     211X,'SHEAR COEFFICIENTS       CAPAY=',1PD12.5,'  CAPAZ=',1PD12.5/
     311X,'CURVED BEAM INDICATOR .....................   ILU =',I5/
     116X,'EQ.0; STRAIGHT BEAM'/ 
     116X,'EQ.1; CURVED BEAM'/ 
     311X,'PIPE ELEMENT INDICATOR ....................   ICP =',I5/
     116X,'EQ.0; NO INTERNAL PRESSURE'/ 
     116X,'EQ.1; INTERNAL PRESSURE'/) 
 6510 FORMAT(///6X,'N E U T R A L   A X I S   O F S E T',//
     311X,'OY =',1PD12.5,'  OZ =',1PD12.5 
     3       ///6X,'S T R E S S    P O I N T S',//
     311X,'YM =',1PD12.5,'  ZM =',1PD12.5)
 6520 FORMAT(///6X,
     1'LOCAL COORDINATES CORECTION AND CROSS-SECTION ROTATION'//
     311X,'LOCAL COORDINATES CORECTION IN YL DIRECTION .. OY =',1PD12.5/
     311X,'LOCAL COORDINATES CORECTION IN ZL DIRECTION .. OZ =',1PD12.5/
     311X,'CROSS-SECTION ROTATION ABOUT XL DIRECTION . ALFAU =',1PD12.5/
     311X,'INDICATOR NEUTRAL AXIS OFSET ................... INDOF =',I5/
     116X,'EQ.0; NEUTRAL AXIS IN CROSS-SECTION GRAVITY CENTRE'/ 
     116X,'EQ.1; NEUTRAL AXIS IN LOCAL COORDINATE SYSTEM ORIGIN'/) 
C-----------------------------------------------------------------------
      END
C=======================================================================
      SUBROUTINE ULPRES (COR,ELM,CORK,NNKAR,NBROJ,ALFAU)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C     PODPROGRAM ZA U$ITAVANJE ULAZNIH PODATAKA ZA TANKOZIDNE PRESEKE
C
      CHARACTER*250 ACOZ
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /PGREDC/ NPUN,NPRBR,MAXPRR,NPRES,ICV1,ICV2,MATG,
     1                NKARD,MG,NVR,NWRITE,NAPG,INDOF
      COMMON /COMPRF/ YC,ZC,YI,ZI,ALFB,TK,CAPAY,CAPAZ,AREA,POVR,YM,ZM,
     1                DDELT,YP,SWO(1),OM(1),DELTAP(3),TAUTK(3),OY,OZ,
     2                NT,NELM,NTIP,NKAR,IND,INDRPR(3),KR1,NEXTR,NPRPR
      COMMON /SRPSKI/ ISRPS
      DIMENSION COR(NT,*),ELM(NELM,*),CORK(NKARD,*),NNKAR(*),
     1NBROJ(NKARD,*)
C
C     KOORDINATE
C
      PI = 1.
      PI = 4.*DATAN(PI)
      ALFAU=ALFAU*PI/180.
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2015)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6015)
      DO 21 I=1,NT
      CALL ISPITA(ACOZ)
      READ(ACOZ,22) N,(COR(N,J),J=2,3)
      COR(N,1) = FLOAT(N)
      WRITE(IZLAZ,23) N,(COR(N,J),J=2,3)
      COR(N,2)=COR(N,2)+OY
      COR(N,3)=COR(N,3)+OZ
      IF(DABS(ALFAU).GT.1.D-9) THEN
      YP=COR(N,2)*DCOS(ALFAU)-COR(N,3)*DSIN(ALFAU)
      ZP=COR(N,2)*DSIN(ALFAU)+COR(N,3)*DCOS(ALFAU)
      COR(N,2)=YP
      COR(N,3)=ZP
      ENDIF
   21 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2016)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6016)
      DO 92 I=1,NT
      WRITE(IZLAZ,23) I,(COR(I,J),J=2,3)
   92 CONTINUE
C
C     SEGMENTS
C
      DDELT = 10000.
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2024)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6024)
      DO 25 I=1,NELM
      CALL ISPITA(ACOZ)
      READ(ACOZ,26) N,NT1,NT2,ELM(N,4)
      IF(I.EQ.1) GO TO 28
      IF(DABS(ELM(N,4)).LT.1.0D-20) ELM(N,4) = ELM(NM1,4)
   28 ELM(N,1) = N
      ELM(N,2) = NT1
      ELM(N,3) = NT2
      WRITE(IZLAZ,27) N,NT1,NT2,ELM(N,4)
      NM1 = N
      IF(ELM(N,4).LT.DDELT) DDELT = ELM(N,4)
   25 CONTINUE
C
C
      DDELT = 0.0001*DDELT
C
      GO TO (70,30),NTIP
C
C     CLOSED SECTION 
C
C     CHARACTERISTIC POINTS
C
   30 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2031)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6031)
      DO 33 I=1,NKAR
      CALL ISPITA(ACOZ)
      READ(ACOZ,34) N,(CORK(N,J),J=2,3)
      WRITE(IZLAZ,35) N,(CORK(N,J),J=2,3)
      CORK(N,1) = N
   33 CONTINUE
C
C     NUMBER OF SEGMENTS CONECTED TO CHARACTERISTIC POINT
C
      CALL ISPITA(ACOZ)
      READ(ACOZ,17) (NNKAR(I),I=1,NKAR)
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2042)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6042)
      WRITE(IZLAZ,39) (I,NNKAR(I),I=1,NKAR)
C
C     SEGMENTS CONECTED TO CHARACTERISTIC POINT
C
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2036)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6036)
      DO 38 N=1,NKAR
      NN = NNKAR(N)
      IN=NN/14+1
      NN1=1
      NN2=NN
      IF(IN.GT.1) NN2=13
      CALL ISPITA(ACOZ)
      READ(ACOZ,17) NPOV, (NBROJ(NPOV,J),J=NN1,NN2)
      IF(IN.GT.1) THEN
      NN1=NN1+13
      NN2=NN2+14
      IF(NN2.GT.NN) NN2=NN
      DO 37 I=2,IN 
      CALL ISPITA(ACOZ)
      READ(ACOZ,17) (NBROJ(NPOV,J),J=NN1,NN2)
      NN1=NN1+14
      NN2=NN2+14
      IF(NN2.GT.NN) NN2=NN
   37 CONTINUE
      ENDIF
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2037) NPOV
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6037) NPOV
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2040) (NBROJ(NPOV,J),J=1,NN)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6040) (NBROJ(NPOV,J),J=1,NN)
   38 CONTINUE
   70 RETURN
C
   17 FORMAT(14I5)
   22 FORMAT(I5,2F10.3)
   23 FORMAT(5X,I10,2F10.3)
   26 FORMAT(3I5,F10.3)
   27 FORMAT(7X,I10,3X,2I5,3X,F10.3)
   34 FORMAT(I5,2F10.3)
   35 FORMAT(5X,I10,3X,2F10.3)
   39 FORMAT(5X,I10,I25)
C-----------------------------------------------------------------------
 2015 FORMAT(//6X,'U C I T A N E    K O O R D I N A T E '//
     16X,'TACKA BR.',8X,'KOORDINATE  ')
 2016 FORMAT(//6X,'G E N E R I S A N E    K O O R D I N A T E '//
     16X,'TACKA BR.',8X,'KOORDINATE  ')
 2024 FORMAT(//6X,'S E G M E N T I'//6X,'SEGMENT BR.',6X,'  TACKE  ',
     15X,'DEBLJINA')
 2031 FORMAT(//6X,'DOPUNSKI PODACI ZA ZATVOREN PROFIL'//
     16X,'COORDINATE KARAKTERISTICNIH TACAKA'
     2/6X,'TACKA BR.',8X,'KOORDINATE')
 2036 FORMAT(//6X,'SEGMENTI ZATVORENOG PROFILA')
 2037 FORMAT(/6X,'SEGMENT BR.',I5)
 2040 FORMAT(/6X,'SEGMENTI :',20I5)
 2042 FORMAT(//6X,'BROJE PRESEKA KOJI PROIPADAJU ZATVORENOM PROFILU'//
     12X,'ZATVOREN PROFIL ',5X,'BROJ SEGEMNATA'/)
C-----------------------------------------------------------------------
 6015 FORMAT(//6X,'R E A D E D    C O O R D I N A T E S'//
     1' ','POINT NU.',8X,'COORD. Z I Y')
 6016 FORMAT(//6X,'G E N E R A T E D    C O O R D I N A T E S'//
     1' ','POINT NU.',8X,'COORD. Z I Y')
 6024 FORMAT(//6X,'S E G M E N T S'//' ','SEGMENT NU.',5X,'NODES NU.',
     15X,'THICKNESS')
 6031 FORMAT(//6X,'ADITIONAL DATA FOR CLOSED SECTION '//
     1' ','COORDINATES OF CARACT. POINT '
     2/' ','POINT NU.',8X,'CKOORDINATES Z I Y')
 6036 FORMAT(//6X,'SEGMENTS FOR CLOSED AREAS ')
 6037 FORMAT(/6X,'CLOSED SEGMENTS NU.',I5)
 6040 FORMAT(/6X,'SEGMENTS :',20I5)
 6042 FORMAT(//6X,'NUMBER OF SECTION BELONGING TO THE CLOSED  
     1AREA'//6X,'CLOSED AREA  NU.',5X,'NUMBER OF SEGMENTS'/)
C-----------------------------------------------------------------------
      END
C=======================================================================
      SUBROUTINE LMIMH6(ID,NEL,LMEL)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C     VECTOR LM AND CLOUMN HIGHTS 
C
      include 'paka.inc'
      
C
      COMMON /GLAVNI/ NP,NGELEM,NMATM,NPER,
     1                IOPGL(6),KOSI,NDIN,ITEST
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /REPERI/ LCORD,LID,LMAXA,LMHT
      COMMON /GEORGE/ TOLG,ALFAG,ICCGG
      COMMON /DRAKCE/ IDRAKCE,NELUK,NZERO,NEED1,NEED2,NEED3,NNZERO
     1                ,IROWS,LAILU,LUCG,LVCG,LWCG,LPCG,LRCG
      DIMENSION ID(NP,*),NEL(NE,*),LMEL(12,*)
C     PETLJA PO ELEMENTIMA
      DO 100 NLM=1,NE
      DO 10 NC=1,2                            
      NNC=6*(NC-1)                               
      JJ=NEL(NLM,NC)                             
      DO 20 I=1,6                                
   20 LMEL(NNC+I,NLM)=ID(JJ,I)                   
   10 CONTINUE                                   
C
      ND=12
      CALL VISINE(A(LMHT),ND,LMEL(1,NLM))
      IF (IABS(ICCGG).EQ.1) THEN
         WRITE(IDRAKCE) ND,(LMEL(I,NLM),I=1,ND)
         NELUK=NELUK+1
      ENDIF
  100 CONTINUE
      RETURN
      END
C=======================================================================
      SUBROUTINE TGRAF6(NEL,MCVEL,CTR,ICVEL)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
CS     PROGRAM ZA STAMPANJE GREDE U UNIVERZALNI FILE
CE     PROGRAM FOR PRINTOUT DATA IN UNIVERSAL GRAPHICS FILE
C
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /SUMELE/ ISUMEL,ISUMGR
      COMMON /LUCGRE/ ILU,ICP
      COMMON /SRPSKI/ ISRPS
      COMMON /NIDEAS/ IDEAS
C
      DIMENSION NEL(NE,*),MCVEL(*),CTR(NE,*)
      IF(ideas.eq.-1) return
      IDUM=0
      ISUMGR=ISUMGR+1
      IF(ISRPS.EQ.0.AND.NCVE.GT.2) WRITE(IZLAZ,2200) NGE
      IF(ISRPS.EQ.1.AND.NCVE.GT.2) WRITE(IZLAZ,6200) NGE
C     GRAFICKI OPIS GREDE: SA 2 CVORA = 1
      IFGD=1
C     VRSTA  ELEMENTA: GREDA SA 2 CVORA  = 21; LUCNA GREDA  = 61;
      IFDI=21
      IF(ILU.EQ.1) IFDI=61
C     TABELA FIZICKIH OSOBINA
      IPTN=ISUMGR
C     TABELA MATERIJALA
      MPTN=ISUMGR
C     BOJA  
      ICOL=7
C     BROJ CVOROVA NA ELEMENTU
      NNODS=2
      IND=-1
      ITYP=71
      WRITE(IGRAF,1100) IND
      WRITE(IGRAF,1100) ITYP
      DO 10 I=1,NE
C        REDNI BROJ ELEMENTA
         IEL=I+ISUMEL
         IF(ICVEL.EQ.1) IEL=MCVEL(I)
         WRITE(IGRAF,1000) IEL,IFGD,IFDI,IPTN,MPTN,ICOL,NNODS
         WRITE(IGRAF,1001) (NEL(I,J),J=1,2),IDUM,(CTR(I,J),J=1,3)
   10 CONTINUE
      WRITE(IGRAF,1100) IND
      ISUMEL=ISUMEL+NE
      RETURN
C
 1000 FORMAT(8I10)
 1001 FORMAT(3I10,3(1PE13.5))
 1100 FORMAT(I6)
C-----------------------------------------------------------------------
 2200 FORMAT(//' PROGRAM ZA GRAFICKO PRIKAZIVANJE REZULTATA "IDEAS"'/
     1' ZAHTEVA GREDU SA 2 CVORA PO ELEMENTU U GRUPI ELEMENATA NGE ='
     1,I5)
C-----------------------------------------------------------------------
 6200 FORMAT(//' GRAPHIC PACKAGE   "IDEAS"'/
     1' PERMITS ONLY BEAM WITH 2 NODES PER ELEMENT IN GROUP',
     1'  NGE =',I5)
C-----------------------------------------------------------------------
      END
C======================================================================
C
C======================================================================
      SUBROUTINE TGRAS6(NOP,CTR,NE,NP,IATYP,NS,NCVP,NGE,IREST,
     1                      CORD,CORS,OS,ZC,YC,ALFB,INDOF)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.    P R O G R A M
CE.       TO PRINT GLOBAL COORDINATES IN UNIVERSAL FILE
CS.    P R O G R A M
CS.       ZA STAMPANJE GLOBALNIH KOORDINATA SEGMENATA U UNIVERZALNI FILE
C .
C ......................................................................
C
      CHARACTER*10 IME
      DIMENSION NOP(NE,*),CTR(NE,*),CORD(NP,*),CORS(NCVP,*),OS(NS,*),
     1          V3(3,3),COR(3),NEL(8),CYZ(3)
C
      YC=-YC
      ZC=-ZC
      IGRFF=34
      IME(1:2)='GG'
      IME(7:10)='.UNV'
      WRITE(IME(3:6),1900) NGE
 1900 FORMAT(I4)
      DO 56 J=3,5
         IF(IME(J:J).EQ.' ') IME(J:J)='0' 
   56 CONTINUE
      IF(IREST.NE.1) THEN
      OPEN (IGRFF,FILE=IME,STATUS='UNKNOWN',FORM='FORMATTED',
     1                       ACCESS='SEQUENTIAL')
         CLOSE (IGRFF,STATUS='DELETE')
      ENDIF
      OPEN (IGRFF,FILE=IME,STATUS='UNKNOWN',FORM='FORMATTED',
     1                       ACCESS='SEQUENTIAL')
      IND=-1
      ITYP=15
      WRITE(IGRFF,5100) IND
      WRITE(IGRFF,5100) ITYP
      IT1=0
      IT2=0
      ICOL=8
      L6=0
      NC4=2
      KK=0
C...  KOORDINATE TEZISTA U LOKALNOM SISTEMU
C      WRITE(3,*) 'YC,ZC,ALFA-62',YC,ZC,ALFA
         IF(INDOF.EQ.0)THEN
           CYZ(2)=0.D0
           CYZ(3)=0.D0
         ELSE
           CAL=DCOS(-ALFB)
           SAL=DSIN(-ALFB)
           CYZ(2)=YC*CAL-ZC*SAL
           CYZ(3)=YC*SAL+ZC*CAL
         ENDIF
C      WRITE(3,*) 'CYZ(2),CYZ(3),INDOF',CYZ(2),CYZ(3),INDOF
C      WRITE(3,*) 'LOK.KORD'
C      DO 22 I=1,NCVP
C      WRITE(3,*) I,(CORS(I,J),J=2,3)
C   22 CONTINUE
      DO 100 NLM=1,NE
         CALL TRANG6(CTR,NOP,CORD,V3,NE,NP,NLM)
      DO 100 NSEG=1,NS
      DO 100 I=1,2
         NV=NOP(NLM,I)
         IF(I.EQ.2) THEN
            I1=3
            I2=2
            I3=-1
         ELSE
            I1=2
            I2=3
            I3=1
         ENDIF
      DO 100 J=I1,I2,I3
         NC=OS(NSEG,J)
         KK=KK+1
         DO 60 K=1,3
            COR(K)=CORD(NV,K)
         DO 60 JK=2,3
            COR(K)=COR(K)+V3(JK,K)*(CORS(NC,JK)-CYZ(JK))
   60    CONTINUE
         WRITE(IGRFF,5000) KK,IT1,IT2,ICOL,(COR(K),K=1,3)
  100 CONTINUE
      WRITE(IGRFF,5100) IND
C
C     STAMPANJE SEGMENATA
C
C     GRAFICKI OPIS LJUSKE: SA 4 CVORA =  5,
      IFGD=5
C     VRSTA  ELEMENTA: SA  4 CVORA = 94,
      IFDI=94
C     BROJ CVOROVA NA ELEMENTU
      NNODS=NC4*2
C     TABELA FIZICKIH OSOBINA
      IPTN=NGE
C     TABELA MATERIJALA
      MPTN=NGE
C     BOJA  
      ICOL=7
      IND=-1
      ITYP=71
      WRITE(IGRFF,1100) IND
      WRITE(IGRFF,1100) ITYP
      IEL=0
      KK=0
      DO 101 NLM=1,NE
      DO 101 NSEG=1,NS
         IEL=IEL+1
         IJ=0
         DO 201 I=1,2
         IF(I.EQ.2) THEN
            I1=NC4
            I2=1
            I3=-1
         ELSE
            I1=1
            I2=NC4
            I3=1
         ENDIF
         DO 201 J=I1,I2,I3
            KK=KK+1
            IJ=IJ+1
            NEL(IJ)=KK
  201    CONTINUE
C        REDNI BROJ ELEMENTA
         WRITE(IGRFF,1000) IEL,IFGD,IFDI,IPTN,MPTN,ICOL,NNODS
         WRITE(IGRFF,1000) (NEL(J),J=1,NNODS)
  101 CONTINUE
      WRITE(IGRFF,1100) IND
      CLOSE (IGRFF,STATUS='KEEP')
      RETURN
C
 5100 FORMAT(I6)
 5000 FORMAT(4I10,3(1PE13.5))
 1000 FORMAT(8I10)
 1100 FORMAT(I6)
      END
C=======================================================================
      SUBROUTINE TRANG6(CTR,NEL,CORD,TRR,NE,NP,N)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
CS    PODPROGRAM ZA FORMIRANJE MATRICE TRANSF.GREDNOG ELEM.TRR(3,3)
CE    TRANSFORMATION MATRIX       
C
      COMMON /PGREDC/ NPUN,NPRBR,MAXPRR,NPRES,ICV1,ICV2,MATG,
     1                NKARD,MG,NVR,NWRITE,NAPG,INDOF
      COMMON /COMPRF/ YC,ZC,YI,ZI,ALFB,TK,CAPAY,CAPAZ,AREA,POVR,YM,ZM,
     1                DDELT,YP,SWO(1),OM(1),DELTAP(3),TAUTK(3),OY,OZ,
     2                NT,NELM,NTIP,NKAR,IND,INDRPR(3),KR1,NEXTR,NPRPR
      DIMENSION CTR(NE,*),NEL(NE,*),CORD(NP,*),TRR(3,3),EF2(3),EF3(3)
      SQRT(X)=DSQRT(X)
C
      DO 1 I=1,3
      DO 1 J=1,3
    1 TRR(I,J)=0.D0
C
CS    ODREDITI BROJEVE CVOROVA I KARAKTERISTIKE ELEMENTA
CE    NODE NUMBERS
      ICV1=NEL(N,1)
      ICV2=NEL(N,2)
C
      X1=CORD(ICV1,1)
      Y1=CORD(ICV1,2)
      Z1=CORD(ICV1,3)
      X2=CORD(ICV2,1)
      Y2=CORD(ICV2,2)
      Z2=CORD(ICV2,3)
      X12 = X1 - X2
      Y12 = Y1 - Y2
      Z12 = Z1 - Z2
      DUZ=SQRT(X12*X12 + Y12*Y12 + Z12*Z12)
C
C
      CA=(X2-X1)/DUZ
      CB=(Y2-Y1)/DUZ
      CG=(Z2-Z1)/DUZ
      X12 = CTR(N,1) - X1
      Y12 = CTR(N,2) - Y1
      Z12 = CTR(N,3) - Z1
C
      CS1=CTR(N,1)-X1
      CS2=CTR(N,2)-Y1
      CS3=CTR(N,3)-Z1
      TRR(3,1)=CB*CS3-CG*CS2
      TRR(3,2)=CG*CS1-CA*CS3
      TRR(3,3)=CA*CS2-CB*CS1
      RB=SQRT(TRR(3,1)*TRR(3,1)+TRR(3,2)*TRR(3,2)+TRR(3,3)*TRR(3,3))
      INGR=0
      IF(RB.LT.1.D-6)THEN
        INGR=1
        WRITE(3,2000) N
        STOP'*** TRANG ***'
      ENDIF
      DO 3 I=1,3
    3 TRR(3,I)=TRR(3,I)/RB      
C
      TRR(1,1)=CA
      TRR(1,2)=CB
      TRR(1,3)=CG
      TRR(2,1)=TRR(3,2)*CG-TRR(3,3)*CB
      TRR(2,2)=TRR(3,3)*CA-TRR(3,1)*CG
      TRR(2,3)=TRR(3,1)*CB-TRR(3,2)*CA
C      CALL WRR(TRR,9,'T61 ')
C
C...   ROTIRANJE U RAVNI PRESEKA ZA UGAO  ALFA
C
      SAL=DSIN(ALFB)
      CAL=DCOS(ALFB)
      DO 4 I=1,3
        EF2(I)= CAL*TRR(2,I)+SAL*TRR(3,I)
    4   EF3(I)=-SAL*TRR(2,I)+CAL*TRR(3,I)
      DO 5 I=1,3
        TRR(2,I)=EF2(I)
    5   TRR(3,I)=EF3(I)
C      CALL WRR(TRR,9,'T61A')
C
      RETURN
 2000 FORMAT(///2X,'**P A Z NJ A'//
     1'ZA ELEMENT',I3,2X,'NEMOGUCE DEFINISATI MATRICU TRANSFORMACIJE')
      END
