C=======================================================================
C
C        STAMPANJE NAPONA OSNOSIMETRICNE LJUSKE
C
C   SUBROUTINE L04NAP
C              STANP7
C           *  STANG7
C              STAN17
C              STAN37
C           *  STAN57
C           *  STAG17
C
C=======================================================================
      SUBROUTINE L04NAP
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C    GLAVNI PROGRAM ZA POZIVANJE PROGRAMA ZA STAMPANJE NAPONA
C
      include 'paka.inc'
      
C
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
C
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
C
      COMMON /ELEMA7/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1                LBETA
C
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
C
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
C
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
C
      COMMON /ZAPISI/ LSTAZA(5)
C
      COMMON /DUPLAP/ IDVA
C
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
C
      LAU=LMAX
C     UCITAVANJE PODATAKA O ELEMENTIMA I NAPONA SA DISKA 8
      CALL READE7(A(LAU),1)
C     PODPROGRAM ZA STAMPANJE NAPONA
      IF(INDPR.EQ.0.OR.INDPR.EQ.2) CALL STANP7(A(LAU))
C     PODPROGRAM ZA STAMPANJE NAPONA ZA POSTPROCESIRANJE
C      IF(INDGR.EQ.0.OR.INDGR.EQ.2) CALL STANG7(A(LAU))
      IF(IATYP.EQ.0) RETURN
      IF(NMODM.LE.4) RETURN
      NPROS=NE*NGAUSX*NGAUSY*16*IDVA
      LMA8=LSTAZA(3)-1
      CALL WRITDD(A(LPLAS1),NPROS/IDVA,IELEM,LMA8,LDUZI)
      RETURN
      END
C======================================================================
      SUBROUTINE STANP7(AU)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      include 'paka.inc'
      
C
      COMMON /ELEMA7/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1                LBETA
C
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
C
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
C
      DIMENSION AU(*)
      REAL AU
C
      GO TO (1,1,3,3,5,5,5,5),NMODM
    1 CALL STAN17(A(LSIGMA),AU(LISNA),AU(LIPRC))
      RETURN
    3 CALL STAN37(A(LSIGMA),AU(LISNA),AU(LIPRC))
      RETURN
C    5 CALL STAN57(A(LPLAST),AU(LISNA),AU(LIPRC))
    5 RETURN
      END
C======================================================================
      SUBROUTINE STAN17(SIGMA,ISNA,IPRC)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
C
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
C
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
C
      DIMENSION SIGMA(NE,MSLOJ,NGAUSX,NGAUSY,*),ISNA(*),IPRC(*)
C
      INDSN=0
      DO 20 NLM=1,NE
      ISN=ISNA(NLM)
      IF(ISN.NE.0) GO TO 20
      IF(INDSN.EQ.0) WRITE(IZLAZ,2010)
      INDSN=1
      IPC=IPRC(NLM)
      WRITE(IZLAZ,2000)NLM
      DO 15 MS=1,MSLOJ
      WRITE(IZLAZ,2030)MS
      DO 10 NGR=1,NGAUSX
      DO 10 NGS=1,NGAUSY
      IF(IPC.NE.1)THEN
      WRITE(IZLAZ,2001)NGR,NGS,(SIGMA(NLM,MS,NGR,NGS,K),K=1,3)
                   ELSE
      WRITE(IZLAZ,2020)NGR,NGS,(SIGMA(NLM,MS,NGR,NGS,K),K=1,3),
     1                         (SIGMA(NLM,MS,NGR,NGS,K),K=5,6)
                  ENDIF
   10 CONTINUE
   15 CONTINUE
   20 CONTINUE
      RETURN
C
 2000 FORMAT(I5)
 2001 FORMAT(11X,I5,I6,8X,3D12.4)
C-----------------------------------------------------------------------
 2010 FORMAT('1'/' ELEM. NU.',3X,'NGX',3X,'NGY',10X,'S T R E S S E S    
     1 I N     A X I S Y M E T R I C   S H E L L                '/
     134X,'RR',10X,'CC',10X,'RS')
CS 2010 FORMAT('1'/' ELEM. BR.',3X,'NGX',3X,'NGY',10X,'K O M P O N E N T E
CS     1   N A P O N A    O S N O S I M E T R I C N E   LJ U S K E'/
CS     134X,'RR',10X,'CC',10X,'RS')
C
 2020 FORMAT(11X,I5,I6,8X,3D12.4,' COORD-X =',D12.4,5X,' COORD-Y =',
     1 D12.4)
C
 2030 FORMAT(' ',14X,'LAYER  = (',I2,')')
CS 2030 FORMAT(' ',14X,'SLOJ BR. = (',I2,')')
C-----------------------------------------------------------------------
      END
C======================================================================
      SUBROUTINE STAN37(SIGMA,ISNA,IPRC)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
C
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
C
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
C
      DIMENSION SIGMA(NE,MSLOJ,NGAUSX,NGAUSY,*),ISNA(*),IPRC(*)
C
      INDSN=0
      DO 20 NLM=1,NE
      ISN=ISNA(NLM)
      IF(ISN.NE.0) GO TO 20
      IF(INDSN.EQ.0) WRITE(IZLAZ,2010)
      INDSN=1
      IPC=IPRC(NLM)
      WRITE(IZLAZ,2000)NLM
      DO 15 MS=1,MSLOJ
      WRITE(IZLAZ,2030)MS
      DO 10 NGR=1,NGAUSX
      DO 10 NGS=1,NGAUSY
      WRITE(IZLAZ,2001)NGR,NGS,(SIGMA(NLM,MS,NGR,NGS,K),K=1,4)
      IF(IPC.NE.1)GO TO 10
      WRITE(IZLAZ,2020)(SIGMA(NLM,MS,NGR,NGS,K),K=5,6)
   10 CONTINUE
   15 CONTINUE
   20 CONTINUE
      RETURN
C
 2000 FORMAT(I5)
C-----------------------------------------------------------------------
 2001 FORMAT(11X,I5,I6,8X,3D12.4,'   TEMPERATURE =',D12.4)
CS 2001 FORMAT(11X,I5,I6,8X,3D12.4,'   TEMPERATURA =',D12.4)
C
 2010 FORMAT('1'/' ELEM. NU.',3X,'NGX',3X,'NGY',10X,'S T R E S S E S    
     1 I N     A X I S Y M E T R I C   S H E L L                '/
     134X,'RR',10X,'CC',10X,'RS')
C
CS 2010 FORMAT('1'/' ELEM. BR.',3X,'NGX',3X,'NGY',10X,'K O M P O N E N T E
CS     1   N A P O N A    O S N O S I M E T R I C N E   LJ U S K E'/
CS     134X,'RR',10X,'CC',10X,'RS')
C
 2020 FORMAT(40X,' COORD-X =',D12.4,5X,' COORD-Y =',D12.4)
C
 2030 FORMAT(' ',14X,'LAYER  = (',I2,')')
CS 2030 FORMAT(' ',14X,'SLOJ BR. = (',I2,')')
C-----------------------------------------------------------------------
      END
