C=======================================================================
C
C     SUBROUTINE ULJ4B
C                UEL4A
C                UEL4B
C                LMMHT8
C=======================================================================
      SUBROUTINE ULJ4B
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
CS     GLAVNI PROGRAM ZA UCITAVANJE ULAZNIH PODATAKA ZA 
CS     IZOPARAMETARSKE TROUGAONE LJUSKE/PLOCE ( DO 6 CVOROVA )
CS     IZOPARAMETARSKE LJUSKE   ( DO 9 CVOROVA )                                        
CE     MAIN PROGRAM FOR INPUT DATA ABOUT
CE     ISOPARAMETRIC TRIANGULAR PLATE/SHELL ( 6 NODES )
CE     ISOPARAMETRIC SHELL   ( 9 NODES )                                      
C
      CHARACTER*250 ACOZ
      include 'paka.inc'
      
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /GLAVNI/ NP,NGELEM,NMATM,NPER,
     1                IOPGL(6),KOSI,NDIN,ITEST
      COMMON /REPERI/ LCORD,LID,LMAXA,LMHT
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /SIMO2D/ LALFE,LHAEM,LHINV,LGEEK,IALFA
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /DUPLAP/ IDVA
      COMMON /ORIENT/ CPP(3,3),XJJ(3,3),TSG(6,6),BETA,LBET0,IBB0
      COMMON /BROJUK/ KARTIC,INDFOR,NULAZ
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /DIREKT/ LSTAZZ(9),LDRV0,LDRV1,LDRV,IDIREK
      COMMON /INTGRA/ INCOTX,INCOTY,INCOTZ
      COMMON /BTHDTH/ INDBTH,INDDTH,LTBTH,LTDTH
      COMMON /PODTIP/ IPODT
      COMMON /INDCEL/ IND3D
      COMMON /SRPSKI/ ISRPS
      COMMON /IKOVAR/ INDKOV
      COMMON /CUVAJN/ TAUCEN(6,5),INDSEL,NGAUSU
      COMMON /DRILLI/ EL14(4),EN14(3,4),IDRIL
C
CS     OSNOVNI PODACI O ELEMENTIMA
CE     BASIC DATA ABOUT ELEMENTS
C
      IDIREK=0
      CALL ISPITA(ACOZ)
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) NGAUSX,NGAUSY,NGAUSZ,MSET,BETA,MSLOJ,
     1                (CPP(J,1),J=1,3),IALFA
C     1              (CPP(J,1),J=1,3),IALFA,IND3D
      IF(INDFOR.EQ.2)
     1READ(ACOZ,1000) NGAUSX,NGAUSY,NGAUSZ,MSET,BETA,MSLOJ,
     1                (CPP(J,1),J=1,3),IALFA
C     1                (CPP(J,1),J=1,3),IALFA,IND3D
      IND3D=0
      INDSEL=0
      IF(IPODT.EQ.0.AND.NMODM.LE.2) THEN
         INDSEL=1
         INDKOV=-1
      ENDIF
      IF(IPODT.EQ.5) INDSEL=1
      IF(NGAUSZ.LT.0) THEN
         NGAUSZ=-NGAUSZ
         INDSEL=0
      ENDIF
      IF(IDRIL.EQ.1) THEN
         INDSEL=0
         IALFA=-1
      ENDIF
      IF(IALFA.EQ.0) IALFA=2
      IF(IALFA.GT.3) IALFA=3
      IF(IPODT.EQ.1.OR.IPODT.EQ.2.OR.IPODT.EQ.3.OR.IPODT.EQ.5) IALFA=-1
CE    CHECK FOR NEWTON-COTES INTEGRATION
      INCOTX=INCOT(NGAUSX)
      INCOTY=INCOT(NGAUSY)
      INCOTZ=INCOT(NGAUSZ)
C OVO ISKLJUCENO ZBOG BRZEG TESTIRANJA
C      IF(NMODM.GE.5.AND.NGAUSZ.LE.3) NGAUSZ=4
C...  NEMA NEWTON-COTES INTEGRACIJE U RAVNI TROUGLA
      IF(IPODT.EQ.1.OR.IPODT.EQ.3) THEN
        IF(NGAUSX.LT.3) NGAUSX=3
        IF(NGAUSX.GT.3) NGAUSX=7
C        NGAUSZ=NGAUSY
        NGAUSY=1
      ENDIF
      IF(MSLOJ.EQ.0) MSLOJ = 10
      IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
        CALL WBROJK(KARTIC,0)
      IF(ISRPS.EQ.0.AND.IPODT.NE.1.AND.IPODT.NE.3.AND.INCOTX.EQ.0)
     1WRITE(IZLAZ,2000) NGAUSX
      IF(ISRPS.EQ.1.AND.IPODT.NE.1.AND.IPODT.NE.3.AND.INCOTX.EQ.0)
     1WRITE(IZLAZ,6000) NGAUSX
      IF(ISRPS.EQ.0.AND.IPODT.NE.1.AND.IPODT.NE.3.AND.INCOTX.EQ.1)
     1WRITE(IZLAZ,2001) NGAUSX
      IF(ISRPS.EQ.1.AND.IPODT.NE.1.AND.IPODT.NE.3.AND.INCOTX.EQ.1)
     1WRITE(IZLAZ,6001) NGAUSX
      IF(ISRPS.EQ.0.AND.IPODT.NE.1.AND.IPODT.NE.3.AND.INCOTY.EQ.0)
     1WRITE(IZLAZ,2002) NGAUSY
      IF(ISRPS.EQ.1.AND.IPODT.NE.1.AND.IPODT.NE.3.AND.INCOTY.EQ.0)
     1WRITE(IZLAZ,6002) NGAUSY
      IF(ISRPS.EQ.0.AND.IPODT.NE.1.AND.IPODT.NE.3.AND.INCOTY.EQ.1)
     1WRITE(IZLAZ,2003) NGAUSY
      IF(ISRPS.EQ.1.AND.IPODT.NE.1.AND.IPODT.NE.3.AND.INCOTY.EQ.1)
     1WRITE(IZLAZ,6003) NGAUSY
      IF(ISRPS.EQ.0.AND.IPODT.NE.1.AND.IPODT.NE.3.AND.INCOTZ.EQ.0)
     1WRITE(IZLAZ,2004) NGAUSZ
      IF(ISRPS.EQ.1.AND.IPODT.NE.1.AND.IPODT.NE.3.AND.INCOTZ.EQ.0)
     1WRITE(IZLAZ,6004) NGAUSZ
      IF(ISRPS.EQ.0.AND.IPODT.NE.1.AND.IPODT.NE.3.AND.INCOTZ.EQ.1)
     1WRITE(IZLAZ,2005) NGAUSZ
      IF(ISRPS.EQ.1.AND.IPODT.NE.1.AND.IPODT.NE.3.AND.INCOTZ.EQ.1)
     1WRITE(IZLAZ,6005) NGAUSZ
      IF(ISRPS.EQ.0.AND.(IPODT.EQ.1.OR.IPODT.EQ.3))
     1WRITE(IZLAZ,2006) NGAUSX,NGAUSZ
      IF(ISRPS.EQ.1.AND.(IPODT.EQ.1.OR.IPODT.EQ.3))
     1WRITE(IZLAZ,6006) NGAUSX,NGAUSZ
        IF(MSET.GT.0) THEN
      IF(ISRPS.EQ.0) WRITE(IZLAZ,2010) MSET,BETA,MSLOJ
      IF(ISRPS.EQ.1) WRITE(IZLAZ,6010) MSET,BETA,MSLOJ
          ELSE
      IF(ISRPS.EQ.0) WRITE(IZLAZ,2020) BETA
      IF(ISRPS.EQ.1) WRITE(IZLAZ,6020) BETA
        ENDIF
      IF(ISRPS.EQ.0) WRITE(IZLAZ,2025) (CPP(J,1),J=1,3),IALFA
C      IF(ISRPS.EQ.0) WRITE(IZLAZ,2025) (CPP(J,1),J=1,3),IALFA,IND3D
      IF(ISRPS.EQ.1) WRITE(IZLAZ,6025) (CPP(J,1),J=1,3),IALFA
C      IF(ISRPS.EQ.1) WRITE(IZLAZ,6025) (CPP(J,1),J=1,3),IALFA,IND3D
      ENDIF
C
      BETA=BETA*3.1415926536D0/180.D0
      IBB0=1
      IF(DABS(CPP(1,1)).LT.1.D-6.AND.DABS(CPP(2,1)).LT.1.D-6.AND.
     1   DABS(CPP(3,1)).LT.1.D-6) IBB0=0
C
CS     REPERI U VEKTORU AU  ZA ULAZNE PODATKE
CE     POINTERS IN INPUT STORAGE VECTOR  AU
C
      IF(IPODT.NE.1.AND.IPODT.NE.3) NCVE=9
      IF(IPODT.EQ.1.OR.IPODT.EQ.3) NCVE=6
      LNSLOJ=1
      LMATSL=LNSLOJ+MSET
      LBBET =LMATSL+MSET*MSLOJ
      CALL DELJIV(LBBET,2,INDL)
      IF(INDL.EQ.0) LBBET=LBBET+1
      LDSLOJ=LBBET+MSET*MSLOJ*IDVA
      LTHID =LDSLOJ+MSET*MSLOJ*IDVA
      LBET0 =LTHID+NE*IDVA
      NDEB=1
      IF(IATYP.GE.3.AND.NMODM.GT.4) THEN
         NDEB=4
         IF(IPODT.EQ.1.OR.IPODT.EQ.3) NDEB=3
         LBET0 =LTHID+NDEB*NE*IDVA
      ENDIF
      LTBTH =LBET0+NE*IDVA
      LTDTH =LTBTH
      IF(INDBTH.EQ.1) LTDTH=LTBTH+NE*IDVA
      LNMAT =LTDTH
      IF(INDDTH.EQ.1) LNMAT=LTDTH+NE*IDVA
      LIPGC =LNMAT+NE
      LISNA =LIPGC+NE
      LIPRC =LISNA+NE
      LNEL  =LIPRC+NE
C
      NTOT=LMAX+LNEL-LNSLOJ+NE*9
      LCEL=LNEL
      IF(ICVEL.EQ.1) THEN
        LNEL=LCEL+NE
        NTOT=NTOT+NE
      ENDIF
      IF(NTOT.GT.MTOT) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2030) NTOT,MTOT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6030) NTOT,MTOT
      STOP
      ENDIF
C
CS     POZIVANJE PROGRAMA ZA ULAZNE PODATKE U VEKTOR AU
CE     CALL ROUTINES FOR INPUT DATA IN VECTOR   AU
C
      LAU=LMAX
      CALL UEL4A(A(LAU))
C
      LMAX=LMAX+(ND*(ND+1)/2+36)*IDVA
      IF(LMAX.GT.MTOT) CALL ERROR(1)
      RETURN
C
 1000 FORMAT(4I5,F10.3,I5,3F10.3,I5,I2)
C-----------------------------------------------------------------------
 2000 FORMAT(
     611X,'BROJ GAUSOVIH TACAKA U PRAVCU OSE R   ......... NGAUSX =',I5/
     616X,'EQ.0; NGAUSX = 2'//)
 2002 FORMAT(
     611X,'BROJ GAUSOVIH TACAKA U PRAVCU OSE S   ......... NGAUSY =',I5/
     616X,'EQ.0; NGAUSY = 2'//)
 2004 FORMAT(
     611X,'BROJ GAUSOVIH TACAKA U PRAVCU OSE T   ......... NGAUSZ =',I5/
     616X,'EQ.0; NGAUSZ = 2')
 2001 FORMAT(
     611X,'BROJ NJUTN-KOTESOVIH TACAKA U PRAVCU OSE R  ... NGAUSX =',I5/
     6//)
 2003 FORMAT(
     611X,'BROJ NJUTN-KOTESOVIH TACAKA U PRAVCU OSE S  ... NGAUSY =',I5/
     6//)
 2005 FORMAT(
     611X,'BROJ NJUTN-KOTESOVIH TACAKA U PRAVCU OSE T  ... NGAUSZ =',I5)
 2006 FORMAT(
     611X,'BROJ GAUSOVIH TACAKA U R,S  RAVNI  ............ NGAUSX =',I5/
     616X,'EQ.0; NGAUSX = 3'///
     611X,'BROJ GAUSOVIH TACAKA U PRAVCU OSE T   ......... NGAUSZ =',I5/
     616X,'EQ.0; NGAUSZ = 2')
 2010 FORMAT(//
     611X,'BROJ RAZLICITIH VISESLOJNIH SETOVA MATERIJALA ... MSET =',I5/
     616X,'GT.0; VISESLOJNA LJUSKA'//
     611X,'UGAO SETOVA U ODNOSU NA REFERENTNI PRAVAC .. BETA =',1PD10.3/
     6/11X,'MAKSIMALAN BROJ SLOJEVA ................... MSLOJ =',5X,I5)
 2020 FORMAT(//
     611X,'UGAO VLAKANA U ODNOSU NA REFERENTNI PRAVAC . BETA =',1PD10.3)
 2025 FORMAT(//
     611X,'KOORDINATE TACKE PROJEKCIONOG PRAVCA ....... CPPX =',1PD10.3/
     611X,'                                     ....... CPPY =',1PD10.3/
     611X,'                                     ....... CPPZ =',1PD10.3/
     6//
     611X,'METOD INKOMPATIBILNIH MODOVA ................... IALFA =',I5/
     616X,'EQ.-1; NE KORISTI SE'/
     616X,'EQ. 0; IALFA=2'/
     616X,'EQ. 1; 4 PARAMETARA - TAYLOR'/
     616X,'EQ. 2; 5 PARAMETARA'/
     616X,'EQ. 3; 6 PARAMETARA'/)
C     611X,'TIP KONSTITUTIVNE MATRICE ...................... IND3D =',I5/
C     616X,'EQ.0; ELEMENT LJUSKE'/
C     616X,'EQ.1; ELEMENT GREDE'/
C     616X,'EQ.2; ELEMENT SMICUCI PANEL'/)
 2030 FORMAT(///' NEDOVOLJNA DIMENZIJA U VEKTORU A ZA PODATKE O ELEMENTI
     1MA LJUSKE'/' POTREBNA DIMENZIJA , LMAX=',I10/' RASPOLOZIVA DIMENZI
     2JA,  MTOT =',I10)
C-----------------------------------------------------------------------
 6000 FORMAT(
     611X,'NUMBER OF GAUSS POINTS IN R-DIRECTION ......... NGAUSX =',I5/
     616X,'EQ.0; NGAUSX = 2'//)
 6002 FORMAT(
     611X,'NUMBER OF GAUSS POINTS IN S-DIRECTION ......... NGAUSY =',I5/
     616X,'EQ.0; NGAUSY = 2'//)
 6004 FORMAT(
     611X,'NUMBER OF GAUSS POINTS IN T-DIRECTION ......... NGAUSZ =',I5/
     616X,'EQ.0; NGAUSZ = 2')
 6001 FORMAT(
     611X,'NUMBER OF NEWTON-COTES POINTS IN R-DIRECTION .. NGAUSX =',I5/
     6//)
 6003 FORMAT(
     611X,'NUMBER OF NEWTON-COTES POINTS IN S-DIRECTION .. NGAUSY =',I5/
     6//)
 6005 FORMAT(
     611X,'NUMBER OF NEWTON-COTES POINTS IN T-DIRECTION .. NGAUSZ =',I5)
 6006 FORMAT(
     611X,'NUMBER OF GAUSS POINTS IN R,S PLANE ........... NGAUSX =',I5/
     616X,'EQ.0; NGAUSX = 3'///
     611X,'NUMBER OF GAUSS POINTS IN T-DIRECTION ......... NGAUSZ =',I5/
     616X,'EQ.0; NGAUSZ = 2')
 6010 FORMAT(//
     611X,'NUMBER OF DIFFERENT MULTILAYERD MATERIAL SETS ... MSET =',I5/
     616X,'GT.0; MULTILAYERD SHELL'//
     611X,'ANGLE OF SETS TO REFERENT DIRECTION ........ BETA =',1PD10.3/
     6/11X,'MAXIMUM NUMBER OF LAYERS .................. MSLOJ =',5X,I5)
 6020 FORMAT(//
     611X,'ANGLE OF FIBER TO REFERENT DIRECTION ....... BETA =',1PD10.3)
 6025 FORMAT(//
     611X,'COORDINATES FOR PROJECTING DIRECTION ....... CPPX =',1PD10.3/
     611X,'                                     ....... CPPY =',1PD10.3/
     611X,'                                     ....... CPPZ =',1PD10.3/
     6//
     611X,'METHOD OF INCOMPATIBLE MODES ................... IALFA =',I5/
     616X,'EQ.-1; NOT USED'/
     616X,'EQ. 0; IALFA=2'/
     616X,'EQ. 1; 4 PARAMETERS - TAYLOR'/
     616X,'EQ. 2; 5 PARAMETERS'/
     616X,'EQ. 3; 6 PARAMETERS'/)
C     611X,'CONSTITUTIVE MATRIX TYPE ....................... IND3D =',I5/
C     616X,'EQ.0; SHELL ELEMENT'/
C     616X,'EQ.1; BEAM ELEMENT'/
C     616X,'EQ.2; SHEAR ELEMENT'/)
 6030 FORMAT(///' NOT ENOUGH SPACE IN WORKING VECTOR  A'
     1/' REQUESTED DIMENSION , LMAX=',I10
     2/' AVAILABLE DIMENSION , MTOT=',I10)
C-----------------------------------------------------------------------
      END
C=======================================================================
      SUBROUTINE UEL4A(AU)
C
CS     UPRAVLJACKI PROGRAM ZA UCITAVANJE ULAZNIH PODATAKA U AU
CE     MENAGEMENT ROUTINE FOR INPUT DATA IN    AU
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      include 'paka.inc'
      
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /GLAVNI/ NP,NGELEM,NMATM,NPER,
     1                IOPGL(6),KOSI,NDIN,ITEST
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /SIMO2D/ LALFE,LHAEM,LHINV,LGEEK,IALFA
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /REPERI/ LCORD,LID,LMAXA,LMHT
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /BTHDTH/ INDBTH,INDDTH,LTBTH,LTDTH
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /DUPLAP/ IDVA
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /PLASTV/ LPLAVT,LPLAV1,LSIGMV
      COMMON /ORIENT/ CPP(3,3),XJJ(3,3),TSG(6,6),BETA,LBET0,IBB0
      COMMON /RESTAR/ TSTART,IREST
      COMMON /MASINA/ INDPC,ICRTA
      COMMON /INTGRA/ INCOTX,INCOTY,INCOTZ
      COMMON /TRANS6/ LTR0,NPD6
      COMMON /VELIKE/ LCOR0,LGM0,JG,NGR,NGS,NGT,NGS4
      COMMON /PODTIP/ IPODT
      COMMON /SRPSKI/ ISRPS
      COMMON /GAUSVR/ LTEMGT,LCORGT,ICORGT
      COMMON /KAKO6O/ LLJUS,LKAKO6
      COMMON /INDCEL/ IND3D
      COMMON /COEFSM/ COEF(3),ICOEF
      COMMON /IKOVAR/ INDKOV
      COMMON /CVSILE/ NSILA,LESILA
      COMMON /CUVAJN/ TAUCEN(6,5),INDSEL,NGAUSU
      COMMON /LEVDES/ ILEDE,NLD,ICPM1
      COMMON /SUMELE/ ISUMEL,ISUMGR
C
      DIMENSION AU(*)
      REAL AU
C
      LMAX8=LMAX8+1
      IF(IREST.EQ.1) THEN
        LMA8=LMAX8
        READ(IELEM,REC=LMAX8)
     1NGAUSX,NGAUSY,NGAUSZ,BETA,NCVE,ITERME,ICORGT,LCEL,LELC,NMA,NMI,
     1LMXAU,MXAU,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,LTR0,IPODT,
     1ND,NGS12,MSLOJ,MXS,MSET,NGS4,NSILA,LESILA,
     1LNSLOJ,LMATSL,LDSLOJ,LBBET,INCOTX,INCOTY,INCOTZ,
     1LBET0,(CPP(J,1),J=1,3),IBB0,LALFE,LHAEM,LHINV,LGEEK,IALFA,IND3D,
     1INDBTH,INDDTH,LTBTH,LTDTH,INDKOV,ICOEF,(COEF(I),I=1,3),INDSEL,
     1ILEDE,NLD,ICPM1
C      WRITE(3,*) 'A',
C     1NGAUSX,NGAUSY,NGAUSZ,BETA,NCVE,ITERME,ICORGT,LCEL,LELC,NMA,NMI
C      WRITE(3,*) 'B',
C     1LMXAU,MXAU,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,LTR0,IPODT
C      WRITE(3,*) 'C',
C     1ND,NGS12,MSLOJ,MXS,MSET,NGS4,NSILA,LESILA
C      WRITE(3,*) 'D',
C     1LNSLOJ,LMATSL,LDSLOJ,LBBET,INCOTX,INCOTY,INCOTZ
C      WRITE(3,*) 'E',
C     1LBET0,(CPP(J,1),J=1,3),IBB0,LALFE,LHAEM,LHINV,LGEEK,IALFA,IND3D
C      WRITE(3,*) 'F',
C     1INDBTH,INDDTH,LTBTH,LTDTH,INDKOV,ICOEF,(COEF(I),I=1,3),INDSEL
        CALL READDD(AU(LNSLOJ),MXAU/IDVA,IELEM,LMAX8,LDUZI)
C      CALL WRR(AU(LALFE),(LMXAU-LALFE)/IDVA,'RA81')
        LMAX8=LMA8
      ENDIF
C
CS     POZIVANJE PROGRAMA ZA ULAZNE PODATKE  O LJUSKAMA
CE     CALL ROUTINE FOR INPUT DATA ABOUT SHELLS
C
      NMA=0
      NMI=0
      CALL UEL4B (AU(LNEL),AU(LNMAT),AU(LIPGC),AU(LISNA),AU(LIPRC),
     1            AU(LTHID),AU(LNSLOJ),AU(LMATSL),AU(LBBET),AU(LDSLOJ),
     1            AU(LTBTH),AU(LTDTH),AU(LCEL),NMA,NMI,ICVEL)
      IF(NCVE.GT.4) THEN
         INDSEL=0
         INDKOV=1
      ENDIF
C*** OVO ZA SINGAUPR
C      IF(IPODT.EQ.0.AND.NCVE.LE.4.AND.NMODM.GT.2) IPODT=4
C***
CE    WRITING DATA ABOUT ELEMENTS IN GRAPHIC OUTPUT FILES
      ISUMG=ISUMGR
      ISUME=ISUMEL
      IF(NBLGR.GE.0.AND.IPODT.NE.1.AND.IPODT.NE.3)
     &   CALL TGRAF8(AU(LNEL),AU(LCEL),ICVEL,AU(LTHID),AU(LNMAT))
      IF(NBLGR.GE.0.AND.(IPODT.EQ.1.OR.IPODT.EQ.3))
     &   CALL TGRAF5(AU(LNEL),AU(LCEL),ICVEL,AU(LTHID),AU(LNMAT))
C
      ISUMGR=ISUMG
      ISUMEL=ISUME
      IF(NBLGR.GE.0)
     +CALL TGRAU8(AU(LNEL),AU(LCEL),ICVEL,AU(LNMAT),AU(LTHID),49)
C
CE    CONNECT NODE NUMBERS FOR FREE NODE NUMERATION
      IF(ICVEL.EQ.1) CALL VEZACE(AU(LNEL),A(LELCV),NE,NCVE)
C
      LLMEL=LNEL+NE*NCVE
      LELC=LLMEL
      IF(ICVEL.EQ.1) THEN
CE      NMA IS MAXIMUM AND NMI IS MINIMUM ELEMENT NUMBERS USED IN FREE
CE      ELEMENT NUMERATION
        LLMEL=LELC+NMA-NMI+1
        LMAX=LAU+LLMEL-1
        IF(LMAX.GT.MTOT) GO TO 4
CE      CLEAR INTEGERS IN WORKING VECTOR
        CALL ICLEAR(AU(LELC),NMA-NMI+1)
CE      CONNECT ELEMENT NUMBERS FOR FREE ELEMENT NUMERATION
        CALL VEZAEL(AU(LCEL),AU(LELC),NE,NMI)
      ENDIF
CS    REDOSLED CVOROVA KAO KOD STANLEYA  IPODT.EQ.2
      IF(IPODT.EQ.2) THEN
         IF(NCVE.EQ.9) THEN
            CALL STANL(AU(LNEL),NE)
         ELSE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2000)      
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6000)
            STOP
         ENDIF
      ENDIF      
      ND=6*NCVE
      LMXAU=LLMEL+NE*ND
      MXAU = LMXAU - 1
      LMAX=LAU+MXAU
      IF(LMAX.GT.MTOT) GO TO 4
C
CS     VEKTOR  LM
CE     VECTOR  LM
C
      CALL LMMHT8(A(LID),AU(LNEL),AU(LLMEL),ND,NPD6,A(LLJUS))
C*** PROSTOR ZA LOKALNU TRANSFORMACIJU CVOROVA SA 6 DOF (PREKO LLMEL)
      LTR0 = LMXAU
      CALL DELJIV(LTR0,2,INDL)
      IF(INDL.EQ.0) LTR0=LTR0+1
      LMXAU=LTR0+NPD6*9*IDVA
      LALFE=LMXAU
      LHAEM=LMXAU
      LHINV=LMXAU
      LGEEK=LMXAU
      LA=1
      IF(IPODT.EQ.0.OR.IPODT.EQ.4.OR.IPODT.EQ.5) THEN
         IF(NCVE.NE.4) IALFA=-1
         IF(IALFA.EQ.1) LA=4
         IF(IALFA.EQ.2) LA=5
         IF(IALFA.EQ.3) LA=6
      ENDIF
      IF(IALFA.GE.0) THEN
         CALL DELJIV(LMXAU,2,INDL)
         IF(INDL.EQ.0) LMXAU=LMXAU+1
         LALFE=LMXAU
         LHAEM=LALFE+NE*LA*IDVA
         LHINV=LHAEM+NE*LA*IDVA
         LGEEK=LHINV+NE*LA*LA*IDVA
         LMXAU=LGEEK+NE*LA*ND*IDVA
      ENDIF
      LESILA=LMXAU
      LMXAU=LESILA+NSILA*ND*IDVA
C
      MXAU = LMXAU - 1
      CALL DELJIV(MXAU,2,INDL)
      IF(INDL.EQ.1) MXAU=MXAU+1
      LMAX=LAU+MXAU
    4 IF(LMAX.GT.MTOT) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2005) LMAX,MTOT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6005) LMAX,MTOT
      STOP
      ENDIF
C
      IF((IALFA.GE.0.OR.NSILA.GT.0).AND.IREST.NE.1) 
     1CALL CLEAR(AU(LALFE),(LMXAU-LALFE)/IDVA)
      NGS12=NGAUSX*NGAUSY*NGAUSZ
      NGS4=NGAUSZ*4
C
CS     ZAPISIVANJE SKALARA NA DIREKT ACCES FILE 
CE     WRITE SCALARS TO A DIRECT ACCESS FILE
C PRIVREMENO SAMO ZA OVAJ SLUCAJ
      IF(IATYP.EQ.5.AND.IPODT.EQ.4) NLD=9
C
      WRITE(IELEM,REC=LMAX8)
     1NGAUSX,NGAUSY,NGAUSZ,BETA,NCVE,ITERME,ICORGT,LCEL,LELC,NMA,NMI,
     1LMXAU,MXAU,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,LTR0,IPODT,
     1ND,NGS12,MSLOJ,MXS,MSET,NGS4,NSILA,LESILA,
     1LNSLOJ,LMATSL,LDSLOJ,LBBET,INCOTX,INCOTY,INCOTZ,
     1LBET0,(CPP(J,1),J=1,3),IBB0,LALFE,LHAEM,LHINV,LGEEK,IALFA,IND3D,
     1INDBTH,INDDTH,LTBTH,LTDTH,INDKOV,ICOEF,(COEF(I),I=1,3),INDSEL,
     1ILEDE,NLD,ICPM1
C      WRITE(3,*) 'A',
C     1NGAUSX,NGAUSY,NGAUSZ,BETA,NCVE,ITERME,ICORGT,LCEL,LELC,NMA,NMI
C      WRITE(3,*) 'B',
C     1LMXAU,MXAU,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,LTR0,IPODT
C      WRITE(3,*) 'C',
C     1ND,NGS12,MSLOJ,MXS,MSET,NGS4,NSILA,LESILA
C      WRITE(3,*) 'D',
C     1LNSLOJ,LMATSL,LDSLOJ,LBBET,INCOTX,INCOTY,INCOTZ
C      WRITE(3,*) 'E',
C     1LBET0,(CPP(J,1),J=1,3),IBB0,LALFE,LHAEM,LHINV,LGEEK,IALFA,IND3D
C      WRITE(3,*) 'F',
C     1INDBTH,INDDTH,LTBTH,LTDTH,INDKOV,ICOEF,(COEF(I),I=1,3),INDSEL
      CALL WRITDD(AU(LNSLOJ),MXAU/IDVA,IELEM,LMAX8,LDUZI)
C      CALL WRR(AU(LALFE),(LMXAU-LALFE)/IDVA,'WA81')
      CALL DELJIV(LMAX,2,INDL)
      IF(INDL.EQ.0) LMAX=LMAX+1
C
CS     PLASTICNOST
CE     PLASTICITY
C
      LPLAST=LMAX
      LPLAS1=LMAX
      LSIGMA=LMAX
      LPLAVT=LMAX
      LPLAV1=LMAX
      LSIGMV=LMAX
      LCOR0 =LMAX
      LGM0  =LMAX
      IF(IATYP.EQ.0) GO TO 10
      IF(NMODM.LE.4) GO TO 10
      NPROS=NE*NGS12*MXS*MODPRO( NMODM )*IDVA
C     REZERVISANJE PROSTORA ZA TACKE ABCD
      IF(IATYP.GE.4.AND.IPODT.EQ.4) THEN
         NPRO1=NE*NGS4*MXS*MODPRO( NMODM )*IDVA
         LPLAVT=LPLAST+NPROS
         LPLAS1=LPLAVT+NPRO1
         LPLAV1=LPLAS1+NPROS
         LMAX=LPLAV1+NPRO1
         NPROS=NPROS+NPRO1
      ELSE
         LPLAS1=LPLAST+NPROS
         LMAX=LPLAS1+NPROS
      ENDIF
      IF(LMAX.GT.MTOT) CALL ERROR(1)
      IF(IREST.NE.1) THEN
         CALL CLEAR(A(LPLAST),NPROS*2/IDVA)
C      WRITE(3,*) 'LSTAZW3',LMAX8+1
         CALL WRITDD(A(LPLAST),NPROS/IDVA,IELEM,LMAX8,LDUZI)
C      WRITE(3,*) 'LSTAZW4',LMAX8+1
         CALL WRITDD(A(LPLAS1),NPROS/IDVA,IELEM,LMAX8,LDUZI)
      ELSE
         CALL READDD(A(LPLAST),NPROS/IDVA,IELEM,LMAX8,LDUZI)
         CALL READDD(A(LPLAS1),NPROS/IDVA,IELEM,LMAX8,LDUZI)
      ENDIF
      IF(IATYP.GE.4) GO TO 10
      NPROS=0
      LSIGMA=LMAX
      IF(ITERME.EQ.1) GO TO 20
      IF(ICORGT.EQ.1) GO TO 30
      RETURN
C
   10 LSIGMA=LMAX
      N45=NLD
      NPROS=NE*NGS12*N45*MXS*IDVA
      IF(NMODM.LE.4) NPROS=NPROS*2
      LMAX=LSIGMA+NPROS
      LCOR0=LMAX
      IF(IATYP.GE.4) THEN
         NPRO1=NE*NCVE*3*IDVA
         LGM0=LCOR0+NPRO1
         LMAX=LGM0+NPRO1
         NPROS=NPROS+2*NPRO1
         IF(IPODT.EQ.4) THEN
            NPRO2=NE*NGS4*N45*MXS*IDVA
            LSIGMV=LMAX
            LMAX=LSIGMV+NPRO2
            NPROS=NPROS+NPRO2
         ENDIF
      ENDIF
   20 LTEMGT=LMAX
      IF(ITERME.EQ.1) THEN
         NPRO1=NE*NGS12*MXS*IDVA
         LMAX=LTEMGT+NPRO1
         NPROS=NPROS+NPRO1
      ENDIF
   30 LCORGT=LMAX
      IF(ICORGT.EQ.1) THEN
         NPRO1=NE*NGS12*3*MXS*IDVA
         LMAX=LCORGT+NPRO1
         NPROS=NPROS+NPRO1
      ENDIF
      IF(LMAX.GT.MTOT) CALL ERROR(1)
      IF(IREST.NE.1) THEN
         CALL CLEAR(A(LSIGMA),NPROS/IDVA)
C
CS       ZADAVANJE POCETNE VREDNOSTI ZA - B
CE       INITIAL VALUE FOR - B 
C
         IF(IATYP.GE.4)
     1   CALL ZADAJB(A(LSIGMA),A(LSIGMV),NE,NGS12,NGS4,MXS,N45,IPODT)
C      WRITE(3,*) 'LSTAZW5',LMAX8+1
         CALL WRITDD(A(LSIGMA),NPROS/IDVA,IELEM,LMAX8,LDUZI)
      ELSE
         CALL READDD(A(LSIGMA),NPROS/IDVA,IELEM,LMAX8,LDUZI)
      ENDIF
C      WRITE(3,*) 'LSTAZWS',LMAX8+1
      RETURN
C-----------------------------------------------------------------------
 2000 FORMAT(///' ELEMENT LJUSKE  82 - A C S MORA BITI SA 9 CVOROVA'/   
     1          ' PROGRAM STOP')
 2005 FORMAT(///' NEDOVOLJNA DIMENZIJA U VEKTORU A ZA PODATKE O ELEMENTI
     1MA LJUSKI'/' POTREBNA DIMENZIJA , LMAX=',I10/' RASPOLOZIVA DIMENZI
     2JA,  MTOT =',I10)
C-----------------------------------------------------------------------
 6000 FORMAT(///' SHELL ELEMENT  82 - A C S HAVE 9 NODES'/   
     1          ' PROGRAM STOP')
 6005 FORMAT(///' NOT ENOUGH SPACE IN WORKING VECTOR  A'
     1/' REQUESTED DIMENSION , LMAX=',I10
     2/' AVAILABLE DIMENSION , MTOT=',I10)
C-----------------------------------------------------------------------
      END
C=======================================================================
      SUBROUTINE UEL4B (NEL,MATV,IPGCV,ISNAP,IPRCV,THICK,NSLOJ,MATSL,
     1                  BBET,DSLOJ,TBTH,TDTH,MCVEL,NMA,NMI,ICVEL)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.   P R O G R A M
CE.      TO READING INPUT DATA ABOUT SHELL ELEMENTS - FREE NUMBERING
CS.   P R O G R A M
CS.      ZA UCITAVANJE ULAZNIH PODATAKA O ELEMENTIMA: LJUSKE
C .
C ......................................................................
C
      CHARACTER*250 ACOZ
      CHARACTER*5  CH
C
      include 'paka.inc'
      
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /BROJUK/ KARTIC,INDFOR,NULAZ
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /BTHDTH/ INDBTH,INDDTH,LTBTH,LTDTH
      COMMON /GAUSVR/ LTEMGT,LCORGT,ICORGT
      COMMON /SRPSKI/ ISRPS
      COMMON /PODTIP/ IPODT
      COMMON /CVSILE/ NSILA,LESILA
      COMMON /RESTAR/ TSTART,IREST
      COMMON /STAPRO/ THIDP(100),NPROPR(100)
C
      DIMENSION NEL(NE,*),MATV(*),IPGCV(*),ISNAP(*),IPRCV(*),THICK(NE,*)
     1         ,NSLOJ(*),MATSL(MSLOJ,*),BBET(MSLOJ,*),DSLOJ(MSLOJ,*),
     1          TBTH(*),TDTH(*),MCVEL(*),THI(4)
      COMMON /CDEBUG/ IDEBUG
C
      IF(IDEBUG.GT.0) PRINT *, ' UEL4B '
      CALL ICLEAR(NPROPR,100)
      CALL CLEAR(THIDP,100)
      NDEB=1
      IF(IATYP.GE.3.AND.NMODM.GT.4) THEN
         NDEB=4
         IF(IPODT.EQ.1.OR.IPODT.EQ.3) NDEB=3
      ENDIF
      IF(ISRPS.EQ.0) CH=' BROJ'
      IF(ISRPS.EQ.1) CH='NUMBE'
      MXS=1
      ICORGT=0
C
CS     P  O  D  A  C  I      O      S  L  O  J  E  V  I  M  A
CE     D  A  T  A      A  B  O  U  T      L  A  Y  E  R  S
C
      IF(MSET.GT.0) THEN
         CH='  SET'
      IF(ISRPS.EQ.0.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,2500)
      IF(ISRPS.EQ.1.AND.(NULAZ.EQ.1.OR.NULAZ.EQ.3))
     1WRITE(IZLAZ,6500)
        DO 2 I=1,MSET
          CALL ISPITA(ACOZ)
          IF(INDFOR.EQ.1)
     1    READ(IULAZ,*) NSLOJ(I)
          IF(INDFOR.EQ.2)
     1    READ(ACOZ,1000) NSLOJ(I)
            IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2530) I,NSLOJ(I)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6530) I,NSLOJ(I)
            ENDIF
            IF(NSLOJ(I).LT.1.OR.NSLOJ(I).GT.MSLOJ) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2505)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6505)
               STOP 'STOP - UEL4B'
            ENDIF
            IF(NSLOJ(I).GT.MXS) MXS=NSLOJ(I) 
            TTT=0.D0
            DO 1 J=1,NSLOJ(I)
               CALL ISPITA(ACOZ)
               IF(INDFOR.EQ.1)
     1         READ(IULAZ,*)   MATSL(J,I),DSLOJ(J,I),BBET(J,I)
               IF(INDFOR.EQ.2)
     1         READ(ACOZ,1515) MATSL(J,I),DSLOJ(J,I),BBET(J,I)
               IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2540) J,MATSL(J,I),DSLOJ(J,I),BBET(J,I)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6540) J,MATSL(J,I),DSLOJ(J,I),BBET(J,I)
               ENDIF
               BBET(J,I)=BBET(J,I)*3.1415926536D0/180.D0
               TTT=TTT+DSLOJ(J,I)
    1       CONTINUE
CS....      PROVERA ZA DEBLJINE
            IF(DABS(TTT-1.D0).LT.1.D-6) GO TO 2
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2550) TTT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6550) TTT
            STOP 'STOP - UL2EKC'
    2    CONTINUE      
      ENDIF
C
CS     P  O  D  A  C  I      O      E  L  E  M  E  N  T  I  M  A
CE     D  A  T  A      A  B  O  U  T      E  L  E  M  E  N  T  S
C
      IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
         IF(IPODT.NE.1.AND.IPODT.NE.3) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2000) NGE,CH
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6000) NGE,CH
         ENDIF
         IF(IPODT.EQ.1.OR.IPODT.EQ.3) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2010) NGE,CH
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6010) NGE,CH
         ENDIF
      ENDIF
      IT1=4
      IT2=9
      IF(IPODT.EQ.1.OR.IPODT.EQ.3) THEN
         IT1=3
         IT2=6
      ENDIF
      NMATS=  1
      IPRCOS=-1
      IPGSS= -1
      ISNAA= -1
      ISNAA=  0
      THICS=  1.D0
      I = 0
      NAUT=0
    5 I = I + 1
      CALL ISPITA(ACOZ)
      IF(I.EQ.1) KARTI=KARTIC
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) NN,NMAT,IPRCO,ISNA,IPGS,THI(1),KORC,BTH,DTH,
     +              (THI(J),J=2,NDEB)
      IF(INDFOR.EQ.2.and.ind56.eq.0)
     1READ(ACOZ,1010) NN,NMAT,IPRCO,ISNA,IPGS,THI(1),KORC,BTH,DTH,
     +                (THI(J),J=2,NDEB)
      IF(INDFOR.EQ.2.and.ind56.eq.1)
     1READ(ACOZ,4010) NN,NMAT,IPRCO,ISNA,IPGS,THI(1),KORC,BTH,DTH,
     +                (THI(J),J=2,NDEB)
      IF(NPROPR(NMAT).EQ.0) THEN
         IF(NMAT.GT.100) STOP 'NMAT.GT.100'
         NPROPR(NMAT)=NMAT
         THIDP(NMAT)=THI(1)
      ELSE
         IF(DABS(THIDP(NMAT)-THI(1)).GT.1.E9) THEN
           WRITE(*,*)'NUMBER OF PROPERTY AND MATERIALS MUST BE THE SAME'
            STOP 'DABS(THIDP(NMAT)-THI(1)).GT.1.E9'
         ENDIF
      ENDIF
      IF(IPRCO.EQ.1) ICORGT=1
      IF(ICVEL.EQ.1) THEN
         MCVEL(I)=NN
         NI=NN
         IF(I.EQ.1) THEN
            NMA=NN
            NMI=NN
         ELSE
            IF(NMA.LT.NN) NMA=NN
            IF(NMI.GT.NN) NMI=NN
         ENDIF
         NN=I
      ENDIF
      CALL ISPITA(ACOZ)
      IF(INDFOR.EQ.1)
     1READ(IULAZ,*) (NEL(NN,J),J=1,NCVE)
      IF(INDFOR.EQ.2.and.ind56.eq.0)
     1READ(ACOZ,1000) (NEL(NN,J),J=1,NCVE)
      IF(INDFOR.EQ.2.and.ind56.eq.1)
     1READ(ACOZ,4000) (NEL(NN,J),J=1,NCVE)
      IF(NMAT.EQ.0) NMAT=NMATS
      NMATS=NMAT
      MATV(NN)= NMAT
      IF(IPRCO.EQ.0) IPRCO=IPRCOS
      IPRCOS=IPRCO
      IF(IPRCO.LT.0) IPRCO = 0
      IPRCV(NN)=IPRCO
      IF(ISNA.EQ.0) ISNA=ISNAA
      ISNAA=ISNA
      IF(ISNA.LT.0) ISNA = 0
      ISNAP(NN)=ISNA
      IF(IPGS.EQ.0) IPGS=IPGSS
      IPGSS=IPGS
      IF(IPGS.LT.0) IPGS = 0
      IPGCV(NN)=IPGS
      IF(DABS(THI(1)).LT.1.D-10) THI(1)=THICS
      THICS=THI(1)
      THICK(NN,1)=THI(1)
      DO 731 J=2,NDEB
C         RELATIVNE DEBLJINE
C         IF(DABS(THI(J)).LT.1.D-10) THI(J)=1.D0
C         THICK(NN,J)=THI(1)*THI(J)
C        UKUPNE DEBLJINE
         IF(DABS(THI(J)).LT.1.D-10) THI(J)=THI(1)
         THICK(NN,J)=THI(J)
  731 CONTINUE
      IF(INDBTH.EQ.1) TBTH(NN)=BTH
      IF(INDDTH.EQ.1) TDTH(NN)=DTH
      IF(NULAZ.EQ.1.OR.NULAZ.EQ.3) THEN
         IF(ICVEL.EQ.1) IN=MCVEL(NN)
         IF(ICVEL.EQ.0) IN=NN
         IF(IPODT.NE.1.AND.IPODT.NE.3)
     1                  WRITE(IZLAZ,5000) IN,(NEL(NN,J),J=1,IT1),NMAT,
     1                  IPRCO,ISNA,IPGS,THI(1),KORC,(THI(J),J=2,NDEB)
         IF(IPODT.NE.1.AND.IPODT.NE.3.AND.NCVE.GT.IT1)
     +                  WRITE(IZLAZ,5011) (NEL(NN,J),J=IT1+1,NCVE)
         IF(IPODT.EQ.1.OR.IPODT.EQ.3)
     1                  WRITE(IZLAZ,5002) IN,(NEL(NN,J),J=1,IT1),NMAT,
     1                  IPRCO,ISNA,IPGS,THI(1),KORC,(THI(J),J=2,NDEB)
         IF((IPODT.EQ.1.OR.IPODT.EQ.3).AND.NCVE.GT.IT1)
     +                  WRITE(IZLAZ,5013) (NEL(NN,J),J=IT1+1,NCVE)
         IF(INDBTH.EQ.1) THEN
         IF(DABS(TBTH(NN)).GT.1.0D-10) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2040) TBTH(NN)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6040) TBTH(NN)
         ENDIF
         ENDIF
         IF(INDDTH.EQ.1) THEN 
         IF(DABS(TDTH(NN)).GT.1.0D-10) THEN 
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2050) TDTH(NN)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6050) TDTH(NN)
         ENDIF
         ENDIF
      ENDIF
      IF(NAUT.GT.0) GO TO 30
      IF(KORC.NE.0) GO TO 20
      IF(I.EQ.NE) GO TO 50
      GO TO 5
C
   20 NAUT=1
      IF(ICVEL.EQ.1) N1=NI
      IF(ICVEL.EQ.0) NN1=NN
      KORA=KORC
      GO TO 5
C
CS     AUTOMATSKO GENERISANJE PODATAKA IZMEDJU CVOROVA N1 I N2
CE     AUTOMATIC  GENERATION BETWEN NODES  N1  AND  N2
C
   30 NN2=NN
      IF(ICVEL.EQ.1) THEN
         NN1=NN-1
         N2=NI
      ENDIF
      N11=NEL(NN1,1)
      N22=NEL(NN2,1)
      N12=N22-N11
      CALL DELJIV(N12,KORA,INDD)
      IF(INDD.EQ.1) GO TO 100
      DO 40 NC=2,IT1
         N11=NEL(NN1,NC)
         N22=NEL(NN2,NC)
         N21=N22-N11
         IF(N12.NE.N21) GO TO 100
   40 CONTINUE
      IF(NCVE.GT.IT1) THEN
         DO 45 NC=IT1+1,NCVE
            N11=NEL(NN1,NC)
            N22=NEL(NN2,NC)
            IF(N11.EQ.0.AND.N22.EQ.0) GO TO 45
            N21=N22-N11
            IF(N12.NE.N21) GO TO 100
   45    CONTINUE
      ENDIF
      IF(ICVEL.EQ.1) NNN=N2-N1-1
      IF(ICVEL.EQ.0) NNN=NN2-NN1-1
      NGG=N12/KORA-1
      IF(NNN.NE.NGG) THEN
         IF(ICVEL.EQ.1) THEN
            NN1=N1
            NN2=N2
         ENDIF
         GO TO 150
      ENDIF
      IAUT=N12/KORA-1
      IF(ICVEL.EQ.1) THEN
         NM=NN+IAUT
         MCVEL(NM)=MCVEL(NN)
         MATV(NM) = MATV(NN)
         IPRCV(NM)=IPRCV(NN)
         ISNAP(NM)=ISNAP(NN)
         IPGCV(NM)=IPGCV(NN)
         DO 732 J=1,NDEB
            THICK(NM,J)=THICK(NN,J)
  732    CONTINUE
         IF(INDBTH.EQ.1) TBTH(NM) = TBTH(NN)
         IF(INDDTH.EQ.1) TDTH(NM) = TDTH(NN)
         DO 32 II=1,NCVE
            NEL(NM,II)=NEL(NN,II)
   32    CONTINUE
      ENDIF
      DO 34 J=1,IAUT
         JJ=NN1+J
         IF(ICVEL.EQ.1) THEN
            N1=N1+1
            MCVEL(JJ)=N1
         ENDIF
         MATV(JJ) = MATV(NN1)
         IPRCV(JJ)=IPRCV(NN1)
         ISNAP(JJ)=ISNAP(NN1)
         IPGCV(JJ)=IPGCV(NN1)
         DO 735 II=1,NDEB
            THICK(JJ,II)=THICK(NN1,II)
  735    CONTINUE
         IF(INDBTH.EQ.1) TBTH(JJ) = TBTH(NN1)
         IF(INDDTH.EQ.1) TDTH(JJ) = TDTH(NN1)
         DO 35 II=1,NCVE
            NODP=NEL(JJ-1,II)
            NEL(JJ,II)=NODP+KORA
            IF(NODP.EQ.0) NEL(JJ,II) = 0
   35    CONTINUE
   34 CONTINUE
      IF(ICVEL.EQ.1) I=NM
      IF(ICVEL.EQ.0) I=I+IAUT
      IF(I.EQ.NE) GO TO 50
      NAUT=0
      IF(KORC.EQ.0) GO TO 5
      KORA=KORC
      NAUT=1
      IF(ICVEL.EQ.1) N1=N2
      IF(ICVEL.EQ.0) NN1=NN2
      GO TO 5
C
CS     ODREDJIVANJE MAKSIMALNOG BROJA CVOROVA
CE     OBTAIN MAXIMUM NUMBER OF NODES PER ELEMENT
C
   50 IF(IREST.EQ.1) GO TO 61
      NCVE=IT1
      DO 60 I=1,NE
      DO 60 J=IT1+1,IT2
         IJ=NEL(I,J)
         IF(IPODT.EQ.4.AND.IJ.GT.0.AND.J.GT.4) THEN
            WRITE (*,*) ' I,NE',I,NE
            STOP
         ENDIF
         IF(IJ.GT.0.AND.J.GT.NCVE) NCVE=J
   60 CONTINUE
C
   61 NSILA=0
      DO 65 I=1,NE
         IF(IPGCV(I).EQ.1) THEN
            NSILA=NSILA+1
            IPGCV(I)=NSILA
         ELSE
            IPGCV(I)=0
         ENDIF
   65 CONTINUE
C
CS     STAMPANJE UCITANIH I GENERISANIH PODATAKA
CE     PRINT INPUT AND GENERATED DATA
C
      IF(NULAZ.NE.1.AND.NULAZ.NE.3) RETURN
         CALL WBROJK(KARTI,0)
         IF(IPODT.NE.1.AND.IPODT.NE.3) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2140) NGE,CH
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6140) NGE,CH
         ENDIF
         IF(IPODT.EQ.1.OR.IPODT.EQ.3) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2240) NGE,CH
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6240) NGE,CH
         ENDIF
         DO 70 I=1,NE
            IF(ICVEL.EQ.1) IN=MCVEL(I)
            IF(ICVEL.EQ.0) IN=I
            IF(IPODT.NE.1.AND.IPODT.NE.3)
     1                     WRITE(IZLAZ,5001) IN,(NEL(I,J),J=1,IT1),
     1                     MATV(I),IPRCV(I),ISNAP(I),IPGCV(I),
     +                     (THICK(I,J),J=1,NDEB)
            IF(IPODT.NE.1.AND.IPODT.NE.3.AND.NCVE.GT.IT1)
     1                     WRITE(IZLAZ,5011) (NEL(I,J),J=IT1+1,NCVE)
            IF(IPODT.EQ.1.OR.IPODT.EQ.3)
     1                     WRITE(IZLAZ,5003) IN,(NEL(I,J),J=1,IT1),
     1                     MATV(I),IPRCV(I),ISNAP(I),IPGCV(I),
     +                     (THICK(I,J),J=1,NDEB)
            IF((IPODT.EQ.1.OR.IPODT.EQ.3).AND.NCVE.GT.IT1)
     1                     WRITE(IZLAZ,5013) (NEL(I,J),J=IT1+1,NCVE)
         IF(INDBTH.EQ.1) THEN
         IF(DABS(TBTH(I)).GT.1.0D-10) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2040) TBTH(I)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6040) TBTH(I)
         ENDIF
         ENDIF
         IF(INDDTH.EQ.1) THEN 
         IF(DABS(TDTH(I)).GT.1.0D-10) THEN 
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2050) TDTH(I)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6050) TDTH(I)
         ENDIF
         ENDIF
   70    CONTINUE
      RETURN
C
  150 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2110) NN1,NN2,NGG
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6110) NN1,NN2,NGG
      STOP
C
  100 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2100) N22,N11,KORA
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6100) N22,N11,KORA
      STOP
C
 1000 FORMAT(14I5)
 4000 FORMAT(14I10)
 1010 FORMAT(5I5,F10.0,I5,2F10.0,3F5.3)
 4010 FORMAT(I10,4I5,F10.0,I5,2F10.0,3F5.3)
 1515 FORMAT(I5,2F10.0)
 5000 FORMAT(I6,1X,4I6,5X,4I6,1PD11.3,I6,3(1PD11.3))
 5001 FORMAT(I6,1X,4I6,5X,4I6,4(1PD11.3))
 5011 FORMAT(6X,5I6)
 5002 FORMAT(I6,3X,3I8,3X,4I6,1PD11.3,I6,3(1PD11.3))
 5003 FORMAT(I6,3X,3I8,3X,4I6,4(1PD11.3))
 5013 FORMAT(6X,3I8)
C-----------------------------------------------------------------------
 2000 FORMAT(///' UCITANI PODACI O CETVOROUGAONIM ELEMENTIMA LJUSKE GRUP
     1E ELEMENATA',I6/1X,71('-')///
     1' ELEME  CVOR1 CVOR2 CVOR3 CVOR4      MATER KOORD NAPON NAPON  DEB
     1LJINA  KORAK'/
     1'  BROJ CVOR5 CVOR6 CVOR7 CVOR8 CVOR9 ',A5,' STAMP STAMP CVORA  EL
     1EMENTA  GENER')
 2010 FORMAT(///' UCITANI PODACI O TROUGAONIM ELEMENTIMA LJUSKE GRUPE EL
     1EMENATA',I6/1X,67('-')///
     1' ELEME      CVOR1   CVOR2   CVOR3    MATER KOORD NAPON NAPON  DEB
     1LJINA  KORAK'/
     1'  BROJ   CVOR4   CVOR5   CVOR6       ',A5,' STAMP STAMP CVORA  EL
     1EMENTA  GENER')
 2100 FORMAT(///' BROJ CVORA N2=',I5,' NE MOZE SE DOBITI SABIRANJEM BROJ
     1A CVORA N1=',I5,' I KONACNOG BROJA KORAKA KORA=',I5)
 2110 FORMAT(///' IZMEDJU ELEMENATA N1=',I5,' I N2=',I5,' NEMA NG=',I5,
     1' ELEMENATA KOJE TREBA GENERISATI')
 2140 FORMAT(' GENERISANI PODACI O CETVOROUGAONIM ELEMENTIMA LJUSKE GRUP
     1E ELEMENATA',I6/1X,74('-')///
     3' ELEME  CVOR1 CVOR2 CVOR3 CVOR4      MATER KOORD NAPON NAPON  DEB
     1LJINA'/
     1'  BROJ CVOR5 CVOR6 CVOR7 CVOR8 CVOR9 ',A5,' STAMP STAMP CVORA  EL
     1EMENTA')
 2240 FORMAT(' GENERISANI PODACI O TROUGAONIM ELEMENTIMA LJUSKE GRUPE EL
     1EMENATA',I6/1X,70('-')///
     1' ELEME      CVOR1   CVOR2   CVOR3    MATER KOORD NAPON NAPON  DEB
     1LJINA'/
     1'  BROJ   CVOR4   CVOR5   CVOR6       ',A5,' STAMP STAMP CVORA  EL
     1EMENTA')
 2500 FORMAT(///6X,' UCITANI PODACI O VISESLOJNIM SETOVIMA MATERIJALA'/
     16X,49('-')///)
 2505 FORMAT(///' BROJ SLOJEVA U MATERIJALNOM SETU MORA BITI VECI OD 0'/
     1' (MAKSIMALNO :     MSLOJ )')
 2530 FORMAT(//10X,'MATERIJALNI SET (',I3,') ',5X,'BROJ SLOJEVA =',I3/)
 2540 FORMAT(/10X,'SLOJ =',I3/10X,'MATERIJAL =',I3/10X,'RELATIVNA ',
     1'DEBLJINA =',1PD10.3/10X,'UGAO VLAKANA =',1PD10.3) 
 2550 FORMAT(/// ' ZBIR RELATIVNIH DEBLJINA SLOJEVA U MATERIJALNOM SETU 
     1MORA BITI   1.00'/' (KONTROLNI ZBIR JE :   TTT =',1PD10.3)
 2040 FORMAT(' VREME NASTAJANJA ELEMENTA - TBTH =',1PD10.3)
 2050 FORMAT(' VREME NESTAJANJA ELEMENTA - TDTH =',1PD10.3)
C-----------------------------------------------------------------------
 6000 FORMAT(///' READING DATA ABOUT TO RECTANGULAR SHELL ELEMENTS FOR G
     1ROUP',I6/1X,64('-')///
     1' ELEME  NODE1 NODE2 NODE3 NODE4      MATER COORD STRES STRES    T
     1HICK    STEP'/
     1' NUMBE NODE5 NODE6 NODE7 NODE8 NODE9 ',A5,' PRINT PRINT  NODE   E
     1LEMENT  GENER')
 6010 FORMAT(///' READING DATA ABOUT TO TRIANGULAR SHELL ELEMENTS FOR GR
     1OUP',I6/1X,63('-')///
     1' ELEME      NODE1   NODE2   NODE3    MATER COORD STRES STRES    T
     1HICK    STEP'/
     1' NUMBE   NODE4   NODE5   NODE6       ',A5,' PRINT PRINT  NODE   E
     1LEMENT  GENER')
 6100 FORMAT(///' NODE NUMBER N2=',I5,' CAN NOT BE DEFINED BY SUPERPOSIT 
     1ION OF NODE N1=',I5,' WITH A NUMBER OF STEPS  KORA=',I5)
 6110 FORMAT(///' AMONG ELEMENTS N1=',I5,' AND N2=',I5,' THERE IS NO  ',
     1'NG=',I5,' ELEMENTS TO GENERATE')
 6140 FORMAT (' GENERATED DATA ABOUT TO RECTANGULAR SHELL ELEMENTS FOR G
     1ROUP',I6/1X,66('-')///
     1' ELEME  NODE1 NODE2 NODE3 NODE4      MATER COORD STRES STRES    T
     1HICK '/
     1' NUMBE NODE5 NODE6 NODE7 NODE8 NODE9 ',A5,' PRINT PRINT  NODE   E
     1LEMENT')
 6240 FORMAT (' GENERATED DATA ABOUT TO TRIANGULAR SHELL ELEMENTS FOR GR
     1OUP',I6/1X,65('-')///
     1' ELEME      NODE1   NODE2   NODE3    MATER COORD STRES STRES    T
     1HICK '/
     1' NUMBE   NODE4   NODE5   NODE6       ',A5,' PRINT PRINT  NODE   E
     1LEMENT')
 6500 FORMAT(///6X,' READING DATA ABOUT MULTILAYERED MATERIAL SETS'/
     16X,46('-')///)
 6505 FORMAT(///' NUMBER OF LAYERS IN MATERIAL SET MUST BE GREATER',
     1          ' THAN   0'/' (MAXIMUM :     MSLOJ )')
 6530 FORMAT(//10X,'MATERIAL SET (',I3,') ',5X,'NUMBER OF LAYERS =',I3/)
 6540 FORMAT(/10X,'LAYER =',I3/10X,'MATERIAL =',I3/10X,'RELATIV ',
     1'THICKNESS =',1PD10.3/10X,'FIBER ANGLE =',1PD10.3) 
 6550 FORMAT(/// ' RELATIV THICKNESSES SUM IN MATERIAL SET MUST BE', 
     1'   1.00'/' (CONTROL SUM IS :   TTT =',1PD10.3)
 6040 FORMAT(' ELEMENT BIRTH TIME - TBTH =',1PD10.3)
 6050 FORMAT(' ELEMENT DEATH TIME - TDTH =',1PD10.3)
C-----------------------------------------------------------------------
      END
C=======================================================================
      SUBROUTINE LMMHT8(ID,NEL,LMEL,ND,NPD6,LJ)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
CS     FORMIRANJE VEKTORA LM I VISINA STUBOVA (MHT)
CE     OBTAIN VECTOR  LM   AND COLUMN HEIGHTS
C
      include 'paka.inc'
      
C
      COMMON /GLAVNI/ NP,NGELEM,NMATM,NPER,
     1                IOPGL(6),KOSI,NDIN,ITEST
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /REPERI/ LCORD,LID,LMAXA,LMHT
      COMMON /GEORGE/ TOLG,ALFAG,ICCGG
      COMMON /DRAKCE/ IDRAKCE,NELUK,NZERO,NEED1,NEED2,NEED3,NNZERO
     1                ,IROWS,LAILU,LUCG,LVCG,LWCG,LPCG,LRCG
      DIMENSION ID(NP,*),NEL(NE,*),LMEL(ND,*),LJ(*)
C     PETLJA PO ELEMENTIMA
      NPD6=0
      DO 100 NLM=1,NE
        KK=0
        DO 10 NC=1,NCVE
          IF(NEL(NLM,NC).EQ.0) GO TO 10
          JJ=NEL(NLM,NC)
            IF(ID(JJ,6).GT.0.OR.LJ(JJ).EQ.1) NPD6=NPD6+1
            DO 20 I=1,6
   20       LMEL(KK+I,NLM)=ID(JJ,I)
          KK=KK+6
   10   CONTINUE
C     FORMIRANJE VISINA STUBOVA
        CALL VISINE(A(LMHT),ND,LMEL(1,NLM))
      IF (IABS(ICCGG).EQ.1) THEN
         WRITE(IDRAKCE) ND,(LMEL(I,NLM),I=1,ND)
         NELUK=NELUK+1
      ENDIF
  100 CONTINUE
      RETURN
      END
C=======================================================================
      SUBROUTINE TGRAF8(NEL,MCVEL,ICVEL,THID,NMAT)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
CS     PROGRAM ZA STAMPANJE LJUSKE U UNIVERZALNI FILE
CE     PROGRAM FOR PRINTOUT DATA IN UNIVERSAL GRAPHICS FILE
C
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /SUMELE/ ISUMEL,ISUMGR
      COMMON /SRPSKI/ ISRPS
      COMMON /NIDEAS/ IDEAS
C
      DIMENSION NEL(NE,*),MCVEL(*),THID(NE,*),NMAT(*)
      DIMENSION FIZ(24),NNEL(8)
C
      IF(ideas.eq.-1) return
      ISUMGR=ISUMGR+1
C
C     M A T E R I J A L I
C
      MAT=NMAT(1)
      IF(IDEAS.LT.7) CALL MELGR(MAT)
C
C     FIZICKE OSOBINE
C
      CALL CLEAR(FIZ,24)
      FIZ(1)=THID(1,1)
      IF(IDEAS.EQ.8) THEN
         NPR=5
         ITYP=2437
      ELSEIF(IDEAS.EQ.7) THEN
         NPR=12
         ITYP=789
      ELSEIF(IDEAS.EQ.6) THEN
         NPR=7
         ITYP=788
         FIZ(2)=FIZ(1)
         FIZ(3)=FIZ(1)
         FIZ(4)=FIZ(1)
      ELSE
         NPR=7
         ITYP=772
      ENDIF
      ICL=1
      IPH=90
      IND=-1
      WRITE(IGRAF,1100) IND
      WRITE(IGRAF,1100) ITYP
      WRITE(IGRAF,1000) ISUMGR,IPH,NPR
      IF(ISRPS.EQ.0)
     1WRITE(IGRAF,2000) ISUMGR
      IF(ISRPS.EQ.1)
     1WRITE(IGRAF,6000) ISUMGR
      IF(IDEAS.EQ.8) THEN
         WRITE(IGRAF,1000) 1,2,4
         WRITE(IGRAF,1300) (FIZ(I),I=ICL,4)
         WRITE(IGRAF,1000) 46,2,1
         WRITE(IGRAF,1300) FIZ(5)
         WRITE(IGRAF,1000) 47,2,1
         WRITE(IGRAF,1300) FIZ(6)
         WRITE(IGRAF,1000) 48,2,1
         WRITE(IGRAF,1300) FIZ(7)
         WRITE(IGRAF,1000) 52,2,2
         WRITE(IGRAF,1300) (FIZ(I),I=8,9)
      ELSEIF(IDEAS.EQ.7) THEN
         WRITE(IGRAF,1300) (FIZ(I),I=ICL,24)
      ELSEIF(IDEAS.EQ.6) THEN
         WRITE(IGRAF,1200) (FIZ(I),I=ICL,19)
      ELSE
         WRITE(IGRAF,1200) (FIZ(I),I=ICL,19)
      ENDIF
      WRITE(IGRAF,1100) IND
C
C     E L E M E N T I
C
      IF(ISRPS.EQ.0.AND.(NCVE.NE.4.AND.NCVE.NE.8))
     1WRITE(IZLAZ,2200) NGE
      IF(ISRPS.EQ.1.AND.(NCVE.NE.4.AND.NCVE.NE.8))
     1WRITE(IZLAZ,6200) NGE
      NNCVE=NCVE
      IF(NCVE.GT.4.AND.NCVE.LT.8) NCVE=4
      IF(NCVE.EQ.9) NCVE=8
      IF(NGAUSX.NE.NGAUSY) GO TO 160
C      IF(NGAUSX.EQ.3.AND.NCVE.EQ.4) GO TO 150
C     GRAFICKI OPIS LJUSKE: SA 4 CVORA =  5, SA 8 CVOROVA =  6
      IFGD=5 
      IF(NCVE.EQ.8) IFGD=6 
C     VRSTA  ELEMENTA: 
C          JEDNOSLOJNA    SA  4 CVORA = 94, SA 8 CVOROVA = 95
      IFDI=94
      IF(NCVE.EQ.8) IFDI=95
C          VISESLOJNA     SA  4 CVORA = 94, SA 8 CVOROVA = 95
      IF(MSET.GT.0) THEN
         IFDI=94
         IF(NCVE.EQ.8) IFDI=95
      ENDIF
C     TABELA FIZICKIH OSOBINA
      IPTN=ISUMGR
C     TABELA MATERIJALA
      IF(IDEAS.LT.7) THEN
         MPTN=ISUMGR
      ELSE
         MPTN=MAT
      ENDIF         
C     BOJA  
      ICOL=7
C     BROJ CVOROVA NA ELEMENTU
      NNODS=NCVE
      IND=-1
      IF(IDEAS.GT.6) THEN
         ITYP=2412
      ELSEIF(IDEAS.EQ.6) THEN
         ITYP=780
         ICOL=11
      ELSE
         ITYP=71
      ENDIF
      WRITE(IGRAF,1100) IND
      WRITE(IGRAF,1100) ITYP
      DO 10 I=1,NE
C        REDNI BROJ ELEMENTA
         IEL=I+ISUMEL
         IF(ICVEL.EQ.1) IEL=MCVEL(I)
         IF(IDEAS.GT.6) THEN
            WRITE(IGRAF,1000) IEL,IFDI,IPTN,MPTN,ICOL,NNODS
         ELSEIF(IDEAS.EQ.6) THEN
            JEDAN=1
            WRITE(IGRAF,1000) IEL,IFDI,JEDAN,IPTN,MPTN,JEDAN,ICOL,NNODS
         ELSE
            WRITE(IGRAF,1000) IEL,IFGD,IFDI,IPTN,MPTN,ICOL,NNODS
         ENDIF
         IF(NCVE.EQ.4) THEN
            WRITE(IGRAF,1000)(NEL(I,J),J=1,4)
         ELSE
            IZ=0
            DO 5 J=1,4
               IZ=IZ+1
               NNEL(IZ)=NEL(I,J)
               IZ=IZ+1
               NNEL(IZ)=NEL(I,J+4)
               IF(NNEL(IZ).EQ.0)NNEL(IZ)=NNEL(IZ-1)
    5       CONTINUE
            WRITE(IGRAF,1000) NNEL
         ENDIF
   10 CONTINUE
      WRITE(IGRAF,1100) IND
      ISUMEL=ISUMEL+NE
      NCVE=NNCVE
      RETURN
C
  160 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2160) NGE
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6160) NGE
      STOP
 1000 FORMAT(8I10)
 1100 FORMAT(I6)
 1200 FORMAT(6(1PE13.5))
 1300 FORMAT(5(1PE15.8))
C-----------------------------------------------------------------------
 2000 FORMAT('FIZICKI SET :',I10)
 2160 FORMAT(//' ZBOG GRAFIKE U GRUPI ELEMENATA NGE =',I5/
     1' GAUSOVA INTEGRACIJA U (R) I (S) PRAVCU MORA BITI ISTOG REDA')
 2200 FORMAT(//' PROGRAM ZA GRAFICKO PRIKAZIVANJE REZULTATA "IDEAS"'/
     1' ZAHTEVA LJUSKU SA 4 ILI 8 CVOROVA U GRUPI ELEMENATA NGE ='
     1,I5)
C-----------------------------------------------------------------------
 6000 FORMAT('PHISICAL PROPERTIES SET :',I10)
 6160 FORMAT(//' FOR GRAPHIC OUTPUT FOR ELEMENT GROUP  NGE =',I5/
     1' GAUSS INTEGRATION IN (R),(S) DIRECTION MUST BE SAME')
 6200 FORMAT(//' GRAPHIC PACKAGE   "IDEAS"'/
     1' PERMITS ONLY SHELLS WITH 4 OR 8 NODES PER ELEMENT IN GROUP',
     1'  NGE =',I5)
C-----------------------------------------------------------------------
      END
C=======================================================================
      SUBROUTINE TGRAF5(NEL,MCVEL,ICVEL,THID,NMAT)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C   
CS     PROGRAM ZA STAMPANJE TROUGAONE LJUSKE U UNIVERZALNI FILE
CE     TRIANGULAR SHELL
CE     PROGRAM FOR PRINTOUT DATA IN UNIVERSAL GRAPHICS FILE
C
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /IZOL4B/ NGS12,ND,MSLOJ,MXS,MSET,LNSLOJ,LMATSL,LDSLOJ,LBBET
      COMMON /SUMELE/ ISUMEL,ISUMGR
      COMMON /SRPSKI/ ISRPS
C
      DIMENSION NEL(NE,*),MCVEL(*),THID(NE,*),NMAT(*)
      DIMENSION FIZ(18),NNEL(6)
C
      ISUMGR=ISUMGR+1
C
C     FIZICKE OSOBINE
C
      CALL CLEAR(FIZ,18)
      ICL=1
      IPH=60
      NPR=6
      FIZ(1)=THID(1,1)
      IND=-1
      ITYP=772
      WRITE(IGRAF,1100) IND
      WRITE(IGRAF,1100) ITYP
      WRITE(IGRAF,1000) ISUMGR,IPH,NPR
      IF(ISRPS.EQ.0)
     1WRITE(IGRAF,2000) ISUMGR
      IF(ISRPS.EQ.1)
     1WRITE(IGRAF,6000) ISUMGR
      WRITE(IGRAF,1200) (FIZ(I),I=ICL,18)
      WRITE(IGRAF,1100) IND
C
C     M A T E R I J A L I
C
      MAT=NMAT(1)
      CALL MELGR(MAT)
C
C     E L E M E N T I
C
      IF(NCVE.NE.3.AND.NCVE.NE.6) THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2200) NGE
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6200) NGE
      ENDIF
      NNCVE=NCVE
      IF(NCVE.GT.3.AND.NCVE.LT.6) NCVE=3
      IF(NGAUSX.EQ.7.AND.NCVE.EQ.3) GO TO 150
C     GRAFICKI OPIS LJUSKE: SA 3 CVORA = 2, SA 6 CVOROVA = 3
      IFGD=2
      IF(NCVE.EQ.6) IFGD=3
C     VRSTA  ELEMENTA: 
C          JEDNOSLOJNA    SA  3 CVORA = 91, SA 6 CVOROVA = 92
      IFDI=91
      IF(NCVE.EQ.6) IFDI=92
C          VISESLOJNA     SA  3 CVORA = 91, SA 6 CVOROVA = 92
      IF(MSET.GT.0) THEN
         IFDI=91
         IF(NCVE.EQ.6) IFDI=92
      ENDIF
C     TABELA FIZICKIH OSOBINA
      IPTN=ISUMGR
C     TABELA MATERIJALA
      MPTN=ISUMGR
C     BOJA  
      ICOL=7
C     BROJ CVOROVA NA ELEMENTU
      NNODS=NCVE
      IND=-1
      ITYP=71
      WRITE(IGRAF,1100) IND
      WRITE(IGRAF,1100) ITYP
      DO 10 I=1,NE
C        REDNI BROJ ELEMENTA
         IEL=I+ISUMEL
         IF(ICVEL.EQ.1) IEL=MCVEL(I)
         WRITE(IGRAF,1000) IEL,IFGD,IFDI,IPTN,MPTN,ICOL,NNODS
         IF(NCVE.EQ.3) THEN
            WRITE(IGRAF,1000)(NEL(I,J),J=1,3)
         ELSE
            IZ=0
            DO 5 J=1,3
               IZ=IZ+1
               NNEL(IZ)=NEL(I,J)
               IZ=IZ+1
               NNEL(IZ)=NEL(I,J+3)
               IF(NNEL(IZ).EQ.0)NNEL(IZ)=NNEL(IZ-1)
    5       CONTINUE
            WRITE(IGRAF,1000) NNEL
         ENDIF
   10 CONTINUE
      WRITE(IGRAF,1100) IND
      ISUMEL=ISUMEL+NE
      NCVE=NNCVE
      RETURN
C
  150 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2150) NGE
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6150) NGE
      STOP
 1000 FORMAT(8I10)
 1100 FORMAT(I6)
 1200 FORMAT(6(1PE13.5))
C-----------------------------------------------------------------------
 2000 FORMAT('FIZICKI SET :',I10)
 2150 FORMAT(//' U GRUPI ELEMENATA NGE =',I5/' ELEMENTI SU LINEARNI I',
     1' NEMA POTREBE ZA GAUSOVOM INTEGRACIJOM U 7 TACAKA')
 2200 FORMAT(//' PROGRAM ZA GRAFICKO PRIKAZIVANJE REZULTATA "IDEAS"'/
     1' ZAHTEVA TROUGAO SA 3 ILI 6 CVOROVA U GRUPI ELEMENATA NGE ='
     1,I5)
C-----------------------------------------------------------------------
 6000 FORMAT('PHISICAL PROPERTIES SET :',I10)
 6150 FORMAT(//' IN ELEMENT GROUP  NGE =',I5/' ELEMENT ARE LINEAR  -',
     1'  THERE IS NO NEED FOR 7 POINTS GAUSS INTEGRATION')
 6200 FORMAT(//' GRAPHIC PACKAGE   "IDEAS"'/
     1' PERMITS ONLY TRIANGLES WITH 3 OR 6 NODES PER ELEMENT IN GROUP',
     1'  NGE =',I5)
C-----------------------------------------------------------------------
      END
      SUBROUTINE STANL(NEL,NE)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
CS    REDOSLED CVOROVA KAO KOD STANLEYA  IPODT.EQ.2
C       
      DIMENSION NEL(NE,*),NC(9)
C
      DO 10 I=1,NE
         DO 20 J=1,9
            NC(J)=NEL(I,J)
   20    CONTINUE
         NEL(I,1)=NC(3)
         NEL(I,2)=NC(7)
         NEL(I,3)=NC(4)
         NEL(I,4)=NC(6)
         NEL(I,5)=NC(9)
         NEL(I,6)=NC(8)
         NEL(I,7)=NC(2)
         NEL(I,8)=NC(5)
         NEL(I,9)=NC(1)
   10 CONTINUE
      RETURN
      END
C=======================================================================
C
C=======================================================================
      SUBROUTINE ZADAJB(TAU,TAD,NE,NGS12,NGS4,MXS,N45,IPODT)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.   P R O G R A M
CE.      TO INITIAL VALUE MATRIX - B
CS.   P R O G R A M
CS.      ZA ZADAVANJE POCETNE JEDINICNE VREDNOSTI ZA MATRICU - B
C .
C ......................................................................
C
      DIMENSION TAU(N45,NGS12,NE,*),TAD(N45,NGS4,NE,*)
C
      DO 10 J=1,MXS
      DO 10 I=1,NE
         DO 20 K=1,NGS12
            IF(N45.EQ.6) THEN
               TAU(1,K,I,J)=1.D0
               TAU(2,K,I,J)=1.D0
               TAU(3,K,I,J)=1.D0
            ELSE
               TAU(1,K,I,J)=1.D0
               TAU(5,K,I,J)=1.D0
               TAU(9,K,I,J)=1.D0
            ENDIF
   20    CONTINUE
         IF(IPODT.EQ.4) THEN
            DO 30 K=1,NGS4
               IF(N45.EQ.6) THEN
                  TAD(1,K,I,J)=1.D0
                  TAD(2,K,I,J)=1.D0
                  TAD(3,K,I,J)=1.D0
               ELSE
                  TAD(1,K,I,J)=1.D0
                  TAD(5,K,I,J)=1.D0
                  TAD(9,K,I,J)=1.D0
               ENDIF
   30       CONTINUE
         ENDIF
   10 CONTINUE
      RETURN
      END
