C=======================================================================
C
C   PLASTICNOST LJUSKE  -  MESOVITO OJACANJE    (17.10.1992)
C
C=======================================================================
      SUBROUTINE D4M14(TAU,DEF,TGT,IRAC,LPOCG,LPOC1,IND3D)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
CE  SPACE IN WORKING VECTOR 
C
      include 'paka.inc'
      
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /REPERM/ MREPER(4)
      COMMON /DUPLAP/ IDVA
C
      LFUN=MREPER(1)
      LNTA=MREPER(2)
      LTEM=MREPER(3)
      MATE=MREPER(4)
      LTAU  =LPOCG
      LDEFT =LTAU   + 6*IDVA
      LDEFPT=LDEFT  + 6*IDVA
      LALFAT=LDEFPT + 6*IDVA
      LTEQT =LALFAT + 6*IDVA
      LDQPT =LTEQT  + 1*IDVA
      LIPL  =LDQPT  + 1*IDVA
C
      LTAU1 =LPOC1
      LDEFT1=LTAU1  + 6*IDVA
      LDEFP1=LDEFT1 + 6*IDVA
      LALFA1=LDEFP1 + 6*IDVA
      LTEQT1=LALFA1 + 6*IDVA
      LDQPT1=LTEQT1 + 1*IDVA
      LIPL1 =LDQPT1 + 1*IDVA
C
      CALL TI414(A(LIPL),A(LDEFPT),A(LALFAT),A(LTEQT),A(LDQPT),
     1            A(LIPL1),A(LTAU1),A(LDEFT1),A(LDEFP1),A(LALFA1),
     1            A(LTEQT1),A(LDQPT1),
     1            A(LFUN),MATE,TAU,DEF,TGT,A(LTEM),A(LNTA),IRAC,IND3D)
C
      RETURN
      END
C=======================================================================
      SUBROUTINE TI414( PL ,DEFPT,ALFAT,TEMT,DEFQPT,
     1                   PL1,TAU1,DEF1,DEFP, ALFA1, TEM, DEFQP,
     1                   FUN,MATE,TAU,DEF,TGT,TREF,NTFUN,IRAC,IND3D)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
CE   THERMO-ELASTOPLASTIC MATERIAL , MIXED HARDENING
C
      COMMON /IZLE4B/ H(9,3),GM(3,9),BLT(6,54),BE(9,54),ETP(6,6),UEL(54)
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /TAUD3/ TAUD(6),DEFDPR(6),DEFDS(6),DDEFP(6),
     1                DETAU(6),DDEF(6)
      COMMON /ELEMEN/ ELAST(6,6),XJ(3,3),ALFA(6),TEMP0,DET,NLM,KK
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /KOREKJ/ AJOT
      COMMON /SRPSKI/ ISRPS
      COMMON /MATIZO/ E,V
      COMMON /COEFSM/ COEF(3),ICOEF
      COMMON /VELIKE/ LCOR0,LGM0,JG,NGR,NGS,NGT,NGS4
      COMMON /CEPMAT/ INDCEP
      COMMON /PERKOR/ LNKDT,LDTDT,LVDT,NDT,DT,VREME,KOR
      COMMON /ITERBR/ ITER
      DIMENSION DEFPT(*),TAU(*),DEF(*),TAU1(*),DEF1(*),
     1          DEFP(*),ALFAT(*),ALFA1(*),SHET(6),GLITL(6),ETHERM(3)
      DIMENSION FUN(4,MATE*4,*),TREF(*),NTFUN(*),COEFE(2)
      DATA ITMAX/100/,EPSIL/1.0D-10/
C      COEFE(1)=0.833333333D0
      COEFE(1)=COEF(1)
      COEFE(2)=COEF(2)
C
CE  INITIAL DATA
C
      IPL =PL
C
CE  E,V,ALFA,TEQY0,CY,AN,TEMP0,EM
C
      MAT4=(MAT-1)*4
      MATE4=MATE*4
      DO 6 J=1,4
        NFE=MAT4+J
        CALL BTAB(FUN,NTFUN,NFE,MATE4,TGT,NL,IND,4)
        IF (IND.EQ.2) GO TO 300
        IF (IND.EQ.1) THEN
          EVA=FUN(2,NFE,1)
        ELSE
          AMU=TGT-FUN(1,NFE,NL)
          DEN=FUN(1,NFE,NL+1)-FUN(1,NFE,NL)
          EVA=((FUN(2,NFE,NL+1)-FUN(2,NFE,NL))/DEN)*AMU+FUN(2,NFE,NL)
        END IF
        IF (J.EQ.1) E   = EVA
        IF (J.EQ.2) V = EVA
        IF (J.EQ.3) THEN
          DO 7 K=1,3
    7       ALFA(K) = EVA
        END IF
        IF (J.EQ.4) THEN
          TEQY0=EVA
          IF (IND.EQ.1) THEN
            CY=FUN(3,NFE,1)
            AN=FUN(4,NFE,1)
          ELSE
            CY=((FUN(3,NFE,NL+1)-FUN(3,NFE,NL))/DEN)*AMU+FUN(3,NFE,NL)
            AN=((FUN(4,NFE,NL+1)-FUN(4,NFE,NL))/DEN)*AMU+FUN(4,NFE,NL)
          END IF
        END IF
    6 CONTINUE
      TEMP0 =TREF(MAT)
      EM    =FUN(3,MAT4+1,1)
C
C      HS    =FUN(1,MAT,4)
      HS=0.
      ISIMO=0
      IF(DABS(HS).GT.1.D-10) ISIMO=1
C
CE    AUXILIARY CONSTANTS
C
      DVT =2.D0/3.
      C1    =(2.-V)/3./(1.-V)
      CNI   =1.-C1
      CYAN23=DVT*CY*AN
      EM1   =1.-EM
      AN1   =AN-1.
      AN2   =AN-2.
      AE    =(1.+V)/E
      AEINV =1./AE
      CM    =E/(1.-2.*V)
      C3    =DVT*(1.+V)
C
      AE5   =AE/COEFE(2)
      AE6   =AE/COEFE(1)
      BA    =1.5/E
C
CE    YIELD STRESS
C     NAPON TECENJA (2.3.38)
      TEQY=TEQY0+CY*(EM*DEFQPT)**AN
C     MATRICA ETP NE SME SE KORIGOVATI SA COEFE
      CALL MEL96(COEFE,ETP,1,IND3D)
      IF(IRAC.EQ.2) RETURN
      CALL CLEAR(TAU,6)
C
CE    THERMAL STRAIN
C
      TEM=TGT
      IF(ITER.EQ.0) TGT=TGT-TEMT
      CALL STERM3(ETHERM,TGT)
      ETH = ETHERM(1)
C     ZA ITER=0, TERMICKE SILE ZA POMERANJA OD TERMICKIH DEFORACIJA
      IF(ITER.EQ.0) GO TO 900
C
C... TRANSFORM ENGENEER. SHEAR STRAIN INTO TENSORIAL
C
      DO 5 I=4,6
    5 DEFPT(I)=0.5*DEFPT(I)
C
C     D E V I A T O R I C   STRAIN, ESEKUNDUM
C     ELASTICNE DEFORMACIJE, (PROBNA RESENJA ZA DDEFQP=0)
      IF(IATYP.LT.4)THEN
C       SREDNJA ELASTICNA DEFORMACIJA (2.3.69) (ZA DDEFQP=0)
        EMT=(1.-2.*V)*(DEF(3)-DEFPT(3)-ETH)/3.+ETH
C       PROBNE DEVIJATORSKE ELASTICNE DEFORMACIJE (2.3.71)
        DEFDS(3)=C3*(DEF(3)-DEFPT(3)-ETH)
        DO 10 I=5,6
   10   DEFDS(I)=0.5*DEF(I)-DEFPT(I)
      ELSE
        EMT = (1.-2.*V)*(DEF(3))/3.
        DEFDS(3)= DEF(3)
        DO 11 I=5,6
   11   DEFDS(I)=0.5*DEF(I)
      ENDIF
        DEFDS(1)=-0.5*DEFDS(3)
        DEFDS(2)=-0.5*DEFDS(3)
        DEFDS(4)= 0.
C
CE   1)  ELASTIC DEVIATORIC STRESS SOLUTION  (TAUD) , (GLITL), (SHET)
C
      DO 40 I=1,6
C     SHET/2G - ZA GREDU
      GLITL(I)=DEFDS(I)-AE*ALFAT(I)
C     PROBNI ELASTICNI DEVIJATORSKI NAPONI (2.3.54)
      TAUD(I) =DEFDS(I)*AEINV
C     PROBNI ELASTICNI RADIJUS NAPONI (2.3.74)
   40 SHET(I) =TAUD(I)-ALFAT(I)
C
CE   2)  CHECK FOR YIELDING
C     PROBNI EFEKTIVNI ELASTICNI RADIJUS NAPON (2.3.50)
      TEQ=DSQRT(1.5*TENDOT(SHET))
C      WRITE(3,*) 'ITER,JG,EMT',ITER,JG,EMT
C      WRITE(3,*) 'TEQY,TEQ',TEQY,TEQ
C      CALL WRR6(TAU,6,'TAU0')
C      CALL WRR6(DEF,6,'DEFU')
C      CALL WRR6(DEFPT,6,'DFPT')
C      CALL WRR6(ALFAT,6,'ALFT')
C      CALL WRR6(DEFDS,6,'DFDS')
C      CALL WRR6(GLITL,6,'GTL0')
C      CALL WRR6(TAUD,6,'TAD0')
C      CALL WRR6(SHET,6,'SHE0')
C     PROVERA TECENJA (2.3.49)
      IF((TEQ-TEQY)/TEQY.LT.1.D-5)THEN
C       ELASTICNA OBLAST
        TEQ  =TEQY
        DEFQP=DEFQPT
        DO 600 I=1,6
  600   DEFP(I)=DEFPT(I)
        GO TO 500
      ENDIF
C
CE   3)   SOLUTION IS ELASTO-PLASTIC.  OBTAIN ZERO OF THE ESF.
C     ELASTO-PLASTICNA OBLAST 
      PL1=1.0D0
C
CE    BISECTION
C     ODREDJIVANJE GRANICA ZA DDEFQP
      DEFQP=DEFQPT
      IF(DEFQP.LE.1.D-4) DEFQP=1.D-4
      IF(ISIMO.EQ.0)THEN
        EP2=AN*CY*DEFQP**AN1      
      ELSE
        EP2=AN*CY*DEXP(-AN*DEFQP)+HS
      ENDIF
C
      IB = 0
      IT = 0
      AF    = 5.D0
      DDD   = 0.1*(TEQ-TEQY)/EP2
      FP    = TEQ - TEQY
      TAUY  = TEQY
      FM    = 0.D0
      DEPBM = 0.D0
      DEPBP = 0.D0
C     PROBNO RESENJE ZA DDEFQP A DOBICE SE RESAVANJEM FUNKCIJE TECENJA
      DDEFQP= DDD
  100 IT=IT+1
      IB1 = IB
C
      IF(IT.GT.ITMAX) THEN
        IF (ISRPS.EQ.0) WRITE(IZLAZ,2000)
        IF (ISRPS.EQ.1) WRITE(IZLAZ,6000)
        WRITE(IZLAZ,2001)NLM,NGR,NGS,NGT
        STOP
      ENDIF
C
C     EFEKTIVNA PLASTICNA DEFORMACIJA (2.3.57)
      DEFQP=DEFQPT+DDEFQP
      IF(ISIMO.EQ.0)THEN
C       MODUL (2.3.29)
        CC=CYAN23*DEFQP**AN1
C       MODUL (2.3.46) ILI (2.3.30)
        EM1CC =EM1*CC
      ELSE
        CC=CYAN23*DEXP(-AN*DEFQP)+DVT*HS
        EM1CC =EM1*CC
      ENDIF
C
        TAUY=TEQY0+CY*(EM*DEFQP)**AN
        DLAM=1.5*DDEFQP/TAUY
        SHET(3)=GLITL(3)/(AE+(C3+EM1CC*AE)*DLAM)
        SHET(5)=GLITL(5)/(AE+(1.+EM1CC*AE)*DLAM)
        SHET(6)=GLITL(6)/(AE+(1.+EM1CC*AE)*DLAM)
        SHET(1)=-0.5*SHET(3)
        SHET(2)=-0.5*SHET(3)
        SHET(4)= 0.
        TEQ =DSQRT(1.5*TENDOT(SHET))
        FB = TEQ-TAUY
C
C      WRITE(3,*) 'IT,FP,FB',IT,FP,FB
C      WRITE(3,*) 'FM,AF',FM,AF
C      WRITE(3,*) 'DEPBM,DEPBP',DEPBM,DEPBP
C      WRITE(3,*) 'DDD,DEFQPT',DDD,DEFQPT
C      WRITE(3,*) 'DEFQP,DDEFQP',DEFQP,DDEFQP
      CALL BISEC (DDEFQP,DEPBM,DEPBP,DDD,FB,FM,FP,AF,IB)
      IF (IB1.EQ.0) GO TO 100
      IF (DABS(DDD).GT.EPSIL.AND.
     1    (DABS(DDD)/(DEPBM+DEPBP)).GT.EPSIL) GO TO 100
C
CE      ...   ( DEVIATORIC STRESS )
C
      DUM =1.+EM1CC*DLAM
      DO 165 I=1,6
C     DEVIJATORSKI NAPON (2.3.43)
  165 TAUD(I)=ALFAT(I)+DUM*SHET(I)
C
CE   4)  DETERMINE SOLUTION 
C
C
CE      ...   ( PLASTIC STRAIN ), ( BACK STRESS )
C
      DO 170 I=1,6
C       PRIRASTAJ PLASTICNE DEFORMACIJE U KORAKU (2.3.19)
        DDEFPS  =DLAM*SHET(I)
C       UKUPNE PLASTICNE DEFORMACIJE (2.3.39)
        DEFP(I) =DEFPT(I)+DDEFPS
C       POLOZAJNI NAPONI (2.3.42)
        ALFA1(I)=ALFAT(I)+EM1CC*DDEFPS
  170 CONTINUE
C
      IF(IATYP.LT.4)THEN
C       SREDNJA ELASTICNA DEFORMACIJA (2.3.69)
        EMT=(1.-2.*V)*(DEF(3)-DEFP(3)-ETH)/3.+ETH
      ELSE
        EMT=(1.-2.*V)*(DEF(3))/3.
      ENDIF
C      WRITE(3,*) ' DLAM,TEQ',DLAM,TEQ
C      CALL WRR6(SHET,6,'SHET')
C      CALL WRR6(TAUD,6,'TAUD')
C      CALL WRR6(DEFP,6,'DEFP')
C      CALL WRR6(ALFA1,6,'ALF1')
C
CE     E L A S T I C  -  P L A S T I C   M A T R I X   CEP
C
      IF(ISKNP.NE.2) THEN
C        GLITL ODGOVARA 3D ELEMENTU A NE GREDI
         IF(IATYP.LT.4)THEN
            GLITL(3)=DEF(3)-EMT-DEFPT(3)-AE*ALFAT(3)
            GLITL(1)=-0.5*GLITL(3)
            GLITL(2)=GLITL(1)
            GLITL(5)=0.5*DEF(5)-DEFPT(5)-AE*ALFAT(5)
            GLITL(6)=0.5*DEF(6)-DEFPT(6)-AE*ALFAT(6)
            GLITL(4)=0.
         ELSE
            GLITL(3)=DEF(3)-EMT-AE*ALFAT(3)
            GLITL(1)=-0.5*GLITL(3)
            GLITL(2)=GLITL(1)
            GLITL(5)=0.5*DEF(5)-AE*ALFAT(5)
            GLITL(6)=0.5*DEF(6)-AE*ALFAT(6)
            GLITL(4)=0.
         ENDIF
         IF(INDCEP.EQ.0)
     1      CALL CEP96(GLITL,DLAM,TEQ,DEFQP,DDEFQP,EM,AE,CM,CC,CY,AN,
     &                 HS,ISIMO)
C         IF(INDCEP.NE.0)
C     1      CALL CEP46(SHET,DLAM,TEQ,DEFQP,E,EM,AE5,AE6,BA,CC,CY,AN)
C         CALL WRR6(ETP,36,'ETP ')
      ENDIF
C
CE   5)    CALCULATE STRESS
C
  500 CONTINUE
      IF(IATYP.LT.4)THEN
C       SREDNJI NAPON (2.3.6)
        TAUM=CM*(EMT-ETH)
      ELSE
C       TAUM=
      ENDIF
C     NAPONI NA KRAJU KORAKA (2.3.56)
C      TAU(1)=0.D0
C      TAU(2)=0.D0
C      TAU(3)=1.5*TAUD(3)
      DO 45 I=1,3
   45 TAU(I)=TAUD(I)+TAUM
      TAU(4)=0.D0
      DO 46 I=5,6
      TAU(I)=TAUD(I)
   46 DEFP(I)=2.*DEFP(I)
C
CE  UPDATE FROM PREVIOUS STEP
C
      IF(IATYP.LT.4)THEN
C       UKUPNE DEFORMACIJE U RAVNI PRESEKA (2.3.75)
        DEF(1)=-V*(DEF(3)-DEFP(3)-ETH)+DEFP(1)+ETH
        DEF(2)=-V*(DEF(3)-DEFP(3)-ETH)+DEFP(2)+ETH
      ELSE
        DEF(1)=-V*DEF(3)
        DEF(2)=-V*DEF(3)
      ENDIF
  900 IF(ITER.EQ.0) THEN
         CALL JEDNA1(TAU,TAU1,6)
         ETH=ETH*E
         TAU(3)=TAU(3)-ETH
      ENDIF
      DO 290 I=1,6
      DEF1(I)=DEF(I)
  290 TAU1(I)=TAU(I)
C      WRITE(3,*) 'TAUM,EMT',TAUM,EMT
C      CALL WRR6(DEF1,6,'DEF1')
C      CALL WRR6(TAU1,6,'TAU1')
      RETURN
  300 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2005) NFE,TGT
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6005) NFE,TGT
      STOP
C-----------------------------------------------------------------------
 2001 FORMAT( ' ELEMENT =',I6,'  IR =',I2,'  IS =',I2,'  IT =',I2)
 2000 FORMAT(/' DOSTIGNUT MAKSIMALAN BROJ BISEKCIJA U TAUI46')
 2005 FORMAT(///' ARGUMENT VAN OPSEGA ZADATE KRIVE U TI414'/
     1' TEMPERATURSKA FUNKCIJA BROJ =',I5/
     2' ARGUMENT TEMPERATURA =',1PD12.4)
C-----------------------------------------------------------------------
 6000 FORMAT(/' MAXIMUM NUMBER OF BISECTION IS REACHED IN TAUI46')
 6005 FORMAT(///' ARGUMENT IS OUT OF RANGE IN TI414'/
     1' TEMPERATURE FUNCTION  =',I5/
     2' ARGUMENT TEMPERATURE  =',1PD12.4)
C-----------------------------------------------------------------------
      END
