C=======================================================================
C
C   SUBROUTINE S92NAP
C              S92NP1
C              STNG99
C              STA925
C              SGR929
C=======================================================================
      SUBROUTINE S92NAP
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
CS     GLAVNI PROGRAM ZA POZIVANJE PROGRAMA ZA STAMPANJE KONTAKTNIH SILA
CS     2/D KONTAKT ELEMENATA
CE     MAIN PROGRAM FOR PRINTOUT CONTACT FORCES
CE     2/D CONTACT ELEMENTS
C
      include 'paka.inc'
      
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEM99/ MXAU,LAU,LLMEL,LNEL,LNMAT,LAPRS,LIPGC,LIPRC,LISNA,
     1                LBETA
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /ZAPISI/ LSTAZA(5)
      COMMON /DUPLAP/ IDVA
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      EQUIVALENCE (IETYP,NTSF),(NGAUSX,NTTOT),(LNMAT,LNCVSF),
     &            (LIPRC,LITSRF),(LIPGC,LNELSF),(LLMEL,LIDC),
     &            (LIK,LPLAST),(LIK1,LPLAS1),(LBETA,LFSFD)
      COMMON /CDEBUG/ IDEBUG
      IF(IDEBUG.GT.0) PRINT *, ' S92NAP'
C
      LAU=LMAX
CS     UCITAVANJE PODATAKA O ELEMENTIMA I SILAMA SA DISKA
CE     READ DATA FROM DISK 
      CALL RD92(A(LAU),4)
CS     PODPROGRAM ZA STAMPANJE SILA/NAPONA
CE     PRINT STRESS
      IF(MOD(LMAX,2).EQ.0) LMAX=LMAX+1
      LAE=LMAX
      IOK=0
      IF(INDPR.EQ.0.OR.INDPR.EQ.2) CALL S92NP1(A(LAU),A(LAE),IOK)
CS     STAMPANJE ZA POSTPROCESIRANJE
CE     PRINT FOR POSTPROCESSING 
      IF(INDGR.EQ.0.OR.INDGR.EQ.2) CALL STNG99(A(LAU),A(LAE),IOK)
      RETURN
      END
C======================================================================
      SUBROUTINE S92NP1(AU,AE,IOK)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      include 'paka.inc'
      
      COMMON /ELEM99/ MXAU,LAU,LLMEL,LNEL,LNMAT,LAPRS,LIPGC,LIPRC,LISNA,
     1                LBETA
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /TEMPCV/ LTECV,ITEMP
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /UPDLAG/ LUL,LCORUL
      COMMON /DUPLAP/ IDVA
      EQUIVALENCE (LNMAT,LNCVSF),(LIPRC,LITSRF),(LIPGC,LNELSF),
     &            (LIK1,LPLAS1)
      DIMENSION AU(*),AE(*)
      REAL AU
      COMMON /CDEBUG/ IDEBUG
      IF(IDEBUG.GT.0) PRINT *, ' S92NP1'
CS     PRERACUNAVANJE ZA SLUCAJ OSNE SIMETRIJE
CE     RECALCULATE FOR AXISYMETRIC CASE
      LPR=LSIGMA
      IF(IATYP.EQ.2.OR.IATYP.EQ.3)THEN
        IOK=1
        LS =1
        LPR=LS+(2*NE+1)*IDVA
        IF(IATYP.EQ.3) LPR=LPR+NE*IDVA
        LMX=LPR+2*NE*IDVA
        CALL AXI99(A(LSIGMA),AU(LNCVSF),AU(LITSRF),AU(LNELSF),AU(LNEL),
     &             A(LCORUL),AE(LS),AE(LMX),AE(LPR),A(LIK1))
      ENDIF
C
      CALL STA925(A(LSIGMA),AE(LPR),AU(LNCVSF),AU(LITSRF),AU(LNELSF),
     &            AU(LNEL),AU(LISNA),A(LIK1),A(LCVEL),ICVEL)
      RETURN
      END
C======================================================================
      SUBROUTINE STNG99(AU,AE,IOK)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      include 'paka.inc'
      
      COMMON /ELEM99/ MXAU,LAU,LLMEL,LNEL,LNMAT,LAPRS,LIPGC,LIPRC,LISNA,
     1                LBETA
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /TEMPCV/ LTECV,ITEMP
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /UPDLAG/ LUL,LCORUL
      COMMON /DUPLAP/ IDVA
      EQUIVALENCE (LNMAT,LNCVSF),(LIPRC,LITSRF),(LIPGC,LNELSF),
     &            (LIK1,LPLAS1)
      DIMENSION AU(*),AE(*)
      REAL AU
      COMMON /CDEBUG/ IDEBUG
      IF(IDEBUG.GT.0) PRINT *, ' STNG99'
CS     PRERACUNAVANJE ZA SLUCAJ OSNE SIMETRIJE
CE     RECALCULATE FOR AXISYMETRIC CASE
      IF(IOK.EQ.0.AND.(IATYP.EQ.2.OR.IATYP.EQ.3))THEN
        LS =1
        LPR=LS+(2*NE+1)*IDVA
        IF(IATYP.EQ.3) LPR=LPR+NE*IDVA
        LMX=LPR+2*NE*IDVA
        CALL AXI99(A(LSIGMA),AU(LNCVSF),AU(LITSRF),AU(LNELSF),AU(LNEL),
     &             A(LCORUL),AE(LS),AE(LMX),AE(LPR),A(LIK1))
      ENDIF
C
      CALL SGR925(A(LSIGMA),AU(LNCVSF),AU(LITSRF),AU(LNELSF),AU(LNEL),
     &            A(LCVEL),NE,ICVEL,IGRAF)
      RETURN
      END
C======================================================================
      SUBROUTINE STA925(RC,PR,NCVSF,ITSRF,NELSF,NEL,ISNA,IK,NCVEL,ICVEL)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /SRPSKI/ ISRPS
C
      EQUIVALENCE (IETYP,NTSF)
      DIMENSION NCVSF(*),ITSRF(*),NELSF(*),NEL(NE,*),PR(NE,*),
     1          RC(2,*),IK(*),ISNA(*),NCVEL(*)
      COMMON /CDEBUG/ IDEBUG
      DATA IT1/1000000/
      IF(IDEBUG.GT.0) PRINT *, ' STA925'
C
C  PETLJA PO KONTAKTNIM CVOROVIMA
C
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2010)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6010)
      DO 10 NLM=1,NE
        IC=NEL(NLM,1)
        IF(ICVEL.NE.0) IC=NCVEL(IC)
        IND =IK(NLM)/IT1
        NCAA=IK(NLM)-IND*IT1
        WRITE(IZLAZ,1000) IC,(RC(J,NLM),J=1,2),IND,NCAA
   10 CONTINUE
C
      IF(IATYP.EQ.2.OR.IATYP.EQ.3)THEN
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2015)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6015)
      DO 20 NLM=1,NE
        IC=NEL(NLM,1)
        IF(ICVEL.NE.0) IC=NCVEL(IC)
        IND =IK(NLM)/IT1
        NCAA=IK(NLM)-IND*IT1
        WRITE(IZLAZ,1000) IC,(PR(NLM,J),J=1,2),IND,NCAA
   20 CONTINUE
      ENDIF
C
C  PETLJA PO CILJNIM POVRSINAMA
C
      INDSN=0
      DO 30 ITS=1,NTSF
      ISN=ISNA(ITS)
      IF(ISN.NE.0) GO TO 30
      IF(ISRPS.EQ.0.AND.INDSN.EQ.0)
     1WRITE(IZLAZ,2020)
      IF(ISRPS.EQ.1.AND.INDSN.EQ.0)
     1WRITE(IZLAZ,6020)
      INDSN=1
C
C  ITS - CILJNI SEGMENT, NNC - BROJ CVOROVA SEGMENTA
      NNC =NCVSF(ITS)
      LL  =IABS(ITSRF(ITS))-1
      NELL=NE+LL
      RX=0.D0
      RY=RX
      DO 28 NC=1,NNC
      IC=NELSF(LL+NC)
      IF(ICVEL.NE.0) IC=NCVEL(IC)
      WRITE(IZLAZ,1000) IC,(RC(J,NELL+NC),J=1,2)
      RX=RX+RC(1,NELL+NC)
      RY=RY+RC(2,NELL+NC)
   28 CONTINUE
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2030) ITS,RX,RY
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6030) ITS,RX,RY
   30 CONTINUE
      RETURN
 1000 FORMAT(I5,5X,2D12.4,3X,I5,5X,I5)
C-----------------------------------------------------------------------
 2010 FORMAT('1'/' CVOR  BR.',6X,'S I L E   N A   K O N T A K T N I M   
     1 C V O R O V I M A'/16X,'SILA-X      SILA-Y    STATUS',
     2 '   PODSEGMENT')
 2015 FORMAT('1'/' CVOR  BR.',3X,'P R I T I S C I   N A    K O N T A K T
     1 N I M   C V O R O V I M A'/15X,'PRIT.-X     PRIT.-Y    STATUS',
     2 '   PODSEGMENT')
 2020 FORMAT('1'/' CVOR  BR.',6X,'S I L E   N A   C I L J N I M    S E',
     1' G M E N T I M A'/16X,'SILA-X      SILA-Y')
 2030 FORMAT(/'  SEGMENT :',I5/'  REZULTUJUCE SILE   SILA-X = ',1PD12.4,
     1'  SILA-Y = ',1PD12.4)
 6010 FORMAT('1'/' CVOR  BR.',6X,'S I L E   N A   K O N T A K T N I M   
     1 C V O R O V I M A'/16X,'SILA-X      SILA-Y    STATUS',
     2 '   PODSEGMENT')
 6015 FORMAT('1'/' CVOR  BR.',3X,'P R I T I S C I   N A    K O N T A K T
     1 N I M   C V O R O V I M A'/15X,'PRIT.-X     PRIT.-Y    STATUS',
     2 '   PODSEGMENT')
 6020 FORMAT('1'/' CVOR  BR.',6X,'S I L E   N A   C I L J N I M    S E',
     1' G M E N T I M A'/16X,'SILA-X      SILA-Y')
 6030 FORMAT(/'  SEGMENT :',I5/'  REZULTUJUCE SILE   SILA-X = ',1PD12.4,
     1'  SILA-Y = ',1PD12.4)
C-----------------------------------------------------------------------
      END
C======================================================================
      SUBROUTINE SGR925(RC,NCVSF,ITSRF,NELSF,NEL,NCVEL,NE,ICVEL,II)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.   PROGRAM
CE.      TO PRINT CONTACT FORCES IN UNIVERZAL FILE
CS.   PROGRAM
CS.      ZA STAMPANJE KONTAKTNIH SILA U UNIVERZALNI FILE
C .
C ......................................................................
C
      CHARACTER*250 NASLOV
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /PERKOR/ LNKDT,LDTDT,LVDT,NDT,DT,VREME,KOR
      COMMON /NASLOV/ NASLOV
      COMMON /SRPSKI/ ISRPS
      COMMON /CDEBUG/ IDEBUG
      EQUIVALENCE (IETYP,NTSF)
      DIMENSION NCVSF(*),ITSRF(*),NELSF(*),NEL(NE,*),RC(2,*),NCVEL(*)
C
      IF(IDEBUG.GT.0) PRINT *, ' SGR925'
CE    STRUCTURAL ANALYSIS = 1
CS    STRUKTURNA ANALIZA = 1
      IMOTY=1
CE    STEADY STATE = 1; TRANSIENT = 4
CS    STACIONARAN = 1; NESTACIONARAN = 4
      IFAT2=1
      IANTY=4
      IFAT1=2
      FATY8=VREME
      IDACH=3
CE    EXCITATION/CONTACT FORCES = 13
CS    POBUDNE/KONTAKTNE SILE = 13
      ISDTY=13
CE    SINGLE PRECISION = 2; DOUBLE PRECISION = 4
CS    PRECIZNOST JEDNOSTRUKA = 2; DVOSTRUKA = 4
      IDATY=2
CE    NUMBER DATA = 2
CS    BROJ PODATAKA = 2
      NDVPN=2
      IND1=-1
      ITYP=55
      WRITE(II,5100) IND1
      WRITE(II,5100) ITYP
      WRITE(II,5003) NASLOV
      WRITE(II,2005)
      WRITE(II,2004) KOR
      WRITE(II,5000) IMOTY,IANTY,IDACH,ISDTY,IDATY,NDVPN
      WRITE(II,5000) IFAT1,IFAT2,KOR
      WRITE(II,5200) FATY8
      DO 10 NLM=1,NE
      IC=NEL(NLM,1)
      IF(ICVEL.EQ.0) THEN
        WRITE(II,5000) IC
      ELSE
        WRITE(II,5000) NCVEL(IC)
      ENDIF
      WRITE(II,5200) (RC(J,NLM),J=1,2)
   10 CONTINUE
C
C  PETLJA PO CILJNIM POVRSINAMA
C
      DO 30 ITS=1,NTSF
      NNC =NCVSF(ITS)
      LL  =IABS(ITSRF(ITS))-1
      NELL=NE+LL
      DO 28 NC=1,NNC
      IC=NELSF(LL+NC)
      IF(ICVEL.EQ.0) THEN
        WRITE(II,5000) IC
      ELSE
        WRITE(II,5000) NCVEL(IC)
      ENDIF
      WRITE(II,5200) (RC(J,NELL+NC),J=1,2)
   28 CONTINUE
   30 CONTINUE
      WRITE(II,5100) IND1
      RETURN
C
 5100 FORMAT(I6)
 5003 FORMAT(A80)
 5000 FORMAT(8I10)
 5200 FORMAT(6(1PE13.5))
C-----------------------------------------------------------------------
 2005 FORMAT(' KONTAKTNE SILE')
 2004 FORMAT('DATUM I VREME'/
     1       'PRAZNA'/
     1       'SLUCAJ OPTERECENJA:',I10)
C-----------------------------------------------------------------------
C 6005 FORMAT(' CONTACT FORCES')
C 6004 FORMAT('DATE AND TIME'/
C     1       'EMPTY '/
C     1       'LOAD CASE NUMBER  :',I10)
C-----------------------------------------------------------------------
      END
C======================================================================
      SUBROUTINE AXI99(RC,NCVSF,ITSRF,NELSF,NEL,CORD,S,MX,PR,IK)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      COMMON /GLAVNI/ NP,NGELEM,NMATM,NPER,
     1                IOPGL(6),KOSI,NDIN,ITEST
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /AXISYM/ INDAX
      COMMON /SRPSKI/ ISRPS
C
      EQUIVALENCE (IETYP,NTSF)
      DIMENSION NCVSF(*),ITSRF(*),NELSF(*),NEL(NE,*),RC(2,*),CORD(NP,*),
     &          S(*),MX(*),PR(NE,*),IK(*)
      COMMON /CDEBUG/ IDEBUG
      IF(IDEBUG.GT.0) PRINT *, ' AXI99'
C
C  PETLJA PO KONTAKTNIM CVOROVIMA
C
      DO 20 NLM=1,NE
      IC=NEL(NLM,1)
      DO 20 J=1,2
   20 PR(NLM,J)=RC(J,NLM)
      MX(1)=1
      MX(2)=2
      DO 25 NLM=3,NE+1
   25 MX(NLM)=MX(NLM-1)+2
      IF(IATYP.EQ.3) MX(NE+1)=MX(NE+1)+NE-1
C...  PRVI PODSEGMENT
      IC0 =NEL(1,1)
      IC  =NEL(2,1)
      DX  =CORD(IC0,1)-CORD(IC,1)
      DY  =CORD(IC0,2)-CORD(IC,2)
      DJ1 =DSQRT(DX*DX+DY*DY)/6.D0
      IF(INDAX.EQ.0)THEN
       S(1)=2.D0*DJ1
       DUM1=DJ1
       DUM2=S(1)
      ELSE
       DJ1 =0.5D0*DJ1
       S(1)=DJ1*(3.D0*CORD(IC0,1)+CORD(IC,1))
       DUM1=DJ1*(CORD(IC0,1)+CORD(IC,1))
       DUM2=DJ1*(CORD(IC0,1)+3.D0*CORD(IC,1))
      ENDIF
      IBR=1
C...  DRUGI DO PREDZADNJEG PODSEGMENTA
      DO 30 NLM=2,NE-1
        IC1 =NEL(NLM+1,1)
        DX  =CORD(IC1,1)-CORD(IC,1)
        DY  =CORD(IC1,2)-CORD(IC,2)
        DJ  =DSQRT(DX*DX+DY*DY)/6.D0
      IF(INDAX.EQ.0)THEN
        IBR=IBR+1
        S(IBR)=2.D0*(DJ1+DJ)
        IBR=IBR+1
        IF(IK(NLM-1).EQ.0.OR.IK(NLM).EQ.0)THEN
          S(IBR)=0.D0
        ELSE
          S(IBR)=DJ1
        ENDIF
      ELSE
        DJ  =0.5D0*DJ
        IBR=IBR+1
        S(IBR)=DJ1*(CORD(IC0,1)+3.D0*CORD(IC,1))+
     &         DJ *(3.D0*CORD(IC,1)+CORD(IC1,1))
        IBR=IBR+1
        IF(IK(NLM-1).EQ.0.OR.IK(NLM).EQ.0)THEN
          S(IBR)=0.D0
        ELSE
          S(IBR)=DJ1*(CORD(IC0,1)+CORD(IC,1))
        ENDIF
      ENDIF
        DJ1=DJ
        IC0=IC
        IC =IC1
   30 CONTINUE
C...  ZADNJI PODSEGMENT
      IF(INDAX.EQ.0)THEN
       IBR=IBR+1
       S(IBR)=2.D0*DJ1
       IBR=IBR+1
       IF(IK(NE-1).EQ.0.OR.IK(NLM).EQ.0)THEN
         S(IBR)=0.D0
       ELSE
         S(IBR)=DJ1
       ENDIF
      ELSE
       IBR=IBR+1
       S(IBR)=DJ1*(CORD(IC0,1)+3.D0*CORD(IC,1))
       IBR=IBR+1
       IF(IK(NE-1).EQ.0.OR.IK(NLM).EQ.0)THEN
         S(IBR)=0.D0
       ELSE
         S(IBR)=DJ1*(CORD(IC0,1)+CORD(IC,1))
       ENDIF
      ENDIF
C...  SLUCAJ ZATVORENE KONTURE
      IF(IATYP.EQ.3.AND.NE.GT.2)THEN
        S(1)  =S(1)+S(IBR-1)
        S(IBR-1)=S(IBR-1)+DUM2
        IBR=IBR+NE-2
        S(IBR)=DUM1
      ENDIF
C...  FAKTORIZACIJA
      CALL RESENA(S,PR,MX,NE,IZLAZ,1)
C...  RESENJA ZA PRITISKE
      CALL RESENA(S,PR(1,1),MX,NE,IZLAZ,2)
      CALL RESENA(S,PR(1,2),MX,NE,IZLAZ,2)
C
C  PETLJA PO CILJNIM POVRSINAMA
C
C  ITS - CILJNI SEGMENT, NNC - BROJ CVOROVA SEGMENTA
      IF(INDAX.NE.0)THEN
      DO 50 ITS=1,NTSF
      NNC =NCVSF(ITS)
      LL  =IABS(ITSRF(ITS))-1
      NELL=NE+LL
      DO 40 NC=1,NNC
      IC=NELSF(LL+NC)
       DO 40 J=1,2
   40  IF(CORD(IC,1).GT.1.D-6) RC(J,NELL+NC)=RC(J,NELL+NC)/CORD(IC,1)
   50 CONTINUE
      ENDIF
      RETURN
      END
