C=======================================================================
C
C   SUBROUTINE S93NAP
C              S93NP1
C              STNG93
C              STA93
C              SGR93
C=======================================================================
      SUBROUTINE S93NAP
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
CS     GLAVNI PROGRAM ZA POZIVANJE PROGRAMA ZA STAMPANJE KONTAKTNIH SILA
CS     3/D KONTAKT ELEMENATA
CE     MAIN PROGRAM FOR PRINTOUT CONTACT FORCES
CE     3/D CONTACT ELEMENTS
C
      include 'paka.inc'
      
      COMMON /DUZINA/ LMAX,MTOT,LMAXM,LRAD,NRAD
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /ORIENT/ CPP(3,3),XJJ(3,3),TSG(6,6),BETA,LBET0,IBB0
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /ZAPISI/ LSTAZA(5)
      COMMON /DUPLAP/ IDVA
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /KONTK3/ FMSTAT,FMDIN,EPSIL,NTSF,NTTOT,LNCVSF,LITSRF,
     &                LNELSF,LIDC,LIK,LIK1,LFSFD,LMASE,LNELAB,NWKCDY
      COMMON /CDEBUG/ IDEBUG
      IF(IDEBUG.GT.0) PRINT *, ' S92NAP'
C
      LAU=LMAX
CS     UCITAVANJE PODATAKA O ELEMENTIMA I SILAMA SA DISKA
CE     READ DATA FROM DISK 
      CALL RD93(A(LAU),4)
CS     PODPROGRAM ZA STAMPANJE SILA/NAPONA
CE     PRINT STRESS
      IF(MOD(LMAX,2).EQ.0) LMAX=LMAX+1
      LAE=LMAX
      IOK=0
      IF(INDPR.EQ.0.OR.INDPR.EQ.2) CALL S93NP1(A(LAU),A(LAE),IOK)
CS     STAMPANJE ZA POSTPROCESIRANJE
CE     PRINT FOR POSTPROCESSING 
      IF(INDGR.EQ.0.OR.INDGR.EQ.2) CALL STNG93(A(LAU),A(LAE),IOK)
      RETURN
      END
C======================================================================
      SUBROUTINE S93NP1(AU,AE,IOK)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      include 'paka.inc'
      
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /ORIENT/ CPP(3,3),XJJ(3,3),TSG(6,6),BETA,LBET0,IBB0
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /UPDLAG/ LUL,LCORUL
      COMMON /DUPLAP/ IDVA
      COMMON /KONTK3/ FMSTAT,FMDIN,EPSIL,NTSF,NTTOT,LNCVSF,LITSRF,
     &                LNELSF,LIDC,LIK,LIK1,LFSFD,LMASE,LNELAB,NWKCDY
      DIMENSION AU(*),AE(*)
      REAL AU
      COMMON /CDEBUG/ IDEBUG
      IF(IDEBUG.GT.0) PRINT *, ' S93NP1'
      LPR=LSIGMA
      CALL STA935(A(LSIGMA),AE(LPR),AU(LNCVSF),AU(LITSRF),AU(LNELSF),
     &            AU(LNELAB),AU(LNEL),AU(LISNA),A(LIK1),A(LCVEL),ICVEL)
      RETURN
      END
C======================================================================
      SUBROUTINE STNG93(AU,AE,IOK)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      include 'paka.inc'
      
      COMMON /ELEMAU/ MXAU,LAU,LLMEL,LNEL,LNMAT,LTHID,LIPGC,LIPRC,LISNA,
     1 LMXAU,LAPRS
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /CVOREL/ ICVEL,LCVEL,LELCV,NPA,NPI,LCEL,LELC,NMA,NMI
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /PLASTI/ LPLAST,LPLAS1,LSIGMA
      COMMON /UPDLAG/ LUL,LCORUL
      COMMON /KONTK3/ FMSTAT,FMDIN,EPSIL,NTSF,NTTOT,LNCVSF,LITSRF,
     &                LNELSF,LIDC,LIK,LIK1,LFSFD,LMASE,LNELAB,NWKCDY
      COMMON /DUPLAP/ IDVA
      DIMENSION AU(*),AE(*)
      REAL AU
      COMMON /CDEBUG/ IDEBUG
      IF(IDEBUG.GT.0) PRINT *, ' STNG93'
      CALL SGR935(A(LSIGMA),AU(LNCVSF),AU(LITSRF),AU(LNELSF),AU(LNEL),
     &            A(LCVEL),NE,ICVEL,IGRAF)
      RETURN
      END
C======================================================================
      SUBROUTINE STA935(RC,PR,NCVSF,ITSRF,NELSF,NELAB,
     &                  NEL,ISNA,IK,NCVEL,ICVEL)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /ELEALL/ NETIP,NE,IATYP,NMODM,NGE,ISKNP,LMAX8
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /KONTK3/ FMSTAT,FMDIN,EPSIL,NTSF,NTTOT,LNCVSF,LITSRF,
     &                LNELSF,LIDC,LIK,LIK1,LFSFD,LMASE,LNELAB,NWKCDY
      COMMON /SRPSKI/ ISRPS
C
      DIMENSION NCVSF(*),ITSRF(*),NELSF(NCVE,*),NEL(NE,*),PR(NE,*),
     1          RC(3,*),IK(*),ISNA(*),NCVEL(*),NELAB(NCVE,*),RXYZ(3)
     2,SUKUPNA(3)
      COMMON /CDEBUG/ IDEBUG
      DATA IT1/1000000/
      CHARACTER*6 IMD
      IF(IDEBUG.GT.0) PRINT *, ' STA935'
C
C  PETLJA PO KONTAKTNIM CVOROVIMA
C
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2010)
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6010)
	SUKUPNA(1)=0.D0
	SUKUPNA(2)=0.D0
	SUKUPNA(3)=0.D0
      DO 10 NLM=1,NE
        IC=NEL(NLM,1)
        IF(ICVEL.NE.0) IC=NCVEL(IC)
        IND =IK(NLM)/IT1
        NCAA=IK(NLM)-IND*IT1
        WRITE(IZLAZ,1000) IC,(RC(J,NLM),J=1,3),IND,NCAA
	  DO J=1,3
	   SUKUPNA(J)=SUKUPNA(J)+RC(J,NLM)
	  ENDDO
   10 CONTINUE
C
C              ZAPISIVANJE UKUPNIH KONTAKTNIH SILA
               IDUM=38
               IMD='ZCFORC'
              OPEN (IDUM,FILE=IMD,STATUS='UNKNOWN',FORM='FORMATTED',
     1               ACCESS='SEQUENTIAL')
       WRITE(38,2021)
       WRITE(38,1001) (SUKUPNA(J),J=1,3)
C
C  PETLJA PO CILJNIM POVRSINAMA
C
      INDSN=0
      DO 30 ITS=1,NTSF
      MAXCE=ISNA(ITS)
      IF(ISRPS.EQ.0.AND.INDSN.EQ.0)
     1WRITE(IZLAZ,2020)
      IF(ISRPS.EQ.1.AND.INDSN.EQ.0)
     1WRITE(IZLAZ,6020)
      INDSN=1
C
      IF(ISRPS.EQ.0)
     1WRITE(IZLAZ,2030) ITS
      IF(ISRPS.EQ.1)
     1WRITE(IZLAZ,6030) ITS
C
      NNC =NCVSF(ITS)
      LL  =IABS(ITSRF(ITS))-1
      DO 20 I=1,3
   20 RXYZ(I)=0.D0
      DO 40 JJ=1,NNC
      WRITE(IZLAZ,1000)JJ
      NCA=LL+JJ
       DO 27 NN=1,MAXCE
        NELL=NE+NELAB(NN,NCA)
        IC=NELSF(NN,NCA)
        IF(ICVEL.NE.0) IC=NCVEL(IC)
        WRITE(IZLAZ,1000) IC,(RC(J,NELL),J=1,3)
   27  CONTINUE
   40 CONTINUE
CC      DO 25 I=1,3
CC   25 RXYZ(I)=RXYZ(I)+RC(I,NELL)
   30 CONTINUE
       WRITE(IZLAZ,2021)
       WRITE(IZLAZ,1001) (SUKUPNA(J),J=1,3)
      RETURN
 1000 FORMAT(I5,5X,3D12.4,2X,I5,5X,I5)
 1001 FORMAT(5X,3D12.4)
C-----------------------------------------------------------------------
 2010 FORMAT('1'/' CVOR  BR.',6X,'S I L E   N A   K O N T A K T N I M   
     1 C V O R O V I M A'/16X,'SILA-X      SILA-Y      SILA-Z   STATUS',
     2 '   PODSEGMENT')
 2020 FORMAT('1'/' POLIGON /',6X,'S I L E   N A   C I L J N I M    C V',
     1' O R O V I M A'/' CVOR  BR.',6X,'SILA-X      SILA-Y      SILA-Z')
 2021 FORMAT(5X,'U K U P N A  K O N T A K T N A  S I L A')
 2030 FORMAT(/'  SEGMENT :',I5)
 6010 FORMAT('1'/' NODE  NO.',6X,'F O R C E   O N   C O N T A C T    N O 
     1 D E S'/16X,'FORCE-X     FORCE-Y     FORCE-Z  STATUS',
     2 '   SUBSEGMENT')
 6020 FORMAT('1'/' POLYGON /',6X,'F O R C E   O N   T A R G E T    N O',
     1' D E S'/' NODE  NO.',6X,'FORCE-X     FORCE-Y     FORCE-Z')
 6030 FORMAT(/'  SEGMENT :',I5)
C-----------------------------------------------------------------------
      END
C======================================================================
      SUBROUTINE SGR935(RC,NCVSF,ITSRF,NELSF,NEL,NCVEL,NE,ICVEL,II)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.   PROGRAM
CE.      TO PRINT CONTACT FORCES IN UNIVERZAL FILE
CS.   PROGRAM
CS.      ZA STAMPANJE KONTAKTNIH SILA U UNIVERZALNI FILE
C .
C ......................................................................
C
      CHARACTER*250 NASLOV
      COMMON /ELEIND/ NGAUSX,NGAUSY,NGAUSZ,NCVE,ITERME,MAT,IETYP
      COMMON /PERKOR/ LNKDT,LDTDT,LVDT,NDT,DT,VREME,KOR
      COMMON /NASLOV/ NASLOV
      COMMON /SRPSKI/ ISRPS
      COMMON /KONTK3/ FMSTAT,FMDIN,EPSIL,NTSF,NTTOT,LNCVSF,LITSRF,
     &                LNELSF,LIDC,LIK,LIK1,LFSFD,LMASE,LNELAB,NWKCDY
      COMMON /CDEBUG/ IDEBUG
      DIMENSION NCVSF(*),ITSRF(*),NELSF(*),NEL(NE,*),RC(3,*),NCVEL(*)
C
      IF(IDEBUG.GT.0) PRINT *, ' SGR935'
CE    STRUCTURAL ANALYSIS = 1
CS    STRUKTURNA ANALIZA = 1
      IMOTY=1
CE    STEADY STATE = 1; TRANSIENT = 4
CS    STACIONARAN = 1; NESTACIONARAN = 4
      IFAT2=1
      IANTY=4
      IFAT1=2
      FATY8=VREME
      IDACH=3
CE    EXCITATION/CONTACT FORCES = 13
CS    POBUDNE/KONTAKTNE SILE = 13
      ISDTY=13
CE    SINGLE PRECISION = 2; DOUBLE PRECISION = 4
CS    PRECIZNOST JEDNOSTRUKA = 2; DVOSTRUKA = 4
      IDATY=2
CE    NUMBER DATA = 2
CS    BROJ PODATAKA = 2
      NDVPN=2
      IND1=-1
      ITYP=55
      WRITE(II,5100) IND1
      WRITE(II,5100) ITYP
      WRITE(II,5003) NASLOV
      IF(ISRPS.EQ.0)THEN
        WRITE(II,2005)
        WRITE(II,2004) KOR
      ELSE
        WRITE(II,6005)
        WRITE(II,6004) KOR
      ENDIF
      WRITE(II,5000) IMOTY,IANTY,IDACH,ISDTY,IDATY,NDVPN
      WRITE(II,5000) IFAT1,IFAT2,KOR
      WRITE(II,5200) FATY8
      DO 10 NLM=1,NE
      IC=NEL(NLM,1)
      IF(ICVEL.EQ.0) THEN
        WRITE(II,5000) IC
      ELSE
        WRITE(II,5000) NCVEL(IC)
      ENDIF
      WRITE(II,5200) (RC(J,NLM),J=1,3)
   10 CONTINUE
C
C  PETLJA PO CILJNIM POVRSINAMA
C
CC      DO 30 ITS=1,NTSF
CC      NNC =NCVSF(ITS)
CC      LL  =IABS(ITSRF(ITS))-1
CC      NELL=NE+LL
CC      DO 28 NC=1,NNC
CC      IC=NELSF(LL+NC)
CC      IF(ICVEL.EQ.0) THEN
CC        WRITE(II,5000) IC
CC      ELSE
CC        WRITE(II,5000) NCVEL(IC)
CC      ENDIF
CC      WRITE(II,5200) (RC(J,NELL+NC),J=1,3)
CC   28 CONTINUE
CC   30 CONTINUE
      WRITE(II,5100) IND1
      RETURN
C
 5100 FORMAT(I6)
 5003 FORMAT(A80)
 5000 FORMAT(8I10)
 5200 FORMAT(6(1PE13.5))
C-----------------------------------------------------------------------
 2005 FORMAT(' KONTAKTNE SILE')
 2004 FORMAT('DATUM I VREME'/
     1       'PRAZNA'/
     1       'SLUCAJ OPTERECENJA:',I10)
C-----------------------------------------------------------------------
 6005 FORMAT(' CONTACT FORCES')
 6004 FORMAT('DATE AND TIME'/
     1       'EMPTY '/
     1       'LOAD CASE NUMBER  :',I10)
C-----------------------------------------------------------------------
      END
