C=======================================================================
C
C=======================================================================
      SUBROUTINE sloba1(RTH,ID,NCVEL,ICVEL,NP,KOR,VREME,IND,NCVP,NCVPR,
     1                 CORD,NELCV)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CS.   PROGRAM
CS.      ZA STAMPANJE rezultata merenja za slobu
C .
C ......................................................................
C
      include 'paka.inc'

      CHARACTER*50    IME
      
      COMMON /GRUPEE/ NGEL,NGENL,LGEOM,NGEOM,ITERM
      COMMON /ITERBR/ ITER
      COMMON /ECLANM/ AMAXK,AMINK,AMAXF,AMINF
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /OPSTIP/ JPS,JPBR,NPG,JIDG,JCORG,JCVEL,JELCV,NGA,NGI,NPK,
     1                NPUP,LIPODS,IPODS,LMAX13,MAX13,JEDNG,JMAXA,JEDNP,
     1                NWP,NWG,IDF,JPS1
      COMMON /ITERAC/ METOD,MAXIT,TOLE,TOLS,TOLM,KONVE,KONVS,KONVM
      COMMON /SRPSKI/ ISRPS
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
      COMMON /MAXREZ/ PMALL,BMALL,AMALL,SMKOR,SMALL,
     +                NPMALL,NBMALL,NAMALL,KPMALL,KBMALL,KAMALL,
     +                NSMKOR,NSMALL,NGRKOR,NGRALL,KSMALL
      COMMON /AUTSTP/ DTUK,ALFG,DELS,IAUTO,ITEOPT,KPNOD,KPDIR,KEQ
      COMMON /AUTST2/ PARAM(5)
      COMMON /AUTSTK/ DELUM,DELFM,KRAJP
      COMMON /GEORGE/ TOLG,ALFAG,ICCGG
      COMMON /MESLESS/ IGBM,ndif,idif(50),NKI,IKI(10)
      COMMON /MATIZO/ E,V
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /CDEBUG/ IDEBUG
      COMMON /BOCACP1/ DP(19)
      COMMON /OPITSL/ VPOMER,SNAPON,OPOVRS,ICVOR(4),IOPITS
      COMMON /SLOBAR/ IOPIT
      COMMON /SLOBAP/ NSLOB(3,1000),NPSLOB
      DIMENSION RTH(*),ID(NP,*),NCVEL(*),NCVP(*),FSP(6),CORD(NP,*),
     1          NELCV(*),DL(19),PA(3),PB(3),PC(3),PD(3),V1(3),V2(3),
     1          P1(3),P2(3),P3(3)
C
      IF(IDEBUG.GT.0) PRINT *, ' sloba1'
C
      I90=90
      IF(KOR.EQ.1) THEN
         IF(IOPIT.EQ.1) IME='TS_SSG1_1PAK.csv'
         IF(IOPIT.EQ.2) IME='TS_SSG1_2PAK.csv'
         IF(IOPIT.EQ.3) IME='TS_SSG1_3PAK.csv'
         IF(IOPIT.EQ.4) IME='TS_SSG1_4PAK.csv'
         IF(IOPIT.EQ.5) IME='TS_BSG1_1PAK.csv'
         IF(IOPIT.EQ.6) IME='TS_BSG1_2PAK.csv'
         IF(IOPIT.EQ.7) IME='TS_BSG1_3PAK.csv'
         IF(IOPIT.EQ.8) IME='TS_BSG1_4PAK.csv'
         IF(IOPIT.EQ.9) IME='TP_HJG1_1PAK.csv'
         IF(IOPIT.EQ.10) IME='TP_VJG1_1PAK.csv'
         IF(IOPIT.EQ.11) IME='TS_SSG2_1PAK.csv'
         IF(IOPIT.EQ.12) IME='TS_SSG2_2PAK.csv'
         IF(IOPIT.EQ.13) IME='TS_SSG2_3PAK.csv'
         IF(IOPIT.EQ.14) IME='TS_SSG2_4PAK.csv'
         IF(IOPIT.EQ.15) IME='TS_SSG2_5PAK.csv'
         IF(IOPIT.EQ.16) IME='TP_VJG2_1PAK.csv'
         IF(IOPIT.EQ.17) IME='TS_BSG3_1PAK.csv'
         IF(IOPIT.EQ.18) IME='TS_BSG3_2PAK.csv'
         IF(IOPIT.EQ.19) IME='TS_BSG3_3PAK.csv'
         IF(IOPIT.EQ.20) IME='TS_BSG3_4PAK.csv'
         IF(IOPIT.EQ.21) IME='TP_VJG3_1PAK.csv'
         IF(IOPIT.EQ.22) IME='TS_SSG4_1PAK.csv'
         IF(IOPIT.EQ.23) IME='TS_SSG4_2PAK.csv'
         IF(IOPIT.EQ.24) IME='TS_SSG4_3PAK.csv'
         IF(IOPIT.EQ.25) IME='TS_BSG4_1PAK.csv'
         IF(IOPIT.EQ.26) IME='TS_BSG4_2PAK.csv'
         IF(IOPIT.EQ.27) IME='TS_BSG4_3PAK.csv'
         IF(IOPIT.EQ.28) IME='TP_VJG4_1PAK.csv'
         IF(IOPIT.EQ.29) IME='TS_BSG5_1PAK.csv'
         IF(IOPIT.EQ.30) IME='TS_BSG5_2PAK.csv'
         IF(IOPIT.EQ.31) IME='TS_BSG5_3PAK.csv'
         IF(IOPIT.EQ.32) IME='TS_BSG5_4PAK.csv'
         IF(IOPIT.EQ.33) IME='TP_VJG5_1PAK.csv'
         IF(IOPIT.EQ.34) IME='TS_SSG6_1PAK.csv'
         IF(IOPIT.EQ.35) IME='TS_SSG6_2PAK.csv'
         IF(IOPIT.EQ.36) IME='TS_SSG6_3PAK.csv'
         IF(IOPIT.EQ.37) IME='TP_VJG6_1PAK.csv'
         OPEN (I90,FILE=IME,STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(IOPIT.EQ.10.OR.IOPIT.EQ.16.OR.IOPIT.EQ.21.OR.
     1   IOPIT.EQ.28.OR.IOPIT.EQ.33.OR.IOPIT.EQ.37) THEN
         WRITE(I90,*) '  Koraci,     dV(mm),       dVo(mm)'
      ELSE
         WRITE(I90,*) '  Koraci,     dV(mm),       Tzy(MN)'
      ENDIF
      ENDIF
      
C     SS
      IF((IOPIT.GE.1.AND.IOPIT.LE.4).OR.(IOPIT.GE.11.AND.IOPIT.LE.15).OR
     1  .(IOPIT.GE.22.AND.IOPIT.LE.24).OR.(IOPIT.GE.34.AND.IOPIT.LE.36))
     2                                                              THEN
         WRITE(*,*) 'IOPIT=',IOPIT
         ICVOR(1)=2101
         ICVOR(2)=3328
      ENDIF
C     BS
      IF((IOPIT.GE.5.AND.IOPIT.LE.8).OR.(IOPIT.GE.17.AND.IOPIT.LE.20).OR
     1  .(IOPIT.GE.25.AND.IOPIT.LE.27).OR.(IOPIT.GE.29.AND.IOPIT.LE.32))
     2                                                              THEN
         WRITE(*,*) 'IOPIT=',IOPIT
         ICVOR(1)=2131
         ICVOR(2)=3790
      ENDIF
C     HJ
      IF(IOPIT.EQ.9) THEN
         WRITE(*,*) 'IOPIT=',IOPIT
         ICVOR(1)=3575
         ICVOR(2)=3575
      ENDIF
C     VJ
      IF(IOPIT.EQ.10.OR.IOPIT.EQ.16.OR.IOPIT.EQ.21.OR.
     1   IOPIT.EQ.28.OR.IOPIT.EQ.33.OR.IOPIT.EQ.37) THEN
         WRITE(*,*) 'IOPIT=',IOPIT
         ICVOR(1)=2023
         ICVOR(2)=3570
         UPOV=0.
         UZAP=0.
         DO II=1,NPSLOB
            IF(ICVEL.EQ.0) THEN
               N1=NSLOB(1,II)
               N2=NSLOB(2,II)
               N3=NSLOB(3,II)
            ELSE
               N1=NELCV(NSLOB(1,II))
               N2=NELCV(NSLOB(2,II))
               N3=NELCV(NSLOB(3,II))
            ENDIF
         DO 11 J=1,3
            P1(J) = 0.D0
            KA=ID(N1,J)
            IF(KA.EQ.0) GO TO 11
            IF(KA.GT.0)THEN
               P1(J)=RTH(KA)
            ELSE
               P1(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KA)
            ENDIF
   11    CONTINUE
         DO 12 J=1,3
            P2(J) = 0.D0
            KA=ID(N2,J)
            IF(KA.EQ.0) GO TO 12
            IF(KA.GT.0)THEN
               P2(J)=RTH(KA)
            ELSE
               P2(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KA)
            ENDIF
   12    CONTINUE
         DO 13 J=1,3
            P3(J) = 0.D0
            KA=ID(N3,J)
            IF(KA.EQ.0) GO TO 13
            IF(KA.GT.0)THEN
               P3(J)=RTH(KA)
            ELSE
               P3(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KA)
            ENDIF
   13    CONTINUE
            DO JJ=1,3
               V1(JJ)=CORD(N2,JJ)-CORD(N1,JJ)
               V2(JJ)=CORD(N3,JJ)-CORD(N1,JJ)
            ENDDO
            CALL AXBVI(V1,V2,D)
            UPOV=UPOV+D
            UZAP=UZAP+D*(P1(1)+P2(1)+P3(1))/3.
         ENDDO
         VPOMER=-1000.*UZAP/UPOV
      ENDIF
C      
            IF(ICVEL.EQ.0) THEN
               NA=ICVOR(1)
               NB=ICVOR(2)
            ELSE
               NA=NELCV(ICVOR(1))
               NB=NELCV(ICVOR(2))
            ENDIF
         DO 10 J=1,3
            PA(J) = 0.D0
            KA=ID(NA,J)
            IF(KA.EQ.0) GO TO 10
            IF(KA.GT.0)THEN
               PA(J)=RTH(KA)
            ELSE
               PA(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KA)
            ENDIF
   10    CONTINUE
         DO 20 J=1,3
            PB(J) = 0.D0
            KB=ID(NB,J)
            IF(KB.EQ.0) GO TO 20
            IF(KB.GT.0)THEN
               PB(J)=RTH(KB)
            ELSE
               PB(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KB)
            ENDIF
   20    CONTINUE

      IF(IOPIT.EQ.10.OR.IOPIT.EQ.16.OR.IOPIT.EQ.21.OR.
     1   IOPIT.EQ.28.OR.IOPIT.EQ.33.OR.IOPIT.EQ.37) THEN
         PAQ=DSQRT(PA(2)*PA(2)+PA(3)*PA(3))
         PBQ=DSQRT(PB(2)*PB(2)+PB(3)*PB(3))
         SNAPON=1000.*(PAQ+PBQ)/2.
      ELSE
         VPOMER=-1000.*(PA(3)+PB(3))/2.
      ENDIF
C
      IF(IOPIT.EQ.9) THEN
         WRITE(I90,5000) KOR,VPOMER
      ELSE
         WRITE(I90,5000) KOR,VPOMER,SNAPON
      ENDIF
C
      RETURN
C
 5000 FORMAT(' ',I5,2F15.6)
C-----------------------------------------------------------------------
      END
C=======================================================================
C
C=======================================================================
      SUBROUTINE BOCAC1(RTH,ID,NCVEL,ICVEL,NP,KOR,VREME,IND,NCVP,NCVPR,
     1                 CORD,NELCV)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CS.   PROGRAM
CS.      ZA STAMPANJE MERNE TABELE ZA TUNEL BOCAC ZA PROFIL 1; 92m
C .
C ......................................................................
C
      include 'paka.inc'
      
      COMMON /GRUPEE/ NGEL,NGENL,LGEOM,NGEOM,ITERM
      COMMON /ITERBR/ ITER
      COMMON /ECLANM/ AMAXK,AMINK,AMAXF,AMINF
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /OPSTIP/ JPS,JPBR,NPG,JIDG,JCORG,JCVEL,JELCV,NGA,NGI,NPK,
     1                NPUP,LIPODS,IPODS,LMAX13,MAX13,JEDNG,JMAXA,JEDNP,
     1                NWP,NWG,IDF,JPS1
      COMMON /ITERAC/ METOD,MAXIT,TOLE,TOLS,TOLM,KONVE,KONVS,KONVM
      COMMON /SRPSKI/ ISRPS
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
      COMMON /MAXREZ/ PMALL,BMALL,AMALL,SMKOR,SMALL,
     +                NPMALL,NBMALL,NAMALL,KPMALL,KBMALL,KAMALL,
     +                NSMKOR,NSMALL,NGRKOR,NGRALL,KSMALL
      COMMON /AUTSTP/ DTUK,ALFG,DELS,IAUTO,ITEOPT,KPNOD,KPDIR,KEQ
      COMMON /AUTST2/ PARAM(5)
      COMMON /AUTSTK/ DELUM,DELFM,KRAJP
      COMMON /GEORGE/ TOLG,ALFAG,ICCGG
      COMMON /MESLESS/ IGBM,ndif,idif(50),NKI,IKI(10)
      COMMON /MATIZO/ E,V
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /CDEBUG/ IDEBUG
      COMMON /BOCACP1/ DP(19)
      DIMENSION RTH(*),ID(NP,*),NCVEL(*),NCVP(*),FSP(6),cord(np,*),
     1          NELCV(*),DL(19)
C
      IF(IDEBUG.GT.0) PRINT *, ' BOCAC'
C
C
      NA1=288349
      NB1=290741
      NC1=297048
      ND1=303317
      NE1=305034
c
      I90=90
      IF(KOR.EQ.1) THEN
         OPEN (I90,FILE='BOCPOM.POM',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
         WRITE(I90,*) '  METAR, NA1XYZ, NB1XYZ, NC1XYZ, ND1XYZ, NE1XYZ'
      ENDIF
      CALL NPOMER1(NA1,NB1,NC1,ND1,NE1,ICVEL,NELCV,ID,RTH,NP,I90,VREME)
C
      TPROF1=53.
      IF(VREME.LT.TPROF1) RETURN
      STAC=145.5001-VREME


C
      NBE111=263081
      NBE112=272672
      NBE113=279537
C
      NBE121=297147
      NBE122=297162
      NBE123=297372
C
      NBE131=338271
      NBE132=328920
      NBE133=314222
C
      KPROF=INT(VREME-TPROF1)
C     RACUNANJE POCETNIH DUZINA ZA KONVERGENCIJU
      II=99
      IF(KPROF.EQ.0) THEN
         OPEN (II,FILE='BOCAC1.POM',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
         WRITE(II,*) '    CELO, A1B1L0, A1C1L0, A1D1L0, A1E1L0,',
     1      ' B1C1L0, B1D1L0, D1C1L0,E1B1L0, E1C1L0, E1D1L0,   ',
     1      ' A111L0, A112L0, A113L0, C121L0, C122L0, C123L0,',
     1      ' E131L0, E132L0, E133L0'
         CALL MERKONV(NA1,NB1,DP(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NC1,DP(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,ND1,DP(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NE1,DP(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB1,NC1,DP(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB1,ND1,DP(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND1,NC1,DP(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NB1,DP(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NC1,DP(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,ND1,DP(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA1,NBE111,DP(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NBE112,DP(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NBE113,DP(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC1,NBE121,DP(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC1,NBE122,DP(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC1,NBE123,DP(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE1,NBE131,DP(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NBE132,DP(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NBE133,DP(19),ICVEL,NELCV,ID,RTH,CORD,NP)
c      WRITE(II,5000) (DP(I),I=1,19)
 5000 FORMAT(' DP0',10(1PE15.8))
      ENDIF
C
         CALL MERKONV(NA1,NB1,DL(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NC1,DL(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,ND1,DL(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NE1,DL(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB1,NC1,DL(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB1,ND1,DL(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND1,NC1,DL(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NB1,DL(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NC1,DL(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,ND1,DL(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA1,NBE111,DL(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NBE112,DL(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA1,NBE113,DL(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC1,NBE121,DL(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC1,NBE122,DL(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC1,NBE123,DL(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE1,NBE131,DL(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NBE132,DL(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE1,NBE133,DL(19),ICVEL,NELCV,ID,RTH,CORD,NP)

c      WRITE(II,5001) (DP(I),I=1,19)
 5001 FORMAT(' DP',10(1PE15.8))
c      WRITE(II,5002) (DL(I),I=1,19)
 5002 FORMAT(' DL',10(1PE15.8))
      DO 30 I=1,19
         DL(I)=(DL(I)-DP(I))*1000.
   30 CONTINUE
      WRITE(II,5100) STAC,(DL(I),I=1,19)
C
      RETURN
C
c 5100 FORMAT(' ',F9.3,10(1PE15.8))
 5100 FORMAT(' ',F9.3,10(F8.3),3x,9(F8.3))
C-----------------------------------------------------------------------
      END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE NPOMER1(NA1,NB1,NC1,ND1,NE1,ICVEL,NELCV,ID,RTH,NP,II,
     1                   VREME)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      include 'paka.inc'
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
C
      DIMENSION RTH(*),ID(NP,*),NELCV(*),PA(3),PB(3),PC(3),PD(3),PE(3)
C
            IF(ICVEL.EQ.0) THEN
               NA=NA1
               NB=NB1
               NC=NC1
               ND=ND1
               NE=NE1
            ELSE
               NA=NELCV(NA1)
               NB=NELCV(NB1)
               NC=NELCV(NC1)
               ND=NELCV(ND1)
               NE=NELCV(NE1)
            ENDIF
         DO 10 J=1,3
            PA(J) = 0.D0
            KA=ID(NA,J)
            IF(KA.EQ.0) GO TO 10
            IF(KA.GT.0)THEN
               PA(J)=RTH(KA)
            ELSE
               PA(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KA)
            ENDIF
   10    CONTINUE
         DO 20 J=1,3
            PB(J) = 0.D0
            KB=ID(NB,J)
            IF(KB.EQ.0) GO TO 20
            IF(KB.GT.0)THEN
               PB(J)=RTH(KB)
            ELSE
               PB(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KB)
            ENDIF
   20    CONTINUE
         DO 30 J=1,3
            PC(J) = 0.D0
            KC=ID(NC,J)
            IF(KC.EQ.0) GO TO 30
            IF(KC.GT.0)THEN
               PC(J)=RTH(KC)
            ELSE
               PC(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KC)
            ENDIF
   30    CONTINUE
         DO 40 J=1,3
            PD(J) = 0.D0
            KD=ID(ND,J)
            IF(KD.EQ.0) GO TO 40
            IF(KD.GT.0)THEN
               PD(J)=RTH(KD)
            ELSE
               PD(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KD)
            ENDIF
   40    CONTINUE
         DO 50 J=1,3
            PE(J) = 0.D0
            KE=ID(NE,J)
            IF(KE.EQ.0) GO TO 50
            IF(KE.GT.0)THEN
               PE(J)=RTH(KE)
            ELSE
               PE(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KE)
            ENDIF
   50    CONTINUE
         DO 60 J=1,3
            PA(J)=PA(J)*1000
            PB(J)=PB(J)*1000
            PC(J)=PC(J)*1000
            PD(J)=PD(J)*1000
            PE(J)=PE(J)*1000
   60    CONTINUE
         METAR=INT(VREME)
      WRITE(II,5100) METAR,(PA(I),I=1,3),(PB(I),I=1,3),(PC(I),I=1,3),
     1                     (PD(I),I=1,3),(PE(I),I=1,3)
C
      RETURN
C
 5100 FORMAT(' ',I5,5(2X,3(F9.3)))
         RETURN
         END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE MERKONV(NA1,NB1,A1B1L0,ICVEL,NELCV,ID,RTH,CORD,NP)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      include 'paka.inc'
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
C
      DIMENSION RTH(*),ID(NP,*),cord(np,*),NELCV(*),PA(3),PB(3)
C
            IF(ICVEL.EQ.0) THEN
               NA=NA1
               NB=NB1
            ELSE
               NA=NELCV(NA1)
               NB=NELCV(NB1)
            ENDIF
         DO 10 J=1,3
            PA(J) = 0.D0
            KA=ID(NA,J)
            IF(KA.EQ.0) GO TO 10
            IF(KA.GT.0)THEN
               PA(J)=RTH(KA)
            ELSE
               PA(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KA)
            ENDIF
   10    CONTINUE
         DO 20 J=1,3
            PB(J) = 0.D0
            KB=ID(NB,J)
            IF(KB.EQ.0) GO TO 20
            IF(KB.GT.0)THEN
               PB(J)=RTH(KB)
            ELSE
               PB(J)=CONDOF(RTH,A(LCMPC),A(LMPC),KB)
            ENDIF
   20    CONTINUE
            DX=CORD(NB,1)+PB(1)-CORD(NA,1)-PA(1)
            DY=CORD(NB,2)+PB(2)-CORD(NA,2)-PA(2)
            DZ=CORD(NB,3)+PB(3)-CORD(NA,3)-PA(3)
            A1B1L0=DSQRT(DX*DX+DY*DY+DZ*DZ)
         RETURN
         END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE BOCACN1(TA,TED,JG,NLM,MCVEL,ICVEL,KOR,VREME)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /BOCACS1/ TAUS(6,8,6),TAUM(6,8,6),TAU0(6,8,6)
      DIMENSION NEL1(6),TED(6,*),TA(*),MCVEL(*)
       
      TPROF1=53.
      IF(VREME.LT.TPROF1) RETURN
      STAC=145.5001-VREME
C
       NEL1(1)=449573
       NEL1(2)=449613
       NEL1(3)=449657
         NMM=NLM
         IF(ICVEL.EQ.1) NMM=MCVEL(NLM)
         DO 11 NC=1,3
         IF(NMM.EQ.NEL1(NC)) GO TO 12
   11    CONTINUE
         RETURN
C
   12 KPROF=INT(VREME-TPROF1)
C     OTVARANJE FAJLA ZA ZAPISIVANJE NAPONA KOJI SE MERE
      IF(NMM.EQ.NEL1(1)) II=91
      IF(NMM.EQ.NEL1(2)) II=92
      IF(NMM.EQ.NEL1(3)) II=93
      IF(KPROF.EQ.0) THEN
      IF(JG.EQ.1) THEN
      IF(NMM.EQ.NEL1(1))
     1   OPEN (II,FILE='BOCAC1.P11',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL1(2))
     1   OPEN (II,FILE='BOCAC1.P12',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL1(3))
     1   OPEN (II,FILE='BOCAC1.P13',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      ENDIF
C
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5103) STAC,NEL1(NC),JG,(TA(I),I=1,6)
 5103 FORMAT('0GL',F9.3,I7,I3,6(1PE12.4))
            DO 20 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAU0(I,JG,NC),0,I)
   20       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5101) STAC,NEL1(NC),JG,(TAU0(I,JG,NC),I=1,6)
 5101 FORMAT('0LO',F9.3,I7,I3,6(1PE12.4))
      ENDIF
C
C      WRITE(II,5104) STAC,NEL1(NC),JG,(TA(I),I=1,6)
 5104 FORMAT(' GL',F9.3,I7,I3,6(1PE12.4))
            DO 21 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAUS(I,JG,NC),0,I)
               TAUM(I,JG,NC)=(TAUS(I,JG,NC)-TAU0(I,JG,NC))/1000.
   21       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5100) STAC,NEL1(NC),JG,(TAUS(I,JG,NC),I=1,6)
 5100 FORMAT(' LO',F9.3,I7,I3,6(1PE12.4))
      IF((NMM.EQ.NEL1(1).AND.JG.EQ.8).OR.
     1   (NMM.EQ.NEL1(2).AND.JG.EQ.8).OR.
     1   (NMM.EQ.NEL1(3).AND.JG.EQ.7))
     1WRITE(II,5105) STAC,NEL1(NC),JG,(TAUM(I,JG,NC),I=1,6)
 5105 FORMAT(' LM',F9.3,I7,I3,6(1PE12.4))
C
      RETURN
C-----------------------------------------------------------------------
      END
C=======================================================================
C=======================================================================
C=======================================================================
      SUBROUTINE BOCAC2(RTH,ID,NCVEL,ICVEL,NP,KOR,VREME,IND,NCVP,NCVPR,
     1                 CORD,NELCV)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CS.   PROGRAM
CS.      ZA STAMPANJE MERNE TABELE ZA TUNEL BOCAC ZA PROFIL 2; 80m
C .
C ......................................................................
C
      include 'paka.inc'
      
      COMMON /GRUPEE/ NGEL,NGENL,LGEOM,NGEOM,ITERM
      COMMON /ITERBR/ ITER
      COMMON /ECLANM/ AMAXK,AMINK,AMAXF,AMINF
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /OPSTIP/ JPS,JPBR,NPG,JIDG,JCORG,JCVEL,JELCV,NGA,NGI,NPK,
     1                NPUP,LIPODS,IPODS,LMAX13,MAX13,JEDNG,JMAXA,JEDNP,
     1                NWP,NWG,IDF,JPS1
      COMMON /ITERAC/ METOD,MAXIT,TOLE,TOLS,TOLM,KONVE,KONVS,KONVM
      COMMON /SRPSKI/ ISRPS
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
      COMMON /MAXREZ/ PMALL,BMALL,AMALL,SMKOR,SMALL,
     +                NPMALL,NBMALL,NAMALL,KPMALL,KBMALL,KAMALL,
     +                NSMKOR,NSMALL,NGRKOR,NGRALL,KSMALL
      COMMON /AUTSTP/ DTUK,ALFG,DELS,IAUTO,ITEOPT,KPNOD,KPDIR,KEQ
      COMMON /AUTST2/ PARAM(5)
      COMMON /AUTSTK/ DELUM,DELFM,KRAJP
      COMMON /GEORGE/ TOLG,ALFAG,ICCGG
      COMMON /MESLESS/ IGBM,ndif,idif(50),NKI,IKI(10)
      COMMON /MATIZO/ E,V
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /CDEBUG/ IDEBUG
      COMMON /BOCACP2/ DP(19)
      DIMENSION RTH(*),ID(NP,*),NCVEL(*),NCVP(*),FSP(6),cord(np,*),
     1          NELCV(*),DL(19)
C
      IF(IDEBUG.GT.0) PRINT *, ' BOCAC'
C
      TPROF2=67.
      IF(VREME.LT.TPROF2) RETURN
      STAC=146.5001-VREME
C
      NA2=253877
      NB2=255123
      NC2=257684
      ND2=260355
      NE2=261191


C
      NBE211=234105
      NBE212=243273
      NBE213=249999
C
      NBE221=258061
      NBE222=258090
      NBE223=258132
C
      NBE231=276910
      NBE232=269994
      NBE233=265225
C
      KPROF=INT(VREME-TPROF2)
C     RACUNANJE POCETNIH DUZINA ZA KONVERGENCIJU
      II=98
      IF(KPROF.EQ.0) THEN
         OPEN (II,FILE='BOCAC2.POM',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
         WRITE(II,*) '    CELO, A2B2L0, A2C2L0, A2D2L0, A2E2L0,',
     1      ' B2C2L0, B2D2L0, D2C2L0,E2B2L0, E2C2L0, E2D2L0,   ',
     1      ' A211L0, A212L0, A213L0, C221L0, C222L0, C223L0,',
     1      ' E231L0, E232L0, E233L0'
         CALL MERKONV(NA2,NB2,DP(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NC2,DP(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,ND2,DP(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NE2,DP(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB2,NC2,DP(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB2,ND2,DP(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND2,NC2,DP(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NB2,DP(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NC2,DP(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,ND2,DP(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA2,NBE211,DP(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NBE212,DP(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NBE213,DP(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC2,NBE221,DP(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC2,NBE222,DP(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC2,NBE223,DP(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE2,NBE231,DP(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NBE232,DP(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NBE233,DP(19),ICVEL,NELCV,ID,RTH,CORD,NP)
c      WRITE(II,5000) (DP(I),I=1,19)
 5000 FORMAT(' DP0',10(1PE15.8))
      ENDIF
C
         CALL MERKONV(NA2,NB2,DL(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NC2,DL(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,ND2,DL(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NE2,DL(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB2,NC2,DL(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB2,ND2,DL(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND2,NC2,DL(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NB2,DL(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NC2,DL(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,ND2,DL(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA2,NBE211,DL(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NBE212,DL(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA2,NBE213,DL(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC2,NBE221,DL(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC2,NBE222,DL(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC2,NBE223,DL(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE2,NBE231,DL(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NBE232,DL(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE2,NBE233,DL(19),ICVEL,NELCV,ID,RTH,CORD,NP)

c      WRITE(II,5001) (DP(I),I=1,19)
 5001 FORMAT(' DP',10(1PE15.8))
c      WRITE(II,5002) (DL(I),I=1,19)
 5002 FORMAT(' DL',10(1PE15.8))
      DO 30 I=1,19
         DL(I)=(DL(I)-DP(I))*1000.
   30 CONTINUE
      WRITE(II,5100) STAC,(DL(I),I=1,19)
C
      RETURN
C
c 5100 FORMAT(' ',F9.3,10(1PE15.8))
 5100 FORMAT(' ',F9.3,10(F8.3),3x,9(F8.3))
C-----------------------------------------------------------------------
      END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE BOCACN2(TA,TED,JG,NLM,MCVEL,ICVEL,KOR,VREME)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /BOCACS2/ TAUS(6,8,6),TAUM(6,8,6),TAU0(6,8,6)
      DIMENSION NEL2(6),TED(6,*),TA(*),MCVEL(*)
       
      TPROF2=67.
      IF(VREME.LT.TPROF2) RETURN
      STAC=146.5001-VREME
C
       NEL2(1)=446963
       NEL2(2)=446973
       NEL2(3)=446984
         NMM=NLM
         IF(ICVEL.EQ.1) NMM=MCVEL(NLM)
         DO 11 NC=1,3
         IF(NMM.EQ.NEL2(NC)) GO TO 12
   11    CONTINUE
         RETURN
C
   12 KPROF=INT(VREME-TPROF2)
C     OTVARANJE FAJLA ZA ZAPISIVANJE NAPONA KOJI SE MERE
      IF(NMM.EQ.NEL2(1)) II=94
      IF(NMM.EQ.NEL2(2)) II=95
      IF(NMM.EQ.NEL2(3)) II=96
      IF(KPROF.EQ.0) THEN
      IF(JG.EQ.1) THEN
      IF(NMM.EQ.NEL2(1))
     1   OPEN (II,FILE='BOCAC2.P21',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL2(2))
     1   OPEN (II,FILE='BOCAC2.P22',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL2(3))
     1   OPEN (II,FILE='BOCAC2.P23',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      ENDIF
C
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5103) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5103 FORMAT('0GL',F9.3,I7,I3,6(1PE12.4))
            DO 20 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAU0(I,JG,NC),0,I)
   20       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5101) STAC,NEL2(NC),JG,(TAU0(I,JG,NC),I=1,6)
 5101 FORMAT('0LO',F9.3,I7,I3,6(1PE12.4))
      ENDIF
C
C      WRITE(II,5104) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5104 FORMAT(' GL',F9.3,I7,I3,6(1PE12.4))
            DO 21 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAUS(I,JG,NC),0,I)
               TAUM(I,JG,NC)=(TAUS(I,JG,NC)-TAU0(I,JG,NC))/1000.
   21       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5100) STAC,NEL2(NC),JG,(TAUS(I,JG,NC),I=1,6)
 5100 FORMAT(' LO',F9.3,I7,I3,6(1PE12.4))
      IF((NMM.EQ.NEL2(1).AND.JG.EQ.2).OR.
     1   (NMM.EQ.NEL2(2).AND.JG.EQ.2).OR.
     1   (NMM.EQ.NEL2(3).AND.JG.EQ.4))
     1WRITE(II,5105) STAC,NEL2(NC),JG,(TAUM(I,JG,NC),I=1,6)
 5105 FORMAT(' LM',F9.3,I7,I3,6(1PE12.4))
C
      RETURN
C-----------------------------------------------------------------------
      END
C=======================================================================
C=======================================================================
      SUBROUTINE BOCAC3(RTH,ID,NCVEL,ICVEL,NP,KOR,VREME,IND,NCVP,NCVPR,
     1                 CORD,NELCV)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CS.   PROGRAM
CS.      ZA STAMPANJE MERNE TABELE ZA TUNEL BOCAC ZA PROFIL 3;
C .
C ......................................................................
C
      include 'paka.inc'
      
      COMMON /GRUPEE/ NGEL,NGENL,LGEOM,NGEOM,ITERM
      COMMON /ITERBR/ ITER
      COMMON /ECLANM/ AMAXK,AMINK,AMAXF,AMINF
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /OPSTIP/ JPS,JPBR,NPG,JIDG,JCORG,JCVEL,JELCV,NGA,NGI,NPK,
     1                NPUP,LIPODS,IPODS,LMAX13,MAX13,JEDNG,JMAXA,JEDNP,
     1                NWP,NWG,IDF,JPS1
      COMMON /ITERAC/ METOD,MAXIT,TOLE,TOLS,TOLM,KONVE,KONVS,KONVM
      COMMON /SRPSKI/ ISRPS
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
      COMMON /MAXREZ/ PMALL,BMALL,AMALL,SMKOR,SMALL,
     +                NPMALL,NBMALL,NAMALL,KPMALL,KBMALL,KAMALL,
     +                NSMKOR,NSMALL,NGRKOR,NGRALL,KSMALL
      COMMON /AUTSTP/ DTUK,ALFG,DELS,IAUTO,ITEOPT,KPNOD,KPDIR,KEQ
      COMMON /AUTST2/ PARAM(5)
      COMMON /AUTSTK/ DELUM,DELFM,KRAJP
      COMMON /GEORGE/ TOLG,ALFAG,ICCGG
      COMMON /MESLESS/ IGBM,ndif,idif(50),NKI,IKI(10)
      COMMON /MATIZO/ E,V
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /CDEBUG/ IDEBUG
      COMMON /BOCACP3/ DP(19)
      DIMENSION RTH(*),ID(NP,*),NCVEL(*),NCVP(*),FSP(6),cord(np,*),
     1          NELCV(*),DL(19)
C
      IF(IDEBUG.GT.0) PRINT *, ' BOCAC'
C
      TPROF3=82.
      IF(VREME.LT.TPROF3) RETURN
      STAC=147.5001-VREME
C
      NA3=212521
      NB3=213066
      NC3=213956
      ND3=214791
      NE3=215052


C
      NBE311=198777
      NBE312=203150
      NBE313=211167
C
      NBE321=214061
      NBE322=214058
      NBE323=214231
C
      NBE331=222845
      NBE332=219067
      NBE333=216263
C
      KPROF=INT(VREME-TPROF3)
C     RACUNANJE POCETNIH DUZINA ZA KONVERGENCIJU
      II=97
      IF(KPROF.EQ.0) THEN
         OPEN (II,FILE='BOCAC3.POM',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
         WRITE(II,*) '    CELO, A3B3L0, A3C3L0, A3D3L0, A3E3L0,',
     1      ' B3C3L0, B3D230, D3C3L0,E3B3L0, E3C3L0, E3D3L0,   ',
     1      ' A311L0, A312L0, A313L0, C321L0, C322L0, C323L0,',
     1      ' E331L0, E332L0, E333L0'
         CALL MERKONV(NA3,NB3,DP(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA3,NC3,DP(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA3,ND3,DP(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA3,NE3,DP(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB3,NC3,DP(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB3,ND3,DP(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND3,NC3,DP(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE3,NB3,DP(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE3,NC3,DP(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE3,ND3,DP(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA3,NBE311,DP(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA3,NBE312,DP(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA3,NBE313,DP(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC3,NBE321,DP(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC3,NBE322,DP(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC3,NBE323,DP(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE3,NBE331,DP(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE3,NBE332,DP(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE3,NBE333,DP(19),ICVEL,NELCV,ID,RTH,CORD,NP)
c      WRITE(II,5000) (DP(I),I=1,19)
 5000 FORMAT(' DP0',10(1PE15.8))
      ENDIF
C
         CALL MERKONV(NA3,NB3,DL(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA3,NC3,DL(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA3,ND3,DL(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA3,NE3,DL(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB3,NC3,DL(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB3,ND3,DL(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND3,NC3,DL(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE3,NB3,DL(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE3,NC3,DL(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE3,ND3,DL(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA3,NBE311,DL(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA3,NBE312,DL(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA3,NBE313,DL(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC3,NBE321,DL(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC3,NBE322,DL(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC3,NBE323,DL(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE3,NBE331,DL(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE3,NBE332,DL(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE3,NBE333,DL(19),ICVEL,NELCV,ID,RTH,CORD,NP)

c      WRITE(II,5001) (DP(I),I=1,19)
 5001 FORMAT(' DP',10(1PE15.8))
c      WRITE(II,5002) (DL(I),I=1,19)
 5002 FORMAT(' DL',10(1PE15.8))
      DO 30 I=1,19
         DL(I)=(DL(I)-DP(I))*1000.
   30 CONTINUE
      WRITE(II,5100) STAC,(DL(I),I=1,19)
C
      RETURN
C
c 5100 FORMAT(' ',F9.3,10(1PE15.8))
 5100 FORMAT(' ',F9.3,10(F8.3),3x,9(F8.3))
C-----------------------------------------------------------------------
      END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE BOCACN3(TA,TED,JG,NLM,MCVEL,ICVEL,KOR,VREME)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /BOCACS3/ TAUS(6,8,6),TAUM(6,8,6),TAU0(6,8,6)
      DIMENSION NEL3(6),TED(6,*),TA(*),MCVEL(*)
       
      TPROF3=82.
      IF(VREME.LT.TPROF3) RETURN
      STAC=147.5001-VREME
C
       NEL3(1)=444168
       NEL3(2)=444158
       NEL3(3)=444147
         NMM=NLM
         IF(ICVEL.EQ.1) NMM=MCVEL(NLM)
         DO 11 NC=1,3
         IF(NMM.EQ.NEL3(NC)) GO TO 12
   11    CONTINUE
         RETURN
C
   12 KPROF=INT(VREME-TPROF3)
C     OTVARANJE FAJLA ZA ZAPISIVANJE NAPONA KOJI SE MERE
      IF(NMM.EQ.NEL3(1)) II=84
      IF(NMM.EQ.NEL3(2)) II=85
      IF(NMM.EQ.NEL3(3)) II=86
      IF(KPROF.EQ.0) THEN
      IF(JG.EQ.1) THEN
      IF(NMM.EQ.NEL3(1))
     1   OPEN (II,FILE='BOCAC3.P31',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL3(2))
     1   OPEN (II,FILE='BOCAC3.P32',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL3(3))
     1   OPEN (II,FILE='BOCAC3.P33',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      ENDIF
C
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5103) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5103 FORMAT('0GL',F9.3,I7,I3,6(1PE12.4))
            DO 20 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAU0(I,JG,NC),0,I)
   20       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5101) STAC,NEL2(NC),JG,(TAU0(I,JG,NC),I=1,6)
 5101 FORMAT('0LO',F9.3,I7,I3,6(1PE12.4))
      ENDIF
C
C      WRITE(II,5104) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5104 FORMAT(' GL',F9.3,I7,I3,6(1PE12.4))
            DO 21 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAUS(I,JG,NC),0,I)
               TAUM(I,JG,NC)=(TAUS(I,JG,NC)-TAU0(I,JG,NC))/1000.
   21       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5100) STAC,NEL2(NC),JG,(TAUS(I,JG,NC),I=1,6)
 5100 FORMAT(' LO',F9.3,I7,I3,6(1PE12.4))
      IF((NMM.EQ.NEL3(1).AND.JG.EQ.4).OR.
c     1   (NMM.EQ.NEL3(2).AND.JG.EQ.4).OR.
     1   (NMM.EQ.NEL3(2)).OR.
     1   (NMM.EQ.NEL3(3).AND.JG.EQ.8))
     1WRITE(II,5105) STAC,NEL3(NC),JG,(TAUM(I,JG,NC),I=1,6)
 5105 FORMAT(' LM',F9.3,I7,I3,6(1PE12.4))
C
      RETURN
C-----------------------------------------------------------------------
      END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE BOCACN11(TA,TED,JG,NLM,MCVEL,ICVEL,KOR,VREME)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /BOCACS4/ TAUS(6,8,6),TAUM(6,8,6),TAU0(6,8,6)
      DIMENSION NEL1(6),TED(6,*),TA(*),MCVEL(*)
       
      TPROF1=53.
      IF(VREME.LT.TPROF1) RETURN
      STAC=145.5001-VREME
C
       NEL1(1)=292126
       NEL1(2)=292066
       NEL1(3)=292000
         NMM=NLM
         IF(ICVEL.EQ.1) NMM=MCVEL(NLM)
         DO 11 NC=1,3
         IF(NMM.EQ.NEL1(NC)) GO TO 12
   11    CONTINUE
         RETURN
C
   12 KPROF=INT(VREME-TPROF1)
C     OTVARANJE FAJLA ZA ZAPISIVANJE NAPONA KOJI SE MERE
      IF(NMM.EQ.NEL1(1)) II=71
      IF(NMM.EQ.NEL1(2)) II=72
      IF(NMM.EQ.NEL1(3)) II=73
      IF(KPROF.EQ.0) THEN
      IF(JG.EQ.1) THEN
      IF(NMM.EQ.NEL1(1))
     1   OPEN (II,FILE='BOCAC1.P41',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL1(2))
     1   OPEN (II,FILE='BOCAC1.P42',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL1(3))
     1   OPEN (II,FILE='BOCAC1.P43',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      ENDIF
C
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5103) STAC,NEL1(NC),JG,(TA(I),I=1,6)
 5103 FORMAT('0GL',F9.3,I7,I3,6(1PE12.4))
            DO 20 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAU0(I,JG,NC),0,I)
   20       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5101) STAC,NEL1(NC),JG,(TAU0(I,JG,NC),I=1,6)
 5101 FORMAT('0LO',F9.3,I7,I3,6(1PE12.4))
      ENDIF
C
C      WRITE(II,5104) STAC,NEL1(NC),JG,(TA(I),I=1,6)
 5104 FORMAT(' GL',F9.3,I7,I3,6(1PE12.4))
            DO 21 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAUS(I,JG,NC),0,I)
               TAUM(I,JG,NC)=(TAUS(I,JG,NC)-TAU0(I,JG,NC))/1000.
   21       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5100) STAC,NEL1(NC),JG,(TAUS(I,JG,NC),I=1,6)
 5100 FORMAT(' LO',F9.3,I7,I3,6(1PE12.4))
      IF((NMM.EQ.NEL1(1).AND.JG.EQ.4).OR.
     1   (NMM.EQ.NEL1(2).AND.JG.EQ.4).OR.
     1   (NMM.EQ.NEL1(3).AND.JG.EQ.8))
     1WRITE(II,5105) STAC,NEL1(NC),JG,(TAUM(I,JG,NC),I=1,6)
 5105 FORMAT(' LM',F9.3,I7,I3,6(1PE12.4))
C
      RETURN
C-----------------------------------------------------------------------
      END
C=======================================================================
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE BOCACN21(TA,TED,JG,NLM,MCVEL,ICVEL,KOR,VREME)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /BOCACS5/ TAUS(6,8,6),TAUM(6,8,6),TAU0(6,8,6)
      DIMENSION NEL2(6),TED(6,*),TA(*),MCVEL(*)
       
      TPROF2=67.
      IF(VREME.LT.TPROF2) RETURN
      STAC=146.5001-VREME
C
       NEL2(1)=286318
       NEL2(2)=286258
       NEL2(3)=286192
         NMM=NLM
         IF(ICVEL.EQ.1) NMM=MCVEL(NLM)
         DO 11 NC=1,3
         IF(NMM.EQ.NEL2(NC)) GO TO 12
   11    CONTINUE
         RETURN
C
   12 KPROF=INT(VREME-TPROF2)
C     OTVARANJE FAJLA ZA ZAPISIVANJE NAPONA KOJI SE MERE
      IF(NMM.EQ.NEL2(1)) II=74
      IF(NMM.EQ.NEL2(2)) II=75
      IF(NMM.EQ.NEL2(3)) II=76
      IF(KPROF.EQ.0) THEN
      IF(JG.EQ.1) THEN
      IF(NMM.EQ.NEL2(1))
     1   OPEN (II,FILE='BOCAC2.P51',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL2(2))
     1   OPEN (II,FILE='BOCAC2.P52',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL2(3))
     1   OPEN (II,FILE='BOCAC2.P53',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      ENDIF
C
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5103) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5103 FORMAT('0GL',F9.3,I7,I3,6(1PE12.4))
            DO 20 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAU0(I,JG,NC),0,I)
   20       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5101) STAC,NEL2(NC),JG,(TAU0(I,JG,NC),I=1,6)
 5101 FORMAT('0LO',F9.3,I7,I3,6(1PE12.4))
      ENDIF
C
C      WRITE(II,5104) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5104 FORMAT(' GL',F9.3,I7,I3,6(1PE12.4))
            DO 21 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAUS(I,JG,NC),0,I)
               TAUM(I,JG,NC)=(TAUS(I,JG,NC)-TAU0(I,JG,NC))/1000.
   21       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5100) STAC,NEL2(NC),JG,(TAUS(I,JG,NC),I=1,6)
 5100 FORMAT(' LO',F9.3,I7,I3,6(1PE12.4))
      IF((NMM.EQ.NEL2(1).AND.JG.EQ.4).OR.
     1   (NMM.EQ.NEL2(2).AND.JG.EQ.4).OR.
     1   (NMM.EQ.NEL2(3).AND.JG.EQ.8))
     1WRITE(II,5105) STAC,NEL2(NC),JG,(TAUM(I,JG,NC),I=1,6)
 5105 FORMAT(' LM',F9.3,I7,I3,6(1PE12.4))
C
      RETURN
C-----------------------------------------------------------------------
      END
C=======================================================================
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE BOCACN31(TA,TED,JG,NLM,MCVEL,ICVEL,KOR,VREME)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /BOCACS6/ TAUS(6,8,6),TAUM(6,8,6),TAU0(6,8,6)
      DIMENSION NEL2(6),TED(6,*),TA(*),MCVEL(*)
       
      TPROF2=82.
      IF(VREME.LT.TPROF2) RETURN
      STAC=147.5001-VREME
C
       NEL2(1)=319222
       NEL2(2)=319162
       NEL2(3)=319096
         NMM=NLM
         IF(ICVEL.EQ.1) NMM=MCVEL(NLM)
         DO 11 NC=1,3
         IF(NMM.EQ.NEL2(NC)) GO TO 12
   11    CONTINUE
         RETURN
C
   12 KPROF=INT(VREME-TPROF2)
C     OTVARANJE FAJLA ZA ZAPISIVANJE NAPONA KOJI SE MERE
      IF(NMM.EQ.NEL2(1)) II=77
      IF(NMM.EQ.NEL2(2)) II=87
      IF(NMM.EQ.NEL2(3)) II=79
      IF(KPROF.EQ.0) THEN
      IF(JG.EQ.1) THEN
      IF(NMM.EQ.NEL2(1))
     1   OPEN (II,FILE='BOCAC3.P61',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL2(2))
     1   OPEN (II,FILE='BOCAC3.P62',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL2(3))
     1   OPEN (II,FILE='BOCAC3.P63',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      ENDIF
C
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5103) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5103 FORMAT('0GL',F9.3,I7,I3,6(1PE12.4))
            DO 20 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAU0(I,JG,NC),0,I)
   20       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5101) STAC,NEL2(NC),JG,(TAU0(I,JG,NC),I=1,6)
 5101 FORMAT('0LO',F9.3,I7,I3,6(1PE12.4))
      ENDIF
C
C      WRITE(II,5104) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5104 FORMAT(' GL',F9.3,I7,I3,6(1PE12.4))
            DO 21 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAUS(I,JG,NC),0,I)
               TAUM(I,JG,NC)=(TAUS(I,JG,NC)-TAU0(I,JG,NC))/1000.
   21       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5100) STAC,NEL2(NC),JG,(TAUS(I,JG,NC),I=1,6)
 5100 FORMAT(' LO',F9.3,I7,I3,6(1PE12.4))
      IF((NMM.EQ.NEL2(1).AND.JG.EQ.4).OR.
     1   (NMM.EQ.NEL2(2).AND.JG.EQ.4).OR.
     1   (NMM.EQ.NEL2(3).AND.JG.EQ.8))
     1WRITE(II,5105) STAC,NEL2(NC),JG,(TAUM(I,JG,NC),I=1,6)
 5105 FORMAT(' LM',F9.3,I7,I3,6(1PE12.4))
C
      RETURN
C-----------------------------------------------------------------------
      END
C=======================================================================
C=======================================================================
      SUBROUTINE BOCAC4(RTH,ID,NCVEL,ICVEL,NP,KOR,VREME,IND,NCVP,NCVPR,
     1                 CORD,NELCV)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CS.   PROGRAM
CS.      ZA STAMPANJE MERNE TABELE ZA TUNEL BOCAC ZA PROFIL 4 - 52.5m;
C .
C ......................................................................
C
      include 'paka.inc'
      
      COMMON /GRUPEE/ NGEL,NGENL,LGEOM,NGEOM,ITERM
      COMMON /ITERBR/ ITER
      COMMON /ECLANM/ AMAXK,AMINK,AMAXF,AMINF
      COMMON /TRAKEJ/ IULAZ,IZLAZ,IELEM,ISILE,IRTDT,IFTDT,ILISK,ILISE,
     1                ILIMC,ILDLT,IGRAF,IDINA,IPOME,IPRIT,LDUZI
      COMMON /OPSTIP/ JPS,JPBR,NPG,JIDG,JCORG,JCVEL,JELCV,NGA,NGI,NPK,
     1                NPUP,LIPODS,IPODS,LMAX13,MAX13,JEDNG,JMAXA,JEDNP,
     1                NWP,NWG,IDF,JPS1
      COMMON /ITERAC/ METOD,MAXIT,TOLE,TOLS,TOLM,KONVE,KONVS,KONVM
      COMMON /SRPSKI/ ISRPS
      COMMON /MPOINC/ MMP,NMPC,NEZAV,LCMPC,LMPC,NEZA1
      COMMON /MAXREZ/ PMALL,BMALL,AMALL,SMKOR,SMALL,
     +                NPMALL,NBMALL,NAMALL,KPMALL,KBMALL,KAMALL,
     +                NSMKOR,NSMALL,NGRKOR,NGRALL,KSMALL
      COMMON /AUTSTP/ DTUK,ALFG,DELS,IAUTO,ITEOPT,KPNOD,KPDIR,KEQ
      COMMON /AUTST2/ PARAM(5)
      COMMON /AUTSTK/ DELUM,DELFM,KRAJP
      COMMON /GEORGE/ TOLG,ALFAG,ICCGG
      COMMON /MESLESS/ IGBM,ndif,idif(50),NKI,IKI(10)
      COMMON /MATIZO/ E,V
      COMMON /POSTPR/ LNDTPR,LNDTGR,NBLPR,NBLGR,INDPR,INDGR
      COMMON /CDEBUG/ IDEBUG
      COMMON /BOCACP4/ DP(19)
      DIMENSION RTH(*),ID(NP,*),NCVEL(*),NCVP(*),FSP(6),cord(np,*),
     1          NELCV(*),DL(19)
C
      IF(IDEBUG.GT.0) PRINT *, ' BOCAC'
C
      TPROF4=94.
      IF(VREME.LT.TPROF4) RETURN
      STAC=147.5001-VREME
C
      NA4=176652
      NB4=177141
      NC4=178028
      ND4=178862
      NE4=179102


C
      NBE411=164268
      NBE412=170792
      NBE413=175448
C
      NBE421=178238
      NBE422=178202
      NBE423=178261
C
      NBE431=182481
      NBE432=181608
      NBE433=180213
C
      KPROF=INT(VREME-TPROF4)
C     RACUNANJE POCETNIH DUZINA ZA KONVERGENCIJU
      II=61
      IF(KPROF.EQ.0) THEN
         OPEN (II,FILE='BOCAC4.POM',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
         WRITE(II,*) '    CELO, A4B4L0, A4C4L0, A4D4L0, A4E4L0,',
     1      ' B4C3L0, B4D230, D4C4L0,E4B4L0, E4C4L0, E4D4L0,   ',
     1      ' A411L0, A412L0, A414L0, C421L0, C422L0, C423L0,',
     1      ' E431L0, E432L0, E433L0'
         CALL MERKONV(NA4,NB4,DP(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA4,NC4,DP(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA4,ND4,DP(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA4,NE4,DP(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB4,NC4,DP(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB4,ND4,DP(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND4,NC4,DP(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE4,NB4,DP(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE4,NC4,DP(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE4,ND4,DP(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA4,NBE411,DP(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA4,NBE412,DP(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA4,NBE413,DP(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC4,NBE421,DP(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC4,NBE422,DP(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC4,NBE423,DP(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE4,NBE431,DP(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE4,NBE432,DP(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE4,NBE433,DP(19),ICVEL,NELCV,ID,RTH,CORD,NP)
c      WRITE(II,5000) (DP(I),I=1,19)
 5000 FORMAT(' DP0',10(1PE15.8))
      ENDIF
C
         CALL MERKONV(NA4,NB4,DL(1),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA4,NC4,DL(2),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA4,ND4,DL(3),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA4,NE4,DL(4),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB4,NC4,DL(5),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NB4,ND4,DL(6),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(ND4,NC4,DL(7),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE4,NB4,DL(8),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE4,NC4,DL(9),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE4,ND4,DL(10),ICVEL,NELCV,ID,RTH,CORD,NP)
C         
         CALL MERKONV(NA4,NBE411,DL(11),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA4,NBE412,DL(12),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NA4,NBE413,DL(13),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NC4,NBE421,DL(14),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC4,NBE422,DL(15),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NC4,NBE423,DL(16),ICVEL,NELCV,ID,RTH,CORD,NP)
C
         CALL MERKONV(NE4,NBE431,DL(17),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE4,NBE432,DL(18),ICVEL,NELCV,ID,RTH,CORD,NP)
         CALL MERKONV(NE4,NBE433,DL(19),ICVEL,NELCV,ID,RTH,CORD,NP)

c      WRITE(II,5001) (DP(I),I=1,19)
 5001 FORMAT(' DP',10(1PE15.8))
c      WRITE(II,5002) (DL(I),I=1,19)
 5002 FORMAT(' DL',10(1PE15.8))
      DO 30 I=1,19
         DL(I)=(DL(I)-DP(I))*1000.
   30 CONTINUE
      WRITE(II,5100) STAC,(DL(I),I=1,19)
C
      RETURN
C
c 5100 FORMAT(' ',F9.3,10(1PE15.8))
 5100 FORMAT(' ',F9.3,10(F8.3),3x,9(F8.3))
C-----------------------------------------------------------------------
      END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      SUBROUTINE BOCACN4(TA,TED,JG,NLM,MCVEL,ICVEL,KOR,VREME)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON /BOCACS4/ TAUS(6,8,6),TAUM(6,8,6),TAU0(6,8,6)
      DIMENSION NEL4(6),TED(6,*),TA(*),MCVEL(*)
       
      TPROF4=94.
      IF(VREME.LT.TPROF4) RETURN
      STAC=147.5001-VREME
C
       NEL4(1)=441782
       NEL4(2)=441742
       NEL4(3)=441698
         NMM=NLM
         IF(ICVEL.EQ.1) NMM=MCVEL(NLM)
         DO 11 NC=1,3
         IF(NMM.EQ.NEL4(NC)) GO TO 12
   11    CONTINUE
         RETURN
C
   12 KPROF=INT(VREME-TPROF4)
C     OTVARANJE FAJLA ZA ZAPISIVANJE NAPONA KOJI SE MERE
      IF(NMM.EQ.NEL4(1)) II=62
      IF(NMM.EQ.NEL4(2)) II=63
      IF(NMM.EQ.NEL4(3)) II=64
      IF(KPROF.EQ.0) THEN
      IF(JG.EQ.1) THEN
      IF(NMM.EQ.NEL4(1))
     1   OPEN (II,FILE='BOCAC4.P41',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL4(2))
     1   OPEN (II,FILE='BOCAC4.P42',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      IF(NMM.EQ.NEL4(3))
     1   OPEN (II,FILE='BOCAC4.P43',STATUS='UNKNOWN',
     1         FORM='FORMATTED',ACCESS='SEQUENTIAL')
      ENDIF
C
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5103) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5103 FORMAT('0GL',F9.3,I7,I3,6(1PE12.4))
            DO 20 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAU0(I,JG,NC),0,I)
   20       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5101) STAC,NEL2(NC),JG,(TAU0(I,JG,NC),I=1,6)
 5101 FORMAT('0LO',F9.3,I7,I3,6(1PE12.4))
      ENDIF
C
C      WRITE(II,5104) STAC,NEL2(NC),JG,(TA(I),I=1,6)
 5104 FORMAT(' GL',F9.3,I7,I3,6(1PE12.4))
            DO 21 I=1,6
CS             KOSIJEVI NAPONI U GLOBAL. ILI LOKAL. DEKART. SISTEMU
CE             CAUCHY STRESS IN GLOBAL OR LOCAL CARTESIAN SYSTEM 
CE             ISN: INDICATOR FOR STRESS STORAGE (=0-LOCAL,=2-GLOBAL)
               CALL GLLOKN(TA,TED,TAUS(I,JG,NC),0,I)
               TAUM(I,JG,NC)=(TAUS(I,JG,NC)-TAU0(I,JG,NC))/1000.
   21       CONTINUE
C STAMPANJE NAPONA NA MERNIM MESTIMA
c      WRITE(II,5100) STAC,NEL2(NC),JG,(TAUS(I,JG,NC),I=1,6)
 5100 FORMAT(' LO',F9.3,I7,I3,6(1PE12.4))
      IF((NMM.EQ.NEL4(1).AND.JG.EQ.2).OR.
c     1   (NMM.EQ.NEL4(2).AND.JG.EQ.2).OR.
     1   (NMM.EQ.NEL4(2)).OR.
     1   (NMM.EQ.NEL4(3).AND.JG.EQ.2))
     1WRITE(II,5105) STAC,NEL4(NC),JG,(TAUM(I,JG,NC),I=1,6)
 5105 FORMAT(' LM',F9.3,I7,I3,6(1PE12.4))
C
      RETURN
C-----------------------------------------------------------------------
      END
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
