C==========================================================================
C     SUBROUTINE  OTVNEU
C                 TGRMAT
C                 TGRAUK
C                 TGRAU2
C                 TGRAU3
C                 STAU09
C                 NEUTRA
C===========================================================================
      SUBROUTINE OTVNEUF(IME,PAKNEU,IDUZIN,ISRPS,II)
CS OTVARANJE DATOTEKE ZA NEU GRAFIKU
CE OPEN FILE FOR NEU GRAPHIC
      LOGICAL OLDNEW
      CHARACTER*24 PAKNEU
      CHARACTER*3  STAT
      character*50 IME

CS IZLAZ ZA GRAFIKU
CE OUTPUT FOR GRAPHIC
C
   15 CONTINUE
      IF(ISRPS.EQ.0)
     *WRITE(*,*)' UNETI IME IZLAZNE DATOTEKE ZA NEU GRAFIKU /"'
     1,PAKNEU(1:IDUZIN),'"'
      IF(ISRPS.EQ.1)
     *WRITE(*,*)' ENTER NAME OF OUTPUT FILE FOR NEU GRAPHICS /"' 
     1,PAKNEU(1:IDUZIN),'"'
C   15 WRITE(*,820)
      READ (*,910) IME
      IF(IME.EQ.'                    ') IME = PAKNEU
  910 FORMAT (A)
C
   20 STAT='NEW'
      INQUIRE(FILE=IME,EXIST=OLDNEW)
      IF(OLDNEW) STAT='OLD'
      IF(STAT.EQ.'NEW') THEN
      OPEN (II,FILE=IME,STATUS='NEW',FORM='FORMATTED',
     1 ACCESS='SEQUENTIAL')
                        ELSE
      OPEN (II,FILE=IME,STATUS='OLD',FORM='FORMATTED',
     1 ACCESS='SEQUENTIAL')
                        ENDIF
C
      IND=0
      IF(STAT.EQ.'OLD') CALL BRISF (IME,II,IND)
      IF(IND.EQ.1)GO TO 20
      IF(IND.EQ.2)GO TO 15
      RETURN
      END
C======================================================================
C
C======================================================================
      SUBROUTINE TGRMATF(TABK,NUMMAT,NETIP,II,NDIM,NASLOV,GAMA,TABC)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.    P R O G R A M
CE.       TO PRINT MATERIALS AND PROPERTIES IN NEU FILE
C .
C ......................................................................
C
      CHARACTER*250 NASLOV
C      DIMENSION GAMA(*),TABK(2,INTABK,*),TABC(2,NUMMAT,*)
      DIMENSION GAMA(*),TABK(2,NUMMAT,*),TABC(2,NUMMAT,*)
C
      IND=-1
      ITYP=100
	VERSION=4.4
      WRITE(II,5100) IND
      WRITE(II,5100) ITYP
      WRITE(II,2002) NASLOV
      WRITE(II,5200) VERSION
      WRITE(II,5100) IND
C
      NULA=0
      ZERO=0.
C
      EX=0.
      EY=0.
      EZ=0.
      GX=0.
      GY=0.
      GZ=0.
      VX=0.
      VY=0.
      VZ=0.
C
      IND=-1
      ITYP=401
      WRITE(II,5100) IND
      WRITE(II,5100) ITYP
      I=1
C      DO I=1,NUMMAT
C      
         AK=TABK(2,I,1)
         AC=TABC(2,I,1)
         GAM=GAMA(I)
C
c         ICOL=124-(I-1)*2
         ICOL=120-(I-1)*3
         WRITE(II,5600) I,ICOL,NULA,I,NULA
         WRITE(II,2000) I
         WRITE(II,5500) EX,EY,EZ
         WRITE(II,5500) GX,GY,GZ
         WRITE(II,5500) VX,VY,VZ
         WRITE(II,5500) EX,ZERO,ZERO,ZERO,ZERO
         WRITE(II,5500) ZERO,EY,ZERO,ZERO,ZERO
         WRITE(II,5500) ZERO,EZ,ZERO,ZERO,ZERO
         WRITE(II,5500) GX,ZERO,ZERO,GY,ZERO
         WRITE(II,5500) GZ
         WRITE(II,5500) EX,ZERO,ZERO,EY,ZERO
         WRITE(II,5500) GX
C        AX,AY,AZ
         WRITE(II,5500) ZERO,ZERO,ZERO,ZERO,ZERO
         WRITE(II,5500) ZERO
         IF(NETIP.EQ.2) 
C        K
     +   WRITE(II,5500) AK,AK,ZERO,ZERO,ZERO
         IF(NETIP.EQ.3) 
C        K
     +   WRITE(II,5500) AK,AK,AK,ZERO,ZERO
         WRITE(II,5500) ZERO
C        CP,RO,BE,TREF
         IF(NETIP.EQ.2) 
     +   WRITE(II,5500) AC,GAM,ZERO,ZERO
         IF(NETIP.EQ.3) 
     +   WRITE(II,5500) AC,GAM,ZERO,ZERO
         WRITE(II,5500) ZERO,ZERO,ZERO,ZERO,ZERO
C        A I D
         WRITE(II,5500) ZERO,ZERO,ZERO,ZERO,ZERO
         WRITE(II,5500) ZERO,ZERO,ZERO,ZERO,ZERO
         WRITE(II,5500) ZERO,ZERO,ZERO,ZERO,ZERO
         WRITE(II,5500) ZERO,ZERO,ZERO,ZERO,ZERO
         WRITE(II,5500) ZERO
         WRITE(II,5500) ZERO,ZERO,ZERO,ZERO,ZERO
C        ET,SY,FI
         WRITE(II,5500) ZERO,ZERO,ZERO
C
         WRITE(II,5600) NULA,NULA,NULA,NULA,NULA
C        0,0,0,F(SY),M,MODEL
         WRITE(II,5600) NULA,NULA,NULA,NULA,NULA,NULA
C        CREEP
         WRITE(II,5500) ZERO,ZERO,ZERO
         WRITE(II,5500) ZERO,ZERO,ZERO,ZERO,ZERO
         WRITE(II,5500) ZERO,ZERO
         WRITE(II,5600) NULA,NULA,NULA,NULA
         WRITE(II,5600) NULA,NULA,NULA,NULA
C      ENDDO
      WRITE(II,5100) IND
C
      IND=-1
      ITYP=402
      WRITE(II,5100) IND
      WRITE(II,5100) ITYP
      IF(NETIP.EQ.3.AND.NDIM.EQ.8) IPRO=25
      IF(NETIP.EQ.3.AND.NDIM.GT.8) IPRO=26
      IF(NETIP.EQ.2.AND.NDIM.EQ.4) IPRO=19
      IF(NETIP.EQ.2.AND.NDIM.GT.4) IPRO=20
      I=1
C      DO I=1,NUMMAT
c         ICOL=124-(I-1)*2
         ICOL=120-(I-1)*3
         WRITE(II,5600) I,ICOL,I,IPRO,I,NULA
         WRITE(II,2001) I
         WRITE(II,5600) NULA,NULA,NULA,NULA
C 45
         WRITE(II,5600) NULA
C 93
         WRITE(II,5600) NULA
C      ENDDO
      WRITE(II,5100) IND
      RETURN
C
 5100 FORMAT(I5)
 5200 FORMAT(F3.1,',')
 5500 FORMAT(5(1PE13.5,','))
 5600 FORMAT(6(I4,','))
 2000 FORMAT(' MAT',I4)
 2001 FORMAT(' PRO',I4)
 2002 FORMAT(A80)
      END
C======================================================================
C
C======================================================================
      SUBROUTINE TGRAUKF(CORD,ID,NP,II)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.    P R O G R A M
CE.       TO PRINT COORDINATES IN NEUTRAL FILE
CS.    P R O G R A M
CS.       ZA STAMPANJE KOORDINATA CVOROVA U NEUTRAL FILE
C .
C ......................................................................
C
      DIMENSION CORD(3,*)
      DIMENSION ID(5,*)
      DIMENSION IDD(6)
C
      IDD(1)=0
      IDD(2)=0
      IDD(3)=0
      IDD(4)=0
      IDD(5)=0
      IDD(6)=0
C
      NULA=0
C
      IND=-1
      ITYP=403
      ICOL=46
      WRITE(II,5100) IND
      WRITE(II,5100) ITYP
      DO 10 I=1,NP
           NI=I
         DO 20 IJ=1,5
            IF(ID(IJ,I).GT.0) THEN
               IDD(IJ)=0
            ELSE
C               IDD(IJ)=1
            ENDIF
   20    CONTINUE
         WRITE(II,5000) NI,NULA,NULA,NULA,ICOL,(IDD(J),J=1,6),
     +                  (CORD(J,I),J=1,3),NULA
   10 CONTINUE
      WRITE(II,5100) IND
      RETURN
C
 5000 FORMAT(I6,',',10(I3,','),3(1PE13.5,','),I2,',')
 5100 FORMAT(I5)
      END
C=====================================================================
      SUBROUTINE TGRAU2F(NEL,NCVE,NE,IGRAF,NMATT)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C .......................................................................
C .
CE.   P R O G R A M
CE.       TO PRINTOUT 2/D ELEMENTS DATA IN NEUTRAL GRAPHICS FILE
CS.   P R O G R A M
CS.       ZA STAMPANJE 2/D ELEMENATA U NEUTRALNI FILE
C .
C .......................................................................
C 
C      DIMENSION NEL(NE,*),MATV(*)
      DIMENSION NEL(NCVE,*)
C      COMMON /CDEBUG/ IDEBUG
C
C      IF(IDEBUG.GT.0) PRINT *, ' TGRAU2'
C
C     FIZICKE OSOBINE
C
      NULA=0
      ZERO=0.
      ONE=1.
      JEDAN=1
      INDPR=25
      INDPD=2
      I11=11
      I2=2
      I4=4
      I8=8
      I14=14
      I48=48
C
C     E L E M E N T I
C
      NNCVE=NCVE
      IF(NCVE.LT.8) NCVE=4
      IF(NCVE.EQ.9) NCVE=8
C     GRAFICKI OPIS ELEMENTA:
C     MEMBRANE - SA 4 CVOROVA = 13, SA 8 CVOROVA = 14
C     PLANE STRAIN - SA 4 CVOROVA = 19, SA 8 CVOROVA = 20
C     AXISYMMETRIC - SA 4 CVOROVA = 23, SA 8 CVOROVA = 24
C     PLATE - SA 4 CVOROVA = 17, SA 8 CVOROVA = 18
C     LAMINATE - SA 4 CVOROVA = 21, SA 8 CVOROVA = 22
      IFGD=19
      IF(NCVE.EQ.8) IFGD=20
C     VRSTA 2D ELEMENTA: SA 4 CVOROVA = 4, SA 8 CVOROVA = 5
      IFDI=4
      IF(NCVE.EQ.8) IFDI=5
C     TABELA FIZICKIH OSOBINA
C      IPTN=ISUMGR
C     BROJ CVOROVA NA ELEMENTU
      NNODS=NCVE
      IND=-1
      ITYP=404
      WRITE(IGRAF,1100) IND
      WRITE(IGRAF,1100) ITYP
      DO 10 I=1,NE
C        TABELA MATERIJALA
         MPTN=1
C         IF(NMATT.GT.1) MPTN=MATV(I)
C        BOJA  
c         ICOL=124-(MPTN-1)*2
         ICOL=120-(MPTN-1)*3
         WRITE(IGRAF,1000) I,ICOL,MPTN,IFGD,IFDI,MPTN,NULA,NULA
         IF(NCVE.EQ.4) THEN
            WRITE(IGRAF,1001) (NEL(J,I),J=1,4),NULA,NULA,NULA,NULA,
     +                        NULA,NULA
            WRITE(IGRAF,1011) NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,
     +                        NULA,NULA
         ELSE
            WRITE(IGRAF,1001) (NEL(J,I),J=1,8),
     +                        NULA,NULA
            WRITE(IGRAF,1011) NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,
     +                        NULA,NULA
         ENDIF
         WRITE(IGRAF,1002) ZERO,ZERO,ZERO
         WRITE(IGRAF,1002) ZERO,ZERO,ZERO
         WRITE(IGRAF,1002) ZERO,ZERO,ZERO
         WRITE(IGRAF,1003) NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,
     +                     NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA
   10 CONTINUE
      WRITE(IGRAF,1100) IND
C      ISUMEL=ISUMEL+NE
      NCVE=NNCVE
      RETURN
C
 1000 FORMAT(I6,',',7(I4,','))
 1001 FORMAT(10(I6,','))
 1011 FORMAT(10(I2,','))
 1002 FORMAT(3(F3.0,','))
 1003 FORMAT(16(I2,','))
 1100 FORMAT(I5)
 1200 FORMAT(6(1PE13.5,','))
      END
C=====================================================================
      SUBROUTINE TGRAU3F(NEL,NCVE,NE,IGRAF,NMATT)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C .......................................................................
C .
CE.   P R O G R A M
CE.       TO PRINTOUT 3/D ELEMENTS DATA IN NEUTRAL GRAPHICS FILE
CS.   P R O G R A M
CS.       ZA STAMPANJE 3/D ELEMENATA U NEUTRALNI FILE
C .
C .......................................................................
C 
C      DIMENSION NEL(NE,*),MATV(*)
      DIMENSION NEL(NCVE,*)
C      COMMON /CDEBUG/ IDEBUG
C
C      IF(IDEBUG.GT.0) PRINT *, ' TGRAU3'
C
C     FIZICKE OSOBINE
C
      NULA=0
      ZERO=0.
      ONE=1.
      JEDAN=1
      INDPR=25
      INDPD=2
      I11=11
      I2=2
      I4=4
      I8=8
      I14=14
      I48=48
C
C     E L E M E N T I
C
      NNCVE=NCVE
      IF(NCVE.LT.20) NCVE=8
      IF(NCVE.EQ.21) NCVE=20
C     GRAFICKI OPIS ELEMENTA: SA 8 CVOROVA = 25, SA 20 CVOROVA = 26
      IFGD=25
      IF(NCVE.EQ.20) IFGD=26
C     VRSTA 3/D ELEMENTA: SA 8 CVOROVA = 8, SA 20 CVOROVA = 12
      IFDI=8
      IF(NCVE.EQ.20) IFDI=12
C     TABELA FIZICKIH OSOBINA
C      IPTN=ISUMGR
C     BROJ CVOROVA NA ELEMENTU
      NNODS=NCVE
      IND=-1
      ITYP=404   
      WRITE(IGRAF,1100) IND
      WRITE(IGRAF,1100) ITYP
      DO 10 I=1,NE
C        TABELA MATERIJALA
         MPTN=1
C         IF(NMATT.GT.1) MPTN=MATV(I)
C        BOJA  
c         ICOL=124-(MPTN-1)*2
         ICOL=120-(MPTN-1)*3
         WRITE(IGRAF,1000) I,ICOL,MPTN,IFGD,IFDI,MPTN,NULA,NULA
         IF(NCVE.EQ.8) THEN
            WRITE(IGRAF,1001) (NEL(J,I),J=5,8),(NEL(J,I),J=1,4),
     +                        NULA,NULA
            WRITE(IGRAF,1011) NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,
     +                        NULA,NULA
         ELSE
            WRITE(IGRAF,1001) (NEL(J,I),J=5,8),(NEL(J,I),J=1,4),
     +                        NEL(13,I),NEL(14,I)
            WRITE(IGRAF,1001) NEL(15,I),NEL(16,I),(NEL(J,I),J=17,20),
     +                        (NEL(J,I),J=9,12)
         ENDIF
         WRITE(IGRAF,1002) ZERO,ZERO,ZERO
         WRITE(IGRAF,1002) ZERO,ZERO,ZERO
         WRITE(IGRAF,1002) ZERO,ZERO,ZERO
         WRITE(IGRAF,1003) NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,
     +                     NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA
   10 CONTINUE
      WRITE(IGRAF,1100) IND
C      ISUMEL=ISUMEL+NE
      NCVE=NNCVE
      RETURN
C
 1000 FORMAT(I6,',',7(I4,','))
 1001 FORMAT(10(I6,','))
 1011 FORMAT(10(I2,','))
 1002 FORMAT(3(F3.0,','))
 1003 FORMAT(16(I2,','))
 1100 FORMAT(i5)
 1200 FORMAT(6(1PE13.5,','))
      END
C======================================================================
      SUBROUTINE STAU09F(GNODE,NPP,II,IND,KOR)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      DIMENSION GNODE(2,5,*),FSP(6),IN(8)
C
      FSP(3)=0.
C
      JEDAN=1
      NULA=0
      ZERO=0.
      ONE=1.
      MJ=-1
      M451=451
      M1=1
      M2=2
      M3=3
      M4=4
      M5=5
      M6=6
      M7=7
      M8=8
      M9=9
C      II=49
C
      IN(1)=IND
      IN(2)=IND+1
      IN(3)=IND+2
      IN(4)=IND+3
      IN(5)=IND+4
      IN(6)=IND+5
      IN(7)=IND+6
      IN(8)=IND+7
C
      IP=0
C
   30 IP=IP+1
      WRITE(II,1000) KOR,IN(IP),JEDAN
      IF(IN(1).EQ.1.AND.IP.EQ.1) WRITE(II,3001) 
      IF(IN(1).EQ.9.AND.IP.EQ.1) WRITE(II,3002) 
      IF(IN(1).EQ.10.AND.IP.EQ.1) WRITE(II,3003) 
      IF(IN(1).EQ.11.AND.IP.EQ.1) WRITE(II,3004) 
      IF(IN(1).EQ.41.AND.IP.EQ.1) WRITE(II,3041) 
      IF(IN(1).EQ.41.AND.IP.EQ.2) WRITE(II,3042) 
      IF(IN(1).EQ.41.AND.IP.EQ.3) WRITE(II,3043) 
      IF(IN(1).EQ.41.AND.IP.EQ.4) WRITE(II,3044) 
      IF(IN(1).EQ.51.AND.IP.EQ.1) WRITE(II,3051) 
      IF(IN(1).EQ.51.AND.IP.EQ.2) WRITE(II,3052) 
      IF(IN(1).EQ.51.AND.IP.EQ.3) WRITE(II,3053) 
      IF(IN(1).EQ.51.AND.IP.EQ.4) WRITE(II,3054)
      WRITE(II,1010) ZERO,ZERO,ZERO
C OVO SU NULE ZA TEMPERATURE
      IF(IP.EQ.1.AND.IN(1).LT.40)
     +WRITE(II,1000) NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA
      IF(IP.EQ.1.AND.IN(1).GT.40)
     +WRITE(II,1000)IN(2),IN(3),IN(4),NULA,NULA,NULA,NULA,NULA,NULA,NULA
      IF(IP.EQ.2)
     +  WRITE(II,1000)IN(2),NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA
      IF(IP.EQ.3)
     +  WRITE(II,1000)NULA,IN(3),NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA
      IF(IP.EQ.4)
     +  WRITE(II,1000)NULA,NULA,IN(4),NULA,NULA,NULA,NULA,NULA,NULA,NULA
      WRITE(II,1000) NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA
C
C 0=ANY,1=DISPL,2=ACCEL,3=FORCE,4=STRESS,5=STRAIN,6=TEMP,OTHER=USER
C     NODAL(7) ,ELEMENTAL(8)
      IF(IN(1).EQ.1) WRITE(II,1000) NULA,NULA,M6,M7
      IF(IN(1).EQ.9) WRITE(II,1000) NULA,NULA,M7,M7
      IF(IN(1).EQ.10) WRITE(II,1000) NULA,NULA,M8,M8
      IF(IN(1).EQ.11) WRITE(II,1000) NULA,NULA,M7,M7
      IF(IN(1).EQ.41.OR.IN(1).EQ.51) WRITE(II,1000) NULA,NULA,M3,M7
C
C =1, CAN NOT LINEARY COMBINE THIS OUTPUT
C =1, COMP(0-2) ARE THE X,Y,Z COMPONENT
C =1, THIS VECTOR HAS CONTROIDAL OR NODAL OUTPUT

C ZA PRVI BROJ "0" ZNACI KOMPONENTA KOJA MOZE DA SE KOMBINUJE ZA RACUNANJE EFF
C ZA PRVI BROJ "1" ZNACI EFF I NE MOZE DA SE KOMBINUJE
C ZA DRUGI BROJ "0" ZNACI DA JE SKALAR
C ZA DRUGI BROJ "1" ZNACI DA SE RADI O VEKTORU SA 3 KOMPONENTE
C ZA TRECI BROJ "1" ZNACI DA JE CVORNA VREDNOST
C ZA TRECI BROJ "0" ZNACI DA JE VREDNOST U TEZISTU

      IF(IN(1).GT.40) THEN
         IF(IP.EQ.1) THEN
            WRITE(II,1000) JEDAN,JEDAN,JEDAN
         ELSE
            WRITE(II,1000) NULA,JEDAN,JEDAN
         ENDIF
      ELSE
         WRITE(II,1000) JEDAN,NULA,JEDAN
      ENDIF
      DO 10 I=1,NPP
	   DO 20 J = 1, 5
	    FSP(J) = GNODE(2,J,I)
   20    CONTINUE  
	   IF(IP.EQ.1.AND.IN(1).EQ.1)  VAL=FSP(5)
	   IF(IP.EQ.1.AND.IN(1).EQ.11) VAL=FSP(4)	            
           
         IF(IP.EQ.1.AND.IN(1).GT.40)
     +      VAL=DSQRT(FSP(1)*FSP(1)+FSP(2)*FSP(2)+FSP(3)*FSP(3))
         IF(IP.EQ.2) VAL=FSP(1)
         IF(IP.EQ.3) VAL=FSP(2)
         IF(IP.EQ.4) VAL=FSP(3)
C         IF(DABS(VAL).LT.1.E-12) GO TO 10
         WRITE(II,5000) I,VAL
   10 CONTINUE
      WRITE(II,5000) MJ,ZERO
      IF(IP.LT.4.AND.IN(1).GT.40) GO TO 30
      RETURN
 1000 FORMAT(10(I5,','))
 1001 FORMAT(I6,',',F12.4,',')
 3001 FORMAT('TEMPERATURE')
 3002 FORMAT('PRESCRIBED POTENTIAL')
 3003 FORMAT('PRESCRIBED SURFACES')
 3004 FORMAT('PRESSURES AT NODES')
 3041 FORMAT('TOTAL VELOCITY')
 3042 FORMAT('VX VELOCITY')
 3043 FORMAT('VY VELOCITY')
 3044 FORMAT('VZ VELOCITY')
 3051 FORMAT('TOTAL GRADIENT')
 3052 FORMAT('GX GRADIENT')
 3053 FORMAT('GY GRADIENT')
 3054 FORMAT('GZ GRADIENT')
 1005 FORMAT('PAK CASE',I5)
 1006 FORMAT('CASE',I5,' TIME',1PD12.4)
 1010 FORMAT(3(1PE12.4,','))
 5000 FORMAT(I5,',',3(1PE12.4,','))
      END
C=======================================================================
C======================================================================
      SUBROUTINE STAU10F(PRES,NPP,II,IND,KOR)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      DIMENSION PRES(3,*),FSP(6),IN(8)
C
      FSP(3)=0.
C
      JEDAN=1
      NULA=0
      ZERO=0.
      ONE=1.
      MJ=-1
      M451=451
      M1=1
      M2=2
      M3=3
      M4=4
      M5=5
      M6=6
      M7=7
      M8=8
      M9=9
C      II=49
C
      IN(1)=IND
      IN(2)=IND+1
      IN(3)=IND+2
      IN(4)=IND+3
      IN(5)=IND+4
      IN(6)=IND+5
      IN(7)=IND+6
      IN(8)=IND+7
C
      IP=0
C
   30 IP=IP+1
      WRITE(II,1000) KOR,IN(IP),JEDAN
      IF(IN(1).EQ.1.AND.IP.EQ.1) WRITE(II,3001) 
      IF(IN(1).EQ.9.AND.IP.EQ.1) WRITE(II,3002) 
      IF(IN(1).EQ.10.AND.IP.EQ.1) WRITE(II,3003) 
      IF(IN(1).EQ.11.AND.IP.EQ.1) WRITE(II,3004) 
      IF(IN(1).EQ.41.AND.IP.EQ.1) WRITE(II,3041) 
      IF(IN(1).EQ.41.AND.IP.EQ.2) WRITE(II,3042) 
      IF(IN(1).EQ.41.AND.IP.EQ.3) WRITE(II,3043) 
      IF(IN(1).EQ.41.AND.IP.EQ.4) WRITE(II,3044) 
      IF(IN(1).EQ.51.AND.IP.EQ.1) WRITE(II,3051) 
      IF(IN(1).EQ.51.AND.IP.EQ.2) WRITE(II,3052) 
      IF(IN(1).EQ.51.AND.IP.EQ.3) WRITE(II,3053) 
      IF(IN(1).EQ.51.AND.IP.EQ.4) WRITE(II,3054)
      WRITE(II,1010) ZERO,ZERO,ZERO
C OVO SU NULE ZA TEMPERATURE
      IF(IP.EQ.1.AND.IN(1).LT.40)
     +WRITE(II,1000) NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA
      IF(IP.EQ.1.AND.IN(1).GT.40)
     +WRITE(II,1000)IN(2),IN(3),IN(4),NULA,NULA,NULA,NULA,NULA,NULA,NULA
      IF(IP.EQ.2)
     +  WRITE(II,1000)IN(2),NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA
      IF(IP.EQ.3)
     +  WRITE(II,1000)NULA,IN(3),NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA
      IF(IP.EQ.4)
     +  WRITE(II,1000)NULA,NULA,IN(4),NULA,NULA,NULA,NULA,NULA,NULA,NULA
      WRITE(II,1000) NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA,NULA
C
C 0=ANY,1=DISPL,2=ACCEL,3=FORCE,4=STRESS,5=STRAIN,6=TEMP,OTHER=USER
C     NODAL(7) ,ELEMENTAL(8)
      IF(IN(1).EQ.1) WRITE(II,1000) NULA,NULA,M6,M7
      IF(IN(1).EQ.9) WRITE(II,1000) NULA,NULA,M7,M7
      IF(IN(1).EQ.10) WRITE(II,1000) NULA,NULA,M8,M8
      IF(IN(1).EQ.11) WRITE(II,1000) NULA,NULA,M7,M7
      IF(IN(1).EQ.41.OR.IN(1).EQ.51) WRITE(II,1000) NULA,NULA,M3,M7
C
C =1, CAN NOT LINEARY COMBINE THIS OUTPUT
C =1, COMP(0-2) ARE THE X,Y,Z COMPONENT
C =1, THIS VECTOR HAS CONTROIDAL OR NODAL OUTPUT

C ZA PRVI BROJ "0" ZNACI KOMPONENTA KOJA MOZE DA SE KOMBINUJE ZA RACUNANJE EFF
C ZA PRVI BROJ "1" ZNACI EFF I NE MOZE DA SE KOMBINUJE
C ZA DRUGI BROJ "0" ZNACI DA JE SKALAR
C ZA DRUGI BROJ "1" ZNACI DA SE RADI O VEKTORU SA 3 KOMPONENTE
C ZA TRECI BROJ "1" ZNACI DA JE CVORNA VREDNOST
C ZA TRECI BROJ "0" ZNACI DA JE VREDNOST U TEZISTU

      IF(IN(1).GT.40) THEN
         IF(IP.EQ.1) THEN
            WRITE(II,1000) JEDAN,JEDAN,JEDAN
         ELSE
            WRITE(II,1000) NULA,JEDAN,JEDAN
         ENDIF
      ELSE
         WRITE(II,1000) JEDAN,NULA,JEDAN
      ENDIF
      DO 10 I=1,NPP
	   DO 20 J = 1,3
	    FSP(J) = PRES(J,I)
   20    CONTINUE  
         IF(IP.EQ.1.AND.IN(1).GT.40)
     +      VAL=DSQRT(FSP(1)*FSP(1)+FSP(2)*FSP(2)+FSP(3)*FSP(3))
         IF(IP.EQ.2) VAL=FSP(1)
         IF(IP.EQ.3) VAL=FSP(2)
         IF(IP.EQ.4) VAL=FSP(3)
C         IF(DABS(VAL).LT.1.E-12) GO TO 10
         WRITE(II,5000) I,VAL
   10 CONTINUE
      WRITE(II,5000) MJ,ZERO
      IF(IP.LT.4.AND.IN(1).GT.40) GO TO 30
      RETURN
 1000 FORMAT(10(I5,','))
 1001 FORMAT(I6,',',F12.4,',')
 3001 FORMAT('TEMPERATURE')
 3002 FORMAT('PRESCRIBED POTENTIAL')
 3003 FORMAT('PRESCRIBED SURFACES')
 3004 FORMAT('PRESSURES AT NODES')
 3041 FORMAT('TOTAL VELOCITY')
 3042 FORMAT('VX VELOCITY')
 3043 FORMAT('VY VELOCITY')
 3044 FORMAT('VZ VELOCITY')
 3051 FORMAT('WALL SHEAR STRESS')
 3052 FORMAT('WALL SHEAR STRESS X')
 3053 FORMAT('WALL SHEAR STRESS Y')
 3054 FORMAT('WALL SHEAR STRESS Z')
 1005 FORMAT('PAK CASE',I5)
 1006 FORMAT('CASE',I5,' TIME',1PD12.4)
 1010 FORMAT(3(1PE12.4,','))
 5000 FORMAT(I5,',',3(1PE12.4,','))
      END
C=======================================================================
 
C=======================================================================
      SUBROUTINE NEUTRAF(NKDT,DTDT,NPER,IND,II)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C ......................................................................
C .
CE.    P R O G R A M
CE.        WITH LOOP OVER TIME PERIODS AND STEPS FOR NEUTRAL FILE
CS.    P R O G R A M
CS.        SA PETLJOM PO VREMENSKIM PERIODIMA I KORACIMA ZA NEUTRAL 
C .
CE.    V A R I A B L E S
CE.        NPER  - TOTAL NUMBER OF PERIODS WITH CONSTANT TIME STEP,
CE.                SEE CARD /3/
C .
C ......................................................................
C
      CHARACTER*250 NASLOVF
      COMMON /NASLOVF/ NASLOVF
      DIMENSION NKDT(*),DTDT(*)
C

C
      JEDAN=1
      NULA=0
      ZERO=0.
      ONE=1.
      MJ=-1
      M2=2
      M3=3
      M4=4
      M5=5
      M8=8
      M9=9
C
      IF(IND.EQ.2) GO TO 999
      WRITE(II,1000) MJ
      M450=450
      WRITE(II,1001) M450
C
      MM=19
C      IF(NGENL.EQ.0.AND.NDIN.EQ.0.AND.ISOPS.EQ.0) MM=1
C
CE    BASIC LOOP OVER TIME PERIODS
CS    OSNOVNA PETLJA PO VREMENSKIM PERIODIMA
CE    BASIC LOOP OVER TIME STEPS
CS    OSNOVNA PETLJA PO VREMENSKIM KORACIMA
C
      VREM0=0.D0
      INDT=0
CE    BASIC LOOP OVER TIME PERIODS
CS    OSNOVNA PETLJA PO VREMENSKIM PERIODIMA
C
      DO 100 IPER=1,NPER
         IINDT=NKDT(IPER)
         DT=DTDT(IPER)
         IPDT=INDT+1
         INDT=INDT+IINDT
C
CE    BASIC LOOP OVER TIME STEPS
CS    OSNOVNA PETLJA PO VREMENSKIM KORACIMA
C
      DO 500 KORBR=IPDT,INDT
         VREM0 = VREM0 + DT
          WRITE(II,1002) KORBR
      IF(NDT.EQ.1) THEN
         WRITE(II,1005) KORBR
         WRITE(II,1002) M9,MM
         WRITE(II,1010) ZERO
      ELSE
         WRITE(II,1006) KORBR,VREM0
         WRITE(II,1002) M9,MM
         WRITE(II,1010) VREM0
      ENDIF
      WRITE(II,1002) JEDAN
      WRITE(II,2000) NASLOVF
  500 CONTINUE 
C
  100 CONTINUE
C
      WRITE(II,1000) MJ
C
      WRITE(II,1000) MJ
      M451=451
      WRITE(II,1001) M451
      RETURN
C
  999 WRITE(II,1000) MJ
C      CLOSE(II,STATUS='KEEP')
      RETURN
C
 1000 FORMAT(10I5)
 1001 FORMAT(I6,F12.4)
 1002 FORMAT(10(I5,','))
 1005 FORMAT('PAK CASE',I5)
 1006 FORMAT('CASE',I5,' TIME',1PE11.4)
 1010 FORMAT(3(1PE11.4,','))
 2000 FORMAT(A80)
      END