
      PARAMETER (PI=3.141592653589793)
      
      COMMON/Blok1/Xp(101),Yp(101),XEC(101),YEC(101),
     *             NFX(101,2),NFY(101,2),KELC(101,4),VX1(2),VX2(2)
     
      COMMON/Blok2/PSI1(4,10),PSI1R(4,10),PSI1T(4,10),
     *             PSI1X1(4,10),PSI1X2(4,10),PSI1X(4,10),PSI1Y(4,10),   
     *             ROO(10),TETA(10),NIZ2(10),FAK1,FAK2

      COMMON/Blok4/NNB,MNB,NEC,NSEGX,IND_EKST,NES,IBRO,KBRO,
     *             LBRO,KEL,KTIP2,KTIP1	      
     
        